### ISSUE TITLE
Feature Request: Add support to validate requests coming from SendGrid webhooks

### ISSUE THREAD

**Issue by ivangalbans** [sendgrid/sendgrid-csharp#1004]
SendGrid recently released new functionality to validate your incoming webhooks: https://sendgrid.com/docs/for-developers/tracking-events/getting-started-event-webhook-security-features/#the-signed-event-webhook

At the moment, the official SendGrid documentation has posted an example in Golang and translating this to csharp can be a bit tricky (working with ECDsa, hashing algorithms etc.), so an inclusion of this functionality in the library would be excellent.

**This is just an idea**, similar to https://github.com/twilio/twilio-csharp/blob/master/src/Twilio/Security/RequestValidator.cs

Add a `RequestValidator` class in the `SendGrid.Security` namespace with useful methods that validate the request.

~~~c#
namespace SendGrid.Security
{
    public class RequestValidator
    {
        private readonly SHA256 _sha;
        private readonly string _secret;

        public RequestValidator(string secret)
        {
            _secret = secret;
            _sha = SHA256.Create();
        }

        public bool Validate(string signature, string timestamp, string body)
        {
            ...
        }
        ...
    }
    
}
~~~

**Comment by childish-sambino** [comment]
Yup, this is high on our backlog and should be completed within the next few weeks.
