### ISSUE TITLE
Access denied when trying to get lists from SendGrid

### ISSUE THREAD

**Issue by darlontrofy77** [sendgrid/sendgrid-csharp#1005]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
Hello,

I have granted my api key all access in SendGrid, but when I make a call to get all the lists of add a new contact to a list, I get an access denied message. I can create lists when I log in to the user interface, but I cant do it from the API. What could I be doing wrong? thanks.

### Code Snippet
```csharp
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-csharp version:
* csharp version:

**Comment by darlontrofy77** [comment]
Hello,

  I have granted my api key all access in SendGrid, but when I make a call to get all the lists of add a new contact to a list, I get an access denied message. I can create lists when I log in to the user interface, but I cant do it from the API. What could I be doing wrong? thanks.

**Comment by thinkingserious** [comment]
Hello @darlontrofy77,

Could you please share the relevant source code here so that we may try and reproduce? 

Thanks!

With best regards,

Elmer

**Comment by darlontrofy77** [comment]
Thanks.
This is my C# code which throws the exception:
 var client = new SendGridClient(apiKey);
                var queryParams = @"{'list_id': " + listId + ", 'page': 1, 'page_size': 1000}";                var response = client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "contactdb/lists/" + listId + "/recipients", queryParams: queryParams);                return new SendGridResponse()                {                    Body = response.Body.ReadAsStringAsync().Result,                    Headers = response.Headers.ToString(),                    StatusCode = response.StatusCode                };

    On Monday, June 1, 2020, 12:50:02 PM CDT, Elmer Thomas <notifications@github.com> wrote:  
 
 


Hello @darlontrofy77,

Could you please share the relevant source code here so that we may try and reproduce?

Thanks!

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @darlontrofy77,

Please remove the `list_id` in `queryParams` and ensure `listId` is a string.

Here is a working example:
```csharp
using System;
using System.Threading.Tasks;
using SendGrid;

class Program
{
    static async Task Main()
    {
        var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
        var client = new SendGridClient(apiKey);
        string queryParams = @"{
            'page': 1, 
            'page_size': 100
        }";
        var list_id = "12168472";
        var response = await client.RequestAsync(
                method: SendGridClient.Method.GET,
                urlPath: "contactdb/lists/" + list_id + "/recipients",
                queryParams: queryParams);
        Console.WriteLine(response.StatusCode);
        Console.WriteLine(response.Body.ReadAsStringAsync().Result);
        Console.WriteLine(response.Headers.ToString());
    }
}
```

[This documentation](https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md#get-contactdblistslist_idrecipients) might help as well.

Thanks!

With best regards,

Elmer
