### ISSUE TITLE
Missing 'SendGrid.Extensions.DependencyInjection' package 

### ISSUE THREAD

**Issue by hhermas** [sendgrid/sendgrid-csharp#1006]
### Issue Summary
'SendGrid.Extensions.DependencyInjection' package not available.

### Steps to Reproduce
1. https://www.nuget.org/packages/SendGrid.Extensions.DependencyInjection
2. Error 404 - Page Not Found

**Comment by dschmack** [comment]
I ran into the same issue following the link in the [documentation](https://github.com/sendgrid/sendgrid-csharp#httpclientfactory--microsoftextensionsdependencyinjection).

**Comment by rangav** [comment]
i am also looking for this package?

**Comment by childish-sambino** [comment]
There's not been a new release of this repo since the package was added in https://github.com/sendgrid/sendgrid-csharp/pull/922. The next release is in 2 days so it should show up after that.
