### ISSUE TITLE
SendGrid Subscription to access email activity api

### ISSUE THREAD

**Issue by maDawi** [sendgrid/sendgrid-csharp#1009]
Good Day,

Question what are the subscription or bill we need to use Email activity api?

Please see the issue we encounter 
![Capture](https://user-images.githubusercontent.com/21037678/83847600-21332680-a73f-11ea-86f4-52b51bdfe63f.PNG)

If we buy this
 Essentials 40K
40,000 emails/month + $0.001 per additional email
we can access now the email activity api ?
![Capture2](https://user-images.githubusercontent.com/21037678/83847300-96eac280-a73e-11ea-8876-c484578851a4.PNG)

Thank you.

**Comment by childish-sambino** [comment]
No, that will not give you email activity API access. You'll need _Extended Email Activity History_: https://app.sendgrid.com/settings/billing/addons/email_activity
