### ISSUE TITLE
Add Custom Headers

### ISSUE THREAD

**Issue by doglesby** [sendgrid/sendgrid-csharp#101]
In talking with SendGrid support, I was told that... as of now, there are no custom header options for our C# library, however, I'd recommend reaching out to our Devs on our GitHub to either request a use case, or add this as a feature request.

I'm specifically interesting in being able to add the on-behalf-of header.

Thanks!

**Comment by brandonmwest** [comment]
You can specify arbitrary headers via the`AddHeaders()` method :) https://github.com/sendgrid/sendgrid-csharp/blob/ca91fad22dfec2cd1219267fe979c1d9a33a522e/SendGrid/SendGridMail/SendGrid.cs#L263

**Comment by brettpostin** [comment]
@brandonmwest this is for setting headers when sending a message. Is there a way to set headers for other endpoints?

I too am trying to set the on-behalf-of header for the "api_keys" endpoint.
