### ISSUE TITLE
Need to know usage of custom_fields attribute in /marketing/contacts (PUT) endpoint

### ISSUE THREAD

**Issue by elenanakhmanson** [sendgrid/sendgrid-csharp#1021]
### Issue Summary
I'm using new marketing campaigns APIs and need to assign custom field value to a contact that gets created/updated in the /marketing/contacts endpoint. [Documentation ](https://sendgrid.api-docs.io/v3.0/contacts/add-or-update-a-contact) states it's an object, but doesn't say anything else. I tried different logical structures for this "object" but all returned errors. For example "custom_fields": [{"company_name": "SendGrid"}] didn't work, we get {"field": "","message": "invalid input"} error.
How can I assign value to a custom field when creating a contact?

### Steps to Reproduce
implement /marketing/contacts API
try to assign value to the custom_fields attribute

### Technical details:
* SendGrid New Marketing Campaigns APIs

**Comment by eshanholtz** [comment]
Hi @elenanakhmanson 

You first need to create your [custom field definitions](https://sendgrid.api-docs.io/v3.0/custom-fields/create-custom-field-definition) before you can add them to your contact using the endpoint you linked. 

For example, first you create a custom field:
```csharp
var apiKey = Environment.GetEnvironmentVariable("YOUR_SENDGRID_API_KEY");
var sg = new SendGridClient(apiKey);

var data = @"{
  'name': 'company_name',
  'field_type': 'text'
}";
var json = JsonConvert.DeserializeObject<Object>(data);
data = json.ToString();
var response = await sg.RequestAsync(method: SendGridClient.Method.POST, urlPath: "marketing/field_definitions", requestBody: data);
```

Then you could do assign a value for it in a contact like:
```csharp
var data = @"{
  'contacts': [
    {
      'email': 'contact@example.com',
      'custom_fields': {
        'company_name': 'SendGrid'
      }
    }
  ]
}";
var json = JsonConvert.DeserializeObject<Object>(data);
data = json.ToString();
var response = await sg.RequestAsync(method: SendGridClient.Method.PUT, urlPath: "marketing/contacts", requestBody: data);
```

**Comment by elenanakhmanson** [comment]
hi @eshanholtz , thank you for the explanation and example, however after trying it out we found that custom_fields attribute expects custom field id and not name. So instead of {'company_name': 'SendGrid'} we have to pass {'w1_T': 'SendGrid'}
