### ISSUE TITLE
Builld add Newtonsoft.Json.dll 9.0.1 also if the project use the version 12

### ISSUE THREAD

**Issue by stojkovic76** [sendgrid/sendgrid-csharp#1022]
### Issue Summary
I have a web service that uses Newtonsoft.Json.dll 12: after adding SendGrid I have some problems with the building because Visual Studio 2019 add Newtonsoft.Json.dll 9.0.1 in the bin folder and of course the project is not able to run.

The sendgrid dll isn't present directly on the web service project but is used inside a DLL project that is present in the same solution. The strange thing is that when building only the DLL alone I have the Newtonsoft.Json.dll version 12, while is I build the web service I found the old version.

If I remove the old file from bin and I replace it with the new version 12 all works but is easy to forget. Where could be the issue'

### Technical details:
* sendgrid-csharp version: 9.17
* csharp version: .net framework 4.7.2

**Comment by stojkovic76** [comment]
<PropertyGroup>
	<AssemblySearchPaths>$(AssemblySearchPaths.Replace('{AssemblyFolders}', '').Split(';'))</AssemblySearchPaths>
  </PropertyGroup>

I solved adding this to the project file behind the line:
<Import Project="$(_WebPublishTargetsPath)\Web\Microsoft.WebSite.Publishing.targets" />

**Comment by stojkovic76** [comment]
I solved adding:
` <PropertyGroup>
	<AssemblySearchPaths>$(AssemblySearchPaths.Replace('{AssemblyFolders}', '').Split(';'))</AssemblySearchPaths>
  </PropertyGroup>`
 
behind the line:

`<Import Project="$(_WebPublishTargetsPath)\Web\Microsoft.WebSite.Publishing.targets" />`

**Comment by thinkingserious** [comment]
Hello @stojkovic76,

Thank you for taking the time to follow up with the solution!

With best regards,

Elmer
