### ISSUE TITLE
SendEmailAsync does not work on AzureWebAPP. 

### ISSUE THREAD

**Issue by itjayeshl** [sendgrid/sendgrid-csharp#1023]
Hello Techies,
I used DotnetCore2.1 and deployed code on AzureWebApp linux hosting environment.
SendGrid works fine in local Dev environment. but while publishing it on AzureApp environment it fails to send email to recepients.

I tried various ways to make my code working on AzureWebApp environment.
I did not received any errors in WebApp logs.

client.SendEmailAsync(msg).Wait(); and client.SendEmailAsync(msg); both but it did not work for me.

Please suggest if i missed anything here.

it will be great if you help me to resolve it.

Waiting for your reply

**Comment by thinkingserious** [comment]
Hello @itjayeshl,

If an AzureWebApp is utilizing ASP.NET, perhaps [this example](https://github.com/sendgrid/sendgrid-csharp/tree/master/ExampleNet45ASPNetProject) may help.

You may also try `var response = await client.SendEmailAsync(msg).ConfigureAwait(false);`.

With best regards,

Elmer
