### ISSUE TITLE
Using Async in a Synchronous Method Throws Exception

### ISSUE THREAD

**Issue by jhenriks79** [sendgrid/sendgrid-csharp#103]
The code in sendgrid-csharp/SendGrid/SendGridMail/Transport/Web.cs is using an async method call in the Deliver method which can throw an AggregateException.  Consider wrapping the PostAsync call with try/catch and handling the specific exception.

General guidance... You should avoid mixing synchronous and asynchronous code.  Mixed async and blocking code can cause deadlocks, more-complex error handling and unexpected blocking of context threads.

**Comment by brandonmwest** [comment]
Woops, definitely a bug, will fix. Thanks!

**Comment by brandonmwest** [comment]
So looking into this more, my understanding is that because the code accesses `.Result` that this is in fact a synchronous operation. Are you seeing `AggregateException`s pop up?

**Comment by jhenriks79** [comment]
It is in fact synchronous but mixing synchronous and asynchronous code can cause problems because of the way the thread context works.  In my case, I was using the Web.Deliver method and about 50% of the time I would get an AggregateException while the rest of the time the email would send fine.  Once I started seeing the AggregateException, I examined the SendGrid code and found the async call in the Deliver method.

There's a really good writeup on MSDN Magazine of why mixing async and sync can cause problems.
https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

**Comment by brandonmwest** [comment]
Thanks! Any thoughts on how to use HttpClient but avoid these problems, since HttpClient only provides Async methods?

I found [this suggestion](http://forums.asp.net/post/4845452.aspx):
```csharp
public T GetDataFromService<T>()
{
    using (var httpClient = new HttpClient())
    {
        var response = httpClient.GetAsync(_endpoint).Result;

        return JsonConvert.DeserializeObject<T>(response.Content.ReadAsStringAsync().Result);
    }
}
```

Would a similar approach work here? Thanks for your help!

**Comment by jhenriks79** [comment]
Unfortunately, that will have the same problem.  It's mixing async and sync code.  One way to get around it is to use the HttpWebRequest class instead of the HttpClient class.  See this link for reference:  https://msdn.microsoft.com/en-us/library/debx8sh9%28v=vs.110%29.aspx

**Comment by brandonmwest** [comment]
Okay, thanks for the help. I'll think more about this.

**Comment by brandonmwest** [comment]
I've determined that the best course of action is probably to deprecate the synchronous send method.

**Comment by brandonmwest** [comment]
I've removed the synchronous method in the next release.
