### ISSUE TITLE
Lack of documentation on SetTemplateData

### ISSUE THREAD

**Issue by BrianMinister** [sendgrid/sendgrid-csharp#1031]
### Issue Summary
For my Dynamic template, I could use simple Dictionary<string,string> to handle everything that I need.

However, the data never made it to the template and I was getting emails with critical fields blank.

I got over this by passing Dictionary<string,object>. This seems to be an undocumented limitation.

### Code Snippet
```csharp
//Failed code:
Dictionary<string,string> templatevalues = GenSomeDataA();
msg.SetTemplateData((dynamic)templatevalues);

//Good code
Dictionary<string,object> templatevalues = GenSomeDataA();
msg.SetTemplateData((dynamic)templatevalues);
```

### Exception/Log
```
No exceptions.
```

### Technical details:
* sendgrid-csharp version: 9.19.0 (Pub: 7/22/2020)
* csharp version: Latest

**Comment by childish-sambino** [comment]
I've tried but have been unable to recreate this issue locally. Recommend first inspecting the request body to make sure it's proper and compare using both types you've listed: https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#viewing-the-request-body
