### ISSUE TITLE
Inability to Upgrade Email Plan on Sendgrid

### ISSUE THREAD

**Issue by JLMBIT** [sendgrid/sendgrid-csharp#1033]
Please I need help ! Seeing this error anytime I want to upgrade Email plan on sendgrid:

**Hold tight!
As a security measure, we are further evaluating your ability to select a plan for upgrade.

We apologize for the inconvenience this may cause. In the meantime, you still have access to your current plan’s features and email volume.**

Please what can I do?

**Comment by JLMBIT** [comment]
> Please I need help ! Seeing this error anytime I want to upgrade Email plan on sendgrid:
> 
> **Hold tight!
> As a security measure, we are further evaluating your ability to select a plan for upgrade.
> 
> We apologize for the inconvenience this may cause. In the meantime, you still have access to your current plan’s features and email volume.**
> 
> Please what can I do?

Hellooooooooooooooooo, please can anyone help with this challenge?

**Comment by eshanholtz** [comment]
Account security issues are not something that can be resolved through this support channel. Please reach out to [support](https://support.sendgrid.com/hc/en-us) for further help.

**Comment by JLMBIT** [comment]
Noted, thank you

However, we have sent support request for over two weeks without feedback on the issue

[cid:image002.png@01D6709B.6CA2F8F0]

**Comment by pboese** [comment]
Same here. Wanted to try out something other than SES. But since they obviously aren't interested in new customers, we'll just use SES for the new project.
