### ISSUE TITLE
This repo contains code taken from another project

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#1035]
@childish-sambino You recently merged a [PR](https://github.com/sendgrid/sendgrid-csharp/pull/789) containing code which was taken from a project I authored and I don't see any attribution. My preference would be to avoid copying and pasting code from my project and instead reference the [published NuGet package](https://www.nuget.org/packages/StrongGrid/) but at the very least, I would appreciate proper attribution.

This is something that I [reported](https://github.com/sendgrid/sendgrid-csharp/issues/766#issuecomment-430020528) and @thinkingserious [led me to believe](https://github.com/sendgrid/sendgrid-csharp/issues/766#issuecomment-430352666) my work would be attributed. Sadly, it hasn't happened.

On a side note, please be aware that the version of my code which was copied is 2 years old and a few bugs have been discovered and resolved in the mean time. The code that you merged, however, still contains these bugs. This is, in my opinion, one more argument in favor of not copying and pasting the code but rather referencing the package available on NuGet.

**Comment by childish-sambino** [comment]
I didn't look through the issue comments when reviewing the PR. I've updated the README to credit you here: https://github.com/sendgrid/sendgrid-csharp/blob/main/examples/inbound-webhook-handler/README.md

While I agree about copy-pasted code in general, I don't see cross-dependencies between these two repos being for the best given the amount of overlap. I'm inclined to leave things as they are and address bugs/enhancements as they arise.
