### ISSUE TITLE
Receive error "A Task Was Cancelled

### ISSUE THREAD

**Issue by nickhut101** [sendgrid/sendgrid-csharp#1040]
Hi, am new to Sendgrid. I have sometimes been able to send emails but I usually receive the "A Task Was Cancelled" error.
I am attaching one file to the email, which can be 30MB or so.

- Visual Studio 15.8.7 (VB.Net)
- Sendgrid 9.21.0

Here is my code:

   Public Async Function SendEmail() As Task(Of Response)
        Dim response As Response
        Dim strKey As String = System.Configuration.ConfigurationManager.AppSettings("SendGridAPIKey")
        Try

            Dim client = New SendGridClient(strKey)
            Dim m As New SendGridMessage
            With m
                .From = New EmailAddress(_Mail.From.Address, _Mail.From.DisplayName)
                .ReplyTo = New EmailAddress(_Mail.From.Address, _Mail.From.DisplayName)
                .Subject = _Mail.Subject
                .AddTo(New EmailAddress(_Mail.To(0).Address, _Mail.To(0).DisplayName))
                .PlainTextContent = _Mail.Body
                Dim lng As Integer = InStr(_Mail.Body, vbCrLf)
                .HtmlContent = Replace(_Mail.Body, vbCrLf, "</br>")
                For Each o As String In _Attachments
                    '     Dim bytedata As Byte() = System.Text.Encoding.ASCII.GetBytes(File.ReadAllText(o))
                    Dim att = New SendGrid.Helpers.Mail.Attachment
                    att.Content = ConvertFileToBase64(o)
                    att.Filename = Path.GetFileName(o)
                    att.Type = "application/pdf"
                    att.Disposition = "attachment"
                    m.AddAttachment(att)
                Next

            End With

            response = Await client.SendEmailAsync(m)

            Return response
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

end function

Error returned:
"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at SendGrid.BaseClient.<MakeRequest>d__20.MoveNext()" & vbCrLf & "--- End of stack trace from previous location where exception was thrown ---" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at SendGrid.BaseClient.<RequestAsync>d__21.MoveNext()" & vbCrLf & "--- End of stack trace from previous location where exception was thrown ---" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at SendGrid.BaseClient.<SendEmailAsync>d__22.MoveNext()" & vbCrLf & "--- End of stack trace from previous location where exception was thrown ---" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & "   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()" & vbCrLf & "   at PatrickFrontEnd.SendGridController.VB$StateMachine_5_SendEmail.MoveNext() in C:\PatrickV4\PatrickFrontEnd\Functions\EmailController.vb:line 164"

**Comment by thinkingserious** [comment]
Hello @nickhut101,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
