### ISSUE TITLE
SendGrid.Extensions.DependencyInjection signature issue

### ISSUE THREAD

**Issue by Jehoel** [sendgrid/sendgrid-csharp#1045]
### Issue Summary

I tried to use `SendGrid.Extensions.DependencyInjection` in an ASP.NET WebForms application (the project already has a DI container) and the `.csproj` builds fine, however `aspnet_compiler.exe` complains:

```
D:\git\me\project\WebApp\web.config(214): error ASPCONFIG: Could not load file or assembly 'SendGrid.Extensions.DependencyInjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4f047e93159395ca' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, o
r it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

[FileLoadException]: Could not load file or assembly 'SendGrid.Extensions.DependencyInjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4f047e93159395ca' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully
signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

### Steps to Reproduce
1. Create an ASP.NET WebForms project.
2. Add the NuGet package `SendGrid.Extensions.DependencyInjection` to the project and build.
3. Perform precompilation with `aspnet_compiler.exe`
4. You'll get that error message.

### Technical details:
* sendgrid-csharp version: 9.21.0
* `SendGrid.Extensions.DependencyInjection` version: 1.0.0.
* csharp version: 8.0 (VS2019)

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by childish-sambino** [comment]
@iammichelleau 
> +1s on the issue summary

**Comment by Jehoel** [comment]
@eshanholtz This is not an issue I believe I can submit a PR for because it involves a delay-signed assembly, which would be part of your build system's secret-management.
