### ISSUE TITLE
Connection issues due to socket exhaustion

### ISSUE THREAD

**Issue by peterneave** [sendgrid/sendgrid-csharp#1047]
### Issue Summary
Just posting this in case someone else has a problem in the future. We were coming up with an intermittent issue where we were getting the following exception:

```
Exception: Unable to read data from the transport connection: The connection was closed.
InnerException: Error while copying content to a stream.
```

Originally I thought it might have been a TLS issue from other issues that were reported here. However, we eventually determined that it was a due to socket exhaustion. In our case we were instantiating a new `SendGridClient` for each email getting sent. Once we started to ramp up production then we noticed that 25%-50% of connections were getting dropped.

The following simplified code snippet highlights the issue

```csharp
//Bad
public class SendGridEmailService(){
    ...
    public async Task<Response> SendEmailAsync(SendGridMessage msg)
        var client = new SendGridClient(_sendGridApiKey); //Bad - leads to socket exhaustion
        return await client.SendEmailAsync(msg);
    }
}
```

We have made the `SendGridClient` static to the email service.

```csharp
//Good
public class SendGridEmailService(){
    ...
    private static SendGridClient _client = new SendGridClient(_sendGridApiKey);
    public async Task<Response> SendEmailAsync(SendGridMessage msg)
        return await _client.SendEmailAsync(msg);
    }
}
```

**Comment by eshanholtz** [comment]
Thank you for the guidance! I'm going to go ahead and close this issue as it requires no further work on our part.
