### ISSUE TITLE
Sendgrid Inbound Parse is not working with https in some cases

### ISSUE THREAD

**Issue by vincentDAO** [sendgrid/sendgrid-csharp#1053]
### Issue Summary
Sendgrid Inbound Parse is not working with https.
Note: I ask question here because I'm using dotnet core as backend app for Inbound parse

### Steps to Reproduce
1. In Sendgrid Web UI, authorized "mydomain.com" (and in my DNS GoDaddy)
2. In Sendgrid Web UI, add HOST + URL
3a. If I use URL without TLS http://link1.mydomain.com/api/sendgrid_inbound_parse => it works.
3b. If I use URL with TLS (GoDaddy) https://link2.mydomain.com/api/sendgrid_inbound_parse => it DOESN'T work.
3c. If I use URL with TLS (Letenscrypt) https://link3.mydomain.com/api/sendgrid_inbound_parse => it DOESN'T work.
3d. If I use URL with TLS (Letenscrypt) https://xxxxx.ngrok.com/api/sendgrid_inbound_parse => it DOESN'T work.

### Exception/Log for Certificate
```
$ openssl s_client -showcerts -connect **link2.mydomain.com**:443 (I hide my real domain)
CONNECTED(000001C0)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 308 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1602129900
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
write:errno=10054
```

### Technical details:
* Kubernetes/Istio/Azure as backend 
* csharp version: 3.1

I have no way to check logs/ diagnostic this issue because the request still not come to my server.
In case I use ngrok.com with HTTPS, It still WORK and that means the configuration for webhook Inbound parse work.

So I guess the cause is "Sendgrid and my server handshake".
Any suggestion to help to diagnostic  this issue?

**Comment by vincentDAO** [comment]
This is our certificate problem.

**Comment by josh-nextstage** [comment]
@vincentDAO, what was the isssue with your certificate? Running into a similar problem
