### ISSUE TITLE
Email Body Links are converted from https to http

### ISSUE THREAD

**Issue by tahiralvi** [sendgrid/sendgrid-csharp#1056]
Hi Everyone,

I have received continues complaints from the client that the Email Body link `<a href="https://app.contractorexch.com"></a>` are converted into the `<a href="http://link.contractorexch.com/......"></a>`. So when they opened the emails which in Gmail, it gives them a warning of 'Suspicious Link'.

I am using the ASP.NET MVC application and SendGrid, below are my settings,

```
<add key="sendGridSmtpServer" value="smtp.sendgrid.net" />
 <add key="EnableSsl" value="true" />
 <add key="sendGridPort" value="587" />
 <add key="sendGridFrom" value="test@gleetech.com" />
 <add key="sendGridUser" value="someUser" />
 <add key="sendGridPassword" value="somePassword" />
```
and below is the method used to send the email,

```
private void SendEmail(MailMessage mail) {
            SmtpClient smtpClient = new SmtpClient(ConfigurationManager.AppSettings["sendGridSmtpServer"]) {
                Port = Convert.ToInt32(ConfigurationManager.AppSettings["sendGridPort"]),
                Credentials = new NetworkCredential(ConfigurationManager.AppSettings["sendGridUser"], 
                ConfigurationManager.AppSettings["sendGridPassword"]),
                EnableSsl = Convert.ToBoolean(ConfigurationManager.AppSettings["EnableSsl"])
            };
            smtpClient.Send(mail);
}
```
Could anyone guide me where I am wrong?
I am using an HTML template to send. In that template, which I have got at runtime by reading the HTML file

**Comment by thinkingserious** [comment]
Hello @tahiralvi,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
