### ISSUE TITLE
Sendgrid Event Webhook: Could not load file or assembly 'StarkbankEcdsa, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

### ISSUE THREAD

**Issue by aadilwani** [sendgrid/sendgrid-csharp#1057]
### Issue Summary
{"Could not load file or assembly 'StarkbankEcdsa, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)":"StarkbankEcdsa, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"}

### Steps to Reproduce
1. I am trying to use SendGrid Event Webhook and getting this error. 
   These are my entries in package,config 

    <package id="SendGrid" version="9.21.0" targetFramework="net461" />
  <package id="starkbank-ecdsa" version="1.2.1" targetFramework="net461" />

**Comment by thinkingserious** [comment]
Hello @aadilwani,

There is an open issue to address this at [starkbank/ecdsa-dotnet](https://github.com/starkbank/ecdsa-dotnet/issues/10).

With best regards,

Elmer

**Comment by aadilwani** [comment]
Any temporary fix until this gets resolved ?

Also I am adding a filter that will validate all my incoming webhook requests. Could you please have a look or there is any other better way SendGrid is providing  us?

namespace SendGridWebApp.Filters
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
    public class ValidateSendGridRequestAttribute : ActionFilterAttribute
    {
        private readonly string _authToken;

        private const string SIGNATURE_HEADER = "X-Twilio-Email-Event-Webhook-Signature";
        private const string TIMESTAMP_HEADER = "X-Twilio-Email-Event-Webhook-Timestamp";


        public ValidateSendGridRequestAttribute()
        {
            authToken = ConfigurationManager.AppSettings["twilio:AuthToken"];            

        }

        public override async Task OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
        {
            try
            {

                if (!await IsValidRequestAsync(actionContext.Request))
                {
                    actionContext.Response = actionContext.Request.CreateErrorResponse(
                        HttpStatusCode.Forbidden,
                        "The SendGrid request is invalid"
                    );
                }

                await base.OnActionExecutingAsync(actionContext, cancellationToken);


            }
            catch (Exception ex)
            {
                actionContext.Response = actionContext.Request.CreateErrorResponse(
                        HttpStatusCode.InternalServerError, ex.ToString());
            }
        }

        private async Task<bool> IsValidRequestAsync(HttpRequestMessage request)
        {
            var sendGridHeaderSignitureExists = request.Headers.TryGetValues(
                SIGNATURE_HEADER, out IEnumerable<string> signature);

            var sendGridHeaderTimeStampExists = request.Headers.TryGetValues(
                TIMESTAMP_HEADER, out IEnumerable<string> timestamp);

            if (sendGridHeaderSignitureExists && sendGridHeaderTimeStampExists)
            {
                var payload = await GetPayloadAsync(request.Content);
                var validator = new RequestValidator();
                var publickey = validator.ConvertPublicKeyToECDSA(_authToken);
                return validator.VerifySignature(publickey, payload, signature.First(), timestamp.First());

            }
            else
            {
                return false;
            }

        }
        

        private async Task<string> GetPayloadAsync(HttpContent content)
        {
            string postData;
            using (var stream = new StreamReader(await content.ReadAsStreamAsync()))
            {
                stream.BaseStream.Position = 0;
                postData = await stream.ReadToEndAsync();
            }
            return postData;
        }        
    }
}

**Comment by thinkingserious** [comment]
We do not have a temporary fix currently. For now, I suggest that you add a thumbs-up to the issue [here](https://github.com/starkbank/ecdsa-dotnet/issues/10).

**Comment by TomLingWu** [comment]
@aadilwani  I have the exact same issue. 
@thinkingserious Is it legal to copy the source code since the license is MIT?
https://raw.githubusercontent.com/sendgrid/sendgrid-csharp/main/src/SendGrid/Helpers/EventWebhook/RequestValidator.cs

If so, then it's the workaround for now.
