### ISSUE TITLE
Is there a way to make the template payload case insensitive?

### ISSUE THREAD

**Issue by plamber** [sendgrid/sendgrid-csharp#1058]
### Issue Summary
We are using dynamic templates to send mails. We are passing a dynamic object using the "SendGridMessage" SetTemplateData method. 

Handlebars used in the dynamic template is using the properties passed by the method above. These properties seem to be case sensitive.

We are wondering if it is possible to tell the API and SendGrid to interpret the properties in a case-insensitive way?

Thank you very much,
Patrick

**Comment by eshanholtz** [comment]
No, this is not possible. All template keys are case sensitive by design. For more information on handlebar substitution, please see our [Handlebars Reference Guide](https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/#handlebars-reference).

**Comment by plamber** [comment]
@eshanholtz: Thank you for the feedback
