### ISSUE TITLE
Cannot delete file after embedding image to mail

### ISSUE THREAD

**Issue by twilly86** [sendgrid/sendgrid-csharp#106]
I'd like to clean up files that were just attached to an email and sent out.

After Web.Deliver() is called, I'm trying to delete the files that were embeded and attached to the email, however I get this following error..

"A first chance exception of type 'System.IO.IOException' occurred in mscorlib.dll

Additional information: The process cannot access the file 'C:\Users\Tom\AppData\Local\Temp\EmailImages\578189429.png' because it is being used by another process."

Using the following code to do attachments..

mail.AddAttachment(attachment.ContentStream, attachment.Name);
mail.EmbedImage(attachment.Name, image.ImageId);

Should FileStream be released here?

https://github.com/sendgrid/sendgrid-csharp/blob/6b2ed696bcd3f9409b1f7a5bef3ce41086f2df85/SendGrid/SendGridMail/Transport/Web.cs#L104

**Comment by twilly86** [comment]
It turns out it was my fault when I created the image, I wasn't closing the filestream and this prevented me from deleting the file.

**Comment by brandonmwest** [comment]
Glad you figure it out and thanks for the PR, I'll check it out!
