### ISSUE TITLE
SendGridMessage serialization changed (backwards incompatible)

### ISSUE THREAD

**Issue by duncanchung** [sendgrid/sendgrid-csharp#1063]
### Issue Summary

Pull request #938 has broken existing serialization behavior on the SendGridMessage.

### Steps to Reproduce

See code snippets.

### Code Snippet

```csharp
            JsonConvert.DefaultSettings = () =>
            {
                return new JsonSerializerSettings()
                {
                    ContractResolver = new CamelCasePropertyNamesContractResolver()
                };
            };

            var message = new SendGridMessage();
            message.SetTemplateData(new { FirstName = "Joe" });
            Console.WriteLine(message.Serialize());

```

Now, this code using version `9.12.0` shows:

```
{"personalizations":[{"dynamic_template_data":{"firstName":"Joe"}}]}
```

but using version `9.21.1` shows:

```
{"personalizations":[{"dynamic_template_data":{"FirstName":"Joe"}}]}
```

Note the difference in the casing of the `f` in `firstName`.  This breaks passing data to existing email templates.

### Technical details:
* sendgrid-csharp version: 9.21.1
* csharp version: net core 3.1

**Comment by eshanholtz** [comment]
The PR is in our backlog for review.
