### ISSUE TITLE
Email templated message to distributions lists

### ISSUE THREAD

**Issue by NickMoores** [sendgrid/sendgrid-csharp#1065]
I have been struggling on the best way to do this for a while, but haven't posted this question here yet.

Our business has a few hundred clients, all of which are signed up to receive emails from us. We send out approximately 10-20 emails to this group per day. The emails contain information like broadcast schedules and news story summaries, so they need to be sent out promptly and reliably.

The email content is very data driven. Whether it's a broadcast schedule or a story summary, there's a very strict structure to the email. In other words, they're ideal candidates for templating. They are also written up in an external tool, and we don't want to change this; we're looking to integrate the tool with SendGrid so that they can trigger the email delivery from the tool.

We're keen to use SendGrid's suppression lists too so that we can provide our customers the ability to unsubscribe, should they wish.

I have identified a couple of ways to do this with SendGrid:

1. Use dynamic templates. Store contacts externally, so that when we call the API to send an email we can provide the list of recipients. When we exceed 1000 contacts on our lists, multiple API calls will need to be made, as calls to send emails support a maximum of 1000 recipients.

2. Use marketing campaigns. Use SendGrid's contact lists. Create single sends via the API, but construct and provide the content of the single send ourselves.

The dilemma I've got is that I'd love to use both dynamic templates and contact lists, but it seems impossible to use both features together - have I got that right, or am I missing something?

**Comment by thinkingserious** [comment]
Hello @NickMoores,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
