### ISSUE TITLE
RequestAsync  no  hay  ninguna respuesta de sengrid

### ISSUE THREAD

**Issue by marcosss2018** [sendgrid/sendgrid-csharp#1067]
hola,  realizo envios a sendgrid desde mi webapi:  de 500 mails cada 5 minutos y en algunos envíos **No hay ninguna    respuesta de sengrid**.  

cual puede ser el problema? 

```csharp
 try
            {
                Mylogger.Logger.Instance(this).Info("iniciando envio a Sendgrid ");
                var response = await clienteSend.RequestAsync(SendGridClient.Method.POST,
                                                     json.ToString(),
                                                     urlPath: "mail/send").ConfigureAwait(false);

                Mylogger.Logger.Instance(this).Info("fin sendgrid");
                return response;
            }
            catch(Exception ex)
            {
                Mylogger.Logger.Instance(this).Error("error al Procesar envio a sendgrid[" + ex.Message + "]", ex);

            }    
```

**Comment by thinkingserious** [comment]
Hello @marcosss2018,

Could you please provide us with your [request body](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#request-body) so that we may try to troubleshoot?

Thanks you!

With best regards,

Elmer

---

Hola @ marcosss2018,

¿Podría proporcionarnos su [cuerpo de la solicitud] (https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#request-body) para que podamos intentar solucionar el problema?

¡Gracias!

Con los mejores deseos,

Elmer

**Comment by marcosss2018** [comment]
Hola gracias por tu respuesta...  primero que nada quiero consultarte si esta bien como estoy llamando  sendgrid desde mi webapi con:
..
 var  respuesta  =  aguardar  clienteSend . RequestAsync ( SendGridClient . Método . POST ,
                                                      json . ToString (),
                                                      urlPath : " mail / send " ). ConfigureAwait ( falso)
.....

el problema es aleatorio: realizo un envio cada 5 minutos, en cada envio van 500 mails en un solo Json y a veces algún envio no sale pero tampoco recibo ningún error por parte de sendgrid y si vuelvo reenviar ,  el mismo se envia sin problemas.

es por esto que no tengo ningun error para pasarles. 

Por eso quiero estar seguro que estoy utilizando el metodo RequestAsyng Correctamente o me esta faltando algo mas

Por favor espero su respuesta. 

Gracias

**Comment by thinkingserious** [comment]
Hello @marcosss2018,

If you are [calling the API from a UI](https://github.com/sendgrid/sendgrid-csharp/blob/82c31f13f6dd3f66c9c7fb775557119ee68e22cb/TROUBLESHOOTING.md#ui-requests-are-failing--deadlocks), then yes. Otherwise, [this](https://github.com/sendgrid/sendgrid-csharp/blob/main/USE_CASES.md#send-a-single-email-to-a-single-recipient) may be the correct method for your application.

---

Si está [llamando a la API desde una interfaz de usuario] (https://github.com/sendgrid/sendgrid-csharp/blob/82c31f13f6dd3f66c9c7fb775557119ee68e22cb/TROUBLESHOOTING.md#ui-requests-are-failing--deadlocks), entonces sí. De lo contrario, [this] (https://github.com/sendgrid/sendgrid-csharp/blob/main/USE_CASES.md#send-a-single-email-to-a-single-recipient) puede ser el método correcto para su aplicación.

**Comment by marcosss2018** [comment]
Hola, muchas Gracias !!! 

 yo estoy llamando a la api desde una WEBAPI (SERVICIO) ,tengo creado un template y armo un json para enviar a varios destinatarios.  Del link que me compartiste anteriormente, estaría usando el caso  without-mail-helper-class [https://github.com/sendgrid/sendgrid-csharp/blob/main/USE_CASES.md#without-mail-helper-class](url), pero yo uso ConfigureAwait (false) en la invocacion del metodo RequestAsync ( y en without-mail-helper-class no se usa).   Mi json ejemplo que uso es el siguiente: 


{"personalizations":[
	{
		"to":[
			{"email":"prueba1@gmail.com",
              "name":"Marcos"				
			}
            ],
          "dynamic_template_data": {
                 "clave1":"3333333301",
                 "link": "http:link_ejemplo.com"   
            }, 
         "subject":"probando !!!!"
		},
        {
		"to":[
			{"email":"prueba2@gmail.com",
              "name":"Marcos2"				
			}
            ],
          "dynamic_template_data": {
                 "clave1":"2222222201",
                 "link": "http:link_ejemplo2.com"   
            }, 
         "subject":"probando !!!!"
		},
     
    {
		"to":[
			{"email":"prueba3@gmail.com",
              "name":"Marcos3"				
			}
            ],
          "dynamic_template_data": {
                 "clave1":"2222222201",
                 "link": "http:link_ejemplo3.com"   
            }, 
         "subject":"probando !!!!"
		}
],

"from":{"email":"marcos@mail.com","name":"Marcos y "},
"reply_to":{"email":"marcos@mail.com","name":"Marcos y"},
 "template_id":"d-3333333xxxxxxxxxxxxxxxxx"
}


consulta:  RequestAsync se usa o no se usa en webapi (servicios)?
                Si tengo que usar si o si SendEmailAsync,  puedo enviar el mismo json con este metodo ?


Gracias por tu tiempo !!!

**Comment by marcosss2018** [comment]
dato: hoy mande 9279 mails en  19 envios (de 500) y  solo uno no tuvo respuesta de sengrid y luego de volver a enviar el mismo...se envio sin tener problemas

**Comment by eshanholtz** [comment]
Me alegra que haya podido enviar correos electrónicos con éxito hoy. Esto no parece ser un problema con la biblioteca de ayuda, por lo que si sigue teniendo problemas para enviar correos electrónicos en el futuro, [comuníquese con el servicio de atención al cliente para obtener más ayuda](https://support.sendgrid.com/hc/en-us).

**Comment by marcosss2018** [comment]
hola, el problema nunca se resolvio, no se por que serraron este caso,  por favor pueden darme una solucion, sino tendre que abrir otro caso con el mismo tema.

**Comment by marcosss2018** [comment]
gracias por abrir el caso nuevamente... espero puedan orientarme  para ver que problema sucede

**Comment by eshanholtz** [comment]
Mis disculpas, entendí mal su último mensaje.
Creo que no entiendo la pregunta "consulta: RequestAsync se usa o no se usa en webapi (servicios)?". ¿De qué webapi estás hablando?
Debería poder usar RequestAsync para enviar sus correos electrónicos y no veo ningún problema con su uso. [SendEmailAsync es solo un ayudante que envuelve RequestAsync](https://github.com/sendgrid/sendgrid-csharp/blob/main/src/SendGrid/BaseClient.cs#L232), y esa implementación es muy similar a cómo la estás usando. Tu json se ve perfectamente bien para mí.

Debido a que no veo ningún problema con su uso de sendgrid-csharp, no creo que este sea un problema con el que podamos ayudarlo aquí. [Comuníquese con el servicio de atención al cliente de SendGrid para obtener más ayuda para resolver este problema.](https://support.sendgrid.com/hc/en-us)
