### ISSUE TITLE
Google Structured Data doesn't work in emails.

### ISSUE THREAD

**Issue by oleg-endovitsky** [sendgrid/sendgrid-csharp#1068]
Hello everyone.
I'm trying to send an email with an event reservation.

The first issue is that when I insert a script into my html template `<script type = "application / ld + json">` then when saving dynamic template script tag is deleted for some reason.

The second: I am trying to use `microdata` instead of a script as in the code below. In the letter that I receive, there are no events that would be automatically added to the calendar. Can anyone help with this?

I want the event to be automatically added to the Google calendar.

```
<div class="event-wrapper" itemscope itemtype="https://schema.org/Event">
    <div class="event-date" itemprop="startDate" content="2020-11-18T21:30">
        Wed Nov 18
    </div>
    <div class="event-title" itemprop="name">
        Typhoon with Radiation City
    </div>
    <div class="event-venue" itemprop="location" itemscope itemtype="https://schema.org/Place">
        <span itemprop="name">The Hi-Dive</span>
        <div class="address" itemprop="address" itemscope itemtype="https://schema.org/PostalAddress">
            <span itemprop="streetAddress">7 S. Broadway</span><br>
            <span itemprop="addressLocality">Denver</span>, <span itemprop="addressRegion">CO</span> <span itemprop="postalCode">80209</span>
        </div>
    </div>
    <div class="event-time">9:30 PM</div>
    <div itemprop="offers" itemscope itemtype="https://schema.org/Offer">
        <div class="event-price" itemprop="price" content="13.00">$13.00</div>
        <meta itemprop="priceCurrency" content="USD"><a itemprop="url" href="http://www.ticketfly.com/purchase/309433">Tickets</a>
    </div>
</div>
```

**Comment by thinkingserious** [comment]
Hello @oleg-endovitsky,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
