### ISSUE TITLE
Body Enocding settings in new C# SendGrid API libraries

### ISSUE THREAD

**Issue by Aarthi-Saba** [sendgrid/sendgrid-csharp#1069]
<img width="233" alt="View Entire Msg" src="https://user-images.githubusercontent.com/57509085/100016715-d8803000-2da7-11eb-8add-69493d5bf624.PNG">
Using SendGrid for mail functionality in client portal

Recently updated the mail settings as per the latest SendGrid API requirement (using SendGrid API Key instead of username and password), installed the necessary libraries 

An HTML content is sent over the mail content in English and Spanish.

Previously there were options to choose BodyEncoding of the mail and setting it to ASCII / UTF8 helped us

In the latest API libraries, unable to find such settings.

The HTML content in English is sent correctly to gmail ids.

But the Spanish HTML content is clipped and 'View Entire Message' option is included at the bottom of the gmail.

Kindly let me know what type of settings in API library is needed for the mail to not get clipped for Spanish.

* sendgrid-csharp version: 9.21.2
* csharp version: C# 5.0

**Comment by shwetha-manvinkurke** [comment]
Hi @Aarthi-Saba, 

Are you using the sendgrid-csharp helper library to send the emails? If so, could you show me the code you have to do so, so I can reproduce the issue? 

Thanks,
Shwetha
