### ISSUE TITLE
I don't want to create templates in Sendgrid , is it possible I can read them in my code

### ISSUE THREAD

**Issue by aadilwani** [sendgrid/sendgrid-csharp#1070]
I don't want to create templates in Sendgrid , is it possible I can read them in my code
 Instead of doing   msg.SetTemplateId(templateId);  is is possible i can do something like  **msg.SetTemplate("C:\template.html")**
                    msg.SetTemplateData(templateSubstitutions);

**Comment by eshanholtz** [comment]
No, this is not possible. You would have to [POST your template to SendGrid first](https://github.com/sendgrid/sendgrid-csharp/blob/7343b4b5d398a37e6302b06492cfabe1db69c928/examples/templates/templates.cs#L11) then use the `id` given in the response in `msg.SetTemplateId(id);`
