### ISSUE TITLE
Mail not landed When From and To address are in SameDomain

### ISSUE THREAD

**Issue by mars-boy** [sendgrid/sendgrid-csharp#1072]
### Issue Summary
I tried to send an Email from my domain lets say "frommail@abc.com" to "tomail@abc.com" mail is not landed in respective 
mail box. 

### Steps to Reproduce
1. Authenticate the Domain
2. Send an  email within domain like from: 'fromuser@abc.com' to: 'touser@abc.com' 
3. Make sure both the emails are valid.

### Code Snippet
```
            var apiKey = "apikey";
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("fromtest@abc.com");
            var subject = "Sendgrid Sample Subject";
            var to = new EmailAddress("touser@abc.com");
            var to2 = new EmailAddress("touser2@abc.com");
            var to3 = new EmailAddress("touser3@abc.com");
            var plainTextContent = "Sendgrid Sample Body";
            var htmlContent = "<strong>Sendgrid Sample Body <a href='http://www.google.com'>google</a> </strong>";
            var msg = MailHelper.CreateSingleEmailToMultipleRecipients(from, new List<EmailAddress>{ to, to2, to3 }, subject, 
                              plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg).ConfigureAwait(false);
```

### Technical details:
* sendgrid-csharp version: 9.21.2
* csharp version: Dotnet core 3.1

**Comment by JenniferMah** [comment]
@mars-boy 
Are you receiving any error messages when you execute the code sample above? Please refer to our [troubleshooting guide](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#error-messages) to print any errors and include them in your response.

**Comment by mars-boy** [comment]
Hi @JenniferMah, Thanks for the reply but I don't see any error log when sending a mail. Looks like there's open question stackoverflow too 

https://stackoverflow.com/questions/54104691/not-able-to-send-mails-to-the-same-domain-using-sendgrid-api

But, I am using domain that I have created recently just for checking sendgrid.

**Comment by thinkingserious** [comment]
Hello @mars-boy,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
