### ISSUE TITLE
I want to send multiple emais to multiple recipients with same cc email address.

### ISSUE THREAD

**Issue by PrashantVasava** [sendgrid/sendgrid-csharp#1074]
I was trying out the code in doc where mails are send to multiple recipients but not allow those recipients to see each other.

I have common mail which has to be added as cc for all recipients as below:

personalizations: [
{
  to: 'xxx@gmail.com',
  subject: 'Test Mail',
  cc: [{'email':'zzz@gmail.com'},{'email':'yyy@gmail.com'}]
},
{
  to: 'aaa@gmail.com',
  subject: 'Test Mail',
   cc: [{'email':'zzz@gmail.com'},{'email':'yyy@gmail.com'}]
},
{
  to: 'bbb@gmail.com',
  subject: 'Test Mail',
   cc: [{'email':'zzz@gmail.com'},{'email':'yyy@gmail.com'}]
}
]

Suppose my mail was 'zzz@gmail.com', I received only one mail from all three. How can I resolve this.

**Comment by JenniferMah** [comment]
Hi @PrashantVasava
It sounds like the goal is to send multiple emails to multiple recipients. Please refer to this [example](https://github.com/sendgrid/sendgrid-csharp/blob/main/USE_CASES.md#send-multiple-emails-to-multiple-recipients) to see how to send to multiple emails to multiple recipients. You should be able to add cc emails with the `msg.AddCc(new EmailAddress(email,name))` function after the message is created.
