### ISSUE TITLE
Debugging HandleBars Templates/NotDelivered Email

### ISSUE THREAD

**Issue by andreqb** [sendgrid/sendgrid-csharp#1075]
### Issue Summary

I have an email template that can not be delivered through the api - the http call returns 202 /Accepted but when checking the activity log in the UI I get a NotDelivered message.  I talked to support - they sent me here, they said that the problem is with the handlebars template and they can not provide support for that.  My question is out side of changing variables one by one is there a better way to be able to debug through this issue - like is there a place that I can see error messages or something like that?

### Steps to Reproduce
Call Api with template parameters

### Technical details:
* sendgrid-csharp version:  Latest
* csharp version: 8

**Comment by JenniferMah** [comment]
@andreqb 
Have you had the chance to checkout our [trouble shooting guide](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#error-messages)? You should be able to log the [error messages](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#error-messages) and [request body](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#viewing-the-request-body) to help debug.

**Comment by andreqb** [comment]
Thank you @JenniferMah I am not getting an error in the api call.  The error that I see is in the SendGrid UI - is there a support guide for trouble shooting accepted ui calls?

**Comment by eshanholtz** [comment]
@andreqb Can you please provide an example of the template you're using as well as the code you're using to pass in the tempalate information?
