### ISSUE TITLE
DeserializeResponseBodyAsync takes parameter?

### ISSUE THREAD

**Issue by worthy7** [sendgrid/sendgrid-csharp#1081]
https://github.com/sendgrid/sendgrid-csharp/blob/3bb16b428b828ac0d931f0ca0f8b88dc672c955f/src/SendGrid/Response.cs#L110

Isn't this supposed to reference `this.body`? Why does it need HttpContent to be input as a parmeter?

Is it supposed to be an extension method instead?

**Comment by eshanholtz** [comment]
I believe you're correct, this method should not take an input parameter and instead deserialize `this.body`. This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by philrowan-mtb** [comment]
Simlarly, https://github.com/sendgrid/sendgrid-csharp/blob/3bb16b428b828ac0d931f0ca0f8b88dc672c955f/src/SendGrid/Response.cs#L122 should remove the `content` parameter and refer to `this.headers`

**Comment by Wind010** [comment]
PR Opened:
https://github.com/sendgrid/sendgrid-csharp/pull/1151
