### ISSUE TITLE
Not able to send mail from web application MVC c# : Response: Bad request : using "SendEmailAsync"  Response: Id = 8, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"  using "RestClient"  

### ISSUE THREAD

**Issue by kaustubhbagwe123** [sendgrid/sendgrid-csharp#1082]
@sendgrid-ci  
@sendgrid-security 
@SendGridDX 

### Issue Summary
Response: Bad request

Not able to send mail from MVC c# web application : 
getting following error 
 Response: Bad request : using "SendEmailAsync"  Response: Id = 8, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"  using "RestClient"  

               
// RestClient
	 var client = new RestClient("https://api.sendgrid.com/v3/mail/send");
                client.Timeout = -1;
                var request = new RestRequest(Method.POST);
                request.AddHeader("Authorization", "Bearer SendGridToken"); // Full access token
                request.AddHeader("Content-Type", "application/json");
                request.AddParameter("application/json", "{\"personalizations\":[{\"to\":[{\"email\":\"jhon@abc.com\"}]}],\"from\":{\"email\":\"abc@xyz.com\"},\"subject\":\"testing Mail for api key implementation\",\"content\":[{\"type\":\"text/plain\",\"value\":\"tesing login \"}]}", ParameterType.RequestBody);
                IRestResponse response = client.Execute(request);
                Console.WriteLine(response.Content);

### Steps to Reproduce
1. Use above code in any MVC application with out static class
2. Run the code 
3. same error will be thorwn.

### Code Snippet
```csharp
// RestClient
	 var client = new RestClient("https://api.sendgrid.com/v3/mail/send");
                client.Timeout = -1;
                var request = new RestRequest(Method.POST);
                request.AddHeader("Authorization", "Bearer SendGridToken"); // Full access token
                request.AddHeader("Content-Type", "application/json");
                request.AddParameter("application/json", "{\"personalizations\":[{\"to\":[{\"email\":\"jhon@abc.com\"}]}],\"from\":{\"email\":\"abc@xyz.com\"},\"subject\":\"testing Mail for api key implementation\",\"content\":[{\"type\":\"text/plain\",\"value\":\"tesing login \"}]}", ParameterType.RequestBody);
                IRestResponse response = client.Execute(request);
                Console.WriteLine(response.Content);

```

### Exception/Log
```
using "SendEmailAsync"  Response: Id = 8, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"  using "RestClient"   Response: Bad request
```

### Technical details:
* sendgrid-csharp version: SendGrid 9.22.0
* csharp version: 4.5

### Note : 
 We are not using any static method for this implementation
 We are not using this as a back job , we are implementing this as a method. 

Please help us to get out of this error.

**Comment by thinkingserious** [comment]
Hello @kaustubhbagwe123,

Could you please try to capture the error message from the Bad request, [like so](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#error-messages)?

Thank you!

With best regards,

Elmer
