### ISSUE TITLE
Intermittent Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by meagy** [sendgrid/sendgrid-csharp#1084]
### Issue Summary
We began receiving these intermittent TLS errors while sending emails via SendGrid libraries in both our live and test environments sometime around 12/24/2020. These errors are occurring in multiple datacenters with separate networks (public cloud and private datacenter), and do not correspond with code, library, or environment changes on our end.

After putting in a ticket to SendGrid support they suggested posting a thread here for the issue to rule out code/library issues. 

Our current issue sounds a lot like the below GitHub problem from a few years ago. The resolution for this issue was to contact SendGrid support.
https://github.com/sendgrid/sendgrid-csharp/issues/505 

I suspect this problem is on the SendGrid infrastructure side but am posting here to get your thoughts.

Details are below.
* Error seen from one of our applications .NET 4.8 application logs:
Error - System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

* In both our live and test environments we are using class libraries to make the calls into the SendGrid system to send emails. Our live environment is using SendGrid.Net40 version 5.1.0.0 and SendGrid.SmtpApi 1.1.3. Our lower test environments are currently using SendGrid 9.22.0.0. We began seeing the TLS errors in all of these environments and with all packages listed above. 

*We have been using the SendGrid.Net40 version 5.1.0.0 and SendGrid.SmtpApi 1.1.3 library versions for quite some time in our live production environment and have not changed code or upgraded versions recently. The SendGrid 9.22.0.0 library used in our lower environments is for some newer development we're working on. As far as we can tell the errors began occurring sometime around 12/24/2020 in all of our environments.

* For one of our main .NET applications we profiled we  saw 428 errors from 8 separate servers from 1/1/2021-1/4/2021. These errors appear to be intermittent as the failures are not occurring every time an API call/email send is attempted.

### Steps to Reproduce
1. Call the SendEmailAsync method
2. Some calls will fail intermittently with the below SSL/TLS error.

### Code Snippet
```csharp
                        await client.SendEmailAsync(email);
```

### Exception/Log
```
Error - System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
```

### Technical details:
* sendgrid-csharp version: 
SendGrid.Net40 version 5.1.0.0
SendGrid.SmtpApi 1.1.3
SendGrid 9.22.0.0

* csharp version: 
Framework 4.8

**Comment by Jericho** [comment]
As you have pointed out, you're not the only one to report this intermittent problem. There's about a half dozen issues regarding this problem in this repo: [here](#1049), [here](#976), [here](#404), [here](#214) and [here](#100). I'm sure you would find even more issues if you looked in SendGrid's repos for their PHP, Python, Java, Node, etc clients. Developers even reported the exact same problem when using 3rd party C# clients such as StrongGrid ([here](https://github.com/Jericho/StrongGrid/issues/254)).

Clearly this problem has nothing to do with the particular client being used by the developer. It's discouraging that developers are being told to contact support and support tells you to raise an issue in this repo.

The typical answer when you contact SendGrid regarding this topic is a variation of something like this:
> Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at

or this:
> We have seen this error before with other clients and in those cases, they were using old versions of .dll files. Is it possible that applies to you? There have been some updates to that library over the past few months and I know that some of our API calls have been updated and the newer library should reflect this. It may be worth making sure that your library is up to date so that we can make sure you're making the most up to date calls to SendGrid.

or this:
> I chalk this up as a transient network issue. Best to employ a retry strategy for such failures. Not sure there's anything we can/should do in this library.

SendGrid seems intent on blaming the developer's code and/or the library (either SendGrid's own or 3rd party) but there's no motivation on their part to get to the bottom of this intermittent problem. I fully understand that intermittent problems are hard to investigate and diagnose, but I haven't seen any indication that they have invested any time at all looking into the problem.

Anyway, sorry for the rant. I realize it's not really helping you but I just wanted to let you know that you are not alone!

**Comment by thinkingserious** [comment]
Hello @meagy,

Could you please let us know what your support ticket number is? 

Thank you @Jericho for taking the time to provide the additional context!

With best regards,

Elmer

**Comment by meagy** [comment]
> Hello @meagy,
> 
> Could you please let us know what your support ticket number is?
> 
> Thank you @Jericho for taking the time to provide the additional context!
> 
> With best regards,
> 
> Elmer

Hi Elmer, the support request number is #5638063
-Matt

**Comment by thinkingserious** [comment]
Thank you @meagy!

I'll keep you posted on our findings.

**Comment by thinkingserious** [comment]
Hello @meagy,

The support team has been made aware of this thread and is continuing investigation through your support ticket. Thank you!
