### ISSUE TITLE
Technical Question: What is the coded workflow to create a User Account

### ISSUE THREAD

**Issue by TaviTruman** [sendgrid/sendgrid-csharp#1085]
I'm certain this is possible with the C# SDK; what is the coded workflow to create a User Account. I've seen examples that demonstrate Update, Read, and Delete user accounts but none that demonstrate how to create a new User Account.

**Comment by thinkingserious** [comment]
Hello @TaviTruman,

We do not provide a means to create a user account via API.

Are you referring to creating a subuser account? If so, [here](https://github.com/sendgrid/sendgrid-csharp/blob/main/USAGE.md#create-subuser) is an example.

With best regards,

Elmer

**Comment by TaviTruman** [comment]
Oh my - as an ISV that means that we would need to hire someone just to administer user accounts for all of our users. That slows our on-boarding process and our users will not view this as an enjoyable user experience. We don't use the SendGrid WebUI so that is a gating issue for us.

**Comment by MarioAument** [comment]
> Oh my - as an ISV that means that we would need to hire someone just to administer user accounts for all of our users. That slows our on-boarding process and our users will not view this as an enjoyable user experience. We don't use the SendGrid WebUI so that is a gating issue for us.

Hi @TaviTruman , how you solve this ? We have the same issue and don't have help from sendgrid support team, can you give us a clue?
