### ISSUE TITLE
Embed Image function -- how to implement this deprecated feature

### ISSUE THREAD

**Issue by nagstaku** [sendgrid/sendgrid-csharp#1091]
### Issue Summary
Previously, in version 5.1.0 of the sendgrid libraries I could use the EmbedImage() function to add embedded images. I can't find any mention of deprecation or work arounds for embedding images now.

### Steps to Reproduce
1. Below is the previous method of embedding images

### Code Snippet
```csharp
var myMessage = new SendGridMessage();
myMessage.Html = "Test <img src=\"cid:foo\">";
myMessage.AddAttachment(System.Web.Hosting.HostingEnvironment.MapPath(@"~/Content/Images/foo.png"));
myMessage.EmbedImage("emailLogo.png", "logo");
```

### Technical details:
* sendgrid-csharp version: 5.1.0 (working version, now on 9.22.0)
* csharp version: 7.0

**Comment by shwetha-manvinkurke** [comment]
Have you tried the example [here](https://github.com/sendgrid/sendgrid-csharp/blob/main/USE_CASES.md#kitchen-sink---an-example-with-all-settings-used)? 

```csharp
var attachments = new List<Attachment>()
{
    new Attachment()
    {
        Content = "base64 encoded string",
        Type = "image/png",
        Filename = "image.png",
        Disposition = "inline",
        ContentId = "Banner"
    }
};
msg.AddAttachments(attachments);
```

**Comment by nagstaku** [comment]
It worked like a charm -- even gmail renders the inline image.

You are the wind beneath my wings Swetha!

I will see about creating a documentation PR for attachments 🥳
