### ISSUE TITLE
Mistake in README.md

### ISSUE THREAD

**Issue by bajtekv** [sendgrid/sendgrid-csharp#1099]
Sorry for weird issue styling. **I have found mistake in README.md**

[Here](https://github.com/sendgrid/sendgrid-csharp/#setup-environment-variables-to-manage-your-api-key) 

Setup Environment Variables using CMD:

Run CMD as administrator
set SENDGRID_API_KEY "YOUR_API_KEY"  <--- this should be:     `set SENDGRID_API_KEY=SG.TFEayMR8R......`

**Comment by JenniferMah** [comment]
Hi @bajtekv thanks for bringing this to our attention! Can you submit a PR with your suggested fix?
