### ISSUE TITLE
Bad Request - No Error Array in Exception

### ISSUE THREAD

**Issue by RollingWave** [sendgrid/sendgrid-csharp#110]
Intermittently we are receiving the following error via the C# SDK when sending emails.  I suspect that an element of the email is not valid however, after reviewing failed examples, I'm not able to determine what element could cause the failure.  The error message returned is, 

> Bad Request Check 'Errors' for a list of errors returned by the API.

How can I check the 'Errors' to review the detail necessary to diagnose?  The array of errors are not included in the exception however appear to be available response back to the SDK.

Background:
Sendgridmail v4.0.30319
Sendgrid.SMTPAPI v4.0.30319

We are not using the X-SMTPAPI.

**Comment by isaldarriaga** [comment]
try with this.. i capture the error in the try/catch block when calling Web.DeliveryAsync and assign the exception to a DeliveryException member of my class for further review. boolean "delivery" is also set to true.

public string getDeliveryError()
        {
            string error = "";
            if (!delivered && this.DeliveryException != null)
            {
               if (this.DeliveryException.GetType() == typeof(AggregateException))
               {
                   foreach (Exception ex in ((AggregateException)this.DeliveryException).InnerExceptions)
                   {
                       if (ex.GetType() == typeof(Exceptions.InvalidApiRequestException))
                       {
                           HttpStatusCode code = ((Exceptions.InvalidApiRequestException)ex).ResponseStatusCode;
                           string strCode = ((byte)code).ToString();
                           error += "\nSTATUS CODE: " + strCode + " " + code.GetDescription();
                           error += "\n\nERRORS: ";
                           foreach (string err in ((Exceptions.InvalidApiRequestException)ex).Errors)
                           {
                               error += "\n" + err;
                           }
                       }
                       else
                       {
                           error += "\n" + ex.Message;
                       }
                   }
               }
               else
               {
                   error += "\nERROR: " + this.DeliveryException.Message;
               }
            }
            return error;
        }

**Comment by brandonmwest** [comment]
```csharp
public string getDeliveryError()
        {
            string error = "";
            if (!delivered && this.DeliveryException != null)
            {
               if (this.DeliveryException.GetType() == typeof(AggregateException))
               {
                   foreach (Exception ex in ((AggregateException)this.DeliveryException).InnerExceptions)
                   {
                       if (ex.GetType() == typeof(Exceptions.InvalidApiRequestException))
                       {
                           HttpStatusCode code = ((Exceptions.InvalidApiRequestException)ex).ResponseStatusCode;
                           string strCode = ((byte)code).ToString();
                           error += "\nSTATUS CODE: " + strCode + " " + code.GetDescription();
                           error += "\n\nERRORS: ";
                           foreach (string err in ((Exceptions.InvalidApiRequestException)ex).Errors)
                           {
                               error += "\n" + err;
                           }
                       }
                       else
                       {
                           error += "\n" + ex.Message;
                       }
                   }
               }
               else
               {
                   error += "\nERROR: " + this.DeliveryException.Message;
               }
            }
            return error;
        }
```
