### ISSUE TITLE
Cannot send emails using Azure and Visual Studio website

### ISSUE THREAD

**Issue by tmataya10** [sendgrid/sendgrid-csharp#1101]
I reviewed the document Azure documentation for c# configuration with SendGrid API Keys.  I have done everything that the document suggested.  Below are the screen shots.  Please help.  My customer is getting quite upset at not having the website fully functional!  Can’t you see that I am trying to send an email with your tracking software?? Is there no record of an attempt to send???  I will also create a issue on Github repo.  (THIS IS IT)

Here I have created an API Key in your SendGrid software
 

Here is the Application settings (SENDGRID_APIKEY)
![image](https://user-images.githubusercontent.com/68469815/114197682-6d269d00-9907-11eb-8e63-a29c487d53c0.png)

 

Now, the C# code
```csharp
using SendGrid;
using SendGrid.Helpers.Mail;
using System.Threading.Tasks;


            Execute(TXT_From.Text, WV[0].Verbiage.Trim(), WV[1].Verbiage.Trim(), strInquiry,
                         WV[2].Verbiage.Trim(), WV[3].Verbiage.Trim()).Wait();

        static async Task Execute(string strFrom, string strFromD, string strSubject,
                                                string strInquiry, string strTo, string strToD)
        {
            var pswd = "password";
            var credentials = new System.Net.NetworkCredential("plateauartsalive@outlook.com", pswd);
            var apiKey = System.Environment.GetEnvironmentVariable("SENDGRID_APIKEY");
            var client = new SendGridClient(apiKey);
            var msg = new SendGridMessage()

            {
                From = new EmailAddress(strFrom, strFromD),
                Subject = strSubject,
                PlainTextContent = strInquiry
            };

            msg.AddTo(new EmailAddress(strTo, strToD));
            await client.SendEmailAsync(msg);
```
It still locks up the page waiting for a response which never comes.  Below is the URL and a screen shot of the process
URL: plateauartsalive.azurewebsites.net)

After the page loads, click on the (Contact) tab at the top of the page
![image](https://user-images.githubusercontent.com/68469815/114197764-84658a80-9907-11eb-8fc5-1dd7daf50328.png)

 

Fill in the information and then tap the (Send) button to see the results, a spinning jpeg awaiting a return of success never finishes

 
![image](https://user-images.githubusercontent.com/68469815/114197818-934c3d00-9907-11eb-81dc-837a8b0e2eaa.png)
![GITHUB2](https://user-images.githubusercontent.com/68469815/114198603-5d5b8880-9908-11eb-8a8f-6fd03852e5f5.jpg)
![GITHUB3](https://user-images.githubusercontent.com/68469815/114198629-63ea0000-9908-11eb-8d5b-f7797309ee87.jpg)
![GITHUB4](https://user-images.githubusercontent.com/68469815/114198650-68161d80-9908-11eb-8c4d-a4bfeaede488.jpg)

Thanks in advance,

Terry Mataya

**Comment by JenniferMah** [comment]
Hi @tmataya10 I've removed the images showing your full API key and strongly suggest you regenerate a new API key to use for development. Can you follow the instructions in our [troubleshooting guide](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#error-messages) to see if any errors are generated when you make the request?

**Comment by tmataya10** [comment]
Jennifer,

I will do so.  I added all the information I could for you to be able diagnose whatever is wrong.  I am assuming that I have done something incorrect, or left something out.  However, I have spent quite a bit of time trying to find out what is incorrect. I am asking for your help so I can get this website up and running.  I am aware of the security issues by sending key data. I can take care of that later.  Right now, I need to be able to send emails.  I will get back to you if there are any errors generated, tomorrow.

Thanks in advance,

Terry

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tmataya10** [comment]
Jennifer,

So, the first thing I tried was to append the     var response = await Client.SendEmailAsync(msg) adding .ConfigureAwait(false);

The next time I ran the sub, the email message popped up right away.

So, having said that, why isn’t that append in all of the documentation that is out there, and what does the ConfigureAwait do??? Thanks for the tip.

Sincerely,

Terry Mataya

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JenniferMah** [comment]
Hi @tmataya10 
Here's a [link to more documentation](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#ui-requests-are-failing--deadlocks) around why we use `ConfigureAwait`. This is normally used when UI requests are failing or becomes deadlocked.

**Comment by tmataya10** [comment]
Jennifer,

I need your help again.  I am not able to send emails yet.  I have contacted Send Grid support and have received the CNAME names and values.  But I tried to put them into Azure with no success.  I am sending you screen copies of both Send Grid and the Azure DNS Zone records.  I tried to find how to delete the records in the DNS Zone with no success.  I am so confused…  BTW, I’m not a network guy if that helps in my defense!!  I can’t seem to delete the DNS Zones in Azure.  The SendGrid help person said to delete all of the zones and add the new ones.  I feel like I’m just not getting this…

Thanks in advance,

Terry Mataya


***@***.***D73041.2FC758C0]

***@***.***D73041.2FC758C0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Terry ***@***.***>
Sent: Friday, April 9, 2021 2:40 PM
To: ***@***.***>
Subject: RE: [sendgrid/sendgrid-csharp] Cannot send emails using Azure and Visual Studio website (#1101)

Jennifer,

So, the first thing I tried was to append the     var response = await Client.SendEmailAsync(msg) adding .ConfigureAwait(false);

The next time I ran the sub, the email message popped up right away.

So, having said that, why isn’t that append in all of the documentation that is out there, and what does the ConfigureAwait do??? Thanks for the tip.

Sincerely,

Terry Mataya

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by shwetha-manvinkurke** [comment]
Hi @tmataya10 I am not sure I follow. In the earlier conversation, you mentioned you could send an email. What changed after? and what's the error you are seeing now? Have you tried logging any of these errors?

**Comment by tmataya10** [comment]
Yes, I can still send.  I need to set up the CNAME and Value that comes from sendgrid.  I don’t exactly how to set it up in Azure.

I will send you a screen shot of what I have done.  I can’t find any good documentation on how to do this.  Some articles show outdated screens that I can’t find.  I appreciate the hand holding until I can get through this. I would like for the DNS to be PAA.com.

I don’t know if I need a Private DNS zone or not?  Help.  Where do I add the CNAME info from Send Grid???

Your help would be appreciated

-terry

***@***.***D73159.72414710]


***@***.***D73159.72414710]

***@***.***D73159.72414710]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by shwetha-manvinkurke** [comment]
@tmataya10 I recommend reaching back to `support.twilio.com` as this doesn't look like a library specific issue to me.
