### ISSUE TITLE
Fails with Newtonsoft.Json v13

### ISSUE THREAD

**Issue by ggrewe** [sendgrid/sendgrid-csharp#1108]
### Issue Summary
With .NetFramework 4.7.2, the dependencies list Newtonsoft.Json (>= 9.0.1).  When Newtonsoft.Json v13.0.1 is installed, the 

### Steps to Reproduce
1. Install Newtonsoft.Json, Version=13.0.1
2. Install SendGrid, File Version: 9.23.1.0, Assembly Version: 9.23.1.0
3. Access the SendGrid DLL

### Code Snippet
```csharp
                SendGridClient client = new SendGridClient(APIkeyHere);
                Response response = await client.SendEmailAsync(_MailMessage);

```

### Exception/Log
```
Message: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	file: :line 0 ```
******* Exception Details **********
	Type: System.IO.FileLoadException
	Message: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	HResult: -2146234304
	Source: SendGrid
	TargetSite: System.String Serialize(Boolean) - SendGrid.dll.Serialize
	Class Defining Member: SendGrid.Helpers.Mail.SendGridMessage
	Member Type: Method
	StackTrace:
   at SendGrid.Helpers.Mail.SendGridMessage.Serialize(Boolean useDefaultSerialization)
   at SendGrid.BaseClient.<SendEmailAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TGBSoftware.TGBEmailUtilities.Clients.SG.EmailClient.<SendEmailAsync>d__16.MoveNext()
	Type: System.IO.FileLoadException
	Message: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	HResult: -2146234304
 ********** Exception Details End **********
	

### Technical details:
* sendgrid-csharp version: 9.23.1.0
* csharp version: .Net Framework 4.7.2

**Comment by shwetha-manvinkurke** [comment]
Hi @ggrewe I'm a little confused. With v13.0.1 installed, do you have references to v9.0.0 and v12.0.0 somewhere in your project?

**Comment by ggrewe** [comment]
![SendGridReferences](https://user-images.githubusercontent.com/83907686/118095427-0e3cc380-b39e-11eb-928d-046dc65684e9.jpg)

> Hi @ggrewe I'm a little confused. With v13.0.1 installed, do you have references to v9.0.0 and v12.0.0 somewhere in your project?

Hello Shwetha,

When we reference version 13.0.1 in our project, the references to v9..0.0. and 12.0.0 are coming from the exception that is thrown when we attempt to send an e-mail in production.  The dependencies list Netwtonsoft >= v9.0.0.  

Attached is a screenshot of our project and the references.  When we update Newtonsoft to version 13.0.x, the exception above is thrown when we send an e-mail.  When version 12.0.0 is used, no exceptions are thrown.

**Comment by shwetha-manvinkurke** [comment]
Have you enabled automatic redirects? [This](https://github.com/twilio/twilio-csharp/issues/431#issuecomment-421478157) might help understand the issue better.

**Comment by ggrewe** [comment]
Hello Shwetha,

This morning I believe that I found the issue.  Someone had added a dependent assembly to the products app.config and it got released that way.  Removing the dependency appears to have resolved the issue.

      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="13.0.0.0" />
      </dependentAssembly>
