### ISSUE TITLE
Improper Character Encoding

### ISSUE THREAD

**Issue by sethgrid** [sendgrid/sendgrid-csharp#111]
Reported on GetSatisfaction, text encoding is incorrect resulting in garbage output.

https://community.sendgrid.com/sendgrid/topics/error-character-encoding-using-template-engine-with-sendgrid-c?utm_source=notification&utm_medium=email&utm_campaign=new_topic&utm_content=reply_button

**Comment by brandonmwest** [comment]
This is fixed in 5.1.0 (or smtpapi-csharp 1.2.0)
