### ISSUE TITLE
Unable to add NuGet package SendGrid 9.23.2

### ISSUE THREAD

**Issue by mkorsukov** [sendgrid/sendgrid-csharp#1114]
### Issue Summary
Unable to add NuGet package SendGrid 9.23.2. Tested on different machines in different countries.

It takes forever in Rider on Windows:

![image](https://user-images.githubusercontent.com/21244808/119689323-5cc27700-be0e-11eb-82e7-938287734f2f.png)

VS 2019 and VS Code failed to add package:

![image](https://user-images.githubusercontent.com/21244808/119689487-81b6ea00-be0e-11eb-9560-11490a4fccb6.png)

### Steps to Reproduce
1. Create a new console project .NET Core 3.1 / 5.0
2. Add NuGet package (CLI or UI)
3. See errors

**Comment by leontev-vyacheslav** [comment]
I was also unable to install the package

**Comment by akunzai** [comment]
Maybe the root cause is the project name conflicted with the package name

Steps to reproduce your issue

```sh
dotnet new console -o SendGrid && cd SendGrid
dotnet add package SendGrid
...
error: NU1108: Cycle detected.
error:   SendGrid -> SendGrid (>= 9.23.2).
```

It should be fine if...

```sh
dotnet new console -o ConsoleApp && cd ConsoleApp
dotnet add package SendGrid
```

## Reference

- https://kmatyaszek.github.io/2019/05/30/nuget-nu1108-cycle-detected.html
- https://github.com/NuGet/Home/issues/6754

**Comment by mkorsukov** [comment]
@akunzai You are right, I have seen that problem in Google search results. My folder was named `SendGrid`, but then I named it `SendGrid1`.

**Comment by mkorsukov** [comment]
@akunzai I tried to reproduce the issue today and it's gone. Closing the issue. Thank you!
