### ISSUE TITLE
Does this library creates batches if recipient is greater than 1000?

### ISSUE THREAD

**Issue by sadiqkhoja** [sendgrid/sendgrid-csharp#1118]
### Issue Summary
I have one more than 1000 recipients, do I have to create batches myself or this library can do the magic itself. Here's my code where `tos` has more then 1000 elements

```
var msg = MailHelper.CreateMultipleEmailsToMultipleRecipients(_fromEmailAddress,
                                  tos,
                                  subjects,
                                  plainTextContent,
                                  htmlContent,
                                  substitutions.ToList()
                                  );
var response = await emailClient.SendEmailAsync(msg);
```

### Technical details:
* sendgrid-csharp version: 9.23.2
* csharp version: .NET Core 3.1

**Comment by thinkingserious** [comment]
Hello @sadiqkhoja,

This helper library does not auto-create the batches for you. However, you may want to check out our [marketing campaigns](https://docs.sendgrid.com/ui/sending-email/how-to-send-email-with-marketing-campaigns) product for the volume of emails you are sending. I also recommend that you reach out to [Twilio SendGrid support](https://support.sendgrid.com/) for further assistance on best practices for sending bulk emails.

With best regards,

Elmer
