### ISSUE TITLE
Send custom headers via Event Webhook

### ISSUE THREAD

**Issue by mayureshs** [sendgrid/sendgrid-csharp#1119]
### Issue Summary
While sending an email through SendGrid I am sending custom headers. I have an Function App listening to Webhook events from SendGrid. But I am not getting those custom headers back in the WebHook events. Is there a way to configure the webhooks to get the custom headers back from SendGrid ?

### Steps to Reproduce
1. Send Email using SendGrid csharp package with custom headers
2. Configure a event Webhook to send back engagement data
3. Unable to configure Webhook to send over custom headers

### Code Snippet
```var client = new SendGridClient("API_KEY");
var from = new EmailAddress("test@example.com", "Example User");
var subject = "Testing with SendGrid API";
var to = new EmailAddress("joe@test.com", "Example User");
var plainTextContent = "Test Content";
var htmlContent = "<strong>Testing with HTML content</strong>";
var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
var identifiers = new Dictionary<String, String>();
identifiers["application"] = "APP_NAME_GOES_HERE";
identifiers["resource"] = "RESOURCE_NAME_GOES_HERE";    
 msg.AddHeaders(identifiers);   
var response = await client.SendEmailAsync(msg);
# paste code here
```

### Technical details:
* sendgrid-csharp version: 9.23.2
* csharp version: .NET core 3.1

**Comment by thinkingserious** [comment]
Hello @mayureshs,

I believe what you need is `AddCustomArgs` ([example](https://github.com/sendgrid/sendgrid-csharp/blob/27effc4c3d7ad1abb55b6f071b5badd438a32f1a/USE_CASES.md#kitchen-sink---an-example-with-all-settings-used)). Please let us know if this solves your issue.

Thank you!

With best regards,

Elmer

**Comment by mayureshs** [comment]
Thanks for the update. That is what I was looking for.
