### ISSUE TITLE
The `SendGrid.Extensions.DependencyInjection` version 1.0.1 was not published on NuGet.org

### ISSUE THREAD

**Issue by akunzai** [sendgrid/sendgrid-csharp#1122]
Related to #1045

### Issue Summary

The `SendGrid.Extensions.DependencyInjection` version 1.0.1 was not published on NuGet.org at the latest release.

According to the [Build log](https://travis-ci.com/github/sendgrid/sendgrid-csharp/builds/230232319#L3785)

```
Pushing SendGrid.Extensions.DependencyInjection.1.0.1.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  BadRequest https://www.nuget.org/api/v2/package/ 218ms
error: Response status code does not indicate success: 400 (This package must be signed with a registered certificate.).
```

This package looks like have additional [signature requirements on NuGet.org](https://docs.microsoft.com/nuget/reference/signed-packages-reference#signature-requirements-on-nugetorg)

Could you check that on NuGet.org, or publish this package manually?

Thanks for your help.

**Comment by shwetha-manvinkurke** [comment]
Hi @akunzai thanks for bringing up the issue. We are going to be looking at how to best sign the packages for the csharp packages and this issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by akunzai** [comment]
Hi, I just discovered the [SendGrid.Extensions.DependencyInjection](https://www.nuget.org/packages/SendGrid.Extensions.DependencyInjection/) version 1.0.1 had been published on NuGet.org since 2021-09-22.

So I'm going to close this issue, thanks.
