### ISSUE TITLE
Readme Link Broken

### ISSUE THREAD

**Issue by DanielHolland** [sendgrid/sendgrid-csharp#1124]
### Issue Summary
In the Readme.md, under "Usage" there is a link to the documentation that is broken, clicking it returns a 404 error on the Twilio site

### Steps to Reproduce
1. Click the link:
![Screenshot 2021-07-21 at 12 41 26](https://user-images.githubusercontent.com/30952472/126476259-9f41e535-41de-4731-8070-fe2280340d63.png)
2. Note the 404 error
![Screenshot 2021-07-21 at 12 39 33](https://user-images.githubusercontent.com/30952472/126476292-4715d8ec-bf84-4a0a-a24e-3fab36d08f6a.png)

**Comment by eshanholtz** [comment]
The new SendGrid docs experience launched recently. I believe the new link is here: https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/authentication

The docs issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by DanielHolland** [comment]
Thank you for the link @eshanholtz - having only worked on private repositories I'm weary of proceeding as I please. Am I encouraged to branch, make the change and create the PR? Or should I just leave it as is and wait for the team to resolve it?

**Comment by DanielHolland** [comment]
> You'll need to fork the repo, make the change, and then submit as a PR.

Cool, will do. Love the username @childish-sambino
