### ISSUE TITLE
SendGrid Unique Custom Argument Issue after Aug 10 Update

### ISSUE THREAD

**Issue by Addhy** [sendgrid/sendgrid-csharp#1129]
* Issue Summary
Receiving hard-coded unique arguments in Notifications. May be after SendGrid latest Update in following area "We will not apply any personalization block substitutions to your custom argument fields in V3 endpoint" we are facing critical problem. Please suggest any alternative to achieve to resolve this asap.
  
* Steps to Reproduce
1. Follow below code snippet
2. Added one required key "ACId" in personalization block  
3. While retrieving we need the "ACId" to update DB  
4. Earlier we received actual "ACId" sent with every message but now we are receiving only hard-coded "ACId" no values. 

### Code Snippet
public async Task SendTranstions(string SendGridApiKey) {
    var client = new SendGridClient(SendGridApiKey);
    EmailAddress from = null;
    try {
        DataTable dtTransEmails = new DataTable();
        dtTransEmails = GetDataTable("GetTransEmails");
        if (dtTransEmails != null && dtTransEmails.Rows.Count > 0) {
            var query = (from DataRow TIds in dtTransEmails.Rows
                                 select TIds.Field<Int64>("TId")).Distinct().OrderBy(TId => TId);
			foreach (var TId in query) {
				var Recipients = new List<EmailAddress>();
				var Subjects = new List<string>();
				string Body = "Hi [CUSTOM-FIELD1] [ACId] .... Complete Transactional Informational will be here ....";
				var Tokens = new List<Dictionary<string, string>>(); // For Custom Fields
				DataRow[] drEmails = null;
				drEmails = dtTransEmails.Select("TId = " + TId.ToString());//Get Survey specific Email Invitations
				for (int _Count = 0; _Count < drEmails.Length; _Count++) {
					Recipients.Add(new EmailAddress(Convert.ToString(drEmails[_Count]["ToEmail"])));
					Subjects.Add(Convert.ToString(drEmails[_Count]["EmailSubject"]);
					Tokens.Add(new Dictionary<string, string>() { // Custom Fields replacement
					{ "[CUSTOM-FIELD1]", Convert.ToString(drEmails[_Count]["CustomFields1"]) },
					{ "[ACId]", Convert.ToString(drEmails[_Count]["ACId"]) },
					});
				}
				from = new EmailAddress("support@mycompany.com");
				var SGMsg = MailHelper.CreateMultipleEmailsToMultipleRecipients(from,Recipients,Subjects,"",Body,Tokens);
				SGMsg.CustomArgs = new Dictionary<string, string>(){{"ACId", "[ACId]"}};
				var SGResp = await client.SendEmailAsync(SGMsg).ConfigureAwait(await);
			}
        }
    } catch (Exception e) {
        SES.WriteLogs("Exception Message: " + e.Message + " Stack Trace: " + e.StackTrace);
    }
}

Receiving Notification JSON like "[{"ACId":"[ACId]","email":"someone@xyz.com", "event":"processed","send_at":0,"sg_event_id":"dHnvY2mzc2VklTIwNyk5sTgyLWIxOHNIVlSrZ01xT3lfjnazdnU3TlEtNC","sg_message_id":"n28sKVRkSNqUy_lylfuABC.filterdrecv-6b5bbbcd5-4tncw-1-912A1A51-5E.0","smtp-id":"<n28sKVRkSNqUy_lylfuABC@geopod-ismtpd-5-0>","timestamp":1522101911}]"

Here I need help to retrive the Substitutional value [ACId] in Custom Argument. Please help asap. Thanks

**Comment by illusio789** [comment]
We have seen this too and it's a big problem for us. 
One thing I have noticed is that looking in SendGrid, the Message IDs now contain the work "canary" e.g.
`jB6uKmdpQ6ePuwsNc66i4A.filterdrecv-canary-6995b85459-b5xsc-1-611A1BDE-2A.123`

The earlier ones which are OK do not contain that e.g.
`m9veFi4lQOOoKf2oForPfQ.filterdrecv-765fd4f9f8-2fns7-1-6114D8AB-44.123`

This makes me think that a change is being trialed.

**Comment by Jericho** [comment]
@Addhy Where did you get information about a change on August 10? I am no longer seeing a change log on [SendGrid's documentation site](https://docs.sendgrid.com/) (if I recall correctly, there used to be a "Release Notes" link at the top of that page) and the most recent SendGrid related change mentioned on [Twilio's site](https://www.twilio.com/changelog?product=sendgrid-email-api) is from February.

**Comment by Addhy** [comment]
From: Twilio SendGrid Team <twilio-notifications@twilio.com>
Date: Fri, Jun 11, 2021
Subject: [Action May Be Required] Twilio SendGrid will require modified Mail Send API behaviors by August 10, 2021

Twilio SendGrid will require modified Mail Send API behaviors by August 10, 2021
As we continue to modernize and monitor our email delivery infrastructure to comply with industry standards, we are changing a few behaviors on the API. The changes are as follows:
  
1. The  word “enabled” (instead of “enable”) will no longer be a recognized parameter for the Mail Send API. The “enable” parameter is required, and if the parameter is omitted, settings will not be applied. Please use “enable” to ensure the desired behavior. 
 
2. Only one of each type of header is permitted.  We will no longer support duplicate headers for the following:
 
o	from
o	sender
o	reply-to
o	to
o	cc
o	bcc
o	x-smtpapi
 
3. We will not apply any personalization block substitutions to your custom argument fields in V3 endpoint.

**Comment by Jericho** [comment]
Thank you for sharing this information. I wonder why they chose to email the info rather than make it available publicly on their change log

**Comment by illusio789** [comment]
There is a reasonable solution to this, but I do feel that the original email warning about this could have been clearer and point at the appropriate [documentation](https://docs.sendgrid.com/api-reference/mail-send/mail-send).

You can add CustomArgs at the personalization level as well as the top level.
These are combined in the webhook event to give you the whole set of custom args.

**Comment by Addhy** [comment]
My point is ... after using below piece of code I am struggling to add personalization ...
var SGMsg = MailHelper.CreateMultipleEmailsToMultipleRecipients(from,Recipients,Subjects,"",Body,Tokens);
After this there is no loop chance to add ACId apart from substitutions and now SendGrid has clearly mentioned that "We will not apply any personalization block substitutions to your custom argument fields in V3 endpoint."
Let me know if anybody can help to add personlizatio as each email identity for a single personalize key ACId so that I can receive notifications like 
"[{"ACId":"123","email":"email1@xyz.com", ......},
"[{"ACId":"456","email":"email2@xyz.com", ......},
"[{"ACId":"789","email":"email3@xyz.com", ......}]
Thanks in advance.

**Comment by illusio789** [comment]
The thing to be aware of now is that substitutions and custom args are now separated.
So, the substitutions will happen in the same way they always have, but, you will have to add the custom args through more verbose code. It would be nice if `CreateMultipleEmailsToMultipleRecipients` had an overload to handle the custom args at the personalization level, but it's not currently there.

Assuming that you want all of the `Tokens` to be passed back in the webhook event, then the following code should work.

``` csharp
var SGMsg = MailHelper.CreateMultipleEmailsToMultipleRecipients(from, Recipients, Subjects, "", Body, Tokens);
for (var i = 0; i < Recipients.Count; i++)
{
    var personalCustomArgs = Tokens[i];
    SGMsg.Personalizations[i].CustomArgs = personalCustomArgs;
}
```

I hope this is enough to get you going.

**Comment by Addhy** [comment]
Thanks ... Great Help! I have resolved the issue in two ways .... 
One is using Unique Message Id n ToEmail combination and second solution by using above code in similar way ....  
for (int iACId = 0; iACId < ACIds.Length; iACId++) {
var ACIdCustomArg = Convert.ToString(LaunchIds[iACId]);
SGMsg.Personalizations[iLaunchId].CustomArgs = new Dictionary<string, string>() { { "ACId", ACIdCustomArg } };
} Thanks again for your valuable suggestion.
