### ISSUE TITLE
Message does not come with <img> tag

### ISSUE THREAD

**Issue by mmario5** [sendgrid/sendgrid-csharp#113]
Hello,

I'm trying to send a message with content:

<p>&lt;p&gt;test&lt;/p&gt;&lt;p&gt;&lt;img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRG38VK4-kYeMdF1fQ6RbhfDoUjbE8smcnFrvJrVg5n1xwP4tN" alt="Obraz" /&gt;&lt;br /&gt;&lt;/p&gt;</p>

but the message does not come to the recipient. When I remove the <img> tag from the message that is ok. I am using C# (SendGrid.Web).

My sample code:

var myMessage = new SendGridMessage();
myMessage.AddTo("10_1@wp.pl");
myMessage.From = new MailAddress("10_1@wp.pl", "John Smith");
myMessage.Subject = "test";
myMessage.Html = "<p>&lt;p&gt;test&lt;/p&gt;&lt;p&gt;&lt;img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRG38VK4-kYeMdF1fQ6RbhfDoUjbE8smcnFrvJrVg5n1xwP4tN\" alt=\"Obraz\" /&gt;&lt;br /&gt;&lt;/p&gt;";
            
var credentials = new NetworkCredential("account", "password");
var transportWeb = new Web(credentials);
transportWeb.Deliver(myMessage);

Where is the problem?

**Comment by brandonmwest** [comment]
Hi there, I don't see any problems with your code. What does SendGrid say about the messages that are not delivered when you look for them in your Email Activity report? They might be getting blocked at the receiving server.

**Comment by mmario5** [comment]
It seems to me that the problem was that the message was not in a correct HTML format. Missing the following tags: &lt;html&gt;, &lt;head&gt; and &lt;body&gt;.

**Comment by brandonmwest** [comment]
ah yes, that would do it :) thanks for letting us know!
