### ISSUE TITLE
MailSettings class missing attributes from specification

### ISSUE THREAD

**Issue by fefi95** [sendgrid/sendgrid-csharp#1135]
### Issue Summary
The specification for Sendgrid's API version 3 has the attributes `bypass_spam_management` , `bypass_bounce_management` and `bypass_unsubscribe_management` on `mail_settings` for the `/mail/send` endpoint. However, they seem to be missing on [MailSettings](https://github.com/sendgrid/sendgrid-csharp/blob/main/src/SendGrid/Helpers/Mail/Model/MailSettings.cs) class. Could they be added? Thanks!

### Technical details:
* sendgrid-csharp version: 9.24.3

**Comment by eshanholtz** [comment]
Similar to https://github.com/sendgrid/sendgrid-java/issues/700. This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by Felix200521** [comment]
> ### Problemzusammenfassung
> Die Spezifikation für Sendgrids API Version 3 hat die Attribute `bypass_spam_management`, `bypass_bounce_management`und `bypass_unsubscribe_management`on `mail_settings`für den `/mail/send`Endpunkt. Sie scheinen jedoch in der [MailSettings-](https://github.com/sendgrid/sendgrid-csharp/blob/main/src/SendGrid/Helpers/Mail/Model/MailSettings.cs) Klasse zu fehlen . Könnten sie hinzugefügt werden? Danke!
> 
> ### Technische Details:
> * sendgrid-csharp-Version: 9.24.3

**Comment by asos-vinodpatil** [comment]
@eshanholtz  Raised the pull request. Please review.

**Comment by rakatyal** [comment]
This should be resolved now. Thank you for the issue and community PR.
