### ISSUE TITLE
Vulnerability (Arbitrary Signature Forgery) in starkbank-ecdsa

### ISSUE THREAD

**Issue by felixse** [sendgrid/sendgrid-csharp#1138]
### Issue Summary
There is a new vulnerability in starkbank-ecdsa 1.3.1, please update to at least 1.3.2 to mitigate this.
More details here: https://research.nccgroup.com/2021/11/08/technical-advisory-arbitrary-signature-forgery-in-stark-bank-ecdsa-libraries/

### Technical details:
* sendgrid-csharp version: 9.24.4

**Comment by JenniferMah** [comment]
Hi @felixse this fix will be included in the release on 11/17/21.
