### ISSUE TITLE
Link removed by sendgrid from custom HTML Template

### ISSUE THREAD

**Issue by meermalik** [sendgrid/sendgrid-csharp#1145]
### Issue Summary
Add a link to redirect from mail app to other app , so in anchor tag i added a link that doesn't contains http and https. but while sending the email sendgrid remove the uRL

**Comment by JenniferMah** [comment]
Hi @meermalik!  Could you provide some code samples for what you're trying to accomplish?

**Comment by meermalik** [comment]
@JenniferMah the link i want to send is 
**com.parkdirekt://signup?token=/xyz&email=abc@gmail.com**

**Comment by meermalik** [comment]
[Sample Link](com.parkdirekt://signup?token=/xyz&email=abc@gmail.com)

**Comment by meermalik** [comment]
[Click Here](com.parkdirekt://signup?token=/xyz&email=abc@gmail.com)

**Comment by shwetha-manvinkurke** [comment]
Do you have a code sample? I recommended going over the [documentation](https://github.com/sendgrid/sendgrid-csharp#quick-start) if you haven't already

**Comment by beebzz** [comment]
Closing due to lack of response.
