### ISSUE TITLE
Bad Request using Deliver when Attachment using Chinese Name

### ISSUE THREAD

**Issue by qin-nz** [sendgrid/sendgrid-csharp#115]
I can deliver email correctly using the following code.

``` 
message.AddAttachment(stream, "English.txt");
```

But When I try to send a attachment with Chinese filename, SendGrid server will response 400 Bad Request.

``` 
message.AddAttachment(stream, "中文.txt");
```

**Comment by 0xdeafcafe** [comment]
What version of the library are you using?

**Comment by DingyuanHu** [comment]
5.1

**Comment by DingyuanHu** [comment]
Using Unicode as a filename will increase the ```Content-Length``` of HTTP request.
And .NET will throw ```System.Net.ProtocolViolationException```.

**Comment by brandonmwest** [comment]
This is a known issue. Unfortunately the built-in HttpClient can only use RFC-2047 encoding for attachments with non-ASCII filenames. Currently our web API doesn't support that, though I've put in a request with our product team to add it. At this time the workaround I can suggest is to use the SMTP transport so you have more control over the MIME message.
