### ISSUE TITLE
Subscription tracking settings do not affect emails

### ISSUE THREAD

**Issue by csalzano** [sendgrid/sendgrid-csharp#1163]
### Issue Summary
I can't get emails to send with any unsubscribe message or links other than two links "[Unsubscribe From This List]() | [Manage Email Preferences]()"

### Steps to Reproduce
1. Turn Subscription Tracking on or off in your SendGrid account, doesn't seem to matter either way
2. Use a `var msg = new SendGridMessage()` object with any of these subscription tracking settings:

 - `msg.SetSubscriptionTracking(true, "Manage your email preferences <%asm_preferences_url%>");`
 - `msg.SetSubscriptionTracking(false);`
 - ```
    msg.TrackingSettings = new TrackingSettings() { SubscriptionTracking = new SubscriptionTracking() {
        Enable = true,
        Html = "We hope you enjoyed this email! <%asm_preferences_url%>",
        Text = "We hope you enjoyed this email!",
    } };
 - ```
    msg.TrackingSettings = new TrackingSettings() { SubscriptionTracking = new SubscriptionTracking() {
        Enable = false,
    } };

3. Review the emails sent

No matter what I change, I see the same two links at the bottom of email messages: "[Unsubscribe From This List]() | [Manage Email Preferences]()". These are not links that I've created. The HTML and text in my Subscription Tracking settings on sendgrid.com does not contain these two links. 

### Technical details:
* sendgrid-csharp version: 9.21.1.0
* csharp version: .NET 4.5.2

**Comment by childish-sambino** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
