### ISSUE TITLE
Non-ascii characters in sender address

### ISSUE THREAD

**Issue by Robelind** [sendgrid/sendgrid-csharp#117]
I started to get "Bad request" errors when trying to send emails. Investigation showed that the problem was "Invalid from email address" and it seems to be choking on non-ascii chars in the sender address.
I believe that this have worked or at least should work.

**Comment by farlop** [comment]
+1

**Comment by thomasrosted** [comment]
We have the same problem. I assume it's related to the API rather than the C# driver, so perhaps we need to direct the issue elsewhere?

**Comment by ShieldPad** [comment]
Same issue here.

**Comment by thinkingserious** [comment]
@Robelind, @farlop, @thomasrosted, @ShieldPad,

Thanks for bringing this to our attention!

Could someone please provide me with sample data so I can rule out this library as the cause?

Also, this library will be replaced by this one in a few weeks: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta. It supports a massively overhauled /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks for your support everyone!

With Best Regards,

Elmer

**Comment by ShieldPad** [comment]
These addresses don't exist specifically, they're just examples of the Swedish characters that can appear in email addresses:

jörgen.davidsson@pergament.se
björn.davidsson@pergament.se
märta.davidsson@pergament.se
mårten.davidsson@pergament.se

**Comment by thinkingserious** [comment]
Thank you @ShieldPad,

This will help with testing.

**Comment by thinkingserious** [comment]
If this issue persists with version 7.X.X of this library, please open a new issue. Thanks!
