### ISSUE TITLE
The 'hr' start tag does not match the end tag of 'body'

### ISSUE THREAD

**Issue by hemami** [sendgrid/sendgrid-csharp#122]
Hey I have implemented API for sending mails. I have used Parallel.for() for sending multiple mails at a time. It is giving following XML error:
Error in SimpleHTMLEmail in Program.cs:System.Xml.XmlException: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
at System.Xml.XmlTextReaderImpl.ParseEndElement()
at System.Xml.XmlTextReaderImpl.ParseElementContent()
at System.Xml.XmlTextReaderImpl.Read()
at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
at System.Xml.XmlDocument.Load(XmlReader reader)
at System.Xml.XmlDocument.Load(Stream inStream)
at SendGrid.Web.GetErrorsInResponse(Stream content)
at SendGrid.Web.CheckForErrors(HttpResponseMessage response)
at SendGrid.Web.Deliver(ISendGrid message)
at BulkEmailSender.Program.SimpleHTMLEmail(String to, StringBuilder myMessage, StringBuilder subj, Web transportInstance, String investarId)

How can this be solved?

**Comment by brandonmwest** [comment]
Have you looked at the contents of the response in your debugger? This could be caused by many things, but right now it looks like your request is resulting in HTML being returned rather than XML. Something could be blocking your connection between the client and the server.

**Comment by hemami** [comment]
brandonmwest thanks for reply.
I am sending 5000 mails together and then there is 2 min wait after which next 5000 mails are sent. Now out of these 5000 requests all do not generate error. 15% of requests generate the error. Now if I try to send again to those users for which error is generated, it sends. I can also say that at the start it sends a large number, problem starts after sending around 3000 mails. I was using same code to send mails since past 1 year and never encountered such problem. This is happening since last 1 month. I had chat for help with sendgrid and I was asked to update my library. I did that but it did not made any difference.
Moreover the method Deliver() does not have return value so we cant get into root cause.

**Comment by brandonmwest** [comment]
Hi there, I just released a new version that changes how HTTP clients are reused that might help. It should drastically improve performance for code that needs multiple connections.

The reason that the Deliver() method doesn't return anything is because our API handles requests asynchronously. We accept the message and then process it so it takes some time for us to determine everything. As a note, this method was removed in the latest version. The only version is DeliverAsync. The old method was mixing sync and async code and could've caused problems.

When you say you are sending 5000 messages together, how are you sending them, in batches via X-SMTPAPI, one API request per recipient, or some other way? Try the new version, if that doesn't help, let me know :)

**Comment by MarcelloCarreira** [comment]
The api handling async is one thing. Other thing is knowing if the api received or not the request. Knowing if the message itself was delivered to the recipient is a next step, done using the Webhooks. But I also believe that transportWeb should return some information from the server when it successfully has delivered the message to the api. I sometimes try to deliver a message, but I got an invalid api key error, but the key is untouchable and also the code, the error is at the transport or at the api itself, and I got no error back.

Maybe you, hemami, have some kind of problem like that and got 3k emails ok, but then the api, by some how, produce some error, but you got no exceptions back. If you use to have an OK message back when the delivery is ok, you would not have them in this case, and could auto try to delivery it again.

So having an OK back message is crucial to have some peace. I forked the this C# rep, to have transportWeb.DeliverAsyncReturn() but I would love to see it in the official one. I think it would help a lot of people.

**Comment by thinkingserious** [comment]
This is on our roadmap.

**Comment by 0xdeafcafe** [comment]
@thinkingserious you should create a GitHub milestone for the roadmap and file this under that milestone, rather than closing it.

**Comment by thinkingserious** [comment]
@0xdeafcafe coming soon ;)

We are the process of reworking all of our open source libraries and we are adopting a Milestone approach as part of that effort. It will take some time, but it's coming soon. 

Sorry for not being clear about that. Please rest assured that this issue will be added to a future Milestone.

Stay tuned ...
