### ISSUE TITLE
Adding a send_at header to schedule an email header doesn't seem to work

### ISSUE THREAD

**Issue by bogeorge** [sendgrid/sendgrid-csharp#123]
I'm using the headers of a SendGridMessage to add the send_at header value which according to the SendGrid documentation should delay the email but it still appears to be getting sent automatically.

SendGridMessage.Headers.Add("send_at", unixTimestamp.ToString());

**Comment by brandonmwest** [comment]
Hi there, `send_at` is a part of the X-SMTPAPI header rather than a standard SMTP header. The X-SMTPAPI header takes a JSON object to describe extensions like scheduling. I'm working on adding a convenience method for this and will have it in the next release.

**Comment by bogeorge** [comment]
Thanks Brandon.

Is there a way to use the x-smtpapi header today before you have the convenience methods?

I've tried these two approach and neither seemed to work

Using the SendGridMessage object
SendGridMessage.Header.AddUniqueArgs(new Dictionary<string, string> { { "send_at", unixTimestamp.ToString() } });

Using a MailMessage in System.Net.Mail namespace and sending with the SMTPClient object

MailMessage.Headers.Add("x-smtpapi", "{ \"send_at\": " + unixTimestamp + " }");

**Comment by brandonmwest** [comment]
Check out smtpapi-csharp 1.3.1 and sendgrid-csharp 6.0.0. You should see a SetSendAt() method now :)

**Comment by bogeorge** [comment]
Awesome!  Thanks so much.  I will get the latest versions and check it out.
