### ISSUE TITLE
Bcc is not working in conjunction with the SMTP API headers

### ISSUE THREAD

**Issue by kzimny** [sendgrid/sendgrid-csharp#124]
here is my code:

        var myMessage = new SendGridMessage();

        List<String> recipients = new List<String> { "inboxA@example.com", "inboxB@example.com" };
        MailAddress[] sTo = new MailAddress[] { new MailAddress("me@example.com") };

        myMessage.To = sTo;
        myMessage.From = new MailAddress("xyz@example.com");
        myMessage.ReplyTo = sTo;
        myMessage.Header.SetTo(recipients);
        myMessage.AddBcc("test@example.com");

        myMessage.Subject = "Testing the SendGrid Library";
        myMessage.Html = "<p>Hello World!\n\n%name%</p>";

        var subs = new List<String> { "A", "B" };
        myMessage.Header.AddSubstitution("%name%", subs);
        
        var credentials = new NetworkCredential("", "");
        var transportWeb = new Web(credentials);
        transportWeb.Deliver(myMessage);

my email address added in myMessage.AddBcc(); is not blocked or bounced. I'm using the latest Version 5.1.0. Is it a known issue? Maybe this one https://github.com/sendgrid/sendgrid-csharp/pull/80

**Comment by thinkingserious** [comment]
Hello @kzimny,

Thanks for reaching out to us!

The new version of our v3 /mail/send endpoint now includes all of this functionality without the need to use our SMTPAPI header. You can check it out here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

This library will be replaced by this one, which supports the new v3 /mail/send, in a few weeks: https://github.com/sendgrid/sendgrid-csharp/teer/v3beta

With Best Regards,

Elmer
