### ISSUE TITLE
DeliverAsync Out of Memory

### ISSUE THREAD

**Issue by dalefraser** [sendgrid/sendgrid-csharp#125]
We are sending a large volume of emails using this method.

However we get Out of Memory errors and don't know how to handle or limit the number of threads created so that we can continue to deliver without running out of memory.

There doesn't seem to be any documentation around your DeliverAsync method and what we should do.

We have tried to slow it down by doing a Thread.sleep every X emails which helps but still we get out of memory issues.

**Comment by brandonmwest** [comment]
Which version are you using?

**Comment by brandonmwest** [comment]
Please try 6.0.1. In previous versions the HttpClient was neither being disposed nor reused. This is likely where the memory leak came from.

**Comment by dalefraser** [comment]
We wern't on that version but are now, the same error. I consistantly happens after around 30k sends. Im not sure any of this is helpful, but here it is.

Message: Exception of type 'System.OutOfMemoryException' was thrown.
Inner Exception: 
Stack Trace: at System.String.ReplaceInternal(String oldValue, String newValue) at System.String.Replace(String oldValue, String newValue) at OneShiftApi.Components.Services.Mailer.SendEmail(String from, String to, String subject, String htmlContent, String[] args, Dictionary`2 attachments, String displayName) at OneShiftApi.Controllers.SchedulerController.DailyJobsCandidate(Int32 scheduleLogId, Int32 startAt, Int32 take, Int32 done) at lambda_method(Closure , Object , Object[] ) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()

**Comment by brandonmwest** [comment]
I don't actually see anything from the SendGrid dll in that stack trace. Additionally, we don't call String.Replace anywhere in our code. This leads me to believe that the problem is occurring somewhere above the actual sending code, perhaps in code that processes data to be used in the emails?

**Comment by wpalombini** [comment]
Hi Brandon,

The error happens along a process where we replace parameters inside a string. The fact is that the whole code works without any issue if we just don't deliver the email (by not calling DeliverAsync(message)). Also, if we run the process using the built in SmtpClient, we also don't get the error. The problem is that it takes about 12 hours to deliver roughly 80k emails.
By keeping an eye in the task manager, I see that RAM increases about 1Gb until we get the Out Of Memory exception. This does not happen through the other two scenarios that I mentioned above.
Do you have any extra thoughts based on this?

Thanks
