### ISSUE TITLE
Web.Deliver is Gone!!

### ISSUE THREAD

**Issue by GorillaSpring** [sendgrid/sendgrid-csharp#128]
After a NuGet update, the .Deliver method is not longer available.  Only DeliverAsync.

Straight from your example,

            // Create credentials, specifying your user name and password.
            var credentials = new NetworkCredential(sendGridAccount, sendGridPassword);

            // Create an Web transport for sending email.
            var transportWeb = new Web(credentials);

            // Send the email.
            // You can also use the **DeliverAsync** method, which returns an awaitable task.            
            transportWeb.Deliver(sgMsg);   // <-- *** Not available, will not compile!!

**Comment by brandonmwest** [comment]
It was removed on purprose. See https://github.com/sendgrid/sendgrid-csharp/blob/master/CHANGELOG.md
