### ISSUE TITLE
Just updated sendgrid via nuget, and not getting an error when building

### ISSUE THREAD

**Issue by doglesby** [sendgrid/sendgrid-csharp#130]
After updating sendgrid on nuget (in visual studio),  when I try and build the project, I get the following error:

Error	30	'SendGrid.Web' does not contain a definition for 'Deliver' and no extension method 'Deliver' accepting a first argument of type 'SendGrid.Web' could be found (are you missing a using directive or an assembly reference?)	

This error occurs on the following line:
transportWeb.Deliver(myMessage);

**Comment by 0xdeafcafe** [comment]
The synchronous deliver methods were removed in this commit, 97bcb9854b8c8d3796b7b1dd56d2525fc8832057. It looks as if only DeliverAsync is available now.

**Comment by brandonmwest** [comment]
Yep, please use the DeliverAsync() method :)
