### ISSUE TITLE
DeliverAsync inside a loop

### ISSUE THREAD

**Issue by silvaalexandre** [sendgrid/sendgrid-csharp#133]
I tested send several messages from my application with call of DeliverAsync inside a loop that reads my data from database. I can´t send just one message with several destinations. My message is user customized. When I run with 10 e-mail address my app runs ok, but with aprox. 1050 addresses not all messages are sent e none error is returned. Here is my routine method:

        public void Send(string email, string subject, string msg)
        {
            SendGridMessage mail = new SendGridMessage();
            mail.From = new MailAddress("noreply@mycustomer.domain");
            mail.AddTo(email);
            mail.Subject = subject;
            mail.Html = msg;
            mail.EnableClickTracking(false);

            var credentials = new NetworkCredential("myuser", "mypassword");
            var transportWeb = new Web(credentials);
            transportWeb.DeliverAsync(mail);
        }

I run a loop that call this method 1006 times and not all message are sent. Some are processed, some are delivered, a few is bounced. In the last test from 1006 messages just 670 are in SendGrid Dashboard. Other 336 are missing from Dashboard and does note appears in "Email Activity" or "Email Reports".

**Comment by brandonmwest** [comment]
Are you catching exceptions anywhere? I bet some of the calls are timing out. Try setting `ServicePointManager.DefaultConnectionLimit` to something reasonable like 10 and see what happens

**Comment by silvaalexandre** [comment]
I made a test with ServicePointManager.DefaultConnectionLimit = 10 and it runs. Thank You.
