### ISSUE TITLE
 SendGrid.Web.CheckForErrors throws random exceptions

### ISSUE THREAD

**Issue by assafBarash** [sendgrid/sendgrid-csharp#136]
Hi There

few days ago, a client of ours complained (not for the first time) that she's unable to send emails. as i investigated the issue i found that SendGrid.Web.CheckForErrors throws an exception. i tried to get more details and investigate it deeper but after two days our client called  us again and told that now she's able to send emails, which prevents me from further investigating the error.
  
I'll be grateful if you'll tell me which details are needed to investigate the issue with this specific client of ours and how can i investigate more properly the exceptions SendGrid.Web.CheckForErrors throws
  
Thank you for your time 
Assaf Barash

**Comment by brandonmwest** [comment]
Hi there, without a stack trace it's very hard to help you debug.

You can see all of the exceptions that can be thrown here; https://github.com/sendgrid/sendgrid-csharp/blob/ea7fc3b65fcaab4060e8e6e89b4da700a19cf3b8/SendGrid/SendGridMail/Transport/ErrorChecker.cs#L43-L50

**Comment by assafBarash** [comment]
Hi Brandon

Thanks for the help. would you like me to send you the stack trace here or
update my current post?

2015-05-05 16:31 GMT+03:00 Brandon West <notifications@github.com>:

**Comment by TheSustainables** [comment]
I've had this issue a couple of times as well. It seems SendGrid is returning html sometimes. This is my stacktrace, hope it helps. I'll try and reproduce this bug locally to get the underlying error message using a sniffer.

	System.ArgumentException: Unknown element: html
	   at SendGrid.ErrorChecker.CheckForErrors(HttpResponseMessage response, Stream stream)
	   at SendGrid.ErrorChecker.<CheckForErrorsAsync>d__0.MoveNext()

**Comment by Grepsy** [comment]
Turned out the error-message returned by sendgrid was the following:
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Which I believe doesn't mean the e-mail is too large, but the `Content-length` header doesn't match the body size. That's why this message is coming from the web-server directly, and why it's formatted this way.

**Comment by Grepsy** [comment]
Forget the content-length stuff, the message was indeed too large. But the error parsing still needs to be fixed though.
