### ISSUE TITLE
A first chance exception of type 'System.NullReferenceException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by ScarlettCode** [sendgrid/sendgrid-csharp#137]
Using the exact code off the Readme file "How to: Send an Email" I'm getting the above error. 

The code used to work when I first wrote it a few weeks back so I don't know what's changed that I'm now not handling. Any assistance would be greatly appreciated. Is the DeliverAsync method working correctly?

Thanks

**Comment by brandonmwest** [comment]
Can you post your code and your stack trace?

**Comment by ScarlettCode** [comment]
Resolved this by moving the DeliverAsync call into a new method. Think my lack of Async understanding was the issue.
