### ISSUE TITLE
Using API Keys

### ISSUE THREAD

**Issue by bjorncoltof** [sendgrid/sendgrid-csharp#139]
How can I use APi keys with this client library? I see there is a branch for API keys, should I pull that and build the lib myself?

**Comment by brandonmwest** [comment]
Please see the readme.

**Comment by bjorncoltof** [comment]
Hi, 

The readme says I can, but not how. Any further pointers would be appreciated.

Bjorn 

-----Original Message-----

**Comment by 0xdeafcafe** [comment]
[This](https://github.com/sendgrid/sendgrid-csharp#how-to-send-an-email) part of the readme states where to get API Keys and how to use them with the library.

**Comment by bjorncoltof** [comment]
Thanks, completely missed the overload that was being called...

-----Original Message-----
