### ISSUE TITLE
Stats API function

### ISSUE THREAD

**Issue by krompjuter** [sendgrid/sendgrid-csharp#140]
We have been using Sengrid C# library for about 2 years (some old version).
It support many API functions like GetBounces, GetStatReports and so on.

In the newest library version any of these are not included.
(here you can see many classes in my OLD project http://screencast.com/t/ttyd2DTlp)

Could you determine what has happened? Does Bounce, Spam, Stats API calls are not supported in newer C# library versions?
Thanks

**Comment by brandonmwest** [comment]
Hi there! This library has never supported anything other than email transport. It looks like you were probably using a fork of this repo. Unfortunately I'm not sure which one that might be. We are planning to add support for many other API endpoints to our official libraries but we are still in the planning stages.
