### ISSUE TITLE
Get DeliverAsync() Response

### ISSUE THREAD

**Issue by rolandocc** [sendgrid/sendgrid-csharp#143]
Hi, I have been googling all day trying to figure it out how to know when this method fails, can anybody provide me with an example?

Thanks.

**Comment by rolandocc** [comment]
In order to complete the documentation I will answer myself:
Simply use "await" and wrap it inside a try-catch block, any error will be trapped by this block!

try{
 // email setup
  await transportWeb.DeliverAsync(mensaje);
}
catch (exception ex){

}

**Comment by brandonmwest** [comment]
Check out this code as well. It uses the SmtpClient but the async handling is the same: https://github.com/sendgrid/smtpapi-csharp/blob/master/Smtpapi/Example/Program.cs
