### ISSUE TITLE
is SetSendAt() supported?

### ISSUE THREAD

**Issue by jamesdecourcy** [sendgrid/sendgrid-csharp#147]
Hi

Im trying to delay sending an email but myMessage.SetSendAt() cannot be resolved.

Do you support this or am i just doing it wrong?

Thanks

**Comment by guao2012** [comment]
Hi everyone.

I have the same problem.
However, in other hand I modified a little bit the smtp.api library and I recompiled it in order to enable these functionality, but the messages are sent immediately even I set a date time for the next hour.

Regards

**Comment by thinkingserious** [comment]
@jamesdecourcy ,

Yes, we now support this setting in our new v3 /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html and the corresponding library: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta (e.g. https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/SendGrid/Example/Example.cs#L175) Both are set to come out of beta in a few weeks.

Thanks for taking the time to write us!

With Best Regards,

Elmer

@guao2012,

Your issue probably requires assistance from our support team. Could you please open a ticket at https://support.sendgrid.com

Thanks!

Elmer
