### ISSUE TITLE
SendGrid on an Azure web site

### ISSUE THREAD

**Issue by ahrenm** [sendgrid/sendgrid-csharp#148]
Does anyone know how to get this working on an Azure website?
I've spent 2 days trying to get basic emailing working and I'm about ready ditch the whole Azure platform and just move over to Wix.

This line:
__transport.DeliverAsync(__newMessage);

Gives me no error and no email message. I've tried running it locally and on Azure. I've put a tap on the returned Task, but it never returns.

If there is a working example out there, that would be amazing.

Thanks and sorry for the ranty...emailing should not be this hard.

**Comment by neil-thompson** [comment]
In the version deployed via NuGet I found that awaiting the task did not work eg:

await __transport.DeliverAsync(__newMessage);

but skipping await was fine
__transport.DeliverAsync(__newMessage);

is this what you have?

**Comment by ahrenm** [comment]
Sorry for the slow response, took me a bit to get back to this project.
I've tried both variations of the above. The returned task from DeliverAsync never gets scheduled. The status just sits on WaitingForActivation.

Seems async calls in IIS are generally troublesome due to a page cycle only really getting allocated a single thread, which causes deadlocks.

My code is 
```        
public static void ProcessPage (string data)
        {
            string __sgUN = "{removed}";
            string __sgPW = "{removed}";
            SendGridMessage __newMessage = new SendGridMessage();
            __newMessage.From = new System.Net.Mail.MailAddress("{removed}");
            __newMessage.AddTo("{removed}");
            __newMessage.Subject = "Email Subject";
            __newMessage.Text = "Test email data:" + data;

            NetworkCredential __creds = new NetworkCredential(__sgUN, __sgPW);
            var __transport = new Web(__creds);
            
            Task __return =  __transport.DeliverAsync(__newMessage);
            //while (__return.Status == TaskStatus.Running) { }
        }
```
The static method is getting called by some Razor code which is triggering on PostBack and pulling some 'data' from a field on the page.

Open to any suggestions.

A

**Comment by davidwholland** [comment]
Any thoughts on the question by @ahrenm ? I've got almost exactly the same code, and it's not working for me either. I'm running a .NET console application as a test with no other code. No exceptions are thrown when I run the program, but no emails show up and SendGrid isn't showing any activity on my account.

**Comment by ahrenm** [comment]
Just tried the same thing in an Azure worker process. No joy.
As the only supported email service for Azure, be nice if someone could show how to make it... you know.....send emails.

**Comment by white-label-development** [comment]
This 'works' for me (it just never awaits - but the SendGrid svc request is successfully sent)
```
    public async Task SimpleHtmlEmailAsync(IEnumerable<string> to, string from, IEnumerable<string> bcc, string subject, string html)
        {
            var message = new SendGridMessage();
            message.From = new MailAddress(from);

            foreach (var recipient in to) {  message.AddTo(recipient);  }
           
            if (bcc != null && bcc.Any())
            {
                foreach (var bccEmailAddress in bcc)  {  message.AddBcc(new MailAddress(bccEmailAddress)); }
            }

            message.Html = html;
            message.Subject = subject;
            var transportInstance = new Web(_apiKey);

            //send the mail
            //use of await never completes, weirdly. 
            //eg: await transportInstance.DeliverAsync(message);    
            transportInstance.DeliverAsync(message);
        }
```

**Comment by ahrenm** [comment]
In order to make sure my thread stays active I've looped the call as per below.
It exits the loop ok, so the task must be completing, just no email :-(

````
var a = __transport.DeliverAsync(__newMessage);
while (a.IsCompleted == false) { }

**Comment by davidwholland** [comment]
Just wanted to leave an update: this code started working correctly after I moved it to my ASP.NET project. For some reason, running it in a Console app didn't work.

I am using the `await` keyword:

```csharp
await transportWeb.DeliveryAsync(message);
```

Also, in my test, I used it in a controller method that's defined as:

```csharp
public async Task<ActionResult> Index()
{
     // snip...
}
```

Obviously, I'm not going to leave it in a controller method for production, but I wanted to let you know what worked in my initial testing.

**Comment by michelscafidi** [comment]
I had the same issue with my console app implementation. I was able to keep the thread active and successfully send a message via the console app by using the `Wait()` method, rather than the `await` keyword.

```C#
transportWeb.DeliverAsync(myMessage).Wait()
```

Hope this solves your issue.

**Comment by PaulParker** [comment]
@michelscafidi's solution to use .Wait() fixed it for me (sending was intermittent but now it seems to be working constently).

**Comment by thinkingserious** [comment]
I was able to confirm the library is working using this tutorial: https://azure.microsoft.com/en-us/documentation/articles/sendgrid-dotnet-how-to-send-email

I used a C# ASP.NET Web Application for testing and put the following code in the Index() controller:
https://gist.github.com/thinkingserious/14208711bd6ee49c8eb5

Upon loading that page on Azure the email was sent.

However, there are several updates that are needed with that tutorial and we have put them in our backlog. 

Thanks to all of you for taking the time to leave some feedback! 

If there is a specific change you would like us to make in the library, please submit an issue here. We will review and consider all issues.

**Comment by PaulParker** [comment]
@thinkingserious the code in the tutorial worked for me when it was in an asp.net application. It did not work when I used it in a webjob.

**Comment by thinkingserious** [comment]
@PaulParker Thanks for the additional feedback!

Based on your previous comment, we should update the documentation to state that if you are running a console application, you must use transportWeb.DeliverAsync(myMessage).Wait().

Is that correct?

Thanks again for your support!

**Comment by PaulParker** [comment]
@thinkingserious  I suppose that would be one approach. But I think it would be better if the usage was the same no matter where you are calling the function from. I don't really understand the internals so I'm not sure if that is realistic or not.

**Comment by thinkingserious** [comment]
We will be tracking that issue here: https://github.com/sendgrid/sendgrid-csharp/issues/154

Thanks again @PaulParker
