### ISSUE TITLE
Templates?

### ISSUE THREAD

**Issue by nbirkes** [sendgrid/sendgrid-csharp#149]
Has the new template functionality been added to this library?

https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/templates.html

**Comment by baywet** [comment]
I don't believe it has with high level object.
Regardless you can do that.
message.Header.EnableFilter("templates");
            message.Header.AddFilterSetting("templates", new List<string> { "template_id"}, <templateId>);

you also have a method "AddSubstitution" on the header prop to add substitution values to your email

**Comment by brandonmwest** [comment]
https://github.com/sendgrid/sendgrid-csharp/blob/e75eaee35beaf9170505db626408021c50307289/SendGrid/SendGridMail/SendGrid.cs#L466-L472

**Comment by nbirkes** [comment]
That's exactly what I was looking for. Thanks for the help guys!
