### ISSUE TITLE
System.Net.Mail.MailMessage does not contain definition for SetCategory

### ISSUE THREAD

**Issue by TaqiOfficial** [sendgrid/sendgrid-csharp#150]
When added `SetCategory` it prompts error `(System.Net.Mail.MailMessage does not contain definition for SetCategory`, else its working. 

```
MailMessage mailMsg = new MailMessage();
 mailMsg.To.Add(new MailAddress(recievermail));
mailMsg.From = new MailAddress(sendermail, sendername);
mailMsg.SetCategory("Pass Reset");
```

**Comment by brandonmwest** [comment]
Yep, System.Net.Mail.MailMessage is the built-in C# class; it won't have any SendGrid methods. Please review the readme and use the SendGridMessage object.
