### ISSUE TITLE
API Keys support

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#153]
Make sure all examples and documentation is updated:

https://azure.microsoft.com/en-us/documentation/articles/sendgrid-dotnet-how-to-send-email/
https://github.com/sendgrid/sendgrid-csharp
https://sendgrid.com/docs/Integrate/Code_Examples/csharp.html

**Comment by antitheos** [comment]
I am trying to use  version 6.2.0, but I am not able to find the constructor for new Web(api_key)
If there an additional piece I am missing?

**Comment by thinkingserious** [comment]
Hello @antitheos, 

We have made the update, but need to merge the pull request: https://github.com/sendgrid/sendgrid-csharp/pull/127

**Comment by thinkingserious** [comment]
@antitheos 

Update complete: https://github.com/sendgrid/sendgrid-csharp/pull/164

Thanks for your patience :)
