### ISSUE TITLE
Console apps only work with transportWeb.DeliverAsync(myMessage).Wait()

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#154]

**Comment by NashCarr** [comment]
This was a life saver!!!

**Comment by NashCarr** [comment]
I was just testing this for the last 2 hours trying to figure out why my aspx page would work but not my web service.

**Comment by thinkingserious** [comment]
You can thank the fine folks in this thread: https://github.com/sendgrid/sendgrid-csharp/issues/148

;)

Thanks for supporting SendGrid!

**Comment by thinkingserious** [comment]
I've confirmed that for Console Applications, you need to call DeliverAsync this way and have put in pull requests to update our documentation:
https://github.com/sendgrid/docs/pull/1286
https://github.com/sendgrid/sendgrid-csharp/pull/155
