### ISSUE TITLE
Attachments not received in correct order

### ISSUE THREAD

**Issue by prateekmaheshwari** [sendgrid/sendgrid-csharp#156]
I tried sending multiple files using sendgrid in a windows store app but the files are not received in the correct sequence. Refer attachment.

![sendgrid_issue](https://cloud.githubusercontent.com/assets/13113989/10427464/a1d4c320-7107-11e5-9d85-c7e507dd1602.PNG)

Kindly help.

**Comment by thinkingserious** [comment]
Hello @prateekmaheshwari,

Thank you for reaching out to us!

We have implemented a new v3 /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html and a new version of this library here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta. You can see how attachments are now handled here: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/SendGrid/Example/Example.cs#L136

I'm going to leave this issue open until we have time to test the functionality on the new library.

Thanks!

With Best Regards,

Elmer
