### ISSUE TITLE
An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle...

### ISSUE THREAD

**Issue by itorian** [sendgrid/sendgrid-csharp#160]
I am using SendGrid API in my MVC 5 Application. Here's the sample code which is in a separate class file SendGridMailer. I call SendEmail method from non-async, controller action or even void type methods whenever needed. I only have control over below code, so how do I resolve below issue:

<b>Error Message</b>
<code>An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async=\"true\" %>. This exception may also indicate an attempt to call an \"async void\" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.</code>

    public static class SendGridMailer
    {
        public static void SendEmail(string receiveremail, string emailsubject, string mailbody)
        {
            var myMessage = new SendGridMessage();
            myMessage.AddTo(receiveremail);
            myMessage.From = new MailAddress("xxxxx", "xxxx");
            myMessage.Subject = emailsubject;
            myMessage.Text = mailbody;
            SendAsync(myMessage);
        }

        private static async void SendAsync(SendGridMessage message)
        {
            var credentials = new NetworkCredential("xxxx", "xxxx");
            var transportWeb = new SendGrid.Web(credentials);
            try
            {
                await transportWeb.DeliverAsync(message);
            }
            catch (Exception ex)
            {
                //
            }
        }
    }

Any clue ?

**Comment by thinkingserious** [comment]
Try SendAsync(myMessage).Wait();

For details see: http://blogs.msdn.com/b/pfxteam/archive/2012/04/12/10293335.aspx, the "Can I use “await” in console apps?" section.

**Comment by thinkingserious** [comment]
@itorian,

If you are still experiencing issues, please feel free to reopen this issue.

Thanks!
