### ISSUE TITLE
No overload constructor on SendGrid.Web for using API Keys

### ISSUE THREAD

**Issue by antitheos** [sendgrid/sendgrid-csharp#162]
All the docs indicate there is an overload constructor to allow you to connect using API Keys.
I am using version v6.2.0  when I try

   `var transportWeb = new Web("This string is an API key");`

I get a message cannot convert string to NetworkCredential.  
In v6.2.0 there does not seem to be a constructor for SendGrid.Web that takes the API key.

I also checked the source code and confirmed that there is no constructor that for API Keys

**Comment by antitheos** [comment]
Just downgraded to version 6.1 and that works as expected

**Comment by dkallen** [comment]
It appears that the NuGet package for SendGrid 6.2.0 refers to the SendGridMail.dll 6.0.0 instead of a later version where the API key has been implemented. Until that is fixed, I recommend people stay on SendGrid 6.1

**Comment by thinkingserious** [comment]
We have made the update, but need to merge the pull request: https://github.com/sendgrid/sendgrid-csharp/pull/127

**Comment by antitheos** [comment]
Thanx, I will wait for the update.

**Comment by thinkingserious** [comment]
@antitheos @dkallen 

Update complete: https://github.com/sendgrid/sendgrid-csharp/pull/164

Thanks for your patience :)
