### ISSUE TITLE
How to add an unique barcode image for each recipient?

### ISSUE THREAD

**Issue by kzimny** [sendgrid/sendgrid-csharp#165]
I'm using substitution tags to generate dynamic content for each recipient on the list:

        private void AddSubstitutionsCertificateDownload(List<Persons> item, SendGridMessage myMessage)
        {
            myMessage.Header.AddSubstitution("{$Email}", item.Select(x => x.Email));
            myMessage.Header.AddSubstitution("{$FirstName}", item.Select(x => x.FirstName));
            myMessage.Header.AddSubstitution("{$LastName}", item.Select(x => x.LastName));
            myMessage.Header.AddSubstitution("{$Password}", item.Select(x => x.Password));
            myMessage.Header.AddSubstitution("{$Salutation}", item.Select(x => x.Salutation));
            myMessage.Header.AddSubstitution("{$Title}", item.Select(x => x.Title));
            myMessage.Header.AddSubstitution("{$UserName}", item.Select(x => x.UserName));
        }

How can I add an unique barcode image for each recipient? It can be an attachment or embedded image. Thanks for any advice.

**Comment by thinkingserious** [comment]
Hello @kzimny, following is our documentation on how to send an attachment using our SendGrid C# library: https://github.com/sendgrid/sendgrid-csharp#how-to-add-an-attachment

**Comment by kzimny** [comment]
I don't think you answer is correct. I don't want send the same attachment to all recipients. Adding Header.AddSubstitution(...,...) allows send email and substitute the tags with recipient values.
With unique barcode I mean a personalized barcode image for each email recipient.

**Comment by thinkingserious** [comment]
Hi @kzimny, 

The issue section of our libraries (issues/pull requests) is for problems/feedback/enhancements for the library itself. 

Please submit this question to either https://community.sendgrid.com/sendgrid or to support@sendgrid.com.

Thanks!

P.S. I don't understand why the code in our example would not work for you. It seems you could simply loop through all of the emails in your list and attach a unique attachment each time.
