### ISSUE TITLE
Api returns "Missing destination email" when only BCC address specified

### ISSUE THREAD

**Issue by davidwkennedy** [sendgrid/sendgrid-csharp#171]
I'm calling the Send Grid API to send an email to one or more recipients. To avoid disclosing everyone's email to everyone else, I'm adding recipients as BCC addresses. The API returns a 400 if no address is present int the "to" field.  Adding noreply@mycompany.com resolves this, but then clutters up my SendGrid analytics. It would be great to send email with BCC addresses only. 
![sendgrid-bcc](https://cloud.githubusercontent.com/assets/743015/11822157/125f52e4-a322-11e5-8f9c-c4a1d67cd043.png)

**Comment by pmuens** [comment]
:+1: for this one. Facing the same1

**Comment by thinkingserious** [comment]
@davidwkennedy, @pmuens,

I am forwarding your feedback to our product team.

Thanks for taking the time to write this feedback!

With Best Regards,

Elmer

**Comment by mbernier** [comment]
You could in fact send the same email to multiple people at the same time, without them seeing each other. 

in mail.send.json - use the X-SMTPAPI to field, which is an array of recipients. Each one will receive a copy of the email address.

In v3/mail/send/beta - you can set up a personalization for each recipient. Each personalization is a different email and will not be seen by other personalzations.
