### ISSUE TITLE
Does this library support the Parse Webhook Settings API?

### ISSUE THREAD

**Issue by ScarlettCode** [sendgrid/sendgrid-csharp#173]
Are these api endpoints supported? https://sendgrid.com/docs/API_Reference/Web_API/parse_settings.html 

Or planned?

Thanks

**Comment by thinkingserious** [comment]
Hello @ScarlettCode,

We do not have library support for our webhooks; however, we have some [examples in our docs](https://sendgrid.com/docs/Integrate/Code_Examples/Webhook_Examples/index.html) and [on our blog](https://sendgrid.com/blog/?s=webhook).

If you still run into trouble, please contact our [support team](https://support.sendgrid.com/hc/en-us). 

Thanks!
