### ISSUE TITLE
DeliverAsync method does not provide the result of call.

### ISSUE THREAD

**Issue by aserdaray** [sendgrid/sendgrid-csharp#174]
I want to get a information after method call. Sending operation is success or failed or invalid etc. The DeliverAsync method does not support this. 

Are there any alternative implementation or way to get information ?

**Comment by thinkingserious** [comment]
Here you go: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Program.cs#L36

**Comment by aserdaray** [comment]
No , does not properly work
https://youtu.be/R5aWlZK6zzY

**Comment by khanja** [comment]
Are there any body to help me ?

**Comment by khanja** [comment]
Are there any body to help me ?

**Comment by thinkingserious** [comment]
This is now on our roadmap to implement.

**Comment by markadrake** [comment]
Has anyone been able to trap the result of `DeliverAsync` or is it not possible without an update from SendGrid?

**Comment by thinkingserious** [comment]
The response can be retrieved here: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/SendGridMail/Transport/Web.cs#L71. 

I suggest you subclass the Web class and override that function in your application.

Please let me know if that will work as temporary solution while we prepare for our new library release.
