### ISSUE TITLE
Use the Web API v3 - Problem

### ISSUE THREAD

**Issue by tiagobernardes** [sendgrid/sendgrid-csharp#175]
I am following the example and is not working for me.
Someone who can help me?

![capture](https://cloud.githubusercontent.com/assets/15774469/12120886/9be48706-b3ca-11e5-9585-c9a7cae03cd8.PNG)

**Comment by thinkingserious** [comment]
It looks like you might have a permissions issue. Please go to your [API Keys settings page](https://app.sendgrid.com/settings/api_keys) and click the gear icon to review.

**Comment by tiagobernardes** [comment]
the key has maximum access at all.

Now with this code already can get eg recipients.
However campaigns give me forbidden.

which problem may be?


![untitled](https://cloud.githubusercontent.com/assets/15774469/12123448/f7b29150-b3d8-11e5-8597-884307629780.png)

**Comment by thinkingserious** [comment]
Please reach out to support so that we can further assist: https://support.sendgrid.com

**Comment by thinkingserious** [comment]
@tiagobernardes is your account provisioned?
