### ISSUE TITLE
SendGridMail 6.1.0 and 6.3.4 have different public key tokens

### ISSUE THREAD

**Issue by tbertenshaw** [sendgrid/sendgrid-csharp#176]
I'm using Sendgrid in a c# webjob using the Microsoft.Azure.Webjobs.Extensions.SendGrid nuget package which has a dependancy on the Sendgrid nugetpackage (https://www.nuget.org/packages/Sendgrid)

after updating from 6.1.0 to 6.3.4.

"Could not load file or assembly 'SendGridMail, Version=6.3.4.0, Culture=neutral, PublicKeyToken=2ae73662c35d80e4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"SendGridMail, Version=6.3.4.0, Culture=neutral, PublicKeyToken=2ae73662c35d80e4"

if you run "sn -T sendgridmail.dll" in cmd you get "**4f047e93159395ca**" if i do the same on the 6.1.0 version i get "**2ae73662c35d80e4**"

Thus dll's which are build against sendgrid.dll or sendgridmail.dll will fail.

Is there a reason for this?

**Comment by thinkingserious** [comment]
@tbertenshaw 

I don't have access to the original key used to generate the old token, so I had to generate a new one for the updates.

Is it a difficult fix? I did not realize this breakage would occur and I'd like to make note of the fix.

Thanks in advance.

**Comment by tbertenshaw** [comment]
Only fix is to generate a new nuget package release with the old public key. Otherwise all dependant DLLs will fail to load
On 7 Jan 2016 16:01, Elmer Thomas <notifications@github.com> wrote:@tbertenshaw 

I don't have access to the original key used to generate the old token, so I had to generate a new one for the updates.

Is it a difficult fix? I did not realize this breakage would occur and I'd like to make note of the fix.

Thanks in advance.

**Comment by thinkingserious** [comment]
I'm looking into this, meanwhile, I suggest you go back to version 6.1.0 or perhaps you can rebuild your DLLs against the updated library.

**Comment by tbertenshaw** [comment]
Yeah I've reverted to 6.1.0. thanks

 Unfortunately its a nuget package from Microsoft which is dependant on sendgrid. That's why its a problem. Any nuget packages people use which have dependency on another will break if the public keys in those dependant dll's changes.

**Comment by thinkingserious** [comment]
@tbertenshaw could you please let me know what package it is?

**Comment by tbertenshaw** [comment]
Its
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.SendGrid/

There could be more  dependant packages but I don't know how you could find that out.

**Comment by thinkingserious** [comment]
Thanks!

**Comment by tbertenshaw** [comment]
any updates or progress on this? Other option would be to liaise with MS and get them to rebuild the sendgrid extension with the new sendgrid library.

**Comment by thinkingserious** [comment]
@tbertenshaw This one is still in our backlog, and yes, our plan is have MS rebuild the SendGrid extension with the new library. Thanks for the follow up!

**Comment by gorillapower** [comment]
I have this same issue, thanks for the info.

**Comment by thinkingserious** [comment]
You can track the progress here: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/34
