### ISSUE TITLE
DNX Core 5.0 Support

### ISSUE THREAD

**Issue by tomaswinston** [sendgrid/sendgrid-csharp#177]
Hi.
Is there any plan to support DNX Core 5.0 in future releaes of SendGrid? Currently I am getting an error that SendGrid.SmtpApi 1.3.1 does not support DNX Core 5.0. If the support is planned can you give an indication as to when I might be available?

Thanks.
T

**Comment by saluce65** [comment]
This is currently under investigation, but there is no time frame yet for .NET Core version.

https://github.com/sendgrid/sendgrid-csharp/issues/146

**Comment by thinkingserious** [comment]
Thanks for the reply @saluce65!

@tomaswinston, @saluce65 is correct. We will post any updates on ticket #146 and/or on the README. We plan to release a roadmap soon where we will be asking for feedback. Please stay tuned.
