### ISSUE TITLE
Received email doesn't include streamed attachments

### ISSUE THREAD

**Issue by Wilapark** [sendgrid/sendgrid-csharp#180]
HI,

Using this library and when I want to send streamed attachments, files are not included in email.
Below is my code:

Creating stream attachments:
            
FileStream fs = new FileStream(@"D:\AppUpdate\Old.txt", FileMode.Open);
            FileStream fs2 = new FileStream(@"D:\AppUpdate\New.txt", FileMode.Open);

            Dictionary<string, Stream> fileStreams = new Dictionary<string, Stream>();

            fileStreams.Add("Old.txt", fs);
            fileStreams.Add("New.txt", fs2);

and in send method , I add them from above dictionary to SendGridMessage object before sending:

                //Attachments
                if (attachments != null)
                {
                    foreach (var attachment in attachments)
                    {
                        if (!string.IsNullOrWhiteSpace(attachment.Key) && attachment.Value != null)
                        {
                            sgMessage.AddAttachment(attachment.Value, attachment.Key);
                        }
                    }
                }

I also tried to set position ( fs.Seek(0, SeekOrigin.Begin);) and also using MemoryStream, but I didn't have any lock.

Have I missed something here?

thanks

**Comment by christophermllr** [comment]
I can also confirm that I'm experiencing this.

**Comment by thinkingserious** [comment]
Thank you @Wilapark and @christophermllr,

We have added this to our backlog.

**Comment by christophermllr** [comment]
For what it's worth, I also tried both rewinding the stream and using MemoryStream to no avail.

**Comment by thinkingserious** [comment]
Thanks, that additional information will help!

**Comment by christophermllr** [comment]
Actually, I was able to get this working.

```
var blob = AttachmentStorageProvider.GetFile(email.AttachmentUrl);
blob.Seek(0, SeekOrigin.Begin);
var ms = new MemoryStream();
blob.CopyTo(ms);
ms.Seek(0, SeekOrigin.Begin);
sgEmail.AddAttachment(ms, email.AttachmentName);
```

**Comment by thinkingserious** [comment]
Awesome, thanks for sharing the fix with us!

**Comment by thinkingserious** [comment]
Hi @Wilapark,

If you are still experiencing this issue, please feel free to re-open.

Thanks!
