### ISSUE TITLE
Why does the library return HttpResponseMessage?

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#181]
Is there a reason the methods in the library return HttpResponseMessage instead of a strongly typed objects?

For instance, a call to GET a given resource (such as `GET https://api.sendgrid.com/v3/asm/groups/:group_id` for example), returns json that looks like this:
```
{
    "id": 100,
    "name": "Newsletters",
    "description": "Our monthly newsletter.",
    "last_email_sent_at": null,
    "is_default": true,
    "unsubscribes": 400
}

```

Wouldn't it be more practical to return an object similar to:
```
public class SuppressionGroup
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public DateTime LastEmailSentOn { get; set; }
    public bool IsDefault { get; set; }
    public int UnsubscribeCount { get; set; }
}
```

**Comment by thinkingserious** [comment]
Thanks for the feedback @Jericho!

Our primary goal is to get coverage for all key v3 endpoints of our API, after that, we will consider these type of enhancements. For now, we are not making any modifications to the returned JSON.

**Comment by Jericho** [comment]
If you think it would be valuable, I am volunteering to fork and submit a PR with strongly typed objects. Also, the library only includes methods for ApiKeys, GlobalStats GlobalSuppressions, Suppressions and UnsubscribeGroups. I am volunteering to submit a PR for the remaining resources such as bounces, recipients, lists, segments, etc.

**Comment by thinkingserious** [comment]
@Jericho, that would be amazing! 

Yes, those are the endpoints we are first implementing across all 7 libraries we support as a baseline (So far we have done PHP, Python and C Sharp). They represent the different types of calls our v3 API can handle. We hope that if someone is urgent need to implement other endpoints, they could use those as an example to get going really quick.

**Comment by mbernier** [comment]
Hey @Jericho I would really like to chat with you about our libraries and API, if you're interested. Please feel free to email me, the address is my github username at my company.
