### ISSUE TITLE
Same email address can be added multiple times to global suppression

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#182]
As far as I know, it doesn't make sense to allow the same email address to be on the global suppression list multiple times but yet the API allows me to do so.

To reproduce:

`POST https://api.sendgrid.com/v3/asm/suppressions/global`
with the following body:
```
{
  "recipient_emails": [
    "myaddress@example.com",
    "myaddress@example.com"
  ]
}
```
The response is `{"recipient_emails":["myaddress@example.com","myaddress@example.com"]}`

In the UI, the result looks like this:
![image](https://cloud.githubusercontent.com/assets/112710/12795340/37fd0878-ca7f-11e5-9733-3b15532640d0.png)

**Comment by thinkingserious** [comment]
Since this is an API issue, do you mind opening a ticket at support@sendgrid.com?

**Comment by Jericho** [comment]
Done. I emailed a link to this github issue to support.

**Comment by thinkingserious** [comment]
Awesome, thanks @Jericho!
