### ISSUE TITLE
Confusing error message when creating an unsubscribe group

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#183]
I am able to create an unsubscribe group sending a request to:
`POST https://api.sendgrid.com/v3/asm/groups`
with the following body:
```
{
  "name": "New group",
  "description": "This is a new group for testing purposes",
  "is_default": false
}
```
The response is:
`{"id":571,"name":"New group","description":"This is a new group for testing purposes","last_email_sent_at":null,"is_default":false}
`

If I send the exact same request with the exact same body, I get the following response:
`{"errors":[{"message":"Sorry, some unexpected error occurred: Failed to add group"}]}`

I am guessing the issue is that I tried to create a second group with the same name and the API doesn't allow two groups with the same name???? Anyway, a more descriptive error message would be appreciated.

**Comment by thinkingserious** [comment]
Thanks for the report! I will pass this feedback along to the API product team.

**Comment by Jericho** [comment]
Sent email to support asking for help to confirm if my guess about API not allowing two groups with same name is correct.

**Comment by thinkingserious** [comment]
Awesome, thanks!
