### ISSUE TITLE
Email Attachment does not get sent if attachment name contains Japanese characters.

### ISSUE THREAD

**Issue by rashmibrahma** [sendgrid/sendgrid-csharp#184]
SendGrid is not sending any attachments if the attachment file name contains any Japanese character.
The Email, once received does not contain any attachments. This is not the case if the attachment name is in ASCII.

**Comment by thinkingserious** [comment]
@rashmibrahma,

Thank you for reaching out to us!

I'm not sure if this is a library issue or an API issue. Could you please provide us with some sample data for testing?

With Best Regards,

Elmer
