### ISSUE TITLE
Access forbidden when trying to GET user/profile

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#185]
The following request: `GET https://api.sendgrid.com/v3/user/profile`

Results in a HTTP 403 response with the following body:
`{"errors":[{"field":null,"message":"access forbidden"}]}`

I went to Settings -> API Keys and clicked on 'Edit details' to view the permissions granted to my API key and, as far as I can tell, there isn't any permission that I can grant (or revoke) that seems related to 'user profile'. Just to be on the safe side, I have configured every single permission to 'Full Access' (when available) or to 'Read Access' if 'full access' is not available but I am still getting this HTTP 403 error.

What is the permission I need to grant to my API key in order to be able to retrieve my user profile?

**Comment by Jericho** [comment]
This seems to be an API issue more than a C# library question so I will contact support but I figured I would ask the question here anyway in case someone else has faced this issue and can share how they resolved this permission issue.

**Comment by Jericho** [comment]
I just noticed that I am getting the exact same HTTP 403 error send sendin a request to:
`GET https://api.sendgrid.com/v3/api_keys`

someone else [reported this problem](https://github.com/sendgrid/sendgrid-csharp/issues/175)

**Comment by thinkingserious** [comment]
@Jericho is your account provisioned?

**Comment by Jericho** [comment]
yes it is

**Comment by thinkingserious** [comment]
Thank you, we are investigating.

**Comment by Jericho** [comment]
Any update?

**Comment by thinkingserious** [comment]
@Jericho could you please check your permissions and try once again? Thanks!

**Comment by Jericho** [comment]
What permissions do you want me to check? As I explained before, I don't see any privilege that would be related to "API Keys". Here's what I see:

![sshot-26](https://cloud.githubusercontent.com/assets/112710/13083512/fce0c038-d49a-11e5-9f54-77b7e106a909.png)

All privileges are "Full Access" (or read-only if full-access is not available).

I ran another test and I am still getting HTTP 403.

**Comment by thinkingserious** [comment]
Thanks for getting that to me so quickly? Do you already have a support ticket number for this issue?

**Comment by Jericho** [comment]
I opened ticket #594726 on February 5. All I heard since is they are "running some tests" and are "still investigating".

**Comment by thinkingserious** [comment]
Thanks, I will follow up.

**Comment by Jericho** [comment]
I just discovered the exact same HTTP 403 when issuing the following request:

`GET https://api.sendgrid.com/v3/categories?limit=50&offset=0`

**Comment by MMLTest** [comment]
Hi,

I have the same problem. Did you have any chance to fix this?

Thanks

**Comment by Jericho** [comment]
Unfortunately, the problem still hasn't been fixed.

**Comment by MMLTest** [comment]
Thanks for your reply. 
So, you also cannot call any of those post method api, right?

**Comment by Jericho** [comment]
Here are the 3 API calls that are returning HTTP 403 for me:

1. `GET https://api.sendgrid.com/v3/user/profile`
2. `GET https://api.sendgrid.com/v3/api_keys`
3. `GET https://api.sendgrid.com/v3/categories?limit=50&offset=0`

All other API calls are working perfectly fine for me.

**Comment by MMLTest** [comment]
Oh, Thanks,

**Comment by erkinkas** [comment]
I have same issue for:
https://api.sendgrid.com/v3/stats
https://api.sendgrid.com/v3/templates

Also I can't generate any new API Key:
![sendgrid_issue](https://cloud.githubusercontent.com/assets/13992901/13140935/bd084e48-d62c-11e5-88f0-c69b8805684a.png)

**Comment by thinkingserious** [comment]
@Jericho I have updated our internal support ticket for you with a link to these details.

@erkinkas Please submit your issue to our support team at support@sendgrid.com.

Thanks!

**Comment by sinaislam** [comment]
I also get this issue for stats.get.json api.

**Comment by thinkingserious** [comment]
@sinaislam please submit your issue to our support team at support@sendgrid.com.

Thanks!

**Comment by courajs** [comment]
For people finding this through google, it seems only the "main" account can generate API keys.
If you are a managed user, you'll have to ask your administrator to generate the API key for you.
To tell whether you are a managed user or an administrator, check your Settings dropdown for "Credentials" or "Plan & Billing Details".
Managed user:
<img width="173" alt="screen shot 2016-07-12 at 4 58 13 pm" src="https://cloud.githubusercontent.com/assets/1588273/16784950/524f14ca-4859-11e6-9e86-cbcda4de9e9d.png">
Admin user:
<img width="175" alt="screen shot 2016-07-12 at 4 58 03 pm" src="https://cloud.githubusercontent.com/assets/1588273/16784952/58c694ea-4859-11e6-9411-8209d2da748a.png">

**Comment by thinkingserious** [comment]
@courajs Thanks for sharing the solution!

**Comment by omarshamali** [comment]
still getting this in 2018. lol
[ GOOD ]{"errors":[{"field":null,"message":"access forbidden"}]}NULL

**Comment by thinkingserious** [comment]
Hi @omarshamali,

Have you tried the solution offered above by @courajs?

With Best Regards,

Elmer

**Comment by omarshamali** [comment]
@thinkingserious  yes, i have the master account, generated a full access API, and still the same, i get access forbidden

**Comment by thinkingserious** [comment]
Hi @omarshamali,

In that case, I suggest you reach out to our [support team](https://support.sendgrid.com) so that they may took a deeper look at your account.

**Comment by branditodesign** [comment]
@omarshamali The API & SendGrid as a whole is a bit broken at the moment in my opinion, I've made atleast 5 or 6 different support tickets in the past 6 months, all different issues. At the moment I'm facing the same issue as you, my API key has full access yet first I was receiving this:

`Failed to load https://api.sendgrid.com/v3/messages?limit=10&query=msg_id%3D%22asdfasdf.0%22: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://sendgrid.api-docs.io' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

Then after navigating to https://api.sendgrid.com/v3/messages to bypass the CORS/ ACAO header(s) I `get {"errors":[{"field":null,"message":"access forbidden"}]}`

**Comment by thinkingserious** [comment]
Hello @branditodesign,

[Here is some documentation](https://sendgrid.com/docs/Classroom/Basics/API/cors.html) on CORS issues. Please let me know if that is what you need.

With Best Regards,

Elmer

**Comment by branditodesign** [comment]
Sadly no it doesn't.
I'm not attempting to send emails via the browser but access other API
endpoints and receiving 403 forbidden.

**Comment by branditodesign** [comment]
@thinkingserious I solved the issue.
As it turns out, since SendGrid changed their pricing model to **charge** for the last 30 days of data, they also restrict ALL access to the API **UNLESS** you pay for the $12/month plan, even if you're only trying to access data about an email from yesterday...

**Comment by Jericho** [comment]
@branditodesign [I noticed the same thing](https://github.com/sendgrid/sendgrid-csharp/issues/689)

**Comment by thinkingserious** [comment]
Hi @branditodesign,

As an alternative, I suggest you checkout the [Event Webhook](https://sendgrid.com/docs/API_Reference/Webhooks/event.html). 

I hope that helps.

With Best Regards,

Elmer

**Comment by branditodesign** [comment]
@thinkingserious A step ahead of you there :p
I just wish I could have the email address each email is sent from included with the webhook events, saves me from going into the activity feed or our CRM and finding it myself.
![chrome_2018-05-15_12-59-21](https://user-images.githubusercontent.com/37203648/40034355-f13a14e8-583f-11e8-8454-e9c84a234270.png)

**Comment by thinkingserious** [comment]
Perhaps [custom args](https://github.com/sendgrid/sendgrid-csharp/blob/master/tests/SendGrid.Tests/Integration.cs#L164) can help make that easier for you by assigning a unique id (perhaps the user id in your CRM) to each outgoing email to make it easier to automatically match with the entry in your CRM.

**Comment by branditodesign** [comment]
The thing is though a lot of the times they're going out from different email address, also it seems that solution requires access to the v3 API, something we don't have :(

**Comment by thinkingserious** [comment]
@branditodesign,

Can you elaborate your use case please? Thanks!

**Comment by thinkingserious** [comment]
Hi @branditodesign,

Thanks for taking the time to elaborate so that I can share with our product team. 

With Best Regards,

Elmer

**Comment by branditodesign** [comment]
Thank you for dealing with the GitHub issues professionally 😃

**Comment by branditodesign** [comment]
Tell me someone deleted that comment from Obi

**Comment by thinkingserious** [comment]
He must have deleted it himself as I did not.

**Comment by branditodesign** [comment]
Sigh, the comment is still in my inbox....
Just a reminder not to post code without first removing your API keys!

**Comment by obioberoi** [comment]
The API key was from the code snippet posted by SendGrid on their docs page as a sample.
I deleted the comment shortly after posting it as I realized it should belong to a different category.

**Comment by branditodesign** [comment]
Strange... Last time I visited the docs I couldn't see any examples including an API key, only examples including YOUR_API_KEY or YOUR_API_KEY_HERE

**Comment by srinivas252** [comment]
**ISSUE** : Request** returned status Code 401Body:{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}

package springboot.SendgridExample;
import java.io.IOException;

import com.sendgrid.*;

public class Sendmail1 {
  public static void main(String[] args) throws IOException {
    Email from = new Email("XXX@gmail.com");
    String subject = "I'm replacing the subject tag";
    Email to = new Email("XXX@mail.com");
    Content content = new Content("text/html", "I'm replacing the <strong>body tag</strong>");
    Mail mail = new Mail(from, subject, to, content);
    mail.personalization.get(0).addSubstitution("-name-", "Example User");
    mail.personalization.get(0).addSubstitution("-city-", "Denver");
    mail.setTemplateId("d-9f26c562e3d34eksfjksdkkj3242"); //dummy value i have that template id

    SendGrid sg = new SendGrid(System.getenv("SENDGRID_API_KEY"));
    Request request = new Request();
    try {
      request.setMethod(Method.POST);
      request.setEndpoint("mail/send");
      request.setBody(mail.build());
      Response response = sg.api(request);
      System.out.println(response.getStatusCode());
      System.out.println(response.getBody());
      System.out.println(response.getHeaders());
    } catch (IOException ex) {
      throw ex;
    }
  }
}

**Comment by srinivas252** [comment]
Hi,

Am not able to access any of the API from sendgrid 
* `GET https://api.sendgrid.com/v3/user/profile`

* `GET https://api.sendgrid.com/v3/api_keys`

Getting Access forbidden issue please help me to resolve
Thanks in advance.

**Comment by tgwaste** [comment]
Still broken
https://api.sendgrid.com/v3/user/credits
{"errors":[{"field":null,"message":"access forbidden"}]}

**Comment by chienkira** [comment]
Still broken now??? 403 even I created a full-access api key

**Comment by tgwaste** [comment]
Ya. May be time to move on here. Lots of competition out there.

**Comment by acip** [comment]
We are getting 403 for https://api.sendgrid.com/v3/contactdb/list ...

**Comment by JClackett** [comment]
Also getting 403 on the endpoint @acip included

**Comment by Bug-Generator** [comment]
Hi folks I am getting a 403 while trying to use the email activity feed Api like so
`https://api.sendgrid.com/v3/messages?limit=10`
The documentation says you have to puchase additional email activity history and I'm not sure if our insatance has that but I see `"email_activity.read"` as one of the permissions (I am using the master API key in my case)

**Comment by albertbenitez** [comment]
It seems this issue happens to FREE accounts. @acip @JClackett @Bug-Generator did you guys have a FREE account or a paid one? Just want to know to confirm.

**Comment by JClackett** [comment]
@albertbenitez I have a paid account!

**Comment by acip** [comment]
free (in trial atm)

**Comment by Bug-Generator** [comment]
I have both a paid and a free account. I get the same issue in both

**Comment by omarshamali** [comment]
this is why i quit sendgrid forever, very weak technical support and bug fixing

**Comment by albertbenitez** [comment]
OFFICIAL SENDGRID TICKET RESPONSE
> I am afraid that all the accounts made through our resellers don't have access to marketing campaigns feature, therefore, this is why you are unable to upload contacts.
> 
> Is not limited because it's free, it's limited because it's made through one of the resellers that don't have access to this feature.

I don't understand that the ticket response means about the resellers. **Did you guys send a ticket as well?**

**Comment by JClackett** [comment]
@albertbenitez i assume using integrations like heroku, where you sign up via heroku

**Comment by Bug-Generator** [comment]
My free account was made on the official sendgrid website

**Comment by JClackett** [comment]
mine also! so not sure whats going on here..

**Comment by Bug-Generator** [comment]
Its quite unfortunate that after this long nothing concrete from sendgrid to fix this issue

**Comment by biplobice** [comment]
Same here

**Comment by astutejoe** [comment]
I guess it's time to move on to the competition folks, this thing is dead :)

**Comment by omarshamali** [comment]
bye bye sendgrid

**Comment by shanwixcode** [comment]
Hey guys! I had to use the V3 API found here: https://sendgrid.api-docs.io/v3.0/contacts/add-or-update-a-contact

It works perfectly using this version of the API.

**Comment by shanwixcode** [comment]
> I'm getting the same "access forbidden" error when trying to create a new contact via https://api.sendgrid.com/v3/contactdb/recipients
> 
> Is there any solution to this?

I had to use the V3 API found here: https://sendgrid.api-docs.io/v3.0/contacts/add-or-update-a-contact

It works perfectly using this version of the API.

**Comment by gotjosh** [comment]
Thanks for your comment @shanwixcode - seems like everything is outdated.

**Comment by burningice2866** [comment]
@shanwixcode after scratching my head on this for many hours i followed your link and after updating my code it works again.. Geez SendGrid, if you depricate api's at least make it clear in documentations and what nut. Technically its all still v3 which can't have breaking changes like this!

**Comment by kfwebmaster** [comment]
The issue is that sendgrid have documentation and examples on their website that is several years old and the API paths have changed.

**Comment by marius-stanescu** [comment]
I think the problem is because they have two versions of marketing campaigns, a new one and a legacy one. I think calls to the legacy API are not allowed anymore, but calls to the new one work. I inferred this from trying out both legacy and new APIs and reading this: https://sendgrid.com/docs/ui/sending-email/migrating-from-legacy-marketing-campaigns/#choosing-a-new-marketing-campaigns-plan.

**Comment by kfwebmaster** [comment]
@marius-stanescu Yes, that is the issue. But why not call the new API "version 4" - now we have two versions labeled "version 3". And when googling issues, I usually find the help for the wrong API. 

I found it very useful to use Postman and to load the API documentiation found here: https://api.stoplight.io/v1/versions/E2KbzZkqZQttfyqxp/export/oas.json

**Comment by veebuv** [comment]
Sendgrid, have to say - really poor form overall with your entire API, worst experience on my end

Docs are out of order, everything that has documentation is deprecated, APIs all over the place

Can't do a simple get request either i'm stuck with the forbidden request for trying to get users from a contact

Oh PS your automation script seems to be broken too...sent out one email and stopped working after that

This level of incompetency for a $100 >million company is sad

**Comment by tgwaste** [comment]
they are worth more than 100 million dollars??  and they cant spend a day getting their API fixed?
