### ISSUE TITLE
Documentation about adding/updating recipient doesn't match my experiences

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#186]
The [documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Recipients-POST) indicates that we should POST to create new recipients and we should PATCH to update existing recipients.

However, I found out by accident that we can combine all recipients into a single POST request and the SendGrid API will update existing recipients and create new recipients for those that are not already present. In essence the POST request allows us to 'upsert'. This behavior does not quite match the documentation but I happen to think the behavior is actually extremely convenient. 

Having said that, there is one problem with the behavior: the response from the POST request does not tell you which recipients were updated and which were created. Let me illustrate with an example:

Step one: create a new recipient with the following request:
```
POST https://api.sendgrid.com/v3/contactdb/recipients 
[
  {
    "email": "111@example.com",
    "first_name": "First",
    "last_name": "Recipient"
  }
]
```

Step two: make the following request. As you can see, we are attempting to update the name of the first recipient AND we are attempting to create a second recipient
```
POST https://api.sendgrid.com/v3/contactdb/recipients 
[
  {
    "email": "111@example.com",
    "first_name": "Bob",
    "last_name": "Smith"
  },
  {
    "email": "222@example.com",
    "first_name": "Second",
    "last_name": "Recipient"
  }
]
```
The response will look like this:
`{"error_count":0,"error_indices":[],"new_count":1,"persisted_recipients":["MTExQGV4YW1wbGUuY29t","MjIyQGV4YW1wbGUuY29t"],"updated_count":1}`

As you can see, this response correctly indicates that one recipient was created and that one recipient was updated but there is no way to tell which one was updated and which one was created.

**Comment by Jericho** [comment]
Email sent to support with link to this github issue.

**Comment by Jericho** [comment]
The feedback i received from support is that this is "by design".

**Comment by mbernier** [comment]
Thank you so much for letting us know and for the example! I will discuss with the team that owns this endpoint.
