### ISSUE TITLE
WebApi: paging is not consistent

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#191]
I noticed that some API calls allow paging by specifying a limit and offset ([example1](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/campaigns.html#Get-all-Campaigns-GET), [example2](https://sendgrid.com/docs/API_Reference/Web_API_v3/Categories/categories.html)) while other API calls allow paging by specifying a page number and a number of records per page ([example1](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#List-Recipients-GET), [example2](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#List-Recipients-on-a-List-GET))

I was wondering if this was intentional or if it was simply overlooked and SendGrid intended to use a consistent paging strategy?

**Comment by thinkingserious** [comment]
Hello @Jericho,

Thanks again for your questions! Please submit these to our support team so we can dig deeper.
