### ISSUE TITLE
WebApi: Sender Identity

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#192]
We must specify the unique identifier of the sender when creating a campaign ([documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/campaigns.html#Create-a-Campaign-POST)) but I am not finding any API documentation about creating a new sender, getting the list of existing senders, etc.

I found documentation about [manually creating a new sender identity](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/senders.html), but nothing in the API documentation.

Is there a way to create sender identities via the API?

**Comment by thinkingserious** [comment]
Hello @Jericho,

Please submit this question to our support team. 

Thanks!
