### ISSUE TITLE
WebApi: Date formats are not consistent

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#193]
I have noticed that the API seems to use a few different date formats and I was wondering if it was intentional or if SendGrid intended to be more consistent.

Here are a few examples I discovered so far:

- "MM/dd/yyyy" format is used when specifying a date criteria for a new [segment](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Create-a-Segment-POST) 
- "yyyy-MM-dd hh:mm:ss" format is used for the updated_at" field on [template version](https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/versions.html)
- "Seconds since epoch" format is used for numerous fields such as "created_at" when [retrieving a recipient](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Retrieve-a-Recipient-GET)

**Comment by thinkingserious** [comment]
Hello @Jericho,

Please report this issue to our support team. Our GitHub issues area or for issues specific to the libraries. 

Thanks!
