### ISSUE TITLE
Use with Authenticated Proxy?

### ISSUE THREAD

**Issue by jjblanco** [sendgrid/sendgrid-csharp#197]
Hi.

I've seen a 2 year old issue where this was mentioned, but apparently abandoned... am I right? It seems odd as it's such a prevalent case; however, fact of the matter is I've been browsing through the code and the default setting of the proxy for the HttpClient used in the Web class...

WebRequest.DefaultWebProxy.Credentials = CredentialCache.DefaultNetworkCredentials;

... doesn't seem to work (I get "Unable to connect to the remote server" errors when attempting to send email from inside the proxy-authenticated network, works fine from Azure), and I can't figure out why (I have it working in several other apps).

Any insights would be appreciated!

**Comment by Jericho** [comment]
I have forked the repo and working on several improvements to the client library. One of the improvements I added is the ability to inject your own httpclient in the client constructor which therefore  allows you to specify your proxy. Here's an example to illustrate:

```
var apiKey = "... your api key ...";
var httpClient = new HttpClient(
    new HttpClientHandler()
    {
        Proxy = new WebProxy("http://localhost:8888"),
        UseProxy = true
    }
);
var client = new SendGrid.Client(apiKey: apiKey, httpClient: httpClient);
var contact = new Contact()
{
    Email = "111@example.com",
    FirstName = "Robert",
    LastName = "Smith"
};
contact.Id = await client.Contacts.CreateAsync(contact);

```

You can find my fork here: https://github.com/Jericho/sendgrid-csharp

**Comment by thinkingserious** [comment]
Hello @jjblanco,

I'm leaving this open because it is on our roadmap to allow what @Jericho has already implemented.

The new version of this library can be found here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta (to come out of beta in weeks) and it now rely's on this client: https://github.com/sendgrid/csharp-http-client

Thank you both for your support!

With Best Regards,

Elmer

**Comment by julianonunes** [comment]
Any updates on this?

**Comment by thinkingserious** [comment]
Hello @julianonunes,

This is on our backlog to implement. Your vote just now helped move it up higher in the list. Thanks!

**Comment by arunkumargan** [comment]
Hi, any news on this? my company allows access to internet via proxy. This is a roadblock as it cant work from inside from company's network.

**Comment by thinkingserious** [comment]
Hi @arunkumargan,

Thanks for the vote on this issue. You have helped move this issue further up on the queue. Currently, it looks like we may be a week or two away from implementing this.

To bump this issue higher on the queue, we need:
- another +1 to the issue
- a pull request with a signed CLA

Thanks!

**Comment by thinkingserious** [comment]
@jjblanco, @Jericho, @julianonunes, @arunkumargan,

This release fixes this issue: https://github.com/sendgrid/sendgrid-csharp/releases/tag/v7.1.0

Apologies for not updating this thread sooner.

**Comment by jingdaz-ma** [comment]
Hi there,

Is there a similar fix of authenticated proxy to Java implementation? We're running into a proxy issue when invoking SendGrid to deliver emails?

Thanks,
Jason

**Comment by thinkingserious** [comment]
Hello @jingdaz-ma,

Could you please provide some further detail on your issue? Preferably in a new issue. Thanks!

e.g: 

1. What version of this library are you using?
2. What's the error you are seeing?
3. Can you share some source code?
