### ISSUE TITLE
Add interfaces to support SOLID

### ISSUE THREAD

**Issue by roryprimrose** [sendgrid/sendgrid-csharp#201]
I would like to use this library, however the lack of interfaces means that I would have to tightly couple my classes to the SendGrid classes. Please add interfaces to the classes to allow for loose coupling.

**Comment by dracan** [comment]
Can't you just abstract the calls out into your own wrapper interfaces/classes? If they add interfaces, then you're still coupled to their interfaces.

**Comment by roryprimrose** [comment]
Yes, that is true. There is always going to be some code of mine that links into theirs. I would rather be coupled to an interface that I can inject into a constructor than an implementation (albeit an abstract one).

**Comment by thinkingserious** [comment]
@roryprimrose Thanks for the suggestion!

We will keep this on our backlog for now.

**Comment by thinkingserious** [comment]
This is note for anyone who wished to contribute on this:

Please add pull requests to this branch: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta and we would need a signed CLA: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/CONTRIBUTING.md#cla

**Comment by M3LiNdRu** [comment]
The following PR, it has started fixing the issue

See: https://github.com/sendgrid/sendgrid-csharp/pull/350
