### ISSUE TITLE
Template version in the wrong timezone

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#202]
When I create a template via the API and also add two versions, the SendGrid UI says that my first version was "Updated 6 hours ago" when in fact it was created only a few seconds earlier.

**Repro steps:**
1) Create a new template with the following API calls:
```
POST https://api.sendgrid.com/v3/templates
{
  "name": "My template"
}
```
Response from API looks like this: `{"id":"c5002709-473b-4a73-8769-3307d6758232","name":"My template","versions":[]}`

2) Create a new version:
```
POST https://api.sendgrid.com/v3/templates/c5002709-473b-4a73-8769-3307d6758232/versions
{
  "name": "Version 1",
  "subject": "My first Subject <%subject%>",
  "html_content": "<html<body>hello world<br/><%body%></body></html>",
  "plain_content": "Hello world <%body%>",
  "active": 1
}
```

At this point SendGrid's UI says that 'Version 1' was "Updated less than a minute ago":
![afterstep2](https://cloud.githubusercontent.com/assets/112710/13330829/471cfe88-dbc0-11e5-9d1a-b4488a8ecfd2.png)

3) Create another version:
```
POST https://api.sendgrid.com/v3/templates/c5002709-473b-4a73-8769-3307d6758232/versions 
{
  "name": "Version 2",
  "subject": "My second Subject <%subject%>",
  "html_content": "<html<body>Qwerty<br/><%body%></body></html>",
  "plain_content": "Qwerty <%body%>",
  "active": 1
}
```

At this point SendGrid's UI says that 'Version 1' was "Updated 6 hours ago" which is off by 6 hours:
![afterstep3](https://cloud.githubusercontent.com/assets/112710/13330834/4c0eddb2-dbc0-11e5-971b-4ed16706b85c.png)

**Comment by thinkingserious** [comment]
Hi @Jericho,

This is great feedback! I'm forwarding this along for action.

With Best Regards,

Elmer

**Comment by mbernier** [comment]
@Jericho this is a known bug for the timezone and we're working to get it resolved in the refresh we're doing for templates soon! 

Thanks for letting us know.
