### ISSUE TITLE
Unable to connect to the server : SendGrid

### ISSUE THREAD

**Issue by DinkuMM** [sendgrid/sendgrid-csharp#204]
Hi all, I am facing issue with sendgrid. When i am sending multiple requests to SendGrid at a time, it get failed due to the refused connection.
i have attached the screenshot of the issue.

![error](https://cloud.githubusercontent.com/assets/17500009/13362398/34921fde-dcea-11e5-9514-60cf7c48fed4.png)

**Comment by thinkingserious** [comment]
For this issue, please contact our support team (support@sendgrid.com) so that can take a look at your individual account. Thanks!
