### ISSUE TITLE
Suppressions by Email Address 

### ISSUE THREAD

**Issue by JonKragh** [sendgrid/sendgrid-csharp#205]
Hi-

Does the API support looking up suppressions by an email address?

I want to have a page on my website showing the groups my user is subscribed to and give the the ability to manage this through my website (and reflecting on sendgrid).

Thanks!
Jon

**Comment by thinkingserious** [comment]
Hello @JonKragh,

The only suppression related API calls we have currently are documented here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/index.html

I like your suggestion though and I suggest you post it here: http://community.sendgrid.com/sendgrid

Thanks!
