### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#208]
Whenever I start my C# project in Visual Studio, I get the following message for several seconds:

![sshot-33](https://cloud.githubusercontent.com/assets/112710/13642219/3a263944-e5e1-11e5-8f7d-7f4cc0becdf2.png)

I'm guessing the path refers to a location on the build machine where SendGrid's nuget package was built.

As far as I can tell, everything works fine but it's annoying to wait several seconds every time I restart my project.

**Comment by thinkingserious** [comment]
Hello @Jericho,

Apologies for the annoyance :( I think you are correct, since I never get this issue on my machine.

Could you please try loading the new project: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta to see if the issue persists.

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
If you are still having this issue, please feel free to re-open, thanks!
