### ISSUE TITLE
x-smtpapi sending to multiple users dropping out mails

### ISSUE THREAD

**Issue by nikhilmysore** [sendgrid/sendgrid-csharp#210]
I am trying to add 1000 ids to x-smtpapi header. It is dropping out 20 mails in every run.

using  the latest library. 
and code : myMessage.Headers.Add("x-smtpapi", header.JsonString());

I also tried inserting new line in place of comma, even then it drops out 20 mail ids in every run.

Sample dropped event list is as below. Have anyone faced the problem?
i	2016-03-17T16:48:01.000Z	2016-03-17T16:48:45.806Z	56eadfed6f31a23c66609e2e	Invalid	NikhilMysore008	dropped
<JhieqlJdTfOuulniB77Itw@ismtpd0017p1sin1.sendgrid.net>	59LKtSyLRvCQHT0JgZ7zlw	1458233280	filter0576p1mdw1.32212.56EADFA29.957	nikhil	2016-03-17T16:48:00.000Z	2016-03-17T16:48:45.800Z	56eadfed6f31a23c66609e0d	Invalid	NikhilMysore008	dropped
<JhieqlJdTfOuulniB77Itw@ismtpd0017p1sin1.sendgrid.net>	e8c99aoaRFyfrkkz-0wbhg	1458233280	filter0576p1mdw1.32212.56EADFA29.924	nikhil0	2016-03-17T16:48:00.000Z	2016-03-17T16:48:45.794Z	56eadfed6f31a23c66609dec	Invalid	NikhilMysore008	dropped
<JhieqlJdTfOuulniB77Itw@ismtpd0017p1sin1.sendgrid.net>	sAw_-aVORmO1wS6q7UPFPw	1458233279	filter0576p1mdw1.32212.56EADFA29.891	nikhil00	2016-03-17T16:47:59.000Z	2016-03-17T16:48:45.788Z	56eadfed6f31a23c66609dcb	Invalid	NikhilMysore008	dropped
<JhieqlJdTfOuulniB77Itw@ismtpd0017p1sin1.sendgrid.net>	S9vnTT4qTFaoLeHk-sRu3w	1458233278	filter0576p1mdw1.32212.56EADFA29.858	nikhil008	2016-03-17T16:47:58.000Z	2016-03-17T16:48:45.783Z	56eadfed6f31a23c66609daa	Invalid	NikhilMysore008	dropped
<JhieqlJdTfOuulniB77Itw@ismtpd0017p1sin1.sendgrid.net>	V2AwE_9tT8Krft22rOjqyA	1458233277	filter0576p1mdw1.32212.56EADFA29.825	nikhil0082	2016-03-17T16:47:57.000Z	2016-03-17T16:48:45.777Z	56eadfed6f31a23c66609d89	Invalid	NikhilMysore008	dropped
<JhieqlJdTfOuulniB77Itw@ismtpd0017p1sin1.sendgrid.net>	LYPPsiyiTLqvAFW_bGFHTg	1458233275	filter0576p1mdw1.32212.56EADFA29.726	nikhil00727@m	2016-03-17T16:47:55.000Z	2016-03-17T16:48:45.759Z	56eadfed6f31a23c66609d26	Invalid	NikhilMysore008	dropped
<JhieqlJdTfOuulniB77Itw@ismtpd0017p1sin1.sendgrid.net>	7kd8QhwGRpCgi6w5QblknQ	1458233273	filter0576p1mdw1.32212.56EADFA29.693	nikhil00694@ma

Can see misformed email ids in the event logs.

Nikhil

**Comment by thinkingserious** [comment]
Hello @nikhilmysore,

Please open a support ticket at https://support.sendgrid.com so we can help you ASAP.

Thanks!

With Best Regards,

Elmer
