### ISSUE TITLE
Add JPEG attachment using streams

### ISSUE THREAD

**Issue by mercer2000** [sendgrid/sendgrid-csharp#212]
How do you add a JPEG attachment to a message using a stream?  Sending a TXT file works fine, but sending a JPEG results in an attachment which cannot be opened.  

```
  private MemoryStream GenerateStreamFromString(string value)
        {
            var data = Convert.FromBase64String(value);
            var str = Encoding.UTF8.GetString(data);
            return new MemoryStream(Encoding.UTF8.GetBytes(str ?? ""));
        }

 // add the attachment
MemoryStream attachment = GenerateStreamFromString(base64String);
myMessage.AddAttachment(attachment, attachmentName);
```

Looking at the CURL example, it shows appending the content type.

https://sendgrid.com/docs/API_Reference/Web_API/mail.html

`curl https://api.sendgrid.com/api/mail.send.json \
-F to=recipient@domain.com -F toname=test -F subject="Example Subject" \
-F text="testing text body" --form-string html="<strong>testing html body</strong>" \
-F from=test@yourdomain.com -F api_user=your_sendgrid_username -F api_key=your_sendgrid_password \
-F files\[attachment.pdf\]=@attachment.pdf;type=application/pdf`

I have tried appending  ;type=image/jpeg  to the filename but that resulted in an attachment named jpeg.

**Comment by thinkingserious** [comment]
Thanks for letting us know about this issue. I've added it to our backlog. We'll update any progress here.

**Comment by thinkingserious** [comment]
Hi @mercer2000,

We have updated our mail/send endpoint, you can check it out here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Also, this library will be updated shortly with this one: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

I'm going to keep this issue open and on our backlog to test against our new library and v3 mail/send endpoint.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @mercer2000,

Here is how we currently handle attachments: https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#attachments

You will need to Base64 encode your JPEG attachment.

Thanks!
