### ISSUE TITLE
Memory leak in sendgrid-csharp?

### ISSUE THREAD

**Issue by kquinbar** [sendgrid/sendgrid-csharp#213]
I have a windows service that we use to send out email from a local database queue. we are currently using smtp directly using MS libraries to send to sendgrid, but we wanted to implement this library (v6.3.4) since using the sendgrid api seems to be the preferred way to send email through sendgrid. With our current implementation using smtp the windows service footprint is very low, most of the time it hovers around 60mb. It may spike a couple of hundred meg during large runs (i.e. monday mornings we probably send out 200,000+ emails), but then it will eventually release any extra memory and come back down. I replaced the one class in our windows service that implements smtp and put in code to call this library. Now when we do some performance testing of even 5000-10000 emails, this same windows service uses 1.2gb of memory and never releases it. How we implemented the code was based off your examples. 

Any thoughts on what is going on or are there known memory leak issues? I have attached our helper code to show implementation.
[SendGridHelper.zip](https://github.com/sendgrid/sendgrid-csharp/files/210144/SendGridHelper.zip)

**Comment by thinkingserious** [comment]
Hi @kquinbar,

Thanks for letting us know and providing the code!

We are currently rewriting this library (it will based on this new HTTP Client: https://github.com/sendgrid/csharp-http-client) and I'm not sure if this issue will persist.

That said, I've added this to our backlog to investigate and ensure the new library does not have this issue.

For my own notes, these may be possibly related tickets (you may want to take a look also):
https://github.com/sendgrid/sendgrid-csharp/issues/125
https://github.com/sendgrid/sendgrid-csharp/issues/118

Thanks again!

**Comment by kquinbar** [comment]
any eta on the rewrite of this library?

**Comment by thinkingserious** [comment]
@kquinbar,

The library is now available here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

We will be coming out of beta in a few weeks.

If you would like to contribute, please make your pull request against the v3beta branch and we will need a signed CLA: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/CONTRIBUTING.md#cla

Thank you for your patience and support!

With Best Regards,

Elmer
