### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by veccsolutions** [sendgrid/sendgrid-csharp#214]
The SSL/TLS channel #100 was reported back in January of 2015, and the solution was to upgrade to v5 of the client. However, we are on 6.3.4 and this issue has returned. Is there any kind of fix or workaround we can do to resolve it? Our current fix is to put the send in a loop (with a limit of 10 tries) and it starts working, usually on the 2nd or 3rd attempt.

**Comment by thinkingserious** [comment]
Hi @veccsolutions,

We have not received any new reports of this issue, besides this one. We will need additional information to help you. Could you please open a ticket at https://support.sendgrid.com with the details? (e.g. example code, stack trace, etc..)

Also, this library is about to be replaced with this one: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta/ which includes a new v3 /mail/send endpoint.

With Best Regards,

Elmer

**Comment by scottadamsmith** [comment]
We also experienced this today. It happened 10 times in 4432 requests. I reprocessed them and then the 10 went through. Definitely seems intermittent.

**Comment by thinkingserious** [comment]
@scottadamsmith thank you for the additional feedback.

**Comment by thinkingserious** [comment]
@scottadamsmith it might be some time before we can dig deeper, in the mean time, could you please try adjusting this setting in your app: http://stackoverflow.com/questions/26389899/how-do-i-disable-ssl-fallback-and-use-only-tls-for-outbound-connections-in-net

With regards to the new send API, we are a few weeks away from exiting beta.

**Comment by thinkingserious** [comment]
@scottadamsmith we came out of beta on 6/14.
