### ISSUE TITLE
Missing substitution values

### ISSUE THREAD

**Issue by codefrenzy** [sendgrid/sendgrid-csharp#215]
Hi there,

We are using this library to send transaction emails using templates and substitutions to replace a few values in the email like the recipient's name (e.g. "Hi Jane,") and links in the email (e.g. password reset link). We're using version 6.3.4, SendGridMessage.AddSubstitution() to add each substitution key and value, and lastly, calling Web.DeliveryAsync() to send the email.

Unfortunately we have found that the value are not always replaced in the email template and instead there is sometimes just a space where the value should be (e.g. "Hi ,"). We've run many tests, sending the same email, same template, same values for substitution, without changing our code, and the results are really unpredictable - sometimes the values are replaced, sometimes they aren't. We've tried changing the substitution keys from using colons, (e.g. :name:) to using dashes (e.g. -name-) but we still see the random behaviour. 

We've checked the network calls out to sendgrid and can see no difference between emails where the substitution works and those where it didn't.

I've also raised a support ticket for this issue but I haven't received much of a response yet.

This is a really serious issue for us. Any help would be much appreciated.

Cheers,
Annie

**Comment by justsayno** [comment]
I have just noticed a similar issue but only when sending to multiple users. Is this your issue to? Does it work fine when sending to one email address?

**Comment by justsayno** [comment]
If this is the case then you have to add the substitution tag per user. For example in my simple cases the substitution values are the same I have a function like this (email is my own C# model I use):

```
 private SendGridMessage addSubstitutions(EmailModel email, SendGridMessage sendGridEmail)
        {
            foreach (KeyValuePair<string, string> entry in email.Substitutions)
            {
                var substitutionValues = new List<string>();
                foreach (KeyValuePair<string,string> recipient in email.Recipients)
                {
                    substitutionValues.Add(entry.Value);
                }
                sendGridEmail.AddSubstitution($"*|{entry.Key}|*", substitutionValues );
            }
            return sendGridEmail;
        }
```

**Comment by thinkingserious** [comment]
@codefrenzy,

Thanks for taking the time to write to us, if this is still an issue, please reference the support ticket number.

@justsayno,

Thanks for jumping in with a solution! *Highest of Fives*

With Best Regards,

Elmer
