### ISSUE TITLE
No Contacts API implemented?

### ISSUE THREAD

**Issue by bogacg** [sendgrid/sendgrid-csharp#217]
Am I missing something or this repo holds only implementation for Mail API?
I'd like to add recipients to Contacts Lists I create using [Contacts API](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html).
Can't find anything about it.

Thanks

**Comment by bogacg** [comment]
Ok, apparently it's not implemented yet.

For those who are looking for the same thing, I've created a small test app: [SendGrid-Contacts-Test](https://github.com/bogacg/SendGrid-Contacts-Test). Basic HttpClient implementation. Code is a bit messy, but gives you the idea.
Creating contacts is done with **recipients** endpoint. Once a new recipient is added, it can be assigned to an existing list if needed, with **lists** endpoint.

**Comment by Jericho** [comment]
I implemented all the SendGrid API (including the Contacts) in my fork and submitted a [PR](https://github.com/sendgrid/sendgrid-csharp/pull/211)

**Comment by thinkingserious** [comment]
@bogacg,

We are just about to release a new version of this library that will support all v3 Web API endpoints including the new v3 /mail/send endpoint.

You can check it out here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

Thanks for your support!

With Best Regards,

Elmer
