### ISSUE TITLE
Error in Windows When Using transportWeb.DeliverAsync(myMessage)

### ISSUE THREAD

**Issue by warrenkc** [sendgrid/sendgrid-csharp#218]
I am getting an error in windows when using  transportWeb.DeliverAsync(myMessage).
http://i.imgur.com/X0flzlB.png

`public bool sendEmail(string to, string subject, string body, string name, string SendGridAPIKey) 
    {
        
            // Create the email object first, then add the properties.
            SendGridMessage myMessage = new SendGridMessage();
            //@"Jeff Smith <jeff@example.com>",
            myMessage.AddTo(string.Format("{0} <{1}>", name, to));
       
            myMessage.Subject = subject;
            myMessage.Html = body;

            // Create a Web transport, using API Key
            var transportWeb = new Web(SendGridAPIKey);

            // Send the email.
            try
            {
                //transportWeb.DeliverAsync(myMessage).Wait();
				transportWeb.DeliverAsync(myMessage);
                return true;
            }
            catch
            {
                return false;
            }
            

        }`

**Comment by warrenkc** [comment]
Here is the event log entry from windows server 2012
[Error.zip](https://github.com/sendgrid/sendgrid-csharp/files/243526/Error.zip)

**Comment by warrenkc** [comment]
Application: w3wp.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.NullReferenceException at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean) at System.Web.HttpApplication.OnThreadEnterPrivate(Boolean) at System.Web.LegacyAspNetSynchronizationContext.CallCallbackPossiblyUnderLock(System.Threading.SendOrPostCallback, System.Object) at System.Web.LegacyAspNetSynchronizationContext.CallCallback(System.Threading.SendOrPostCallback, System.Object) at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback, System.Object, System.Threading.Tasks.Task ByRef) at System.Threading.Tasks.AwaitTaskContinuation+<>c.<ThrowAsyncIfNecessary>b__18_0(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by warrenkc** [comment]
I fixed this by updating the web.config to this:
    <compilation debug="true" targetFramework="4.5.2" />
    <httpRuntime targetFramework="4.5.2" />

From:

    <compilation debug="true" targetFramework="4.5" />

**Comment by SeanKendle** [comment]
To what?
