### ISSUE TITLE
Which client lib to use?

### ISSUE THREAD

**Issue by RyanONeill1970** [sendgrid/sendgrid-csharp#220]
Looking over the open issues, the partial V3 implementation and backlog of pull requests it seems that this project is not getting any attention from the official SendGrid development team.

I'd like to use the official client but I can't figure out which one is stable. V2 docs say to use V3. V3 is incomplete and I cannot find anywhere in V3 that simply sends an email. Should I use SMTP to send direct?

I would submit a pull request but until the others have been merged or refused I think it would cause more hassle.

My requirements for a client are;
 1) Add a user to a list (I've done this with a recent V3 pull request).
 2) Send email (not been able to figure out if V3 even does this).
 3) Some assurance that issues like 'Non-ascii characters in sender address' are fixed or not actual bugs.

Could anyone recommend a branch of a single client lib that addresses these issues?

Regards

Ryan

**Comment by thinkingserious** [comment]
Hello @RyanONeill1970,

I apologize for all the confusion. Fortunately, I have an answer :) 

The new library is here https://github.com/sendgrid/sendgrid-csharp/tree/v3beta and will get out of beta within weeks. That includes a new v3 /mail/send endpoint, which you can read about here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

I suggest you test your project against the above v3beta branch.

Thank you for your support!

With Best Regards,

Elmer

**Comment by RyanONeill1970** [comment]
Thank you, that's good to hear. I'll go away and play and send feedback.

**Comment by thinkingserious** [comment]
Have fun! We can't wait to hear your feedback :)
