### ISSUE TITLE
Missing <% body %> tag in template HTML

### ISSUE THREAD

**Issue by mabbashm110** [sendgrid/sendgrid-csharp#222]
I have the following code and a template that has an image with a <%body%> tag
how do i add this body tag in a simple way to avoid the error

` 
               var myMessage = new SendGridMessage();

                // Add the message properties.
                myMessage.From = new MailAddress("user@gmail.com", "Trial");
                myMessage.AddTo(email);
                myMessage.Subject = txtSubject.Text;

                //Add the HTML and Text bodies
                myMessage.SetCategory("<%body%>");
                myMessage.Html = txtHTML.Text;

                myMessage.EnableTemplate("xxxx-xxx-xxxxxx-xxxxx");
                                
                myMessage.EnableFooter("PLAIN TEXT FOOTER", txtFooter.Text);

                myMessage.EnableClickTracking(true);

                var transportWeb = new SendGrid.Web(txtAPI.Text);
                transportWeb.DeliverAsync(myMessage);

                MessageBox.Show(transportWeb.DeliverAsync(myMessage).Status.ToString());`

**Comment by thinkingserious** [comment]
@mabbashm110,

I believe that error happens when you don't include the <% body %> tag in the template itself.

If you need further help with templates, I suggest you reach out to our support team at: https://support.sendgrid.com

Thanks!

With Best Regards,

Elmer
