### ISSUE TITLE
Move InvalidApiRequestException to properly named namespace

### ISSUE THREAD

**Issue by madmunsterdaddy** [sendgrid/sendgrid-csharp#223]
Currently InvalidApiRequestException exists in a namespace called "Exceptions"

Could you move that to something more specific like "SendGrid.Exceptions"?

**Comment by thinkingserious** [comment]
Hello @madmunsterdaddy,

Thanks for the feedback!

In the new version of the library we have not yet implemented custom SendGrid exceptions. If and when we do, we'll namespace them properly.

For reference, here is the new library: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

With Best Regards,

Elmer
