### ISSUE TITLE
Conflicting/confusing messages being sent around the NuGet package versus the state of v3beta

### ISSUE THREAD

**Issue by dmackmiicard** [sendgrid/sendgrid-csharp#227]
This is a little confusing:
- the NuGet package links back to the (v2) branch but is documented to contain assemblies referencing v3beta
- the v3beta REAME indicates that the NuGet package contains assemblies references master (v2)

The README on https://github.com/sendgrid/sendgrid-csharp/tree/v3beta (last updated 20 hours ago) states that
> Once we are out of v3 BETA, the following will apply
> ....
> `PM> Install-Package SendGrid`

It seems this applies _right now_.  As of https://www.nuget.org/packages/Sendgrid/6.2.0 (Nov 2015), it seems that "`Install-Package SendGrid`" will install assemblies targetting v3beta (with the NuGet summary stating "C# client library and examples for using SendGrid API's to send mail and access Web API v3 endpoints").

- Is v3 out of beta, or is there an issue with the documentation on both the NuGet package and v3beta README?
- Would you still recommend that production systems target the master branch (v2)?
 - If so, which is the most stable NuGet package available?
 - (https://www.nuget.org/packages/Sendgrid/6.1.0 (Apr 2015) appears to be the last which doesn't make reference to "Web API v3")

**Comment by thinkingserious** [comment]
Hello @dmackmiicard,

The version that is currently on Nuget does indeed support a handful of v3 Web API endpoints, but is not related to the v3beta branch. It was an initial attempt at supporting v3 Web API endpoints.

The v3beta branch is a complete rewrite and supports all of the v3 Web API endpoints.

Version 6.3.4 is the last stable version for v2 (with some limited v3 support).

Moving forward, we will only be supporting the v3beta branch, which should be merged to master within weeks.

Apologies for the confusion and thanks for your patience. We are finally close to completing the transition.

With Best Regards,

Elmer
