### ISSUE TITLE
Support for decompression or custom HttpClientHandler?

### ISSUE THREAD

**Issue by aaron-horst** [sendgrid/sendgrid-csharp#230]
Is there any thought of supporting decompression via [HttpClientHandler](https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler%28v=vs.118%29.aspx)? Ideally it would be nice to have the [automatic decompression option](https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler.automaticdecompression%28v=vs.118%29.aspx) enabled for the Deflate and GZip flags.

**Comment by thinkingserious** [comment]
Hello @aaron-horst,

This is not a feature that is currently on our radar. What is your current solution and how does this make things better?

Thanks for your support and contribution!

With Best Regards,

Elmer

**Comment by aaron-horst** [comment]
HTTP compression is a capability that can be built into web servers and web clients to improve transfer speed and bandwidth utilization. I would think that compressing the payload before issuing the postasync call would speed up the overall throughput. When managing a high volume sending application with a larger message size I would think there are efficiencies to be gained here.

**Comment by thinkingserious** [comment]
Hi @aaron-horst,

This will help make a case for including this feature in the next update. Thanks!

**Comment by aaron-horst** [comment]
Thanks I appreciate it.  I notice the library has been updated significantly since I originally submitted the inquiry. Do you believe performance will be about the same, better, or slightly degraded from the previous version?

**Comment by eshanholtz** [comment]
Closing as this was marked as a non-library issue.
