### ISSUE TITLE
How do I do async await's with the new API?

### ISSUE THREAD

**Issue by jahmai** [sendgrid/sendgrid-csharp#238]
As per the topic. While the new API provides the full v3 API functionality, which is welcome, it seems like a huge step back in C# API design.

How do I 'await' the API calls - we simply do not do synchronous network calls in our system (and frankly, nobody should be writing code that does them anymore).

**Comment by jahmai** [comment]
More specifically, how do I do the following with the new API:

`            SendGridMessage message = new SendGridMessage
                                      {
                                          To = new[] { from },
                                          Bcc = emailAddresses.ToArray(),
                                          From = from,
                                          Subject = subject,
                                          Html = body,
                                      };

            WebTransport transport = new WebTransport(_settings.Credentials);
            await transport.DeliverAsync(message);

`

**Comment by thinkingserious** [comment]
Hello @jahmai,

Thanks for the feedback!

This issue is related to https://github.com/sendgrid/sendgrid-csharp/issues/235 which I will be digging into today. Please follow that ticket for progress.
