### ISSUE TITLE
Apostrophe anywhere in email (including content) causes a BadRequest

### ISSUE THREAD

**Issue by aaronamer** [sendgrid/sendgrid-csharp#241]
Sending an email with an Apostrophe anywhere in the email results in a BadRequest response.

#### Steps to Reproduce
var mail = new Mail();

mail.AddContent(new Content("text/plain", "Aaron's"));

var personalization = new Personalization() { 
	Tos = new List<Email> { new Email("xxx@xxx.com") },
	Subject = "Test"
};

mail.AddPersonalization(personalization);
mail.ReplyTo = mail.From = new Email("xxx@yyy.com");
mail.Subject = "Test";

var response = sendGrid.client.mail.send.beta.post(requestBody: mail.Get());
var trueResult = response.StatusCode != HttpStatusCode.Accepted;

#### Technical details:

* sendgrid-csharp Version: 7.0.1 (Nuget)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Thanks for the issue report @aaronamer!

Please follow this ticket for updates: https://github.com/sendgrid/sendgrid-csharp/issues/232
