### ISSUE TITLE
Escape single quotes in request body

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#247]
#### Issue Summary

If you include an unescaped single quote in your request body content, you get a BadRequest error.

#### Steps to Reproduce

https://github.com/sendgrid/sendgrid-csharp/issues/245

#### Technical details:

* sendgrid-csharp Version: 7.X.X
* .NET Version: 4.5.2

**Comment by charles-smith** [comment]
Possibly a duplicate of #241?

**Comment by thinkingserious** [comment]
@charles-smith yes, that's true. I'll go ahead and close this one. Thanks!
