### ISSUE TITLE
Create an Attachment Helper

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#248]
#### Issue Summary
- automatically encode the file and select the correct content type
#### Steps to Reproduce

https://github.com/sendgrid/sendgrid-csharp/issues/244
#### Technical details:
- sendgrid-csharp Version: 7.X.X
- .NET Version: 4.5.2

**Comment by rlaraujo** [comment]
Just in case this could be of any help!!!

Instead of making:
System.Text.Encoding.UTF8.GetString(pdfBuf);

I did a:
attachment.Content = Convert.ToBase64String(pdfBuf);

And it worked like Charm!

**Comment by thinkingserious** [comment]
Thanks @rlaraujo, I will try it out.

**Comment by rlaraujo** [comment]
Hi @thinkingserious  did it work for you?

**Comment by thinkingserious** [comment]
@rlaraujo,

I have not had a chance to try it :(

It's still in my backlog though and it will get there. 

If other people vote this up, it can get a higher spot in the queue.

**Comment by thinkingserious** [comment]
Please see [here](https://github.com/sendgrid/sendgrid-csharp/pull/522).
