### ISSUE TITLE
apostrophe causes BadRequest StatusCode when using v3 api

### ISSUE THREAD

**Issue by wpalombini** [sendgrid/sendgrid-csharp#249]
I am using the latest version 7.0.2 downloaded from Nuget package on my asp.net MVC 5 (.net 4.5.2) and whenever I send an email where the html content has a ' apostrophe, the response is BadRequest and the email is not sent.

**Comment by charles-smith** [comment]
I reported this the other day. It's already being tracked in #247.

**Comment by thinkingserious** [comment]
@wpalombini,

@charles-smith is correct. Thanks for taking the time to report the issue!
