### ISSUE TITLE
Build error when pulling NuGet package in .NET 4.5 and 4.5.1 projects

### ISSUE THREAD

**Issue by valverij** [sendgrid/sendgrid-csharp#250]
#### Issue Summary

I am receiving a build error when using the sample code for the "Hello Email" in the project's README.md in a .NET 4.5 project.

> The type or namespace name 'Helpers' does not exist in the namespace 'SendGrid' (are you missing an assembly reference?)

The compiler indicates the error is right in the `using` statements:

    using System;
    using SendGrid;
    using SendGrid.Helpers.Mail; // <-- build error: The type or namespace name 'Helpers' does not exist in the namespace 'SendGrid'

For reference, `using global::SendGrid.Helpers.Mail;` also breaks.

Interestingly enough, the namespace and classes appear in IntelliSense, despite breaking on build.

#### Steps to Reproduce

1. Start a new **.NET 4.5 or 4.5.1 project** (I tried both a console application and a unit test project)
2. Install the SendGrid package through NuGet: `Install-Package SendGrid`
3. Add `using SendGrid.Helpers.Mail;` to a class
4. Attempt to build.

#### Technical details:

* sendgrid-csharp Version: 7.0.2 (last published 6/16/2016 in NuGet)
* .NET Version: 4.5 and 4.5.1

*Note, 4.5.2 and 4.6 projects build without any issues*

**Comment by thinkingserious** [comment]
Hello @valverij,

Currently, this library is compiled for 4.5.2. I suspect that is the issue.

We already have an issue open to support .NET Core. I'm thinking support for .NET 4.5 could be added as well using the same strategy. 

That said, is there a compelling reason to use .NET 4.5 or 4.5.1 over 4.5.2?

Thanks!

**Comment by valverij** [comment]
I'm working with a large enterprise application that is targeting .NET 4.5. I wanted to check out some of the newer features of the most recent SendGrid C# library (it's using 5.0.0). Upgrading to 4.5.2 could require us to upgrade several other Nuget packages, some of which may also have breaking changes.

**Comment by thinkingserious** [comment]
Hello @valverij,

Because 4.5 and 4.5.1 are no longer supported by Microsoft (https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) we will not be supporting that build.

That said, you can try compiling our source code with .NET 4.5 as the target. With any luck, changes to get it working may be minimal.

Or perhaps you can convince your team to upgrade to 4.5.2.

With Best Regards,

Elmer

**Comment by valverij** [comment]
Manually compiling for 4.5 worked perfectly. Thank you.
