### ISSUE TITLE
New version seems to have lost the ability to add multiple substitution values per key

### ISSUE THREAD

**Issue by yielr** [sendgrid/sendgrid-csharp#253]
#### Issue Summary

I'm using version 7.0.2 and I can't find a way to add multiple values per substitution key.
The current version has this method in Personalization: 

personalization.AddSubstitution(string, string);

but I don't see a way to do:

personalization.AddSubstitution(string, List<string>);

Thank you.

#### Technical details:

* sendgrid-csharp Version: 7.0.2
* .NET Version: 4.5.2

**Comment by yielr** [comment]
It looks like you need to specify a "Personalization" per different substitution value. Is this the case? Thank you.

**Comment by yielr** [comment]
It's one Personalization per recipient and then you just stick the substitutions for that recipient in the particular personalization object.

**Comment by thinkingserious** [comment]
Thanks for following up with the solution @yielr!
