### ISSUE TITLE
multiple recipients

### ISSUE THREAD

**Issue by lijaso** [sendgrid/sendgrid-csharp#254]
#### Issue Summary

When using the email helper to send an email to multiple recipients, only the first recipient receives the email.

#### Steps to Reproduce

1. set recipients like "user1@sample.com,user2@sample.com"
2. send the email to the recipients
3. only user1@sample.com received the email, though "user2@sample.com" is shown in the recived email "To" field

Would be nice to have multi recipients supported. Cheers,

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by yielr** [comment]
Can you add more information? Using the latest version (7.0.2), I can send to multiple recipients like this:

Personalization personalization = new Personalization();
            email = new Email();
            email.Name = "Example User";
            email.Address = "test1@example.com";
            personalization.AddTo(email);

            email2 = new Email();
            email2.Name = "Example User2";
            email2.Address = "test2@example.com";
            personalization.AddTo(email2);

**Comment by lijaso** [comment]
Thanks for the quick reply. Never used Personalization, will have a look. 

Here is the code I used to send email,

dynamic sg = new SendGridAPIClient(apiKey);

SendGrid.Helpers.Mail.Email from = "noreply@example.com";
Email to = new Email("user1@example.com,user2@example.com");
Content content = new Content("text/plain", body);
Mail mail = new Mail(from, subject, to, "testing");

dynamic response = sg.client.mail.send.post(requestBody: mail.Get());

**Comment by thinkingserious** [comment]
@lijaso,

Here is an example with multiple recipients: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L47

@yielr thanks for providing some help!
