### ISSUE TITLE
Long Subject causes BadRequest

### ISSUE THREAD

**Issue by Surfrat** [sendgrid/sendgrid-csharp#258]
My subject is 

`New Client created in Mi-Gateway - User: Peter J, Client: Client Last Name PJ 2 Client First Name PJ 2`

This caused a BadRequest error. After lots of debugging I found it was the length of my subject. Can the error message at least return something useful!!!!

If I shortened the subject to
`New Client created in Mi-Gateway - User: Peter J,`
it was successfully sent.

After my last problem I thought it might be the :.

All worked perfectly with the v2 API!

**Comment by thinkingserious** [comment]
Hello @Surfrat,

Thanks for letting us know!

We restrict the subject length to 78 characters per the recommendations given by this RFC: https://tools.ietf.org/html/rfc2822

Our goal is to encourage best practices to increase your deliverability.

As for the error message, this is the actual error message (obtained by wrapping your call in a try catch and reading the return message). I'll be updating the documentation to make this clearer in the next iteration of library improvements:

```
{"errors":[{"message":"The subject must not be longer than 78 characters.","field":"subject","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.subject"}]}
```

I'll also note your desire for a longer subject length for consideration by our project team.

Thanks!

**Comment by Surfrat** [comment]
Thanks for the feedback. I have shortened my subject. I already had my call in a try catch. My code is as follows:

```
try
                    {
                        response = sendGridApiClient.client.mail.send.post(requestBody: mail.Get());
                        if (response.StatusCode == HttpStatusCode.Accepted)
                        {
                            string successMessage = $"Send - Email sent to: {_toAddress}.";
                            result = successMessage;
                            Log.Info(successMessage);
                            Log.Info($"Send - Response code: {response.StatusCode}.");
                        }
                        else
                        {
                            string errorMessage = $"Send - Error sending Email to: {_toAddress}.";
                            result = errorMessage;
                            Log.Error(errorMessage);
                            Log.Error($"Send - Response code: {response.StatusCode}.");
                            Log.Error($"Send - Error message: {response.Body.ReadAsStringAsync().Result}.");
                        }
                    }
                    catch (Exception e)
                    {
                        string errorMessage = $"Send - Error sending email. Error message: : {e.Message}.";
                        result = errorMessage;
                        Log.Error(errorMessage);
                        if (response != null)
                        {
                            Log.Error($"Send - Response code: {response.StatusCode}.");
                            Log.Error($"Send - Error message: {response.Body.ReadAsStringAsync().Result}.");
                        }
                    }
```

**Comment by thinkingserious** [comment]
@Surfrat,

Thanks for the follow up!

In your catch, you did not receive the error message? "message":"The subject must not be longer than 78 characters."

If not, you might try e.ToString().

We will make this more intuitive in the next iteration of this library.
