### ISSUE TITLE
Can't Add List of Substitution Values

### ISSUE THREAD

**Issue by colomadman** [sendgrid/sendgrid-csharp#260]
With the new version, I cannot figure out how to add multiple substitution values.  Previously in the dictionary of subsitutions we would add a key -toName- and then a list of string "John", "Jane" so that each email would be customized.  Now subsitutions will only accept a string value.

Is this a bug or am I missing something?

**Comment by thinkingserious** [comment]
@colomadman,

The new v3 /mail/send endpoint handles them differently using personalizations. Please review the following resources:

https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thank you!

**Comment by colomadman** [comment]
Thanks.  I have reviewed them and am using personalizations.  The only way I see to add to personalization is the AddSubsitution which takes a string, string argument.  Since some of our substitutions have one key and many values we cannot figure out how to add them.

We have migrated the to, from, cc etc into the personalization but are still stumped on the substitution.

Was there something in the links that I missed?

Thanks

**Comment by thinkingserious** [comment]
Hi @colomadman,

Can you provide us with your code or JSON request body that you have so far? I might not be fully understanding your issue.

Also, you might want to check out this comment: https://github.com/sendgrid/sendgrid-csharp/issues/253#issuecomment-228935201

**Comment by colomadman** [comment]
Public Shared Sub SendbySendGrid(ByVal sendFrom As MailAddress, ByVal sendTo As List(Of MailAddress), subject As String, bodyHTML As String,
                                     Optional substitutions As Dictionary(Of String, List(Of String)) = Nothing, Optional bcc As List(Of MailAddress) = Nothing,
                                     Optional Categories As List(Of String) = Nothing)

        Dim apiKey As String = System.Web.Configuration.WebConfigurationManager.AppSettings("SENDGRID_APIKEY")
        Dim sg As Object = New SendGrid.SendGridAPIClient(apiKey)
        Dim mail As New Mail

        'Setup Info
        Dim trackSettings As New TrackingSettings
        Dim openTracking As New OpenTracking
        Dim clickTracking As New ClickTracking
        openTracking.Enable = True
        clickTracking.Enable = True
        trackSettings.OpenTracking = openTracking
        trackSettings.ClickTracking = clickTracking
        mail.TrackingSettings = trackSettings
        '        mail.TrackingSettings.OpenTracking.Enable = True
        '       mail.TrackingSettings.ClickTracking.Enable = True


        'Add From
        mail.From = New SendGrid.Helpers.Mail.Email(sendFrom.Address, sendFrom.DisplayName)
        mail.ReplyTo = New SendGrid.Helpers.Mail.Email(sendFrom.Address, sendFrom.DisplayName)

        'Add To, cc, bcc Email Addresses
        Dim emailPersonalization As New Personalization
        For Each e In sendTo
            emailPersonalization.AddTo(New SendGrid.Helpers.Mail.Email(e.Address, e.DisplayName))
        Next
        If bcc IsNot Nothing Then
            For Each e In bcc
                emailPersonalization.AddBcc(New SendGrid.Helpers.Mail.Email(e.Address, e.DisplayName))
            Next
        End If

        'Add Subject & Content
        mail.Subject = subject
        mail.AddContent(New Content("text/html", bodyHTML))

        'Add Subsitutions

        If substitutions IsNot Nothing Then
            For Each _i In substitutions
                '                MsgBox(Conversions.JSON.Serialize(_i.Value))
                emailPersonalization.AddSubstitution(_i.Key, _i.Value)
            Next
        End If

        'Add Email Categories
        If Categories IsNot Nothing Then
            For Each c In Categories
                mail.AddCategory(c)
            Next
        End If

        'Send Email
        mail.AddPersonalization(emailPersonalization)
        Dim mailString As String = mail.Get()
        Dim response As Object = sg.client.mail.send.post(requestBody:=mailString)
        Dim statusCode As String = response.StatusCode
        Select Case statusCode
            Case "400", "401", "406", "429", "500"

        End Select


    End Sub

**Comment by colomadman** [comment]
The issue I get is based on this specific code:

If substitutions IsNot Nothing Then
        For Each _i In substitutions
            '                MsgBox(Conversions.JSON.Serialize(_i.Value))
            emailPersonalization.AddSubstitution(_i.Key, _i.Value)
        Next
    End If

We are passing in a list of substitutions that contain a key (string) and then values (list of strings).  Previously we could add a key and list of strings for substitution.  Now it appears that we can only add a string with a singular string value (not a list).

**Comment by thinkingserious** [comment]
Hello @colomadman,

The substitutions used to be an array that matched index for index with the recipients array. Now, each substitution goes to a personalization. 

Previously, you would do the following: 

to: email1, email2, email3
substitutions: name = sam, jane, mike 

Now, you would do the following:

personalization1:
- email: email1
- substitution: name = sam

personalization2:
- email: email2
- substitution: name = jane

personalization3:
- email: email3

etc..

For more on the changes between v2 and v3, please review: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
