### ISSUE TITLE
How do you send a message to multiple recipients?

### ISSUE THREAD

**Issue by JohnGalt1717** [sendgrid/sendgrid-csharp#263]
(using version 7.0.3) 

This was trivial on 6.x but now it appears that every message has to be sent separately for multiple recipients. How do we reproduce the old functionality of having a collection of recipients?

Thanks!

**Comment by thinkingserious** [comment]
Hello @JohnGalt1717,

This is now achieved using personalizations, here is an example that has 2 personalizations: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L47

This is also a useful resource: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html

Thanks!

**Comment by JohnGalt1717** [comment]
Thank you!
