### ISSUE TITLE
BCC emails do not show the To contents

### ISSUE THREAD

**Issue by erikkross** [sendgrid/sendgrid-csharp#265]
#### Issue Summary

I'm not really sure if this should be posted here or to SendGrid support. Using the latest version of the C# API, emails that are sent to the BCC address (the BCC address that is setup in the SendGrid Management console), do not contain any email addresses for the To field. 

For example, in SendGrid I have a BCC address setup so all emails sent through sendgrid get copied to bcc@example.com. 

When using the old C# api (6.1), all the emails sent to bcc@example.com showed me the To addresses that the email was sent to. Using the new C# API (7.0.4), any emails sent to bcc@example.com have an empty To field. 

#### Steps to Reproduce

1. Turn on the BCC option at app.sendgrid.com (Settings > Mail Settings > BCC). 
2. Send an email using the C# API. 
3. Check the email that was sent to the BCC address setup in step 1. The To field is completely blank. 

I expect the emails sent to the BCC address to show the To recipients, just like the emails sent to the To recipients do. 

#### Technical details:

* sendgrid-csharp Version: 7.0.4 (downloaded through NuGet)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
@erikkross,

Thanks for reaching out. Indeed, this is support issue. Please reach out at https://support.sendgrid.com.

I suspect this pertains to changes within the v3 /mail/send endpoint.
