### ISSUE TITLE
Attachments are no longer showing up in the email

### ISSUE THREAD

**Issue by andronachev** [sendgrid/sendgrid-csharp#270]
Hi, 

Our implementation uses the .NET client (V 6.3.4), and everything used to work fine. Except until today, when we noticed that the attachments are no longer showing up in the e-mail. 

I debugged our code, and nothing has changed (check the code below), also no exception is thrown; everything seems normal.

'public async Task SendMail(string[] to, string templateId, EmailPlaceHolder[] substitutions, Stream attachment, string attachmentName)
        {
            var message = GetMessage();

            message.AddAttachment(attachment, attachmentName);

            message.AddTo(to.OrderBy(t => t));

            message.EnableTemplateEngine(templateId);

            AddSubstitutions(message, substitutions);

            await SendMessage(message);
        }
       
       private SendGridMessage GetMessage()
        {
            SendGridMessage message = new SendGridMessage();
            var fromEmail = configurationService.GetValueByKey(GlobalConfigurationRowKeys.FromEmailAddress);
            var fromName = configurationService.GetValueByKey(GlobalConfigurationRowKeys.FromFullName);

            message.From = new MailAddress(fromEmail, fromName);

            //https://github.com/sendgrid/sendgrid-csharp/issues/157
            message.Subject = " ";
            message.Text = " ";
            message.Html = " ";

            return message;
        }
'

the **attachment** variable is a Stream, and the **attachmentName** is a string.

I wanted to ask if this is an issue caused by some changes in your API ? Maybe some recent deploys you did, related to V3, or whatever. Alternatively, can you suggest some loggs that we could check ? I am not sure where to look for error logs (other than the really thin summary that is shown to us in the Activity Feed (in the SendGrid app))

Thanks, @thinkingserious

**Comment by thinkingserious** [comment]
Hello @andronachev,

Verson 7.X.X is a breaking change from version 6.X.X. The most notable difference is the support of the new v3 /mail/send endpoint, which does handle attachments differently.

If you have not updated your client and are still using v6.3.4, nothing should have changed.

Can you verify what version of the SendGrid .Net Client you are using?

Thanks!

**Comment by andronachev** [comment]
Hi @thinkingserious ,

We're using v6.3.4 (just checked), so no change there. Are there any logs that we can check, or anything of that nature ? 

Thanks

**Comment by thinkingserious** [comment]
This is an issue our support team can help with at https://support.sendgrid.com.

Thanks!
