### ISSUE TITLE
Disable (or set) tracking

### ISSUE THREAD

**Issue by jeancroy** [sendgrid/sendgrid-csharp#273]
#### Issue Summary

I'm trying to improve my deliverability, and one thing I have seen in report of tool like mail-tester.com is that I use tracking with my email by default and some point are taken off because of that.

I have a base setup that work. However when trying to add tracking option configuration Sendgrid answer with 400 bad request. Removing the tracking configuration, everything work fine.

I've tried to add/remove different bit and pieces, each time having a bad request error. In term of communicating what need to be fixed, sendgrid is one of the least verbose api we use and it's a bit frustrating to work with.

Here's my latest attempt
```` c#
public static void DisableTracking(Mail mail)
{

    mail.TrackingSettings = new TrackingSettings
    {
        ClickTracking = new ClickTracking {Enable = false, EnableText = false},
        Ganalytics = new Ganalytics { Enable = false, UtmCampaign = "", UtmContent = "", UtmMedium = "", UtmSource = "", UtmTerm = "" },
        OpenTracking = new OpenTracking {Enable = false, SubstitutionTag = ""},
        SubscriptionTracking = new SubscriptionTracking {Enable = false, Html = "",SubstitutionTag = "",Text = ""},
    };

}
````

And it would be used like so

````c#
    var mail = new Mail(from: from, subject: subject, to: to, content: plainContent);
    mail.AddContent(htmlContent);

    DisableTracking(mail);

    dynamic response = sg.client.mail.send.post(requestBody: mail.Get());
````

#### Technical details:

* sendgrid-csharp Version: 7.0.4
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
@jeancroy,

Thanks for the detailed report!

There is now an open pull request (see above) to fix this issue. Please track there.

Thanks!

**Comment by jeancroy** [comment]
Hi @thinkingserious  thanks for the quick response.

About that issue, I see a reference to error `The click_tracking enable parameter is required.`
I'd love very much to see those error when sending mail. 

Is there a way to catch those from output of 
````c#
    dynamic response = sg.client.mail.send.post(requestBody: mail.Get());
````

**Comment by thinkingserious** [comment]
Please keep an eye on this repo, I'll be adding a TROUBLESHOOTING.md file that explains how to use a Try/Catch block to grab the error message from the server. Thanks!

**Comment by thinkingserious** [comment]
Fixed: https://github.com/sendgrid/sendgrid-csharp/pull/293

Will be updated to Nuget as version 8.0.2.

Here are the instructions on how to grab the errors: https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error-messages
