### ISSUE TITLE
he type or namespace name 'Helpers' 

### ISSUE THREAD

**Issue by loganwasif005** [sendgrid/sendgrid-csharp#277]
#### Issue Summary

Error	40	The type or namespace name 'Helpers' does not exist in the namespace 'SendGrid' (are you missing an assembly reference?)	D:\development\RunApp\RunApp\Models\SendEmailModel.cs	9	16	RunApp

#### Steps to Reproduce

1. Go to nuget
2. install the package
3. compile.

you will get error

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.1

**Comment by thinkingserious** [comment]
Hello @loganwasif005,

The Helpers namespace is compiled against .NET 4.5.2, the current officially supported version.

You can either update your project to target .NET 4.5.2 or you can compile the source code directly, changing the target to .NET 4.5.1.

Thanks!

**Comment by sagar-rao-1306** [comment]
thank you, i was fighting on this for quite a while.

**Comment by thinkingserious** [comment]
No problem and apologies for the bad experience. The v9 version of this library, when released, should alleviate this problem: https://github.com/sendgrid/sendgrid-csharp/projects
