### ISSUE TITLE
Can't add recipient with custom field with an apostrophe in value

### ISSUE THREAD

**Issue by grahamha** [sendgrid/sendgrid-csharp#279]
#### Issue Summary

The web service to add multiple recipients is returning invalid request body when I include a custom field with an apostrophe in the value. According to JSONLint the JSON is valid.

I have tried encoding in various ways such as URL, JavaScript, HTML. This results in the request being accepted but the string doesn't get decoded when it's displayed on the SendGrid website. 

#### Steps to Reproduce

I am using Newtonsoft to serialize my list of objects into JSON and get this - 

[{
	"email": "graham@graham.com",
	"first_name": "Graham",
	"last_name": "Ha",
	"interests": "Don't know"
}]

I then use pass the json string to this method - 

sg.client.contactdb.recipients.post(requestBody: json);
 
The response is BadRequest - invalid request body.

If I pass the same JSON without the apostrophe on Don't know then it accepts it. 

#### Technical details:

* sendgrid-csharp Version: 7.0.4
* .NET Version: 4.5

**Comment by thinkingserious** [comment]
Hello @grahamha,

This issue is just about fixed, please follow this issue for updates: https://github.com/sendgrid/sendgrid-csharp/issues/256
