### ISSUE TITLE
SendGrid.CSharp.HTTP.Client version issue

### ISSUE THREAD

**Issue by Schenz** [sendgrid/sendgrid-csharp#280]
#### Issue Summary

I have a C# Console application running as a web job in an azure website.  When I install SendGrid 7.0.6 it also installs SendGrid.CSharp.HTTP.Client 2.0.4 as a dependency as expected.  When run with these versions all work as expected. SendGrid.CSharp.HTTP.Client has a newer version available 2.0.5, but when I install that version I start getting an exception:

Message: [FileLoadException: Could not load file or assembly 'SendGrid.CSharp.HTTP.Client, Version=2.0.4.0, Culture=neutral, PublicKeyToken=79219bf4e5ecaaca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
 SendGrid.SendGridAPIClient..ctor(String apiKey, String baseUri, String version):-1

#### Steps to Reproduce

1. Create Console application to send emails
2. Install SendGrid 7.0.6 (Install-Package Sendgrid)
3. Validate email sends
4. Update SendGrid.CSharp.HTTP.Client to 2.0.5
5. Run application again and get exception documented above

#### Technical details:

* sendgrid-csharp Version: 7.0.6
* SendGrid.CSharp.HTTP.Client Version: 2.0.5
* .NET Version: 4.6

**Comment by thinkingserious** [comment]
@Schenz,

My apologies, it looks like I did not correctly sign the assembly. I'll fix this today and the new version will be 2.0.6.

**Comment by thinkingserious** [comment]
This version should be good: https://www.nuget.org/packages/SendGrid.CSharp.HTTP.Client/2.0.6

Thanks for your patience!
