### ISSUE TITLE
I have issue with _emailSender.SendEmailAsync, 

### ISSUE THREAD

**Issue by cathyd0701** [sendgrid/sendgrid-csharp#281]
#### Issue Summary

Issue with executing:
await _emailSender.SendEmailAsync(model.Email, "Confirm your account",
                        $"Please confirm your account by clicking this link: <a href='{callbackUrl}'>link</a>");
errors: 
An unhandled exception occurred while processing the reques

#### Steps to Reproduce

Occurred when executing public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)  in AccountController.cs

**Comment by thinkingserious** [comment]
Hi @cathyd0701,

Could you please let us know what version of .NET and SendGrid client you are using?

**Comment by cathyd0701** [comment]
Thank you so much for response.

.NET 4.5.2, sendgrid v7.0.6

Best regards,
Cathy

2016-07-18 15:49 GMT-04:00 Elmer Thomas <notifications@github.com>:

**Comment by thinkingserious** [comment]
Thank you, that definitely helps. 

Can you please share the relevant code (please remove any sensitive data)? If you are not comfortable with sharing publicly, you can email us at dx@sendgrid.com. Thanks!

**Comment by cathyd0701** [comment]
Hi,

I called from here: for email confirmation purpose
        public async Task<IActionResult> Register(RegisterViewModel model,
string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email,
Email = model.Email };
                var result = await _userManager.CreateAsync(user,
model.Password);
                if (result.Succeeded)
                {
                    // For more information on how to enable account
confirmation and password reset please visit
http://go.microsoft.com/fwlink/?LinkID=532713
                    // Send an email with this link
                    var code = await
_userManager.GenerateEmailConfirmationTokenAsync(user);
                    var callbackUrl = Url.Action("ConfirmEmail", "Account",
new { userId = user.Id, code = code }, protocol:
HttpContext.Request.Scheme);
                    await _emailSender.SendEmailAsync(model.Email, "Confirm
your account",
                        $"Please confirm your account by clicking this
link: <a href='{callbackUrl}'>link</a>");
                    //await _signInManager.SignInAsync(user, isPersistent:
false);
                    _logger.LogInformation(3, "User created a new account
with password.");
                    return RedirectToLocal(returnUrl);
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

failed at await _emailSender.SendEmailAsync

errors reported as :Errors:
An unhandled exception occurred while processing the request.
InvalidApiRequestException: Bad Request Check `Errors` for a list of errors
returned by the API.



2016-07-18 15:58 GMT-04:00 Elmer Thomas <notifications@github.com>:

**Comment by cathyd0701** [comment]
continue ...

I have API Key, name is GKey-CJazz, I found it was put in           var
credentials = new System.Net.NetworkCredential(
                Options.SendGridUser,
                Options.SendGridKey);

 Options.SendGridUser, and the actually api key was put in
Options.SendGridKey

2016-07-18 16:01 GMT-04:00 cdeng cdeng <cdeng09@gmail.com>:

**Comment by thinkingserious** [comment]
It looks like you are trying to use the 7.X.X version of the library with the 6.X.X examples. For the current documentation, please head over to the current README: https://github.com/sendgrid/sendgrid-csharp. Version 7.X.X was a breaking changes from version 6.X.X

**Comment by cathyd0701** [comment]
These code actually created by .NET FRAMEWORK core application template...

2016-07-18 16:06 GMT-04:00 Elmer Thomas <notifications@github.com>:

**Comment by cathyd0701** [comment]
Thanks . Maybe I should try with new code. I just thought the template
should be right previously.

2016-07-18 16:09 GMT-04:00 cdeng cdeng <cdeng09@gmail.com>:

**Comment by thinkingserious** [comment]
@cathyd0701,

In that case, you are not using this library to send your emails. You are using the built in SMTP service. It's possible to use it that way, but I would recommend you try using the examples we have here.

**Comment by cathyd0701** [comment]
Thank you so much. I will try that. It is so happy I can get helps for
using of SendGrid. I was blocked by the issue for several days.


2016-07-18 16:15 GMT-04:00 Elmer Thomas <notifications@github.com>:

**Comment by cathyd0701** [comment]
Solved.

Lot's thanks.

2016-07-18 16:18 GMT-04:00 cdeng cdeng <cdeng09@gmail.com>:
