### ISSUE TITLE
Why is `StringEscapeHandling.EscapeHtml` used for JSON serialization?

### ISSUE THREAD

**Issue by ohadschn** [sendgrid/sendgrid-csharp#288]
https://github.com/sendgrid/sendgrid-csharp/blob/03807ce2a60d5d1c895ff867565db4dbc8cfb569/SendGrid/SendGrid/Helpers/Mail/Mail.cs#L350

Just curious. The [docs](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_StringEscapeHandling.htm) say the following characters are escaped: `<`, `>`, `&`, `'` (they also mention `"` but those are always escaped). Anyway I sent a JSON with all of them to the REST API and it worked... no surprise since the JSON is in the request's body, no HTML is involved there.

**Comment by thinkingserious** [comment]
@ohadschn,

I believe it was done to encode the HTML text within the content object.

**Comment by ohadschn** [comment]
Do you mean HttpContent, i.e. the HTTP request body? Like I said, that's unnecessary because that's not HTML. I tested it, it works fine without encoding them...

**Comment by thinkingserious** [comment]
I meant this content object: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L135

But is sounds like it is still not needed.

**Comment by ohadschn** [comment]
Yep, that's just one component of the JSON that gets serialized and sent in the REST request body, and like I demonstrated above it can contain HTML characters...
