### ISSUE TITLE
Sendgrid client response breaking

### ISSUE THREAD

**Issue by RyanCEI** [sendgrid/sendgrid-csharp#290]
The following snippet broke in the latest 8.0.1 release.  response.StatusCode no longer exists.  Please advise how to check for a response code.

            var apiKey = ConfigurationManager.AppSettings["SendGridApiKey"];
            dynamic sg = new SendGridAPIClient(apiKey);

            dynamic response = sg.client.mail.send.post(requestBody: mail.Get());

            HttpStatusCode statusCode = response.StatusCode;
            if (statusCode == HttpStatusCode.Accepted)

**Comment by thinkingserious** [comment]
@RyanCEI,

I can not reproduce your error. Here is what I did:

1. Created new console app
2. Used Nuget to add the SendGrid dependency (version 8.0.1)
3. Input the following code:

```csharp
using System;
using SendGrid;
using SendGrid.Helpers.Mail;
using System.Threading.Tasks;

namespace Example
{
    internal class Example
    {
        private static void Main()
        {
            Execute().Wait();
        }

        static async Task Execute()
        {
            string apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY", EnvironmentVariableTarget.User);
            dynamic sg = new SendGridAPIClient(apiKey);

            Email from = new Email("dx@sendgrid.com");
            string subject = "Hello World from the SendGrid CSharp Library!";
            Email to = new Email("elmer@sendgrid.com");
            Content content = new Content("text/plain", "Hello, Email!");
            Mail mail = new Mail(from, subject, to, content);

            dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());
            Console.WriteLine(response.StatusCode);
            Console.WriteLine(response.Body.ReadAsStringAsync().Result);
            Console.WriteLine(response.Headers.ToString());
            Console.ReadLine();
        }
    }
}
```

Which send the email and gave me the following return value:

```
Accepted

Connection: keep-alive
X-Message-Id: 7nnDhrUXTACxU9eUO6S1BQ
X-Frame-Options: DENY
Date: Tue, 26 Jul 2016 14:58:42 GMT
Server: nginx
```

It seems like you are missing the await keyword. Please note that version 8.0.0 was a breaking change that fixed the async functionality. Please see: https://github.com/sendgrid/sendgrid-csharp/releases/tag/v8.0.0

Thanks!

**Comment by RyanCEI** [comment]
That fixed it thanks.
