### ISSUE TITLE
Access forbidden Error when trying to GET user/profile 

### ISSUE THREAD

**Issue by shijuamt** [sendgrid/sendgrid-csharp#291]
The following API request: **GET https://api.sendgrid.com/v3/user/profile**

Results in a HTTP 403 response with the following body:
**{"errors":[{"field":null,"message":"access forbidden"}]}**

I went to Settings -> API Keys and clicked on 'Edit details' to view the permissions granted to my API key and, as far as I can tell, there isn't any permission that I can grant (or revoke) that seems related to 'user profile'. Just to be on the safe side, I have configured every single permission to 'Full Access' (when available) or to 'Read Access' if 'full access' is not available but I am still getting this HTTP 403 error.

What is the permission I need to grant to my API key in order to be able to retrieve my user profile?

**Comment by thinkingserious** [comment]
@shijuamt,

This is an issue our support team will be able to help with. Please reach out to them at https://support.sendgrid.com

Thanks!
