### ISSUE TITLE
Emails received with no subject

### ISSUE THREAD

**Issue by Schenz** [sendgrid/sendgrid-csharp#292]
#### Issue Summary

When I send an email via the send grid client, the email I receive has no subject.

var content = mail.Get();
dynamic response = await sg.client.mail.send.post(requestBody: content);

content looks like this:
{
	"from": {
		"email": "developmentqa@touchstone-group.com"
	},
	"subject": "DEV - Website Registration",
	"personalizations": [{
		"to": [{
			"email": "developmentqa@touchstone-group.com"
		}]
	}],
	"content": [{
		"type": "text/html",
		"value": "\u003cp\u003eDear Harry Daimler,\u003c/p\u003e\r\n\t\t\t\u003cp\u003eWelcome! You are now able to register on the new website.\u003c/p\u003e"
	}],
	"categories": ["Website Registration"],
	"tracking_settings": {
		"click_tracking": {
			"enable": true
		},
		"open_tracking": {
			"enable": true
		}
	}
}

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.6

**Comment by thinkingserious** [comment]
Hello @Schenz,

I will need a bit more detail, as I can not reproduce. Here is the source code I used (In a console application):

```csharp
using System;
using SendGrid;
using SendGrid.Helpers.Mail;
using System.Threading.Tasks;

namespace Example
{
    internal class Example
    {
        private static void Main()
        {
            Execute().Wait();
        }

        static async Task Execute()
        {

            string apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY", EnvironmentVariableTarget.User);
            dynamic sg = new SendGridAPIClient(apiKey);

            Mail mail = new Mail();
            Email email = new Email();
            email.Address = "dx@sendgrid.com";
            mail.From = email;

            mail.Subject = "Hello World from the SendGrid CSharp Library";

            Personalization personalization = new Personalization();
            email = new Email();
            email.Address = "elmer@sendgrid.com";
            personalization.AddTo(email);
            mail.AddPersonalization(personalization);

            Content content = new Content();
            content.Type = "text/html";
            content.Value = "\u003cp\u003eDear Harry Daimler,\u003c/p\u003e\r\n\t\t\t\u003cp\u003eWelcome! You are now able to register on the new website.\u003c/p\u003e";
            mail.AddContent(content);

            mail.AddCategory("Website Registration");

            TrackingSettings trackingSettings = new TrackingSettings();
            ClickTracking clickTracking = new ClickTracking();
            clickTracking.Enable = true;
            trackingSettings.ClickTracking = clickTracking;
            OpenTracking openTracking = new OpenTracking();
            openTracking.Enable = true;
            trackingSettings.OpenTracking = openTracking;
            mail.TrackingSettings = trackingSettings;

            dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());
            Console.WriteLine(mail.Get());
            Console.WriteLine(response.StatusCode);
            Console.WriteLine(response.Body.ReadAsStringAsync().Result);
            Console.WriteLine(response.Headers.ToString());
            Console.ReadLine();
        }
    }
}
```

Here was the generated JSON:

```json
{
  "categories": [
    "Website Registration"
  ],
  "content": [
    {
      "type": "text/html",
      "value": "<p>Dear Harry Daimler,</p>\r\n\t\t\t<p>Welcome! You are now able to register on the new website.</p>"
    }
  ],
  "from": {
    "email": "dx@sendgrid.com"
  },
  "personalizations": [
    {
      "to": [
        {
          "email": "elmer@sendgrid.com"
        }
      ]
    }
  ],
  "subject": "Hello World from the SendGrid CSharp Library",
  "tracking_settings": {
    "click_tracking": {
      "enable": true
    },
    "open_tracking": {
      "enable": true
    }
  }
}
```

I noticed that you are using .NET 4.6 and this library is compiled against 4.5.2. I'm not sure if that would cause an issue.

**Comment by Schenz** [comment]
It appears to be something specific with my sendgrid account.  when I send same message with different apikey, it all works as I expect it to, but change to this account having a problem and there is no subject...

**Comment by Schenz** [comment]
not just API key specific, but account specific.  When I use API key from another account it works, but when I create a new API key in the account having issues it does not work.  I have also attempted to open a ticket on the support.sendgrid.com site: https://support.sendgrid.com/hc/en-us/requests/718346?page=1

have you ever heard of this before?

**Comment by thinkingserious** [comment]
@Schenz,

No, I have not heard of this. But thanks for putting in a ticket with support, they will get to the bottom of it.
