### ISSUE TITLE
How to Add Attachments from FilePaths - C#

### ISSUE THREAD

**Issue by LorenDorez** [sendgrid/sendgrid-csharp#294]
I am moving from v2 to V3 and have everything updated but Attachments. In the old VS i could do this
```
 foreach(string filePath in attachments)
            {
                myMessage.AddAttachment(filePath);
            }
```
But this doesnt work on v3. So how do i do this, I do not know the content Type of the files in the FilePaths as it dynamic.

* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @LorenDorez,

Here is an example of how to add an attachment: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L142

To find out the content/type dynamically: https://msdn.microsoft.com/en-us/library/system.web.mimemapping.getmimemapping(v=VS.110).aspx

To Base64 encode: https://msdn.microsoft.com/en-us/library/system.convert.tobase64string(v=vs.110).aspx

I hope that helps!

**Comment by LorenDorez** [comment]
The issue is the MimeMapping is dependent on System.Web which isnt in the AP.Net Core Framework.

Im in the process of testing but this is what i have so far.

```
foreach (string filePath in attachments)
            {
                string fileContents = Convert.ToBase64String(File.ReadAllBytes(filePath));

                string contentType;
                new FileExtensionContentTypeProvider().TryGetContentType(filePath, out contentType);
                contentType =  contentType ?? "application/octet-stream";

                Attachment attachment = new Attachment();
                attachment.Content = fileContents;
                attachment.Type = contentType;
                attachment.Filename = Path.GetFileName(filePath);
                attachment.Disposition = "attachment";
                myMessage.AddAttachment(attachment);
            }
```

**Comment by thinkingserious** [comment]
I was just about to point you to this solution: http://stackoverflow.com/a/35880687, but it looks like you are already there :)

Did that work?

**Comment by LorenDorez** [comment]
Yes but most of the time the contentType is "octet-stream" until theres a better ContentType selector in aspnet-core
