### ISSUE TITLE
StatusCode is Forbidden When Trying To Execute GET /user/email In ASP.NET MVC5

### ISSUE THREAD

**Issue by petercoin** [sendgrid/sendgrid-csharp#295]
#### Issue Summary
I am following the example of user.cs to retrieve user's email but the StatusCode shows Forbidden after executing the method: sg.client.user.email.get().

The source code is as below:
```
private async Task configSendGridasync(IdentityMessage message)
{
    string apiKey = ConfigurationManager.AppSettings["sendGridKey"];
    dynamic sg = new SendGrid.SendGridAPIClient(apiKey, "https://api.sendgrid.com");
    dynamic retrievedEmail = await sg.client.user.email.get();

    Email from = new Email(retrievedEmail);
    String subject = message.Subject;
    Email to = new Email(message.Destination);
    Content content = new Content("text/html", message.Body);
    Mail mail = new Mail(from, subject, to, content);

    dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());
}
```

I also changed all the API key's permission to read but this issue still occurs.
Is this a bug or is there any settings I need to modify?

#### Technical details:

* sendgrid-csharp Version: 8.0.2.0
* .NET Version: 4.5.2
* IDE: VS2013

**Comment by thinkingserious** [comment]
@petercoin,

Please contact our support team at https://support.sendgrid.com. They will be able to inspect your API key permissions to help troubleshoot.

Thanks!
