### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by karneshkumar** [sendgrid/sendgrid-csharp#299]
Getting below error while send mail.

An exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll but was not handled in user code

Additional information: Could not load file or assembly 'SendGrid, Version=8.0.2.0, Culture=neutral, PublicKeyToken=4f047e93159395ca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Please reply me as soon as possible

**Comment by thinkingserious** [comment]
Hi @karneshkumar,

Could you please provide the relevant source code?

Also, please let me know what version of .NET you are compiling for. (e.g. v4.5.2).

**Comment by karneshkumar** [comment]
Hi, Here is the code
**Web Project Target Version 4.6.1**
int retMessage = 0;
            string MAILSERVICE = System.Configuration.ConfigurationManager.AppSettings["MAILSERVICE"].ToString();
            if (MAILSERVICE == "ON")
            {
                string domain = System.Configuration.ConfigurationManager.AppSettings["DOMAIN"].ToString();
                string INFO = System.Configuration.ConfigurationManager.AppSettings["INFO"].ToString();
                // SIGN UP EMAIL
                string SignUpTemplate = string.Format("http://{0}/template/SignUpTemplate.htm", domain);
                WebClient client = new WebClient();
                string body = client.DownloadString(SignUpTemplate);
                string INFOEMAIL = System.Configuration.ConfigurationManager.AppSettings["INFOEMAIL"].ToString();
                string INFOTELEPHONE = System.Configuration.ConfigurationManager.AppSettings["INFOTELEPHONE"].ToString();
                body = body.Replace("[INFOEMAIL]", INFOEMAIL);
                body = body.Repla
ce("[INFOTELEPHONE]", INFOTELEPHONE);
                sendgrid.sendgrid.SendMail("from@domain.com", "to@domain.com", "Welcome Subject!", body).Wait();
            }
**SendGrid Project Target Version 4.6.1 (sendgrid.cs)**
using System;
using SendGrid;
using SendGrid.Helpers.Mail;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace sendgrid
{
    public class sendgrid
    {
        public static async Task SendMail(string _from, string _to, string _subject, string _body)
        {
            string apiKey = Environment.GetEnvironmentVariable("key", EnvironmentVariableTarget.User);
            dynamic sg = new SendGridAPIClient(apiKey);

            Email from = new Email(_from);
            //string subject = "Hello World from the SendGrid CSharp Library!";
            Email to = new Email(_to);
            Content content = new Content("text/html", _body);
            Mail mail = new Mail(from, _subject, to, content);

            dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());
        }
    }
}

**Comment by karneshkumar** [comment]
Please suggest solution

**Comment by thinkingserious** [comment]
Hello @karneshkumar,

Our library is compiled against v4.5.2. 

To use this library with v4.6.1 you will need to download the source code and re-compile, after changing the compile target to be v4.6.1.

**Comment by karneshkumar** [comment]
**Is this source code, i need build for 4.6.1 framework**

using System;
using System.Collections.Generic;
using System.Text;
using System.Net.Mail;
using System.Net.Mime;

namespace SmtpMail
{
  class Program
  {        
    static void Main()
    {
      try
      {
        MailMessage mailMsg = new MailMessage();

        // To
        mailMsg.To.Add(new MailAddress("to@example.com", "To Name"));

        // From
        mailMsg.From = new MailAddress("from@example.com", "From Name");

        // Subject and multipart/alternative Body
        mailMsg.Subject = "subject";
        string text = "text body";
        string html = @"<p>html body</p>";
        mailMsg.AlternateViews.Add(AlternateView.CreateAlternateViewFromString(text, null, MediaTypeNames.Text.Plain));
        mailMsg.AlternateViews.Add(AlternateView.CreateAlternateViewFromString(html, null, MediaTypeNames.Text.Html));

        // Init SmtpClient and send
        SmtpClient smtpClient = new SmtpClient("smtp.sendgrid.net", Convert.ToInt32(587));
        System.Net.NetworkCredential credentials = new System.Net.NetworkCredential("username@domain.com", "yourpassword");
        smtpClient.Credentials = credentials;

        smtpClient.Send(mailMsg);
      }
        catch (Exception ex)
      {
        Console.WriteLine(ex.Message);
      }
    }
  }
}

**Comment by thinkingserious** [comment]
@karneshkumar,

Here is the source code you will need: https://github.com/sendgrid/sendgrid-csharp/tree/master/SendGrid

**Comment by TerrySlack** [comment]
It's 2019 and I've just run into the same issue
I have a simple project, setup that does nothing more than attemp to send an email as a test.  However, I get the following error
Could not load file or assembly 'SendGrid, Version=9.10.0.0, Culture=neutral, PublicKeyToken=4f047e93159395ca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

The only code I'm using is the sample code.  

Has this bug been fixed?
