### ISSUE TITLE
Hide internal details of API

### ISSUE THREAD

**Issue by yaplex** [sendgrid/sendgrid-csharp#300]
#### Issue Summary

You have properties of type List<T>, but you also have methods, for example, .AddPersonaliation(). It is confusing, Should I use a method or just do Presentations.Add(new….), should I verify if list is null…. You better make it IEnumerable with a private setter.

```
private IList<Presentations> _presentations = new List<Presentations>();
public IEnumerable<Presentation> Pesentations {get{return _presentations;} } // no setter

public void AddPresentation(Presentation p) {
_presentations.Add(p)
}

```

**Comment by thinkingserious** [comment]
Thanks @yaplex!

This issue will move up our queue with +1s, comments or a pull request with a signed CLA.

**Comment by thinkingserious** [comment]
Hello @yaplex,

The C# SDK has since been updated. Could you please [take a look](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md) and provide updated feedback? 

With Best Regards,

Elmer
