### ISSUE TITLE
new SendGridAPIClient(apiKey) silenty kills application flow

### ISSUE THREAD

**Issue by famschopman** [sendgrid/sendgrid-csharp#302]
I tried to work with the basic demo code; Hello World and I am experiencing strange issues with application flow. I am using version 8.0.2.

The moment I execute the dynamic sg = new SendGridAPIClient(apiKey); the flow stalls (no errors or exceptions being thrown), any debugging points after are being skipped, and the basically the GetStripeService call (from the parent method) is not being executed at all. It continue execiting though when I disable instantiating of the SendGridAPIClient. So something is wrong.

It looks like the application is performing well, but in fact it just skips execution of anything after instantiating the SendGridAPIClient.

I have a suspicion this has something to do with async but I can't debug it because there are no errors and debugging points are simply skipped.

```
public async Task<Account> Create(Account account, string subscriptionPlanId)
        {
            var userId = await CreatePrimaryUser(account); // create account owner (first user)
            account.AccountOwnerId = userId;

            var stripeAccountResult = BusinessServiceFacade.GetStripeService(RavenMasterSession).CreateCustomer(account); // register account in Stripe
                       
            return account;
        }

```
```
 private async Task<string> CreatePrimaryUser(Account account)
        {
            var user = new User()
            {
                UserName = account.AccountOwner.Email,
                FirstName = account.AccountOwner.FirstName,
                LastName = account.AccountOwner.LastName,
                Email = account.AccountOwner.Email
            };
            RavenContext.GetTenantSession().Store(user);

            var result = await UserManager.CreateAsync(user);
            if (result.Succeeded)
            {
                Execute().Wait(); // send the mail welcoming the user
            }
            else
            {
                RavenContext.GetTenantSession().Delete(user);
            }
            return user.Id;
        }
```

```
static async Task Execute()
        {
            string apiKey = "my key registered in SendGrid";
            dynamic sg = new SendGridAPIClient(apiKey);

            //Email from = new Email("test@example.com");
            //string subject = "Hello World from the SendGrid CSharp Library!";
           // Email to = new Email("test@example.com");
           // Content content = new Content("text/plain", "Hello, Email!");
            //Mail mail = new Mail(from, subject, to, content);

            //dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());
        }

```

**Comment by thinkingserious** [comment]
Hi @famschopman,

I don't see anything obvious, but I have some follow up questions:

1. When you uncomment the code in Execute(), none of those statements are executed?
2. Can you log the values at every step in the Execute function?
3. After you make the post at the end, can you try:

```csharp
Console.WriteLine(response.StatusCode);
Console.WriteLine(response.Body.ReadAsStringAsync().Result);
Console.WriteLine(response.Headers.ToString());
```

**Comment by famschopman** [comment]
I solved the issue. I caused an async deadlock because the calling controller wasn't executed async. This issue has nothing todo with the Sendgrid library, it was my own stupid mistake.

**Comment by thinkingserious** [comment]
Thank you for the update @famschopman!
