### ISSUE TITLE
text/plain no longer working to send as plain text

### ISSUE THREAD

**Issue by NuNn-DaDdY** [sendgrid/sendgrid-csharp#305]
#### Issue Summary

After upgrading to 8.0.2.0 I noticed that my e-mail was no longer being sent as plain text.  When looking at the API reference I noticed one of the calls was using "text" in place of "text/plain" (https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html).  When I switched to "text" instead of "text/plain", the message did indeed send as plain text.   

#### Steps to Reproduce

Substitute "text" for "text/plain" in the method below:

`public async Task Send(string recipient, string subject, string message)
{
   var content = new Content("text/plain", message);
   var mail = new Mail(new Email(FromAddress), subject, new Email(recipient), content);
   dynamic response = await _sendGrid.client.mail.send.post(requestBody: mail.Get());
}`

The documentation seems to indicate that "text/plain" should send as plain text and was a bit confused when this changed was made.

#### Technical details:

* sendgrid-csharp Version: 8.0.2.0
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @NuNn-DaDdY,

Thanks for the heads up! We will investigate and let you know what we find.

**Comment by thinkingserious** [comment]
@NuNn-DaDdY,

In the v3 Web API we expect a valid content-type such as text/plain or text/html.

I've put in a pull request to update the documentation: https://github.com/sendgrid/docs/pull/2090

Thanks!
