### ISSUE TITLE
NewtonSoft.Json - dependency on >= 9.0 ?

### ISSUE THREAD

**Issue by ssujay** [sendgrid/sendgrid-csharp#306]
#### Issue Summary

I'm trying to hook up some of these new SendGrid capabilities behind an Umbraco website running Umbraco version 7.4.  There are a lot of incompatibilities around the NewtonSoft.Json package dependency of >= 9.0 for the SendGrid package when I attempt to perform the install via Package Manager.

Any assistance in overcoming these incompatibilities would be greatly appreciated.
* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hi @ssujay,

Could you please let us know what errors you are seeing? Thanks!

**Comment by ssujay** [comment]
Thanks for the assistance.
Here is the Package Manager output when I attempt to install.

PM> install-package sendgrid
Attempting to gather dependency information for package 'sendgrid.8.0.2' with respect to project '{myproject}', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'sendgrid.8.0.2' with DependencyBehavior 'Lowest'
install-package : Unable to find a version of 'Newtonsoft.Json' that is compatible with 'Microsoft.AspNet.WebApi.Client 5.2.3 constraint: 
Newtonsoft.Json (>= 6.0.4)', 'Microsoft.Owin.Security.OAuth 3.0.1 constraint: Newtonsoft.Json (>= 6.0.4)', 'Sendgrid 8.0.2 constraint: 
Newtonsoft.Json (>= 9.0.1)', 'UmbracoCms 7.4.3 constraint: Newtonsoft.Json (>= 6.0.8 && < 9.0.0)', 'UmbracoCms.Core 7.4.3 constraint: 
Newtonsoft.Json (>= 6.0.8 && < 9.0.0)'.
At line:1 char:1
+ install-package sendgrid
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId :

**Comment by thinkingserious** [comment]
@ssujay,

Here are a few paths you can try:

1. See if UmbracoCms would relax their constraint to at least include 9.0.X releases, since those would be bug fixes.
2. You could re-compile our library to be dependent on a lower version of Newtonsoft.Json as we are not using any version 9.X.X specific functionality.

Please let me know how that goes.

Meanwhile, I'll leave this ticket open and we will look into making the dependency to Newtonsoft.Json more flexible.

Thanks!

**Comment by thinkingserious** [comment]
@ssujay,

Looks like Umbraco 7.5 will no longer have this issue: http://issues.umbraco.org/issue/U4-8794
