### ISSUE TITLE
Multiple email.AddContent() sequence results in overwrite

### ISSUE THREAD

**Issue by ssujay** [sendgrid/sendgrid-csharp#307]
Using the following from Example.cs
            Content content = new Content();
            content.Type = "text/plain";
            content.Value = " ";
            mail.AddContent(content);
            content = new Content();
            content.Type = "text/html";
            content.Value = "<html><body>&nbsp</body></html>";
            mail.AddContent(content);

Results in the first mail.AddContent() call adding an entry to the Content array with the expected "text/plain" content.  However, when the second mail.AddContent() executes, the results are two entries - both matching the request to add "text/html" content.

I'm using the Transactional Email templates - so I really don't need any content.  However, these values must be present to get through the interface.  Further, it seems I must have both of them to get the email to send in both text and html - without it, I get text only renditions of the templates. While odd behavior, this can be overcome (I think), but adding these entries to the object prior to submission.

This consequently, causes the "BadRequest" result when trying to send (as expected).

Given folks are using this to actually send email, how is anyone overcoming this issue?

Thanks for any assistance which you can provide.

**Comment by thinkingserious** [comment]
Hello @ssujay,

The content values are no longer required when you have a template ID set.

We will investigate your report also, that is not expected behavior.

Thanks!

**Comment by thinkingserious** [comment]
@ssujay,

I have confirmed that the Content object should not be included when using a template. Please let me know if you continue to have any issues.
