### ISSUE TITLE
CC and BCC examples?

### ISSUE THREAD

**Issue by snobrdinrtiste** [sendgrid/sendgrid-csharp#311]
been reading up i don't see anywhere that has examples of adding cc and bcc addresses.
i have read closed issues about cc and bcc not supported in v3.
so ... does v3 support cc and bcc?  if so, can someone direct me to some examples?
and if it doesn't... do earlier versions like v2 support cc and bcc???

**Comment by thinkingserious** [comment]
Hi @snobrdinrtiste,

Please see: 

1. With Mail Helper: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L119
2. Without Mail Helper: https://github.com/sendgrid/sendgrid-csharp/blob/master/examples/mail/mail.cs#L29

Thanks!
