### ISSUE TITLE
Send to Multiple recipients not working

### ISSUE THREAD

**Issue by mbalcarek** [sendgrid/sendgrid-csharp#313]
#### Issue Summary

When I run the following code, only the first recipient gets the email. I have tried comma delimiting and semi-colon delimiting. The email shows all 3 recipients, but only the first gets the email.

using System;
using SendGrid;
using SendGrid.Helpers.Mail;
using System.Threading.Tasks;

namespace PCS.ConsoleApp.SendGridMail
{
    internal class Example
    {
        private static void Main(string[] args)
        {
            Execute().Wait();
        }

        static async Task Execute()
        {
            string apiKey = "ourkey";
            dynamic sg = new SendGridAPIClient(apiKey);

            SendGrid.Helpers.Mail.Email from = new SendGrid.Helpers.Mail.Email("test@xyz.com");
            string subject = "Hello World from the SendGrid Test 6";
            SendGrid.Helpers.Mail.Email to = new SendGrid.Helpers.Mail.Email("user1@xyz.com,user2@msn.com,user3@xyz.com");
            Content content = new Content("text/plain", "Hello, Email content.");
            Mail mail = new Mail(from, subject, to, content);

            dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());
        }
    }
}

Please provide instructions on how to send to multiple recipients.

#### Technical details:

* sendgrid-csharp Version: 8.0.3
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @mbalcarek,

In that case, you don't want to use the Mail constructor. 

You can either use the [AddTo function multiple times](https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L137) or pass the emails as a [List type](https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/SendGrid/Helpers/Mail/Mail.cs#L1134).

Also, you can use [this syntax](https://github.com/sendgrid/sendgrid-csharp#without-mail-helper-class).

Please let me know if you have additional trouble.

Thanks!

**Comment by mbalcarek** [comment]
That worked perfectly, thank you.

**Comment by thinkingserious** [comment]
Hi @mbalcarek,

Awesome!

Thanks for sharing the final code too :) Can we give you a small token of our appreciation by sending you a T-shirt? We just need you to email us at dx@sendgrid.com with your mailing address and T-shirt size. 

Thank again!
