### ISSUE TITLE
Substitutions are limited to 10000 bytes per personalization

### ISSUE THREAD

**Issue by mespinozadsac** [sendgrid/sendgrid-csharp#316]
#### Issue Summary

Hi, I'm sending a parameter containing an HTML with a list of about 100 products and prodcutos me the following error message: Substitutions are limited to 10000 bytes per personalization. Any idea how puee send such mail SendGrid?

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @mespinozadsac,

Please reach out to https://support.sendgrid.com to help figure out a solution for your use case. 

Thanks!
