### ISSUE TITLE
Add recipient 

### ISSUE THREAD

**Issue by girishus** [sendgrid/sendgrid-csharp#323]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by girishus** [comment]
.net Add AddRecipients not working for me . I was able to add list and Recipients to list.
I do have one custom field called parcel_number, but even simple email is not adding.
static async Task ExecuteAddRecipients()
        {

            string apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY", EnvironmentVariableTarget.User);
            dynamic sg = new SendGrid.SendGridAPIClient(apiKey);
            Object json = null;
            try
            {

                string data = @"
                {
                'email': 'girish_us@yahoo.com'
                }";
                json = JsonConvert.DeserializeObject<Object>(data);
                data = json.ToString();
                dynamic response = await sg.client.contactdb.recipients.post(requestBody: data);

                Log.Info(string.Format("Status Code = {0} ", response.StatusCode));
                Log.Info(string.Format("Result = {0} ", response.Body.ReadAsStringAsync().Result));

            }
            catch (Exception ex)
            {
                Log.Info(ex.Message);
            }
        }

Please suggest what might wrong.

**Comment by thinkingserious** [comment]
Hi @girishus,

The request body expects an array of objects, please see:

https://github.com/sendgrid/sendgrid-csharp/blob/master/examples/contactdb/contactdb.cs#L211
https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Single-Recipient-POST

Thanks!

**Comment by girishus** [comment]
works great!!
Thank you - thinkingserious
