### ISSUE TITLE
Is Duplicate email in list with different custom field allowed?

### ISSUE THREAD

**Issue by girishus** [sendgrid/sendgrid-csharp#326]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by girishus** [comment]
I have one to many relationship with email to parcel number ( may be some cases 100 parcel with same email).
i.e. one email have more than one parcel number.
I was not able to add same email with different parcel number in recipient or in list.
Recipient was which ever is last one stand - i.e. update Recipient.
I want each parcel as separate record with email. (even same email)

I was able to transnational email send from my application.  
I want this tool as just like CRM. So I can use two way update my system.

Is any one face this issue or suggest how to resolve my issue.

**Comment by girishus** [comment]
Any suggestion are wellcome

**Comment by thinkingserious** [comment]
Hello @girishus,

Please contact our support team at https://support.sendgrid.com. Thank you!
