### ISSUE TITLE
Create a Inbound Parse data parser

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#328]
A consumer and parser for the [SendGrid Inbound Parse Webhook](https://sendgrid.com/docs/API_Reference/Webhooks/inbound_email.html).

## Acceptance Criteria:
- Implement all the functions [here](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/inbound/parse.py).

## Reference:
- https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/inbound/parse.py
- https://sendgrid.com/docs/Classroom/Basics/Inbound_Parse_Webhook/setting_up_the_inbound_parse_webhook.html
- https://sendgrid.com/docs/API_Reference/Webhooks/parse.html

**Comment by pichardoSoftware** [comment]
May I help in this??

**Comment by thinkingserious** [comment]
That would be great @pichardoSoftware!

Please take a moment to [sign our CLA](https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla), so that we may accept your contributions.

For context, please [check out the project](https://github.com/sendgrid/sendgrid-csharp/projects) "Inbound Parse Helper" and please let me know if you have any questions.

**Comment by pichardoSoftware** [comment]
Thanks @thinkingserious I will.

**Comment by pichardoSoftware** [comment]
So I was working on this, and I saw the `_init_(self,config,request):`, and in the app.py file I saw that request is from flask, so I was wondering is there any other framework going to be used instead of Flask, something like Nancy?

**Comment by thinkingserious** [comment]
Hello @pichardoSoftware,

Nancy looks solid, or you can keep [even simpler](https://msdn.microsoft.com/en-us/library/system.net.httplistener(v=vs.110).aspx).

**Comment by pichardoSoftware** [comment]
I used the `HttpListenerRequest` and parsed the form data with an static method. But I stumbled on the  `email.message_from_string` do you have any preferences on this or should I parse it manually?

**Comment by thinkingserious** [comment]
@pichardoSoftware,

I don't have any preference on how it's executed internally. The end result should be parsed content for the user.  Thanks!

**Comment by mbernier** [comment]
It looks like this one is open, since there has been no movement since last year!

**Comment by KoditkarVedant** [comment]
Hello @thinkingserious, I would like to contribute on this issue/enhancement. If I understand the requirement correctly, we need to implement the inbound helper same as the one implemented [here](https://github.com/sendgrid/sendgrid-python/tree/master/sendgrid/helpers/inbound). (it should be a deployable webhook handler). 

Looking at the python code it looks like an example than a helper (which can be reused in the SendGrid Client), what are your thoughts?

Can you please confirm if my understanding is correct?

**Comment by thinkingserious** [comment]
Hello @KoditkarVedant,

Your understanding is correct.

Additionally, I believe this should be implemented within a Docker container. And I don't think it should be packaged up as part of this library though. It should be a stand-alone service. 

The [StrongGrid SDK](https://github.com/Jericho/StrongGrid#parser) has an implementation for reference.

With Best Regards,

Elmer

**Comment by KoditkarVedant** [comment]
Hello @thinkingserious,

Is there any repository you can point me to use to create branch from and PR against or should I create the repository myself?

Thanks,
Vedant

**Comment by thinkingserious** [comment]
Hi @KoditkarVedant,

Please [check this repo](https://github.com/sendgrid/hacktoberfest) on October 1rst. At that time we will be thinking through how to handle these types of projects. 

Currently, I'm not sure if we should just include the code in this repo or create a new repo.

With Best Regards,

Elmer

**Comment by KoditkarVedant** [comment]
Hello @thinkingserious,

I have created a repository for Inbound Webhook Parser [here](https://github.com/KoditkarVedant/sendgrid-inbound). I'm currently updating it. How can I ask for review once I completed the implementation?

I also see that you have opened a new issue #766 which describes the same requirement.

Thanks,
Vedant

**Comment by thinkingserious** [comment]
Hi @KoditkarVedant,

Just ping me when it's ready for review :)

My apologies, [this issue](https://github.com/sendgrid/sendgrid-csharp/issues/766) should replace this one. I will mark it as work in progress for you. 

Thanks!

With Best Regards,

Elmer
