### ISSUE TITLE
Send a Single Email to a Single Recipient

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#331]
Acceptance Criteria:
- A email object that represents the response body payload
- A mail object that handles sending email objects, data validation and error handling

Reference:
- https://github.com/sendgrid/sendgrid-csharp/tree/master/SendGrid/SendGrid/Helpers/Mail
- https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by M3LiNdRu** [comment]
If you don't mind, I'd say I can help here. I'll do a PR.

**Comment by thinkingserious** [comment]
That's awesome @M3LiNdRu!

Could you please take a moment and sign our CLA so we will be able to merge your work? https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla

A bit more detail on the project can be found here: https://github.com/sendgrid/sendgrid-csharp/projects

**Comment by pichardoSoftware** [comment]
Is this issue taken?

**Comment by M3LiNdRu** [comment]
Yep, I´m working on it. I'll do a PR once it´s finished

**Comment by pichardoSoftware** [comment]
Ok thanks

**Comment by M3LiNdRu** [comment]
@thinkingserious About previous points:

- A email object that represents the response body payload. 

What are you meaning? Create an object to handle http response body payloads of the request? Assuming you're using with dynamic objects right now...

- A mail object that handles sending email objects, data validation and error handling

Is it already created? As I can see there is an object (https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/SendGrid/Helpers/Mail/Mail.cs) for that purpose.

Many Thanks,
Roger

**Comment by thinkingserious** [comment]
Yes, the objects are already, this is to be a refactor based on the feedback from the community. I suggest you also take a look at the other v9beta projects here: https://github.com/sendgrid/sendgrid-csharp/projects and also the links included int the description. I'm currently working on "Remove Dynamic Dependency".

For this task, I would start by suggesting a new Interface that implements this use case.

For example we have this now:

```csharp
string apiKey = Environment.GetEnvironmentVariable("NAME_OF_THE_ENVIRONMENT_VARIABLE_FOR_YOUR_SENDGRID_KEY", EnvironmentVariableTarget.User);
dynamic sg = new SendGridAPIClient(apiKey);

Email from = new Email("test@example.com");
string subject = "Hello World from the SendGrid CSharp Library!";
Email to = new Email("test@example.com");
Content content = new Content("text/plain", "Hello, Email!");
Mail mail = new Mail(from, subject, to, content);

dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());
```

On solution might be:

```csharp
string apiKey = Environment.GetEnvironmentVariable("NAME_OF_THE_ENVIRONMENT_VARIABLE_FOR_YOUR_SENDGRID_KEY", EnvironmentVariableTarget.User);
sg = new SendGridAPIClient(apiKey);

// Build the Mail object
Email from = new Email("test@example.com", "Example User");
Subject subject = new Subject("Hello World from the SendGrid CSharp Library!");
Email to = new Email("test@example.com", "Example User");
Content content = new Content("text/plain", "Hello, Email!");
Mail mail = new Mail(from, subject, to, content);

Response response = await sg.client.send(mail);
```

or

```csharp
string apiKey = Environment.GetEnvironmentVariable("NAME_OF_THE_ENVIRONMENT_VARIABLE_FOR_YOUR_SENDGRID_KEY", EnvironmentVariableTarget.User);
sg = new SendGridAPIClient(apiKey);

Mail mail = new Mail(sg);
mail.AddToEmail("test@example.com", "Example User");
mail.SetFromEmail("test@example.com", "Example User");
mail.SetSubject("Hello World from the SendGrid CSharp Library!");
mail.AddContent("text/plain", "Hello, Email!");
mail.AddContent("text/html", "Hello, Email!");
Response response = await mail.Send()
```

I hope that helps. Please reach back out with further questions and feedback.

**Comment by thinkingserious** [comment]
Also, please be sure to fork off this branch: https://github.com/sendgrid/sendgrid-csharp/tree/v9beta Thanks!

**Comment by M3LiNdRu** [comment]
Perfect, I'll work on this.

Thanks for the details

**Comment by thinkingserious** [comment]
@M3LiNdRu,

I'm now actively working on this issue: https://github.com/sendgrid/sendgrid-csharp/issues/303

My work is on the remove-dynamic branch: https://github.com/sendgrid/sendgrid-csharp/tree/remove-dynamic

I've already removed the dependency to SendGrid.CSharp.HTTP.Client and I'm in the process of removing the dynamic functionality.

**Comment by thinkingserious** [comment]
@M3LiNdRu something to consider: https://github.com/sendgrid/sendgrid-csharp/issues/352

**Comment by M3LiNdRu** [comment]
@thinkingserious You should close this issue and merge the PR before start fixing #352.

Meanwhile I will have a look at it.

Cheers

**Comment by thinkingserious** [comment]
@M3LiNdRu,

I'm not finished yet, but I've merged this to the v9beta branch so you can start thinking about integration: https://github.com/sendgrid/sendgrid-csharp/pull/356/files

Basically, I've removed the dynamic dependency and brought the client functionality into the library.

**Comment by thinkingserious** [comment]
Also, here are my next steps:

- combine SendGridAPIClient and Client
- update the README
- update all tests

Then, I'm moving over to help you with the Mail Helper refactor.

**Comment by jkewley** [comment]
I've got to concur with @chadwackerman on the naming conventions he [objected to over here](https://github.com/sendgrid/sendgrid-csharp/issues/317#issuecomment-260132022). This thread is titled 'Send a Single Email to a Single Recipient' but if you applied those names to the V3 API, you'd end up sending an unknown entity someone's email address. I hate to be pedantic, but

**Email** is a term that the one generally uses to describe the complete message (send a single email)
**Mail**, when not a verb, is not commonly used in place of Email (can I mail you a quote? I'd prefer email)
**Content** by itself is a collection of information, not a type of information 
**Client** is a suffix for a fully named type that explains what it is a client of

These are quick reactions to the limited part of the API that I see [in your sample code over here](https://github.com/sendgrid/sendgrid-csharp/tree/v9beta#hello-email).

I feel like you are trying to abbreviate widely-used terms to make the verbiage more succinct, but so many devs use intellisense-powered coding tools that the names of variables and types don't really matter to productivity. And instead of making something easier through brevity, (in my opinion) you've made it harder through ambiguity and redefinition.

Since you're targeting C# devs with this library, why not use the type names (or something very close) used by System.Net.Mail? If you do that, people will just know how to use your library without any trouble.

**Comment by Bartmax** [comment]
100% Agree with @jkewley 
The entity names are misleading, confusing and very very obscure.

Few more issues I want to note is the implementation of client.

Content looks like have "body" and "header" (or mailtype).
if I'm not mistaken the most common mail-types are only 2.
Is it really needed to specify text/plain as a magic string? If it's possible i would avoid that, by having different objects (EmailBodyHtml & EmailBodyText [and a custom if needed]) or as part of the method signature.


----------------

The order of the parameters of the Mail constructor looks weird.
`Main(from, subject, to, content)`;
I think from,to,subject,content will be more familiar, i suggest that pick the ordering from the System.Net.Mail or another popular mail library.

-----------------


Why the client isn't an abstraction?
```
Response response = await client.RequestAsync(method: Client.Methods.POST,
                                                          requestBody: mail.Get(),
                                                          urlPath: "mail/send");
```

I would imagine more into this lines:
```
SendEmailResponse response = await client.SendEmailAsync(mail, cancellationToken);
```

-----------------

I think it's also important to address that normally people send 2 versions of same email text/plain and html. So i think it would be great to have this consideration in mind. Maybe it is supported just not used in the sample.

Those were my 2 cents! _by only reading the sample code_

**Comment by Bartmax** [comment]
One more question:
This is an implementation of IMAP or SMTP client or just a wrapper around HttpClient and REST API ?

**Comment by thinkingserious** [comment]
Thanks for the solid feedback @Bartmax! We will definitely be absrtacting the client in the helper and you should see your suggestions reflected shortly on this thread when I propose the updated interface.

Regarding your question, this is a wrapper around our v3 Web API.

**Comment by Jericho** [comment]
@Bartmax totally agree with your statement

> Is it really needed to specify text/plain as a magic string? If it's possible i would avoid that, by having different objects (EmailBodyHtml & EmailBodyText [and a custom if needed]) or as part of the method signature.

In fact, I implemented something very similar to what you are suggesting in the [StrongGrid library](https://github.com/Jericho/StrongGrid). I added two convenient methods called `SendToSingleRecipientAsync` and `SendToMultipleRecipientsAsync` that accept, among other things, a `htmlContent` and `textContent` parameters and the library takes care of adding the appropriate "magic strings" before making the request to SendGrid's API.

**Comment by thinkingserious** [comment]
Following is a proposal for the interface rewrite for the Mail Helper and interface for the use case of sending a single email. 

I would like to begin implementation within days, if possible. Any feedback is appreciated as always.

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;

//// GENERIC HELLO WORLD SEND
// Wraps https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html 

var sg = new SendGridClient("APIKEY");
var msg = new SendGridMessage();
var from = new MailAddress("dx@example.com", "Name");
msg.From(from);
var to = new MailAddress("test@example.com", "Name");
msg.AddTo(to);
msg.Subject("Subject String");
msg.Content("HTML content string", sg.MimeType.HTML);
// or msg.ContentHTML("HTML content string");
msg.Content("Plain text content string", sg.MimeType.TEXT);
// or msg.ContentText("HTML content string");
var response = await sg.SendEmailAsync(msg);

//// SEND A SINGLE EMAIL TO A SINGLE RECIPIENT

var sg = new SendGridClient(APIKEY);
var from = new MailAddress("dx@example.com", "Name");
var to = new MailAddress("test@example.com", "Name");
var subject = "Subject String";
var contentHTML = "<bold>HTML content</bold>";
var contentText = "Text content";
// Optionally, you can pass a fifth parameter of type
// SendGridMessage, to include things like attachments
// or turn on/off settings
var response = await sg.SendSingleEmailAsync(from, to, subject, contentHTML, contentText); 
```

The goal will be to keep this interface through the lifetime of the v3 API, adding functionality as needed.

With regards to the new version of `SendGridMessage` class, the plan is to stay close to the previous [SendGridMessage class](https://github.com/sendgrid/sendgrid-csharp/blob/b27983a8f3d84a9d28972f2720cca0315ad9fe32/SendGrid/SendGridMail/SendGrid.cs#L13), but we will not include System.Net.Mail as it seems [unstable at best in .NET Core](https://github.com/dotnet/corefx/issues/1006).

I deviated from using `Body` instead of `Content`, as System.Net.Mail does, to be consistent with the v3 API conventions. 

Thanks for taking the time to review!

**Comment by thinkingserious** [comment]
The WIP is here: https://github.com/sendgrid/sendgrid-csharp/tree/single-email

The next step is that I will be uploading a beta to Nuget v9.0.0-beta and requesting additional feedback before we push the official v9.0.0 release.

Thanks again for the patience and continued support!

**Comment by darrelmiller** [comment]
Using functions to assign values is fairly uncommon thing to do in C#.  Using properties is much more common as it allows you to take advantage of property initialization. Off the top of my head, this is how I would do it.

```Csharp
var sg = new SendGridClient("APIKEY");
var msg = new SendGridMessage() {
  From = new MailAddress("dx@example.com", "Name"),
  To = new MailAddress[] { new MailAddress("test@example.com", "Name")},
  Subject = "Subject String",
  Content = new PlainTextContent("Plain text content string"),
  Content = new HtmlContent("HTML content string")  // or
};
var response = await sg.SendEmailAsync(msg);
```
Using this initialization syntax is completely option and devs could assign values to properties in separate lines.  
I also changed the capitalization of HTML.  .Net framework guidelines say any acronym over 3 chars should be Pascal cased.
The use of String/HTML Content classes mirror the way HttpClient handles content.  It allows keeping the serialization details of the particular format with the class and the content-type header can be predefined in the content class, so there is no need for a user to specify it.

**Comment by jkewley** [comment]
@thinkingserious  - I don't mean this as an attack or dismissal in any way, but [the code sample you put forth](https://github.com/sendgrid/sendgrid-csharp/issues/331#issuecomment-265664085) feels like an approach by someone who is coming to C# as a second or third programming language (your GitHub activity suggests that you dev across multiple languages). I'd strongly suggest that you reach out to someone who works with C# on a regular basis as a consumer of APIs and platforms. Given your preferred status within Azure at Microsoft, I'd expect that you should be able to engage someone over there for a little help/feedback.

I've got to say that @darrelmiller's suggested approach seems so obvious that I can't imagine the implementation being much different. It makes appropriate use of C# language features, library names, and programming patterns and is exactly the style of code that you'll find on any current blog, article, or open source repository across the .Net ecosystem. (I personally would use EmailAddress over MailAddress, but that's fairly insignificant relative to everything else). 

He made several good arguments for his approach, including the use of [properties over methods](https://msdn.microsoft.com/en-us/library/ms229054(v=vs.100).aspx). I don't think I've seen the use of a method to set plain properties on a class since the 1.x versions of .Net. Maybe have a look at the [Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/ms229042.aspx). 

As for .Net Core, it looks like they've [decided which APIs they'll be re-implementing](https://github.com/dotnet/corefx/issues/11792#issuecomment-248139058) and have apparently made an [initial commit](https://github.com/dotnet/corefx/pull/12416) to the [System.Net.Mail namespace](https://github.com/dotnet/corefx/tree/master/src/System.Net.Mail/src).

**Comment by thinkingserious** [comment]
@darrelmiller,

Thanks for feedback along with the quick turn around time :)

I'm definitely implementing your changes and they will be reflected on the [single-email](definitely) branch shortly.

@jkewley,

Indeed, I dev across 7 languages currently and C# is not my primary language. But I'm very much enjoying it and I've always loved Visual Studio since my C++ days at the University. I especially enjoy the passionate community here, within the C# community in general and at Microsoft. I've learned so much from all of you in such a short period. Thanks again!

Also, thanks for the confirmation on Darrel's suggestions and the heads up on the System.Net.Mail namespace, I will revisit this. We will continue to lean on this community and our friends at Microsoft as we continue to iterate forward. If you are interested, you can follow the branch I mentioned above for progress.

@chadwackerman,

Thanks for the upvote on Darrel's comments!

**Comment by thinkingserious** [comment]
@darrelmiller,

I have rewritten the two code samples as follows and have verified that the code is functional:
- [Generic Hello World Send using the Mail Helper](https://github.com/sendgrid/sendgrid-csharp/blob/single-email/src/Example/Program.cs#L22)
- [Send a Single Email using the Mail Helper](https://github.com/sendgrid/sendgrid-csharp/blob/single-email/src/Example/Program.cs#L45)

Your feedback would be greatly appreciated.

@jkewley, @chadwackerman,

Your feedback on the changes would also be greatly appreciated.

I will now clean up the code, update the examples, add comments and update the tests before moving on to the case of "Send a Single Email to Multiple Recipients".

**Comment by jkewley** [comment]
Looks much better. Couple of suggestions:

- consider renaming Client to something more specialized. SendGrid is probably going to be used in a project that has several types of clients which perform different interactions with other APIs
- the Personalization hierarchy feels like an API leak. As a consumer I would prefer to not have to know about that entity because it's not something that is typically part of an email api. Flatten everything out, use methods (AddRecipient) to add to internal collections using flat objects (EmailAddress) as parameters
- Same feedback on Contents. Plain text and html content have a 1 to 1 relationship with an email message, right? So let them be properties of the SendGridMessage class

**Comment by chadwackerman** [comment]
@jkewley in the absence of providing actual code may I present the likely outcome here. https://www.flickr.com/photos/sluggerotoole/153603564

**Comment by chadwackerman** [comment]
@jkewley Given the skills mismatch, in the absence of you providing actual code may I present the likely outcome here. https://www.flickr.com/photos/sluggerotoole/153603564

**Comment by jkewley** [comment]
Ok, I wrote some throw away code and [pushed it out here](https://github.com/jkewley/SendGridScratch). 

Note that I implemented 2 approaches for adding a recipient. 
The first is just a public List of EmailAddress types hanging off of the SendGridMessage. This makes for nice object initialization, but classes shouldn't expose underlying collections, so
The second is the AddRecipient approach which uses methods to add recipients

I'd welcome any feedback (except for my variable naming approach, which I acknowledge is non-standard) considering I whipped it up in about 10 mins.

**Comment by thinkingserious** [comment]
Thanks for the quick turnaround on the feedback @jkewley!

I will rename the Client to SendGridClient.

[Personalizations](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html) is a key concept for advanced usage of the API, so I will hide that usage under a section called "Advanced or Custom", as there are some users who want to directly manipulate the [entire request body](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html) for custom solutions. The helpers (e.g. [Send a Single Email using the Mail Helper](https://github.com/sendgrid/sendgrid-csharp/blob/single-email/src/Example/Program.cs#L45) will serve to [hide the implementation](https://github.com/sendgrid/sendgrid-csharp/blob/single-email/src/SendGrid/Helpers/Mail/MailHelper.cs#L8) details, and we will highlight these use cases in README. [These are the helpers](https://github.com/sendgrid/sendgrid-csharp/projects/2) I will implement for v9.0.0.

I agree with your comment on Contents and I will make that adjustment.

**Comment by thinkingserious** [comment]
@jkewley,

Just saw your comment, I will review shortly. Thanks for taking the time to do that!

**Comment by thinkingserious** [comment]
@jkewley,

Thanks again for taking the time to write up a useful code sample!

In addition the updates I mentioned above, I will add some convenience methods to the SendGridMessage object. I'll push the result up to the [single-email](https://github.com/sendgrid/sendgrid-csharp/tree/single-email) branch.

**Comment by jkewley** [comment]
@chadwackerman, @darrelmiller please have a look at my scratch solution to provide feedback before @thinkingserious heads down the path of integrating the suggestions

**Comment by thinkingserious** [comment]
@jkewley,

[Using the convenience methods added to SendGridMessage](https://github.com/sendgrid/sendgrid-csharp/blob/single-email/src/Example/Program.cs#L22)

**Comment by chadwackerman** [comment]
Looks good. I think you're missing a ".com" on this line: ... new EmailAddress("dx@sendgrid", "DX Team")

On the non-helper version you're creating a string, converting it to Object via JsonConvert, then converting it back to a string. I suppose this gives you some crude form of validation but better to create wrapper classes:

public class SendMailOptions
{
  // (other fields needed)
  public EmailAddress From { get; set; }
  public System.Net.Http.HttpContent Content { get; set; }
}

The user fills that out, passes it to you, and you call JsonConvert.SerializeObject() to convert it to string for sending to your web service.

Gradually build up these little wrapper objects and you wind up with a clean library. You can often reuse types from the .NET libraries which will make things instantly familiar to .NET devs.

You may also want to check out Swagger.

**Comment by thinkingserious** [comment]
Thanks for taking the time to check out the changes @chadwackerman! And for the useful feedback, once again.

I'll fix the .com typo. For the final release, those will be fake email addresses.

That non-helper version was for those who prefer to cut and paste the actual JSON object. There was at least one person who specifically asked for that. It sounds like is probably a rare use case so we should probably tuck that example away in a dark corner.

What you describe with the SendMailOptions class, I believe, is achieved with the [SendGridMessage class](https://github.com/sendgrid/sendgrid-csharp/blob/single-email/src/SendGrid/Helpers/Mail/SendGridMessage.cs). True?

I will go through the code and look for places where we can use .NET types. Thanks!

We use [Swagger](https://github.com/sendgrid/sendgrid-oai) to auto-generate [interactive docs](https://sendgrid.com/docs/API_Reference/api_v3.html), [usage docs](https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md), [integration tests](https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/UnitTest/UnitTest.cs) and [examples](https://github.com/sendgrid/sendgrid-csharp/tree/master/examples).

**Comment by chadwackerman** [comment]
Was the Swagger autogenerated C# client a total disaster? (Is that how we got here in the first place?)

https://github.com/swagger-api/swagger-codegen

**Comment by thinkingserious** [comment]
Hello everyone,

BIG thanks to all of those that have contributed on this thread, we greatly appreciate your patience and support!

The [v9beta branch](https://github.com/sendgrid/sendgrid-csharp/tree/v9beta) has been pushed to Nuget as a [prerelease](https://www.nuget.org/packages/Sendgrid/9.0.0-beta) for testing. Please give it a spin and let us know what you think :)

The main updates are:
- Removed dynamic dependencies
- Added support for .NET Standard 1.3
- Updated the Mail Helper for better UX/DX

Here is what we think needs to be completed before we exit beta:
- A few weeks of iterative improvements based on your feedback and internal testing
- Updated docs (USAGE, USE_CASES, TROUBLESHOOTING, CONTRIBUTING, /examples and the Helper Example)
- Update the auto-generated portions of the tests to use CamelCase function names
- Move from Travis to Appveyor
- Implement SendSingleEmailToMultipleRecipientsAsync
- Implement SendMultipleEmailsToMultipleRecipientsAsync
- Adopt StyleCop

The remainder of our wants for this version will be added to GitHub as issues.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
v9 is launched
