### ISSUE TITLE
Send a Single Email to Multiple Recipients

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#333]
Acceptance Criteria:
- A email object that represents the response body payload
- A mail object that handles sending email objects, data validation and error handling

Reference:
- https://github.com/sendgrid/sendgrid-csharp/tree/master/SendGrid/SendGrid/Helpers/Mail
- https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by pichardoSoftware** [comment]
@thinkingserious I want to help, if permited, with this issue, but I wonder if I should wait until the "Send a Single Email to Single Recipient" issue is completed.

**Comment by thinkingserious** [comment]
@pichardoSoftware,

I think it's best to wait as this is all part of this greater project, and it depends on "Send a Single Email to Single Recipient": https://github.com/sendgrid/sendgrid-csharp/projects "[v9beta] Mail Helper Enhancement (v3 mail/send)"

**Comment by pichardoSoftware** [comment]
Excellent, then I wait.

**Comment by M3LiNdRu** [comment]
Please, find the PR for that issue here: https://github.com/sendgrid/sendgrid-csharp/pull/350

**Comment by imsam67** [comment]
Is it not possible to send a single email to multiple recipients? Do I need to create multiple email messages?

**Comment by thinkingserious** [comment]
Hello @imsam67,

It is possible, please see this example: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L119

This issue is for the v9 refactor.

**Comment by thinkingserious** [comment]
v9 is launched
