### ISSUE TITLE
Utilize Transactional Templates

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#334]
Acceptance Criteria:
- Demonstration of usage with all three cases: Send a Single Email to a Single Recipient, Send a Single Email to Multiple Recipients, Send Multiple Emails to Multiple Recipients and

Reference:
- https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional_templates
- https://github.com/sendgrid/sendgrid-csharp/tree/master/SendGrid/SendGrid/Helpers/Mail
- https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md
- https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

**Comment by MrCsabaToth** [comment]
Is this ticket just for the use case? I'm trying to send an email utilizing a transactional template and getting back `BadRequest`. No detailed error message.

**Comment by thinkingserious** [comment]
@MrCsabaToth,

This issue is for the v9beta refactor.

I think this is the documentation you are looking for: https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional_templates

If you are still having issues, please open a new issue along with the code that is giving you trouble and we will do our best to help you.

Thanks!

**Comment by MrCsabaToth** [comment]
It was that actually: https://stackoverflow.com/questions/41433676/how-to-substitute-sendgrid-template-variables-in-c

I choose the wrong notation. Mind you, I couldn't get details of the error, why I was dissed.

**Comment by thinkingserious** [comment]
Thanks for the update @MrCsabaToth,

I am relaying your feedback to our documentation team.

**Comment by MrCsabaToth** [comment]
If I was wrong about the https://stackoverflow.com/questions/41433676/how-to-substitute-sendgrid-template-variables-in-c (which can happen) please post correct answer on SO and I'll accept it.

**Comment by thinkingserious** [comment]
Sounds good, will do @MrCsabaToth. Thanks!
