### ISSUE TITLE
whitelabel.domains.get vs whitelabel.links.get

### ISSUE THREAD

**Issue by kquinbar** [sendgrid/sendgrid-csharp#337]
#### Issue Summary

There seems to be a difference in the arguments that can be passed into client.whitelabel.domains.get vs client.whitelabel.links.get. The domains method allows you to pass in a username to filter the list of whitelabels down by. the links method does not and i think this is actually a limitation of V3 api, but i wanted to verify this. was there ever an intent of these to behave the same or will the links method on the api be updated at some point to support this. I have a need to return both domain whitelabels and link whitelabels for a specific username, similar to how your UI shows them in the whitelabels administration page.
#### Steps to Reproduce

```
var client = new SendGridAPIClient(ApiKey).client;
 var queryParams = new StringBuilder();
            queryParams.Append(@"{'domain': '', 'exclude_subusers': 'false', 'limit': 10, 'offset': 0, ");
            queryParams.Append(string.Format(CultureInfo.InvariantCulture, "'username': '{0}'", userName));
            queryParams.Append("}");

            var response = await client.whitelabel.domains.get(queryParams: queryParams);

```

```
var client = new SendGridAPIClient(ApiKey).client;
            var queryParams = new StringBuilder();
            queryParams.Append(@"{'domain': '', 'exclude_subusers': 'false', 'limit': 10, 'offset': 0, ");
            queryParams.Append(string.Format(CultureInfo.InvariantCulture, "'username': '{0}'", userName));
            queryParams.Append("}");

            var response = await client.whitelabel.links.get(queryParams: queryParams);
```
#### Technical details:
- sendgrid-csharp Version: 8.0.4
- .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @kquinbar,

Thanks for reporting this issue! I've passed this along to the API team and they now have it on their backlog. I don't have a good estimate for you, but we will circle back with you when it's updated.

**Comment by eshanholtz** [comment]
Closing this as it has been marked a non-library issue.
