### ISSUE TITLE
Performance getting emails to sendgrid

### ISSUE THREAD

**Issue by alex2833** [sendgrid/sendgrid-csharp#340]
#### Issue Summary

We are sending emails to sendgrid using SmtpClient and it appears to throttle us to about 10 emails in 7 seconds.  Is the connection time really that bad? 
#### Technical details:
- sendgrid-csharp Version: master (latest commit: [commit number])
- .NET Version: 4.0

**Comment by thinkingserious** [comment]
Hello @alex2833,

Please reach out to our support team so they can take a deeper look at your account: https://support.sendgrid.com.

Thanks!
