### ISSUE TITLE
How to add Unique Arguement using the V3 API

### ISSUE THREAD

**Issue by valokafor** [sendgrid/sendgrid-csharp#343]
This is a question, I am looking around but cannot find an example or guide to add unique arguments to emails using the V3 API so I can retrieve the arguments in a Webhook callback. Please point me to the guide if any exists.

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hi @valokafor,

They are called Custom Args: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L159

Thanks!

**Comment by valokafor** [comment]
Thank you,
