### ISSUE TITLE
vb.net sample

### ISSUE THREAD

**Issue by nfirfire** [sendgrid/sendgrid-csharp#347]
#### Issue Summary

do you have any working example in vb.net it seems there are few libraries are missing 
any help in this direction would be appreciated

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @nfirfire,

Unfortunately, we do not :(

But maybe this might help: https://github.com/sendgrid/sendgrid-csharp/issues/260
