### ISSUE TITLE
USAGE.md - Retrieve all recipients on a List, list_id should not be part of queyparams

### ISSUE THREAD

**Issue by robledosm** [sendgrid/sendgrid-csharp#351]
There is an error in Retrieve all recipients on a List example in USAGE.md document. The parameter list_id should not be part of the queryParams, otherwise you get an error (BadRequest) saying that list_id is not part of the custom filters. Removing list_id from queryParams fixes the issue.

**Comment by thinkingserious** [comment]
Thanks for the heads up @robledosm!

I've added this to our backlog for a fix.
