### ISSUE TITLE
CakeBuild + SendGrid

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#361]
If anybody is using the .NET build automation tool called [CakeBuild](http://cakebuild.net/) and would like to be able to send emails via SendGrid as a step during their build process, I have released an addin for CakeBuild to do exactly that. [Short blog post describing how to use the addin ](http://cakebuild.net/blog/2016/10/email-addins-released).

Also, please note that this addin is built using my [StrongGrid](https://www.nuget.org/packages/StrongGrid/) library which is a strongly typed library intended to be an alternative to the SendGrid library which uses 'dynamic' types.

**Comment by thinkingserious** [comment]
Hi @Jericho,

This is awesome!

Can you please add your tool here? https://sendgrid.com/docs/Integrate/libraries.html

**Comment by Jericho** [comment]
Done. [PR submitted](https://github.com/sendgrid/docs/pull/2283)
