### ISSUE TITLE
Usage.md - Retrieve information about multiple suppression groups

### ISSUE THREAD

**Issue by andrewchilcott** [sendgrid/sendgrid-csharp#365]
#### Issue Summary

 #Usage.md includes the following "This endpoint will return information for each group ID that you include in your request. To add a group ID to your request, simply append &id= followed by the group ID." 

Adding &id= will not work in a c# call to sg.client.asm.groups.get(queryParams: queryParams) it has to be in the queryParams.

Although
```
string queryParams = @"{
  'id': 1
}";
```
works for a single id, i haven't been able to get
```
string queryParams = @"{
  'id': 1, 'id': 2
}";
```
to work! Is this a bug or is my syntax incorrect?

Also, there is no mention of how to retrieve all suppression groups. By trial and error, I determined that this is achieved by using:
`string queryParams = @"{ 
}";

#### Technical details:
* sendgrid-csharp 8.0.4
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @andrewchilcott,

My guess is that we have a bug where we are overwriting values when there are multiple query parameters passed in with the same name.

Thanks for the heads up on how to retrieve all suppression groups.

I've added this issue to our backlog for a fix.

Thanks!
