### ISSUE TITLE
Usage.md - Add Http response StatusCode to documentation

### ISSUE THREAD

**Issue by andrewchilcott** [sendgrid/sendgrid-csharp#366]
#### Usage.md - Suggestion for documentation improvement

I have recently been creating an internal service to consume the v3 api. Usage.md was invaluable to this effort, but I did find one thing missing that I was constantly having to refer back to the main SendGrid documentation, that is the potential response.StatusCodes that could be returned by the call so that I could build in my error trapping.

Might I suggest that these be added in a future update of Usage.md

**Comment by thinkingserious** [comment]
Great suggestion! I've added it to our backlog. Thanks!
