### ISSUE TITLE
The type or namespace name 'Helpers' does not exist in the namespace 'SendGrid' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by arilishu** [sendgrid/sendgrid-csharp#373]
#### Issue Summary

After installing via nuget the tool, i have this problem:
The type or namespace name 'Helpers' does not exist in the namespace 'SendGrid' (are you missing an assembly reference?)

the problem is here:
using SendGrid.Helpers.Mail;

**Comment by thinkingserious** [comment]
Hello @arilishu,

I'm thinking you may have run into the issue: https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#missing-classes

If that's not the case, please let me know.

Thanks!
