### ISSUE TITLE
Add Async suffix

### ISSUE THREAD

**Issue by Vitalii-Efremov** [sendgrid/sendgrid-csharp#374]
Hi!

It's better to name the post method with Async suffix.

sendGridClient.client.mail.send.post(requestBody: mail.Get());

===>

await sendGridClient.client.mail.send.post**Async**(requestBody: mail.Get());

**Comment by thinkingserious** [comment]
Hi @Vitalii-Efremov,

Thanks for taking the time to let us know and yes, we agree :)

This is being resolved in the [v9beta branch](https://github.com/sendgrid/sendgrid-csharp/projects) which is under development currently. 

With Best Regards,

Elmer
