### ISSUE TITLE
Destination address with special characters like cpsáez (note the a)

### ISSUE THREAD

**Issue by cpsaez-Lendsum** [sendgrid/sendgrid-csharp#379]
#### Issue Summary

Trying to send an email using c# library to the address pruéba AT cpsaez.com (note the spanish tilde in the leter a) I'm receiving a bad request. I have customers right now with the special symbol in the gmail address.

example to reproduce.

string apiKey = "APIKey";
                    SendGridAPIClient sg = new SendGridAPIClient(apiKey);

                    Email from = new Email("cpsáezfromsendgrid@cpsaez.com");
                    String subject = "Hola ";
                    Email to = new Email(email);
                    Content content = new Content("text/html", "Hola ");
                    Mail mail = new Mail(from, subject, to, content);

                    mail.TemplateId = templateId;

                    SendGrid.CSharp.HTTP.Client.Response result = sg.client.mail.send.post(requestBody: mail.Get()).GetAwaiter().GetResult();

                    if (result == null || result.StatusCode != System.Net.HttpStatusCode.Accepted) throw new ....

Feel free to use any mail address under domain cpsaez.com to test the issue.

**Comment by thinkingserious** [comment]
Thanks for reporting this to us @cpsaez-Lendsum.

I have added this to our backlog for investigation.

**Comment by thinkingserious** [comment]
I just sent a test email using v9 of this SDK and it looks like it sent correctly, can you verify?

Here is the code I used:

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Threading.Tasks;

namespace Example
{
	internal class Example
	{
		private static void Main()
		{
			Execute().Wait();
		}

		static async Task Execute()
		{
			var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
			var client = new SendGridClient(apiKey);
			var from = new EmailAddress("dx@sendgrid.com");
			var subject = "Subject";
			var to = new EmailAddress("cpsáezfromsendgrid@cpsaez.com");
			var body = "Email Body";
			var msg = MailHelper.CreateSingleEmail(from, to, subject, body, null);
			msg.AddCc(new EmailAddress("elmer.thomas@sendgrid.com"));
			var response = await client.SendEmailAsync(msg);
		}
	}
}
```

**Comment by cpsaez-Lendsum** [comment]
I cannot see it in the inbox, spawn or any other folder. Maybe is a google app issue I don't know. Do you have it marked as sent correctly in your sendgrid account?

**Comment by thinkingserious** [comment]
@cpsaez-Lendsum,

On my end it was marked as an invalid email.

I did some research and found that while there are RFC specifications for your use case, there is currently not standard support across the industry for this type of email, so SendGrid does not support it. That said, you are not the only one with this issue, so I have added your voice to our product team for future consideration.
