### ISSUE TITLE
Send email to multiple recipients using C# Library

### ISSUE THREAD

**Issue by imsam67** [sendgrid/sendgrid-csharp#383]
I want to send an email to multiple recipients. I'm using the C# library.

In the examples, you're showing a JSON object. Is this the only way to send an email to multiple recipients? Is it not possible to work with objects and still be able to send an email to multiple recipients?

**Comment by warrenkc** [comment]
For an earlier version, I had to do some crazy stuff as you can see below:

// Create the email object first, then add the properties.
        SendGridMessage myMessage = new SendGridMessage();
        myMessage.AddTo("123@sink.sendgrid.net");
        List<string> formattedList = new List<string>();
        //TODO: Loop for more than 10,000 per email sending.
        foreach (var item in list)
        {
            formattedList.Add(item.Address);
        }

        var header = new Header();

        header.SetTo(formattedList);

        myMessage.Headers.Add("X-SMTPAPI", header.JsonString());

        myMessage.From = new MailAddress(MailingListEmail, BusinessName);
        myMessage.Subject = txtSubject.Text;
        myMessage.Html = EditorDescription.Text;
        MailAddress rpto = new MailAddress(ReturnEmail, BusinessName);
        var addresses = new[] { rpto };
        myMessage.ReplyTo = addresses;
        
        // Create a Web transport, using API Key
        var transportWeb = new Web(SendGridAPIKey);
        
        // Send the email.
        if (list.Count > 0)
        {
            transportWeb.DeliverAsync(myMessage);
        }

**Comment by thinkingserious** [comment]
@imsam67,

Please take a look at this example: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L119

Please let me know if you have further questions.

Thanks!

**Comment by warrenkc** [comment]
Thank you for the information. How many emails can we add to the BCC? Example, we have 8000 users signed up and need to email them all.

**Comment by thinkingserious** [comment]
@warrenkc,

The total recipients per call must not exceed 1000. Please see: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Limitations

Thanks!

**Comment by warrenkc** [comment]
@thinkingserious Hi. I tried to use the link posted on Jan 25. However the link is broken. 
What I would like to do is send an email message to 100 emails without the users seeing the list of emails. So, I can do this by adding the emails to the BCC right? However, it looks like this image below:
![image](https://user-images.githubusercontent.com/6418791/27759821-2c95ad64-5e6c-11e7-8bde-9e042494b156.png)

How can I not show the 123@sink.sendgrid.net address to the user? And make it look like the email is only to them?

**Comment by thinkingserious** [comment]
I believe [this function](https://github.com/sendgrid/sendgrid-csharp/blob/master/tests/SendGrid.Tests/Integration.cs#L410) should do what you need.

Thanks!
