### ISSUE TITLE
SendGrid unnecessarily takes dependency on Microsoft.AspNet.WebApi.Client

### ISSUE THREAD

**Issue by jt000** [sendgrid/sendgrid-csharp#384]
#### Issue Summary

SendGrid takes a dependency on Microsoft.AspNet.WebApi.Client, which is unnecessary and prevents usage in a simpler application like a console app.

#### Steps to Reproduce

1. Create a console application
2. Add NuGet reference to SendGrid

Note that a reference to Microsoft.AspNet.WebApi.Client is added. From briefly scanning through the code it doesn't look like this dependency is necessary and can be easily removed (it's not even referenced in the examples).

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
@jt000,

Thanks for bringing this to our attention. We have removed that dependency in the latest beta branch: https://github.com/sendgrid/sendgrid-csharp/tree/v9beta

With Best Regards,

Elmer
