### ISSUE TITLE
The type or namespace name 'SendGridMessage' could not be found

### ISSUE THREAD

**Issue by omsharma1** [sendgrid/sendgrid-csharp#385]
Issue Summary

MVC using .NET 4.5.2. Code below taken from: http://www.asp.net/mvc/overview/security/create-an-aspnet-mvc-5-web-app-with-email-confirmation-and-password-reset

using System;
using SendGrid;
using System.Net;
using System.Configuration;
using System.Diagnostics;

    public class EmailService : IIdentityMessageService
    {
        public async Task SendAsync(IdentityMessage message)
        {
            await configSendGridasync(message);
        }

        // Use NuGet to install SendGrid (Basic C# client lib)
        private async Task configSendGridasync(IdentityMessage message)
        {
            var myMessage = new SendGridMessage();
            myMessage.AddTo(message.Destination);
            myMessage.From = new System.Net.Mail.MailAddress(
                                "Joe@contoso.com", "Joe S.");
            myMessage.Subject = message.Subject;
            myMessage.Text = message.Body;
            myMessage.Html = message.Body;

            var credentials = new NetworkCredential(
                       ConfigurationManager.AppSettings["mailAccount"],
                       ConfigurationManager.AppSettings["mailPassword"]
                       );

            // Create a Web transport for sending email.
            var transportWeb = new Web(credentials);

            // Send the email.
            if (transportWeb != null)
            {
                await transportWeb.DeliverAsync(myMessage);
            }
            else
            {
                Trace.TraceError("Failed to create Web transport.");
                await Task.FromResult(0);
            }
        }
    }
![9b57ea66-711c-11e6-916b-301e2d363318](https://cloud.githubusercontent.com/assets/25195854/22056931/8e7f6cdc-dd88-11e6-9626-456400b66f6b.png)

SendGridMessage will not work... typing SendGrid. only shows up with CSharp, Helpers, and SendGridAPIClient.

Please advise. Thank you.

Technical details:

sendgrid-csharp Version: master (latest commit: [commit number]) (8.0.4)
.NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @omsharma1,

That example is for this version of the library: https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#v2 (6.3.2)

To use version 8.0.4, please follow the examples here: https://github.com/sendgrid/sendgrid-csharp

Thanks!
