### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by tbrookin** [sendgrid/sendgrid-csharp#387]
This library cannot currently be used from within an ASP.NET Core project.

**Comment by Jericho** [comment]
@tbrookin Please have a look at [StrongGrid](https://www.nuget.org/packages/StrongGrid). It's fully compatible with .NET Core

**Comment by thinkingserious** [comment]
@tbrookin,

This is a duplicate issue: https://github.com/sendgrid/sendgrid-csharp/issues/221

Support for .NET Core is coming shortly.

In the mean time @Jericho's solution is a solid alternative.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @tbrookin,

v9 of this SDK is now live and supports ASP.NET Core.
