### ISSUE TITLE
V3 SendGridAPIClient with BBC / CC Not working

### ISSUE THREAD

**Issue by xaviertremblay** [sendgrid/sendgrid-csharp#388]
I have a bad request when I try to post the following payload on the V3 endpoint using the c# SendGridAPIClient. 

The payload seems fine based on the doc here https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html

**Payload:** 
```
{
	"from": {
		"email": "no-reply@certifi.ca"
	},
	"subject": "subject",
	"personalizations": [{
		"to": [{
			"email": "xavier@xyz.com"
		}],
		"bcc": [{
			"email": "xavier@xyz.com"
		}],
		"substitutions": {
			"-url-": "substitution"
		}
	}],
	"content": [{
		"type": "text/html",
		"value": " "
	}],
	"template_id": "xxxxxxxx-yyyy-..."
}
```

**C# code that works if I remove the CC lines**

```
            var subject = message.Subject;

            var apiClient = new SendGridAPIClient(SendGridApiKey);
            var to = new Email(message.ToEmail);
            var from = new Email(message.FromEmail);
            var content = new Content("text/html", " ");
            var mail = new Mail(from, subject, to, content);
            mail.TemplateId = message.EmailTemplate;

            foreach (var bcc in message.BlindCarbonCopy.Select(x => new Email(x)).ToList())
            {
                mail.Personalization[0].AddCc(bcc);
            }

            foreach (var key in message.Data.Keys)
            {
                mail.Personalization[0].AddSubstitution(key, message.Data[key]);
            }

            AddAttachment(message, mail);
            var response = apiClient.client.mail.send.post(requestBody: mail.Get()).GetAwaiter().GetResult();
            return response.StatusCode == HttpStatusCode.Accepted;

```

Looks like a bug in the api client, but I might be missing something.

Thank you

**Comment by thinkingserious** [comment]
Hello @xaviertremblay,

I have added this issue into our backlog for further review.

Thanks!

Elmer

**Comment by Trouche** [comment]
Hi all,

I have just experienced this exact issue myself.  It appears that you can't use the CCs function at all right now from the latest C# library.  Definitely interested in a fix for this issue.  :)

Thanks

**Comment by thinkingserious** [comment]
@Trouche,

Please have a look at the beta to be released to our stable channel within a few weeks (this is not an issue in that release): https://www.nuget.org/packages/Sendgrid/9.0.4-beta

Documentation: https://github.com/sendgrid/sendgrid-csharp/tree/v9beta

Thanks!

**Comment by kirajhpang** [comment]
Hi, I do experience CC doesn't reach issues on V8 library, I think somehow maybe same situation with this case.  I do raise several support ticket to SendGrid, thought might not because of library but endpoint to endpoint issues. 
But I working on apply update to V9 and see how is the new library goes to. 

btw, @thinkingserious thanks for rolling out new v9 library, grad to see initialize and send mail code become more C# style!

**Comment by thinkingserious** [comment]
Thank you @kirajhpang,

Please let us know how the v9 library works for you.

**Comment by thinkingserious** [comment]
The v9 library is now out of beta and in the stable release channel in Nuget.

For retrieving the error message, please see: https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error-messages

@xaviertremblay,

I have found that the to, cc and bcc fields must all have unique email addresses. 

@Trouche,

I'm not sure if that's the case for you as well, but tagging you just in case.

Thanks!
