### ISSUE TITLE
£ symbol in attachment name results in no attachment on email

### ISSUE THREAD

**Issue by mark-quinn-cf247** [sendgrid/sendgrid-csharp#390]
#### Issue Summary

If the file name of the attachment contains a £ sign it will not add the attachment to the email:

email.AddAttachment(new MemoryStream(x.Bytes), "How to Claim your £100.pdf"));

If i remove the £ sign everything works fine. Is this a known issue?

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @mark-quinn-cf247,

Yes, this is a [known issue](https://github.com/sendgrid/sendgrid-csharp/issues/296#issuecomment-245842106) and I've added your vote. Thanks!

**Comment by mark-quinn-cf247** [comment]
are there any known work arounds?

**Comment by thinkingserious** [comment]
I'm not sure @mark-quinn-cf247.

When this issue reaches the top of our queue, I'll investigate and post my discoveries.
