### ISSUE TITLE
Substitutions in v3

### ISSUE THREAD

**Issue by thekuom** [sendgrid/sendgrid-csharp#392]
On the old v2 version of SendGrid, I was able to customize substitutions per email into the emails with the SMTP API. Is there a way to do this in v3?

**Comment by thinkingserious** [comment]
Hello @thekuom,

Yes, and here is the documentation: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

In version 8 (the current stable release), here is an example: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L188

In version 9 (the latest beta, to replace version 8 shortly - recommend you use this version), here is an example: https://github.com/sendgrid/sendgrid-csharp/blob/v9beta/tests/SendGrid.Tests/Integration.cs#L107

I hope that helps!

Thanks!

Elmer

**Comment by thekuom** [comment]
I believe those examples you included will substitute the same value for the given key. What I was referring to was having multiple emails per `SendGrid.Helpers.Mail.Email` and having a list of substitution values per key. For example, if my Email is sending to Jane and John, then I want `%name%` to be replaced with "Jane" for Jane and "John" for John. In v2, I was able to do this:
`var header = new Header();

// assume names is a list of names
header.AddSubstitution("%name%", names);

// message is SendGridMessage
message.Header = header`

**Comment by thinkingserious** [comment]
Thanks @thekuom! 

This helper may also be useful to you: https://github.com/sendgrid/sendgrid-csharp/blob/v9beta/tests/SendGrid.Tests/Integration.cs#L331
