### ISSUE TITLE
Make 'stylecop' a development dependency

### ISSUE THREAD

**Issue by onionhammer** [sendgrid/sendgrid-csharp#394]
#### Issue Summary
Installing latest SendGrid 9.07 from nuget forces a dependency on stylecop. Stylecop probably should only be a development-only dependency.

**Comment by thinkingserious** [comment]
@onionhammer,

Well, that is no good :(

Thanks for the heads up!

Hopefully version 9.0.8 fixes the issue: https://www.nuget.org/packages/Sendgrid/9.0.8

Thanks again!

**Comment by onionhammer** [comment]
Thanks for the quick fix!
