### ISSUE TITLE
Issue with CreateSingleEmail

### ISSUE THREAD

**Issue by knopa** [sendgrid/sendgrid-csharp#396]
When create SendGridMessage via that helper, with text null and html: "sdfsdf" - got exception from API content is missed

#### Technical details:

* sendgrid-csharp Version: master (9.0.8.0)
* .NET Version: 4.5.2

**Comment by knopa** [comment]
workaround - new SendGridMessage without MailHelper

**Comment by thinkingserious** [comment]
Thanks for the heads up @knopa,

Fix is on it's way: https://github.com/sendgrid/sendgrid-csharp/pull/397

**Comment by thinkingserious** [comment]
This is fixed in version 9.0.9

Thanks again!
