### ISSUE TITLE
.Net Core support 

### ISSUE THREAD

**Issue by PaybackMan** [sendgrid/sendgrid-csharp#398]
#### Issue Summary

Are there any plans to support Cross platform .net core with the sdk?

**Comment by thinkingserious** [comment]
Hello @PaybackMan,

Currently we are supporting .NET Standard 1.3. According to [this matrix](https://github.com/dotnet/standard/blob/master/docs/versions.md), we would need to support .NET Standard 1.1 to support all the listed .NET Platforms. Is that what you are referring to?

With Best Regards,

Elmer
