### ISSUE TITLE
Create ASP.NET example

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#401]
#### Issue Summary

The example should demonstrate a simple web form that sends an email.

See [issue 400](https://github.com/sendgrid/sendgrid-csharp/issues/400) for follow up.

**Comment by paritoshmmmec** [comment]
Hi @thinkingserious I have created a  ASP.NET sample to provide feature. It contains very simple feature to send email.

https://github.com/paritoshmmmec/Sendgrid-WebSample

Please let me know if you want to add more feature.

**Comment by thinkingserious** [comment]
This is awesome @paritoshmmmec!

I will take a deeper look and give some feedback :)

**Comment by vinsajon** [comment]
Is there anyway you could provide a similar sample using webforms instead of MVC.  I am trying to use SendGrid to verify the email address of a user when creating an account and I am having a difficult time with this.  The tutorial I was using is outdated and I cannot seem to convert the code properly.  I am using VS2013 web forms project and version 9.1.1 of sendgrid. I can provide my code if that would help

**Comment by paritoshmmmec** [comment]
@vinsajon please share the codebase, happy to help.

**Comment by vinsajon** [comment]
This is the code that I added to the Email Service in the Identity Config file: 
I added:
 using SendGrid;
using SendGrid.Helpers.Mail;
using System.Net;
using System.Configuration;
using System.Diagnostics;

The Code:
public class EmailService : IIdentityMessageService
    {
        public async Task SendAsync(IdentityMessage message)
        {            
            // Plug in your email service here to send an email.
            await configSendGridasync(message);
        }
         private async Task configSendGridasync(IdentityMessage message)
        {            
            var apiKey = System.Environment.GetEnvironmentVariable("APIKEY");
            var client = new SendGridClient(apiKey);
            var msg = new SendGridMessage()
            {
                From = new EmailAddress("test@example.com", "DX Team"),
                Subject = "Hello World from the SendGrid CSharp SDK!",
                PlainTextContent = "Hello, Email!",
                HtmlContent = "<strong>Hello, Email!</strong>"
            };
            msg.AddTo(new EmailAddress(message.Destination));
            var response = await client.SendEmailAsync(msg);
        }

In the web.config file I added this: 
<appSettings>
    <add key="APIKEY" value="I_PUT_MY_APIKEY_IN_HERE"/>
  </appSettings>
I am not getting any errors when I create a new user, it is just redirecting to the home page as before and not sending a confirmation email.  I plan on not using the webconfig file for the key in the future, I am just trying to get it to work for now.  I really appreciate any help with this.

**Comment by vinsajon** [comment]
The web.config didn't get added.  Here it is:
<appsettings
<add key="APIKEY" value="I_PUT_MY_APIKEY_HERE"
appsettings>
I left some of the brackets out on purpose

**Comment by vinsajon** [comment]
it won't let me post it but I put in add value equals APIKEY and then my apikey I got from SendGrid

**Comment by thinkingserious** [comment]
Hello @vinsajon,

It looks like your issue is properly reading your APIKEY. You can verify this, by trying:

`var apiKey = "YOUR_SENDGRID_API_KEY";`

If the above works, it means you are having trouble retrieving the APIKEY variable from your environment. 

Since it looks like you are holding the API key in your web.config, [please try this](http://stackoverflow.com/questions/3854777/read-variable-from-web-config).

Thanks!

@paritoshmmmec,

Thanks for offering to create the example!

**Comment by vinsajon** [comment]
I was able to get it to work.  I cannot begin to thank you enough.  I am mostly self taught with coding so sometimes I get stuck on simple things for a long time.  
I also had to change the subject to subject = message.subject and the htmlcontext and plaintextcontext to equal message.body for the link to go through.

**Comment by thinkingserious** [comment]
Hello @paritoshmmmec,

Please add the example to `ExampleNet45ASPNetProject` in the root directory.

Also, could you please update the README to point out where the API Key gets changed in the code and a brief explanation on how to run the example and make modifications if necessary.

Thank you!

With Best Regards,

Elmer

**Comment by paritoshmmmec** [comment]
@thinkingserious  Thanks , I will work upon it and add it

**Comment by paritoshmmmec** [comment]
PR #464 submitted
