### ISSUE TITLE
Make SendGridClient implement an interface for DI and mocking in tests

### ISSUE THREAD

**Issue by Tarball** [sendgrid/sendgrid-csharp#403]
#### Issue Summary

I would like to be able to mock the SendGridClient object so I can unit test my code without actually making any calls to the SendGrid API. Unfortunately the SendGridClient does not implement any interfaces so I have to instantiate it directly instead of being able to use dependency injection to inject the interface.

The old 6.X.X version of the SendGrid client included an ITransport interface which could be mocked for testing without actually hitting the API.

**Comment by thinkingserious** [comment]
Hello @Tarball,

I'm adding this to our backlog.

In the meantime, we are using [StopLight.io's prism](https://stoplight.io/platform/prism/) to create a mock client.

The instructions for setting this up locally for testing against a mocked version of the SendGrid API is here: https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#testing (this happens automatically on Travis).

With Best Regards,

Elmer

**Comment by rodchenkov** [comment]
Hi @thinkingserious 

I also want to mock SendGridClient.
Can you please provide update on this? I mean when are you planning to apply this change?

Thank you!

**Comment by thinkingserious** [comment]
Hello @rodchenkov,

This PR fixes this issue: https://github.com/sendgrid/sendgrid-csharp/pull/434

It should be merged soon. Thanks!

With Best Regards,

Elmer

**Comment by ottomatic** [comment]
Actually, this is a different issue. My PR enables the mocking of http responses. The request at hand is for SendGridClient to implement a (new) ISendGridClient interface so that the SendGridClient cancer be altogether mocked.

**Comment by ottomatic** [comment]
*can*. Damn you, auto-correct.

**Comment by thinkingserious** [comment]
Thanks for clarifying @ottomatic!

I've added @rodchenkov vote to this issue in our backlog.

In the mean time @rodchenkov,

You can [mock the SendGrid API currently with Prism](https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#testing).

**Comment by Jericho** [comment]
@rodchenkov Please have alook at [StrongGrid ](https://www.nuget.org/packages/StrongGrid/). It's an alternative .net client for SendGrid'a API which implements an interface for easy mocking.

**Comment by thinkingserious** [comment]
Fixed with https://github.com/sendgrid/sendgrid-csharp/pull/456
