### ISSUE TITLE
Re-use HTTP Client

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#405]
#### Issue Summary

See https://github.com/sendgrid/csharp-http-client/pull/18/files
https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGridClient.cs#L315

**Comment by jonnybee** [comment]
Do you accept Pull Requests?

**Comment by thinkingserious** [comment]
Yes we do @jonnybee :)

We will just need a [signed CLA](https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#cla).

And a pull request would push this issue much higher in our backlog.

**Comment by thinkingserious** [comment]
@jonnybee,

We have received your CLA, thanks!
