### ISSUE TITLE
Create an AddTo, AddBcc, AddCc and SetFrom that just takes an email and name

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#408]
#### Issue Summary

`msg.AddTo(new EmailAddress("test@example.com", "Test User"));`

should also work as

`msg.AddTo("test@example.com", "Test User");`

Where in the latter case we build the `EmailAddress` object behind the scenes.

**Comment by paritoshmmmec** [comment]
PR #444 has been added

**Comment by thinkingserious** [comment]
Solved by https://github.com/sendgrid/sendgrid-csharp/pull/444
