### ISSUE TITLE
Can't install via nuget for dotnet framework 4.5

### ISSUE THREAD

**Issue by 0xffAA** [sendgrid/sendgrid-csharp#412]
I try to install Sendgrid package via nuget, but i have error **"Could not install package 'Sendgrid 9.0.11'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."** Was the package broken?

Sendgrid 9.0.11
dotnet framework v4.5
nuget v3.4.4
VS Community 2015 v14.025431.01 Update 3

**Comment by 0xffAA** [comment]
I installed Sendgrid v8.0.5 successfully... But I still can't install any packages v9.0.xx

**Comment by thinkingserious** [comment]
Hello @0xffAA,

v9 supports .NET 4.5.2 and above. We do not support lower versions, because [Microsoft no longer provides security updates](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) for those versions.

I hope that helps.

Thanks!

**Comment by 0xffAA** [comment]
Thx for help and thx for provided link. I will use v8.0.5, while my project will not migrated to dotnet v4.5.2
