### ISSUE TITLE
HttpClient - wrong usage in library

### ISSUE THREAD

**Issue by jonnybee** [sendgrid/sendgrid-csharp#413]
SendGridClient always create a new HttpClient and then dispose this object for each request. 
This is wrong usage of HttpClient and may lead to instability in performance. 

See: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ 
and https://blogs.msdn.microsoft.com/henrikn/2012/02/16/httpclient-is-here/ 
(and also read the comments on the last article)

**Comment by xt0rted** [comment]
Duplicate of #405

**Comment by thinkingserious** [comment]
Hi @jonnybee,

I've added your vote to issue #405.

Thanks!
