### ISSUE TITLE
Provide support for .NET 4.5 and 4.5.1

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#415]
#### Issue Summary

We have resisted implementing this, because [Microsoft no longer supports these versions](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#net45). However, we have had several requests to support these versions for legacy applications.

I am creating this ticket to gauge interest. If you would like us to include a .dll compiled for .NET 4.5 and 4.5.1 in our Nuget package. Please let us know by adding a +1 or comment.

Thank you!

**Comment by rdeslonde** [comment]
+1 I have a 4.5.1 project that needs this library. However since MS is no longer supporting it I might just have to go ahead and upgrade the project, though I hate to do so.

**Comment by thinkingserious** [comment]
Thanks for your feedback @rdeslonde!

The current work around is to download the source code and recompile with your desired target version.

**Comment by rdeslonde** [comment]
Makes sense. I think we will just upgrade to .net 5.0. Thanks!

**Comment by patros** [comment]
For anyone else coming across this you can change to target 4.5.2 instead.
