### ISSUE TITLE
Same code one calling from .net Console app and other from .net Web Api and web api fails

### ISSUE THREAD

**Issue by fireole** [sendgrid/sendgrid-csharp#416]
Web Api Method (Fails)

![image](https://cloud.githubusercontent.com/assets/985103/23774226/03d3b172-04e0-11e7-9421-ac3037e426c9.png)

Console Method (Success)

![image](https://cloud.githubusercontent.com/assets/985103/23774259/27f58292-04e0-11e7-846e-141df3009bc5.png)

* sendgrid-csharp Version: the latest  9.0.12
* .NET Version: 4.6

The Console sends the template email.
The Web API returns Status Code Bad Request and the in the Headers a DENY  

I used the same api key, template id, and msg params.   

Am I totally missing something?

**Comment by thinkingserious** [comment]
Hi @fireole,

Could you please tell me the error message? You can grab it like this:

```csharp
Console.WriteLine(response.Body.ReadAsStringAsync().Result);
```

Thanks!

**Comment by fireole** [comment]
so the console app works, but in the web api does not.

so I did this in the web api and captured a screenshot

![image](https://cloud.githubusercontent.com/assets/985103/23775799/b7c72680-04e7-11e7-824d-2b8f43ff9694.png)

you can see it comes back as BadRequest.  

I also put this line in 

 var test = response.Body.ReadAsStringAsync().Result;

and got this:

{"errors":[{"message":"The content value must be a string at least one character in length.","field":"content.0.value","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content.value"}]}

does this help?

**Comment by fireole** [comment]
got it.

So I was using a template and not really sending an body text.  So I added this line

mailDto.Body = "test" which will fill the msg.AddContent(MimeType.Text, mailDto.Body);

and then it worked.

the msg.AddContent  is mandatory whether you use it or not.

**Comment by thinkingserious** [comment]
Hello @fireole,

After digging a little deeper, I found that we have not considered the case when you pass an empty string to the Content helper when using a template. We will update the SDK to handle this situation. You can follow that progress here: https://github.com/sendgrid/sendgrid-csharp/issues/419

If you do not have any content you wish to pass, then you do not need to call the `msg.AddContent` method.

With Best Regards,

Elmer
