### ISSUE TITLE
Support for Visual Studio 2013

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#420]
#### Issue Summary

The latest version of this SDK does not work in Visual Studio 2013

**Comment by thinkingserious** [comment]
@RealRaven2000,

What are the errors when you try to add this SDK via Nuget to Visual Studio 2013?

**Comment by RealRaven2000** [comment]
Ok, here are the dependencies:
Newtonsoft.Json >= 9.0.1
System.Net.Http >= 4.0.0
"The System.Net.Http 4.0.0;' package reqiures NuGet client version '3.0' or above but the current Nuget Version is 2.8.60610.756

I managed to upgrade Nuget to 2.12 but that is thee maximum version for VS 2013

**Comment by RealRaven2000** [comment]
when I tried installing SnedGrid 7.1.1 I got this:

Install-Package Sendgrid -Version 7.1.1
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Client (≥ 5.2.3)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.4)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 9.0.1)'.
Attempting to resolve dependency 'SendGrid.CSharp.HTTP.Client (≥ 2.0.7)'.
Installing 'Microsoft.AspNet.WebApi.Client 5.2.3'.
You are downloading Microsoft.AspNet.WebApi.Client from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.WebApi.Client 5.2.3'.
Installing 'Newtonsoft.Json 9.0.1'.
Successfully installed 'Newtonsoft.Json 9.0.1'.
Installing 'SendGrid.CSharp.HTTP.Client 2.0.7'.
Successfully installed 'SendGrid.CSharp.HTTP.Client 2.0.7'.
Installing 'Sendgrid 7.1.1'.
Successfully installed 'Sendgrid 7.1.1'.
Install failed. Rolling back...
Install-Package : Updating 'Microsoft.AspNet.WebApi.Client 4.0.20710.0' to 'Microsoft.AspNet.WebApi.Client 5.2.3' failed. Unable to find a version of 
'Microsoft.AspNet.WebApi.Core' that is compatible with 'Microsoft.AspNet.WebApi.Client 5.2.3'.
At line:1 char:1
+ Install-Package Sendgrid -Version 7.1.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by thinkingserious** [comment]
Hi @RealRaven2000,

v7 of this SDK was the first version of the v3 API.

It seems like if we update our dependency to System.NET.Http v4.3.1 it would solve your issue, as that version depends on Nuget 2.12 or higher: https://www.nuget.org/packages/System.Net.Http I have added this to our backlog to test. If your need is urgent, I suggest you try recompiling this SDK with that updated dependency.

- Elmer

**Comment by RealRaven2000** [comment]
(Maybe after raising all libraries to .NET 4.5.2) I have a reference to 
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Net.Http.dll

Is this too high?
Do I need to downgrade .NET again?

**Comment by thinkingserious** [comment]
@RealRaven2000,

This SDK only supports 4.52 and higher. The issue seems to be that System.Net.Http v4.0.0 is requiring Nuget 3.0. After some digging, I found the following:

1. It does not actually need Nuget 3.0, so I'm guessing that's one reason why they rolled that dependency back in v4.3
2. Nuget 3.0 is not available on VS2013

So that's why I'm thinking that by upgrading System.Net.Http to v4.3 would do the trick.

**Comment by RealRaven2000** [comment]
"So that's why I'm thinking that by upgrading System.Net.Http to v4.3 would do the trick."

"upgrade" How? according to object browser it is already 4.5.2? Would that not be a downgrade??
Assembly System.Net.Http
    C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Net.Http.dll

**Comment by RealRaven2000** [comment]
I tried this with package manager:

PM> Install-Package System.Net.Http 
Installing 'System.Net.Http 4.3.1'.
You are downloading System.Net.Http from Microsoft, the license agreement to which is available at http://go.microsoft.com/fwlink/?LinkId=329770. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'System.Net.Http 4.3.1'.
Adding 'System.Net.Http 4.3.1' to eIFU.Web.
Successfully added 'System.Net.Http 4.3.1' to eIFU.Web.
One or more packages could not be completely uninstalled: SendGrid.SmtpApi.1.3.1. Restart Visual Studio to finish uninstall.

**Comment by thinkingserious** [comment]
@RealRaven2000,

I am referring to the version of `System.Net.Http`, not the version of .NETFramework.

If you are using the latest version of the SendGrid SDK, then the examples for sending an email are here: https://github.com/sendgrid/sendgrid-csharp#hello-email

**Comment by RealRaven2000** [comment]
The problem with that example is that it uses SendGrid.Helpers.Mail which doesn't exist in the version I have linked. What should I do next?

**Comment by thinkingserious** [comment]
@RealRaven2000,

v6 is stable, however, it is no longer supported and it uses the v2 API, which while we will continue to support, we are recommending that you upgrade to the v3 API.

v9 is the latest stable SDK to support our v3 API. If you can get it to work in your project, then that would be the route I recommend. That said, v6 would provide the quick and dirty solution you require.

**Comment by thinkingserious** [comment]
Note that, for v6, you would need to follow this documentation: https://github.com/sendgrid/sendgrid-csharp/tree/b27983a8f3d84a9d28972f2720cca0315ad9fe32

**Comment by RealRaven2000** [comment]
I don't mind using the latest and greatest as long as I do not have to remove anything vital from the actual project and can stay in VS2013 (the project is inherited and based on MVC)
I have 7.1.1 linked now whats the minimum requirement for Helper namespace? Is there a complete version log where I can see when this was introduced?  Do I need SendGridMail.dll, I can't seem to gind a version > 6.3. So confused right now...

**Comment by RealRaven2000** [comment]
good news: I revisited the package manager and tried the upgrade process again, apparently this time it worked. Now the Sendgrid reference maps to 

C:\clients\....\packages\Sendgrid.9.0.12\lib\net452\SendGrid.dll

after adding the reference to my notification library Sendgrid.Helpers.Mail is also allowed so I can use  SendGridClient

**Comment by RealRaven2000** [comment]
last thing since I have to do some refactoring any idea how to convert 
System.Net.Mail.Attachment 
to   
SendGrid.Helpers.Mail.Attachment?
I had Attachments.Add(attachment.ContentStream, attachment.Name);

**Comment by thinkingserious** [comment]
@RealRaven2000,

Great to hear the upgrade process worked! I think the manual upgrade of `System.Net.Http` did the trick. That means I should upgrade that dependency, so I'll keep this issue open.

With regards to attachments, you will need the [`AddAttachments` method](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L928). Note that your content will need to be [Base64 encoded](https://msdn.microsoft.com/en-us/library/dhx0d524(v=vs.110).aspx).

**Comment by RealRaven2000** [comment]
ok - since I have a backwards compatible wrapper for local testing I will need to convert at least
contentype and the byte[] stream (see below) and shoehorn it into the new format. the main attachments are pdf files which are stored in a database using some sort of blob structure. For the purpose of email they need to converted back so that they become readable.

public partial class Attachment
    {
        public int ID { get; set; }
        public int IFUID { get; set; }
        public string Name { get; set; }
        public byte[] AttContent { get; set; }
        public string AttContentType { get; set; }
        public bool AttPrimary { get; set; }
    ...
    }

**Comment by thinkingserious** [comment]
@RealRaven2000,

Did you get it to work?

**Comment by RealRaven2000** [comment]
Sending mail - yes. 
Attachments - not there yet.
I had a bigger problem in that the remote server always gave an error about razor referencing the wrong version (2.0.0.0) although I had removed all references and it worked locally, Bit of a nightmare - was working to get it online for an audit until 2:30am and gave up. The solution was to reinstall mvc:

Update-Package Microsoft.AspNet.Mvc -Reinstall

that took about 100 or so newsgroups to find :) If you have any snippets for converting byte[] to base64 (or System.Net.Mail.Attachment to SendGrid.Helpers.Mail.Attachment) I would be interested to see that somewhere?

**Comment by thinkingserious** [comment]
Hi @RealRaven2000,

Ouch, I hope things are smoother today!

To convert from byte[] to base64, [here is the function](https://msdn.microsoft.com/en-us/library/dhx0d524(v=vs.110).aspx) you need.

**Comment by EdgeFintech** [comment]
I just tried to install sendgrid 9.1.1 and received an error stating that it does not support .NETFramework 4.5.1. Per the NuGet page, sendgrid 9.1.1 supports .NETFramework 4.0 (see error below)*. Do you know what is causing this error?

**Package dependency versions:**
Newtonsoft.Json 10.0.2
System.Net.Http 4.3.1

*The error is as follows:

Install-Package : Could not install package 'Sendgrid 9.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not c
ontain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
