### ISSUE TITLE
SendGridMessage.Headers.Add throws "Headers is Null"

### ISSUE THREAD

**Issue by RealRaven2000** [sendgrid/sendgrid-csharp#421]
#### Issue Summary

Trying to add a Priority Header to  SandGridMessage() throws an error

#### Steps to Reproduce

		var msg = new SendGridMessage()
		{
			From = new EmailAddress(from),
			Subject = subject,
			PlainTextContent = body.Replace("\\n", "\n")
		}; // we can also set HtmlConent or Html (older version)
		// list of to addresses - use generic list, convert to array.
		msg.AddTo(new EmailAddress(to)); // from SendGrid.Helpers.Mail namespace
		msg.Headers.Add("Priority", "Normal");

this last line throws
System.NullReferenceException: Object reference not set to an instance of an object.

if Headers is a Dictionary<string, string> why does Add not work? ITs also not possible to assign it to a newe dictionary. Looks to me like it's broken.

#### Technical details:

* sendgrid-csharp Version: 9.0.12
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Please try:

msg.AddHeader("Priority", "Normal");

Thanks!
