### ISSUE TITLE
Forward bounce to reply-to address

### ISSUE THREAD

**Issue by benjamineberle** [sendgrid/sendgrid-csharp#426]
We need a way to forward bounces to the reply-to address instead of the sender address.

[PR #371](https://github.com/sendgrid/sendgrid-csharp/pull/371/) was closed recently without an alternative.

Can you merge or is there another way to achieve that?

**Comment by thinkingserious** [comment]
Hi @benjamineberle,

This is a feature that is not currently supported by our [API](https://sendgrid.com/docs/API_Reference/api_v3.html). I have forwarded your request to our product team for consideration.

With Best Regards,

Elmer

**Comment by benjamineberle** [comment]
Hi Elmer,

The service team mentioned something about filters that could be applied on each message, not just globally for the whole account. True or is that definitely not supported currently?
PR #371 seems to apply global settings and might be irrelevant for our need.

Only way out to run our own server?

thanks,
Benjamin

**Comment by thinkingserious** [comment]
Hi @benjamineberle,

I am not aware of that [filter](https://sendgrid.com/docs/API_Reference/SMTP_API/apps.html). I believe this is not supported currently. 

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @benjamineberle,

To achieve this, we need you to contact support and ask to have your return path set to a specific address. We will then override all emails with that return path moving forward.

With Best Regards,

Elmer

**Comment by benjamineberle** [comment]
Hi Elmer,

Is that a fixed return path or a dynamic one based on the reply-to address?
Fixed ones can be set in the portal, just not dynamic ones.

We implemented email logging to work around this limitation, but the API only returns invalid email addresses without being able to identify individual emails. Would be nice to have an id or custom header on each email that is returned when getting invalids, bounces etc.

Thanks,
Benjamin

**Comment by thinkingserious** [comment]
Hi @benjamineberle,

I'm not sure about the return path question, that would be a question best suited for our [support team](https://support.sendgrid.com).

Have you seen our [event webhook](https://sendgrid.com/docs/API_Reference/Webhooks/event.html)? That might be what you need.

With Best Regards,

Elmer
