### ISSUE TITLE
Locked out of my account due to IP address whitelisting

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#427]
@mbernier or @thinkingserious, can either of you help? 

I was experimenting with the `POST https://api.sendgrid.com/v3/access_settings/whitelist` end point and added a bogus IP address to the whitelist which worked fine but it had the side effect of locking me out of my account. As a result, I no longer have access to my account, neither from the web interface nor from the API.

If I attempt to log on the web, I am denied access and a few seconds later I receive the following email: `An IP address that is not on your whitelist attempted to access your account`. If I attempt any API call, the response I get is: `HTTP 403 Access forbidden`.

I contacted SendGrid support (ticket 1040510) but they want to very account ownership and the only way they want me to prove ownership is by sending an email with a given subject from my SendGrid account to an address they specified. Obviously, I can't do that since I'm locked out. It's a catch 22: they won't help me until I can prove ownership and I can't prove ownership until they help me!

Can either of you talk to Cole Crawford and vouch for the fact that I am indeed the legitimate owner of my account so he can go ahead and remove the bogus IP address from my account's IP whitelist which would restore access to my account?

Thanks

**Comment by thinkingserious** [comment]
Hello @Jericho,

Are you still locked out? I have reached out to Cole on your behalf.

**Comment by Jericho** [comment]
@thinkingserious yes, still locked out.

**Comment by Jericho** [comment]
Got in touch with Cole and he restored access to my account. Thanks for your assistance.

**Comment by efantozzi** [comment]
Hello @thinkingserious, **sorry for the inconvenience** but I´m having the exact same problem here (**Ticket #1124532**), and I cant verify my account through phone verification nor credit card verification because my account is set up through Softlayer (IBM Service). I am the legitimate owner of my account (I can verify that through my Softlayer Invoices). 

Is there any chance you could PLEASE help me remove the IP address from my account's IP whitelist which would restore access to my account?

Thanks!!

**Comment by thinkingserious** [comment]
Hello @efantozzi,

Unfortunately, this is something I can not help with. It looks like our support team is awaiting your response.

With Best Regards,

Elmer

**Comment by hash2code** [comment]
@thinkingserious  I am facing the same issue of lockout from sendgrid account.
Can you help us regarding the same?

**Comment by childish-sambino** [comment]
@hash2code Please use this form regarding IP lockout support: https://support.sendgrid.com/hc/en-us/requests/new#ipam-lockout

**Comment by itAsia** [comment]
Hi
I have the same problem but I cannot contact support. The system asks me to log in. I cannot login because my IP is not allowed. so I cannot contact support.
Help ! 
:)

**Comment by lowwy-99** [comment]
Hi

I have the same problem now.

I already sent tickets to their supports, but no dice. I understand we have 14 hours of different time zone but if they can treat it as priority would be great. 

If someone in this thread knows or knew: **Mihai Petrovici** and **Ruxandra Andrioae** from Twilio-SendGrid. Could you tell them that the administrator of SendGrid account Narrada waiting for their answers.

Cheers
