### ISSUE TITLE
Readme - broken link to Examples and image

### ISSUE THREAD

**Issue by bcnzer** [sendgrid/sendgrid-csharp#428]
In the README.md, under Usage there is a link "Example Code" which link points to: https://github.com/sendgrid/sendgrid-csharp/tree/master/SendGrid/Example

The above link serves up a 404. I'm not sure if you meant to have it pointing against ExampleCoreProject, ExampleNet45Project or examples.

Also, one minor thing: at the bottom there is an About section. The logo is not showing up.
![SendGrid Logo] (https://uiux.s3.amazonaws.com/2016-logos/email-logo%402x.png)

**Comment by SendGridDX** [comment]
Thanks for the heads up @bcnzer, fixed with: https://github.com/sendgrid/sendgrid-csharp/pull/429
