### ISSUE TITLE
SendGridClient.RequestAsync returns 200 OK on any exception

### ISSUE THREAD

**Issue by benmiller86** [sendgrid/sendgrid-csharp#433]
#### Issue Summary

The `SendGridClient.RequestAsync` method returns a response with the status code of 200 when **any** exception is thrown. I ran into this as I wanted to implement retries in the even of transient errors. The easiest of which to create was disconnecting my PC from the internet (or at least the first I thought of). To my surprise I got a 200 OK suggesting nothing had gone wrong. I know that it returns a 202 Accepted when the email is actually sent so I can deal with this, but returning a 200 OK is pretty misleading.

#### Steps to Reproduce

1. Disconnect your PC from the internet
2. Try to send an email using this library
3. Check the response code (it will be 200 OK)

**Comment by ottomatic** [comment]
Is this a duplicate of issue #358 which I am working on or is it different functionality (info request vs sending messages)?

**Comment by benmiller86** [comment]
It is, my apologies. I scanned through the open issues bit didn't see that one. I'll close this.

**Comment by ottomatic** [comment]
@benmiller86: It could actually have been separate but similar errors in the code. But in this case one method (SendEmailAsync) calls the other (RequestAsync) so I will fix both by not swallowing the exception inside RequestAsync.

Best regards.

**Comment by benmiller86** [comment]
@ottomatic You are quite correct. I am actually consuming the SendEmailAsync method myself, but when I referred to the source code I saw that it was the RequestAsync method that was the issue.
