### ISSUE TITLE
SendEmailAsync hangs without returning anything.

### ISSUE THREAD

**Issue by jeancroy** [sendgrid/sendgrid-csharp#436]
#### Issue Summary

In some cases  
````cs
await ( new SendGridClient(_sendGridApiKey) ).SendEmailAsync(mail)
````

Hangs without returning an error. I see the mail is sent but it don't let the code continue and create a timeout error eventually.

#### Steps to Reproduce

See this gist for our reproduction. (I edited api key and emails address)
https://gist.github.com/jeancroy/81397ac4417e2543ce763bd2e8ec706c

I'm not sure why, maybe I'm doing something wrong with the new api syntax.

#### Technical details:

Sendgrid 9.1.1 , Sendgrid.CSharp.Http.Client 3.20

**Comment by thinkingserious** [comment]
Hello @jeancroy,

I believe [this](https://github.com/sendgrid/sendgrid-csharp/issues/423#issuecomment-287853152) is your solution.

Please give it a try and let me know how it goes. 

Thanks!

**Comment by jeancroy** [comment]
Thanks
