### ISSUE TITLE
How to embed images in email body by using C# code Urgent

### ISSUE THREAD

**Issue by lczc1988** [sendgrid/sendgrid-csharp#437]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by lczc1988** [comment]
Please let me know how to embed images in email body by using C# code ?

Below code does not work!

var attachments = new List<SendGrid.Helpers.Mail.Attachment>();
            var attachment = new SendGrid.Helpers.Mail.Attachment()
            {
                Content = "BwdW",
                Type = "image/png",
                Filename = Server.MapPath("~/Images/EmailHeader.png"),
                Disposition = "inline",
                ContentId = "EmailHeader"
            };
            attachments.Add(attachment);
            
            msg.AddAttachments(attachments);


In html body: @"<img src=""cid:EmailHeader""/>"

**Comment by thinkingserious** [comment]
Hello @lczc1988,

`Content` should be the base64 encoded version of `~/Images/EmailHeader.png`.  [`Convert.ToBase64String`](https://msdn.microsoft.com/en-us/library/dhx0d524(v=vs.110).aspx) is the method you will use for that.

`Filename` is the name of file. In your case, it would likely be `EmailHeader.png`.

Please try the above and let me know how it goes.

Thanks!

Elmer

**Comment by thinkingserious** [comment]
Also, I've added your vote to this issue: https://github.com/sendgrid/sendgrid-csharp/issues/402

**Comment by GauravSgh** [comment]
Hi,

I am trying to put svg inside email body, but image is not rendering, need quik help on this.
my code to send email:

public async Task<HttpResponseMessage> SendEmailAsync(EmailDeliveryModel model)
        {
            var response = new HttpResponseMessage(System.Net.HttpStatusCode.BadRequest);
            var client = new SendGridClient(ConfigurationManager.AppSettings[CommonObject.SendGridKey]);
            var msg = new SendGridMessage();
            msg.SetFrom(new EmailAddress(model.SourceEmail));
            var recipients = new List<EmailAddress>();  
            //multiple recipients
            foreach(string emailAddress in model.DestinationEmail.Trim(',').Split(','))
            {
                recipients.Add(new EmailAddress(emailAddress.Trim()));
            }
            msg.AddTos(recipients);
            msg.SetSubject(model.Subject);
            if (model.ContentType.Equals(CommonObject.ContHTML, StringComparison.OrdinalIgnoreCase))
            {
                msg.AddContent(MimeType.Html, model.EmailContent + "\n \n \n \n \n");
            }
            else
            {
                msg.AddContent(MimeType.Html, model.EmailContent + "\n \n \n \n \n");
            }
            var sendGridresponse = await client.SendEmailAsync(msg);
            if (sendGridresponse.StatusCode == System.Net.HttpStatusCode.Accepted)
            {
                response.StatusCode = System.Net.HttpStatusCode.OK;
            }
            return response;
        }

And in EmailContent i am injecting html as:
<!DOCTYPE html><html><body><table><tbody><tr><td align='left'><div id="myDIV"><svg xmlns='http://www.w3.org/2000/svg' version='1.1' id='Capa_1' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='50' height='50' viewBox='0 0 56 56' style='enable-background:new 0 0 56 56;' xml:space='preserve'><g><path style='fill:#E9E9E0;' d='M36.985,0H7.963C7.155,0,6.5,0.655,6.5,1.926V55c0,0.345,0.655,1,1.463,1h40.074 c0.808,0,1.463-0.655,1.463-1V12.978c0-0.696-0.093-0.92-0.257-1.085L37.607,0.257C37.442,0.093,37.218,0,36.985,0z'/><polygon style='fill:#D9D7CA;' points='37.5,0.151 37.5,12 49.349,12'/><path style='fill:#91CDA0;'d='M48.037,56H7.963C7.155,56,6.5,55.345,6.5,54.537V39h43v15.537C49.5,55.345,48.845,56,48.037,56z'/><g><path style='fill:#FFFFFF;' d='M20.379,48.105L22.936,53h-1.9l-1.6-3.801h-0.137L17.576,53h-1.9l2.557-4.895l-2.721-5.182h1.873 			l1.777,4.102h0.137l1.928-4.102H23.1L20.379,48.105z'/><path style='fill:#FFFFFF;' d='M27.037,42.924v8.832h4.635V53h-6.303V42.924H27.037z'/><path style='fill:#FFFFFF;' d='M39.041,50.238c0,0.364-0.075,0.718-0.226,1.06S38.453,51.94,38.18,52.2s-0.611,0.467-1.012,0.622	c-0.401,0.155-0.857,0.232-1.367,0.232c-0.219,0-0.444-0.012-0.677-0.034s-0.467-0.062-0.704-0.116	c-0.237-0.055-0.463-0.13-0.677-0.226c-0.214-0.096-0.399-0.212-0.554-0.349l0.287-1.176c0.127,0.073,0.289,0.144,0.485,0.212 c0.196,0.068,0.398,0.132,0.608,0.191c0.209,0.06,0.419,0.107,0.629,0.144c0.209,0.036,0.405,0.055,0.588,0.055 c0.556,0,0.982-0.13,1.278-0.39c0.296-0.26,0.444-0.645,0.444-1.155c0-0.31-0.105-0.574-0.314-0.793 c-0.21-0.219-0.472-0.417-0.786-0.595s-0.654-0.355-1.019-0.533c-0.365-0.178-0.707-0.388-1.025-0.629 c-0.319-0.241-0.583-0.526-0.793-0.854c-0.21-0.328-0.314-0.738-0.314-1.23c0-0.446,0.082-0.843,0.246-1.189 s0.385-0.641,0.663-0.882c0.278-0.241,0.602-0.426,0.971-0.554s0.759-0.191,1.169-0.191c0.419,0,0.843,0.039,1.271,0.116 c0.428,0.077,0.774,0.203,1.039,0.376c-0.055,0.118-0.119,0.248-0.191,0.39c-0.073,0.142-0.142,0.273-0.205,0.396 c-0.064,0.123-0.119,0.226-0.164,0.308c-0.046,0.082-0.073,0.128-0.082,0.137c-0.055-0.027-0.116-0.063-0.185-0.109 s-0.167-0.091-0.294-0.137c-0.128-0.046-0.296-0.077-0.506-0.096c-0.21-0.019-0.479-0.014-0.807,0.014 c-0.183,0.019-0.355,0.07-0.52,0.157s-0.31,0.193-0.438,0.321c-0.128,0.128-0.228,0.271-0.301,0.431 c-0.073,0.159-0.109,0.313-0.109,0.458c0,0.364,0.104,0.658,0.314,0.882c0.209,0.224,0.469,0.419,0.779,0.588 c0.31,0.169,0.647,0.333,1.012,0.492c0.364,0.159,0.704,0.354,1.019,0.581s0.576,0.513,0.786,0.854	C38.936,49.261,39.041,49.7,39.041,50.238z'/></g><path style='fill:#C8BDB8;' d='M23.5,16v-4h-12v4v2v2v2v2v2v2v2v4h10h2h21v-4v-2v-2v-2v-2v-2v-4H23.5z M13.5,14h8v2h-8V14z M13.5,18h8v2h-8V18z M13.5,22h8v2h-8V22z M13.5,26h8v2h-8V26z M21.5,32h-8v-2h8V32z M42.5,32h-19v-2h19V32z M42.5,28h-19v-2h19V28 z M42.5,24h-19v-2h19V24z M23.5,20v-2h19v2H23.5z'/></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg></div><label style='font-size:14px;font-family:Roboto-Regular;font-weight:normal;color:#676767;'></td><td align='left'><p><a href = 'https://crdsreportviewer-qa.azurewebsites.net/Home/Index/34011'>SPEC1</a></p></label></td></tr></tbody></table></body></html>
I know thread is being already closed but I didn't any other better place to ask this.
Need a quick help on this

**Comment by GauravSgh** [comment]
@thinkingserious

**Comment by thinkingserious** [comment]
Hello @GauravSgh,

You will want to add the image as an [inline attachment](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#kitchensink). Please try that and let me know how it goes. Thanks!

With Best Regards,

Elmer
