### ISSUE TITLE
400 bad request on adding multiple recipients 

### ISSUE THREAD

**Issue by rictokyo** [sendgrid/sendgrid-csharp#438]
#### Issue Summary

I cannot add multiple recipients to a campaign list

#### Steps to Reproduce

<pre>
 internal class CustomHttpClient : HttpClient
    {
        private string token;

        internal void AddAuthorization(string token)
        {
            var authenticationHeaderValue = new AuthenticationHeaderValue("Bearer", token);
            this.DefaultRequestHeaders.Authorization = authenticationHeaderValue;
            this.token = token;
        }

        internal bool PostJson(string url, IDictionary<string,string> values)
        {
            string data = JsonConvert.SerializeObject(values).ToString();

            var response = this.PostAsync(url, new StringContent(data, Encoding.UTF8, "application/json")).Result;

            return response.IsSuccessStatusCode;
        }
    }
</pre>

And then have a class call it as:

<pre>

 private const string CampaignApiUrl = "https://api.sendgrid.com/v3/campaigns";

        SendGridHttpClient client = new SendGridHttpClient();

        public void AddRecipientsToList(string list_id, IList<string> recipients)
        {
            var recipients1 = new Dictionary<string, string>();

            foreach (var recipient in recipients)
            {
                recipients1.Add("email", recipient);
                //recipients1.Add("age", " ");
                //recipients1.Add("first_name", " ");
                //recipients1.Add("last_name", " ");
            }

            client.Instance.PostJson(ListsApiUrl + "/" + list_id + "/recipients", recipients1);
        }

</pre>

When I then call AddRecipientsToList with a valid list id and an array such as new[] {"test@mail.com"} as the second parameter will always returns 400 bad request

Can you tell me what I'm doing wrong?

**Comment by thinkingserious** [comment]
Hello @rictokyo,

To add multiple recipients to a list: https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md#add-multiple-recipients-to-a-list ([API level docs](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Multiple-Recipients-POST))

With Best Regards,

Elmer

**Comment by rictokyo** [comment]
Hi @thinkingserious 

This also fails with 400 bad request, can you give me a quick simple example of this working for you with using HttpClient ?

Hasnt worked for me ever.. thanks

**Comment by thinkingserious** [comment]
Can you please tell me the underlying error? https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error
