### ISSUE TITLE
CreateSingleEmailToMultipleRecipients only sends email to first recipient

### ISSUE THREAD

**Issue by bprime** [sendgrid/sendgrid-csharp#439]
#### Issue Summary

Basically I want to send a single email to multiple recipients. However trying to do so using the `MailHelper.CreateSingleEmailToMultipleRecipients` function results in only one email being sent to the first recipient.

No errors are raised and it looks like the call is completed successfully.

If I look in the SendGrid Activity log I can see that only one email was sent, but when I get the email in my inbox, I can see the other recipients in the "To" line.

I would have expected every recipient to receive a copy of the email.

#### Steps to Reproduce

1. Create a list of email addresses.
2. Call MailHelper.CreateSingleEmailToMultipleRecipients using that list of recipients.
3. Check the Activity Log, there will only be one email delivered.
4. Check the email, the other recipients will be listed in the To line.

#### Technical details:

* sendgrid-csharp Version: v9.1.1
* .NET Version: 4.6.2

**Comment by thinkingserious** [comment]
Hello @bprime,

Unfortunately, I could not reproduce. Here is the sample code I used:

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Example
{
	internal class Example
	{
		private static void Main()
		{
			Execute().Wait();
		}

		static async Task Execute()
		{
			var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
			var client = new SendGridClient(apiKey);
			var from = new EmailAddress("dx@sendgrid.com", "DX Team");
			var subject = "Hello World from the SendGrid CSharp SDK!";
                        var toEmails = new List<EmailAddress>()
                        {
                              new EmailAddress("elmer.thomas@sendgrid.com", "Elmer Thomas"),
                              new EmailAddress("elmer.thomas@gmail.com", "Elmer Thomas Personal")
                        };
			var plainTextContent = "Hello, Email!";
			var htmlContent = "<strong>Hello, Email!</strong>";
                        var msg = MailHelper.CreateSingleEmailToMultipleRecipients(from, toEmails, subject, plainTextContent, htmlContent);
			var response = await client.SendEmailAsync(msg);
		}
	}
}
```

I was able to receive the email at both email addresses.

Please take a look and let me know how your code differs. Thanks!

**Comment by bprime** [comment]
Thanks for the sample code, it helped me track down the problem and it was indeed my mistake.

Basically the code was parsing the list of To email addresses from a single string but splitting on the wrong delimiter resulting in an email address object that actually looked like this:

`new EmailAddress("elmer.thomas@sendgrid.com;elmer.thomas@gmail.com")`

Calling CreateSingleEmailToMultipleRecipients with this email address as the `tos` parameter results in the first email address actually getting an email and the others not. However, when the email shows up in my inbox (I'm using Outlook 2016) the "To" line is parsed out and displayed as multiple recipients.

Splitting the email addresses out correctly obviously fixes the issue.

I'm not sure if this is what's supposed to happen when passing in a badly formed email address (if it is even considered badly formed), but I'm not complaining. It was definitely better for me to at least get the one email than nothing (or an error).

Thanks again.

**Comment by thinkingserious** [comment]
Thanks for sharing the solution @bprime!
