### ISSUE TITLE
Is there a version for .NETFramework 4.5?

### ISSUE THREAD

**Issue by wjsiv** [sendgrid/sendgrid-csharp#447]
I'm getting this message:

install-package : Could not install package 'Sendgrid 9.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by thinkingserious** [comment]
Hello @wjsiv,

This library only supports v4.52+. However, we do have an [open issue](https://github.com/sendgrid/sendgrid-csharp/issues/415) for v4.5 support and I've added your vote there. Thanks!

With Best Regards,

Elmer

**Comment by wjsiv** [comment]
No problem I can upgrade .NET.
