### ISSUE TITLE
Adding BCC to Sengrid 9.1.1 gives Bad Request

### ISSUE THREAD

**Issue by SushantKadam008** [sendgrid/sendgrid-csharp#448]
#### Issue Summary

Hi,
I have created a sample with BCC. Once I add a BCC it gives a bad request. Without BCC everything works fine
[SendgridSamples.zip](https://github.com/sendgrid/sendgrid-csharp/files/982598/SendgridSamples.zip)

#### Steps to Reproduce

Please fins attached zip for more information

#### Technical details:
Sendgrid 9.1.1
* .NET Version: 4.5.2

**Comment by paritoshmmmec** [comment]
@SushantKadam008 Each email address in the personalization block should be unique between to, cc, and bcc. sushantkadam17@gmail.com is repeated between to and cc.

**Comment by thinkingserious** [comment]
@SushantKadam008,

@paritoshmmmec is correct, this is expected behavior. 

Thanks!

**Comment by SushantKadam008** [comment]
I tested it and it works with different email address. But in this atleast proper exception needs to be raised as Bad Request does not tell clearly that To and Bcc are same. We might get Bad Request in mutliple scenarios

**Comment by thinkingserious** [comment]
Hi @SushantKadam008,

You should be able to retrieve the exception message like so: https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error

Please let me know if that does not fit your needs.

Thanks!
