### ISSUE TITLE
Cannot send attachements

### ISSUE THREAD

**Issue by Nkmol** [sendgrid/sendgrid-csharp#452]
#### Issue Summary

Sending StreamedAttachment is not send or received (either Hotmail or Gmail).

My `SendGridMessage` contains one `.StreamedAttachment` which is a `System.IO.MemoryStream` with all the right values. With an explicit stream position of 0.

#### Steps to Reproduce

```
// var attachments is IEnumerable<System.Net.Mail.Attachment>
var message = new SendGridMessage();
message.From = new MailAddress(sender);
message.AddTo(new List<string> { "myemail@provider.com" });
message.Subject = subject;
message.Html = "<h1>test</h1>";

if (attachments?.Any() == true)
{
    var streamAttachment = attachments.First().ContentStream;
    streamAttachment.Position = 0;
    message.AddAttachment(streamAttachment, attachments.First().Name);
}

```

#### Technical details:

* sendgrid-csharp Version: 6.3.4
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @Nkmol,

[Here is an example](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#attachments) of how to send with attachments. I believe the key element you are missing is the conversion to base64.

With Best Regards,

Elmer
