### ISSUE TITLE
The remote server returned an error: (400) Bad Request.    

### ISSUE THREAD

**Issue by ashishradadia** [sendgrid/sendgrid-csharp#454]
I am not using any sendgrid dll 

Currently using sendgrid web api v3 
url : "https://api.sendgrid.com/v3/mail/send"

{"personalizations":[{"to":[{"email":"ashishradadia147@gmail.com","name":"John Doe"}],"subject":"Hello, World!"}],"from":{"email":"sam.smith@example.com","name":"Sam Smith"},"reply_to":{"email":"sam.smith@example.com","name":"Sam Smith"},"subject":"Hello, World!","content":[{"type":"text/html","value":"my full html code here "}]}

`              HttpWebRequest request = (HttpWebRequest)WebRequest.Create(URL);

                            var authorization = Convert.ToBase64String(Encoding.Default.GetBytes(Emailoperator.ApiKey));
                            request.Headers["authorization"] = "Bearer " + Emailoperator.ApiKey;
                            
                            byte[] bytes;
                            bytes = System.Text.Encoding.ASCII.GetBytes(Parameter);
                            request.ContentType = "application/json";
                            request.Method = "POST";
                            Stream requestStream = request.GetRequestStream();
                            requestStream.Write(bytes, 0, bytes.Length);
                            requestStream.Close();
                            HttpWebResponse response;
                            response = (HttpWebResponse)request.GetResponse();
                            if (response.StatusCode == HttpStatusCode.OK || response.StatusCode == HttpStatusCode.Accepted)
                            {
                                Emailxml = "";
                                Stream responseStream = response.GetResponseStream();
                                responseStr = new StreamReader(responseStream).ReadToEnd();
                            }
`

i use this code for sending mail but response as  "The remote server returned an error: (400) Bad Request.    "

**Comment by thinkingserious** [comment]
Hello @ashishradadia,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by ashishradadia** [comment]
i also send mail to support but they have no solution even he is not familiar with HTML

**Comment by thinkingserious** [comment]
@ashishradadia,

Could you please provide me with your support ticket number?

Also, have you considered using our SDK? It should make this easier for you.

**Comment by ashishradadia** [comment]
Request #1094056 
yes now i am going with SDK

**Comment by thinkingserious** [comment]
Thanks @ashishradadia,

If you have any problems using the SDK, please let me know.
