### ISSUE TITLE
API calls using a SubUser key are failing in 9.x.x - all worked in 8.0.5

### ISSUE THREAD

**Issue by andrewchilcott** [sendgrid/sendgrid-csharp#462]
I have recently created a new library for my application, based on 9.2.0 and have now upgraded to 9.4.1 but the problem persists. The original library was based on 8.0.5 and all of the sub-user pages worked

I have a Master Admin page which lists all the keys for the Master account together with a list of all SubUsers. The API calls for these lists work fine when using the Master key in both 8.0.5 and 9.4.1.

When a sub user is selected, further data calls are triggered to collect the monitoring, reputation and ip addresses for the sub user. These API calls also work fine. I then need a list of the keys for each sub user so get the sub-user master key using a call passing the subuser name, password and key_id. This too, is successful. When I use this key to retrieve a list of sub user api keys the call just hangs in 9.4.1 but is successful in 8.0.5.

I also have other pages for sub-users such as Suppression Management, Stats Management, Email Admin, Bulk and Single email. These all use specific sub-user keys which provide the security context. All of these worked in 8.0.5 and now none work in 9.4.1

The only difference in the code between my 8.0.5 library and my 9.4.1 library is that in each of the functions I have replaced the ‘dynamic’ code, such as
                dynamic sg = new SendGrid.SendGridAPIClient(key.Key);
                dynamic response = await sg.client.api_keys.get(queryParams: queryParams);

with
                SendGridClient client = new SendGridClient(key.Key);
                var response = await client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "api_keys", queryParams: queryParams);

nothing else has changed.

if I use a straight forward request to https://api.sendgrid.com/v3/api_keys using my sub-user master key with Telerik's API Tester, I retrieve the list correctly

if I use a straight forward request to https://api.sendgrid.com/v3/api_keys/[key_id] using my sub-user master key with Telerik's API Tester, I retrieve the requested key correctly

#### Technical details:

* sendgrid-csharp Version: master (latest commit: 9.4.1)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @andrewchilcott,

Can you please provide the code that is failing so that I may try to reproduce? It might also help if you post the code that works under version 8.0.5. Thanks!

With Best Regards,

Elmer

**Comment by andrewchilcott** [comment]
Elmer

I have created two mini projects one with the 8.0.5 code which works and the other with the 9.4.1 code which doesn’t work. I don’t really want these projects posted to on the github site as they contain key information that should not be publicly available but are necessary for the code to work. Could you please email me at andrew.chilcott@stpsolutions.com<mailto:andrew.chilcott@stpsolutions.com> with an address that I can send these projects to.

My best guess at what the problem is would be that there is a blocking call somewhere in your code (or mine) related to sub user keys.

Andrew

**Comment by thinkingserious** [comment]
No problem, please send the code to dx@sendgrid.com. Thanks!

**Comment by thinkingserious** [comment]
For future people who might have a similar issue:

The fix was to replace

```csharp
var response = await client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "api_keys", queryParams: queryParams); 
```

with

```csharp
var response = await client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "api_keys", queryParams: queryParams).ConfigureAwait(false); 
```

**Comment by mbernier** [comment]
I added this summary to the troubleshooting guide - https://github.com/sendgrid/sendgrid-csharp/pull/514

**Comment by xt0rted** [comment]
For anyone running on newer versions of .NET you can turn on a couple different Roslyn based analyzers that will trigger build errors if you're not calling `.ConfigureAwait(false)` on your async methods.

I do this in my library projects and it's helped catch issues like this a number of times. Since this issue has come up a few times now it could be useful for those with deadlocks to try it out.

The primary one I've been using is [Roslynator.Analyzers](https://www.nuget.org/packages/Roslynator.Analyzers/) which can be installed through NuGet or as [a VS plugin](https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator), but if you use the plugin then the analyzers won't run on build servers and trigger build errors like the NuGet package would.

If this is a common issue with WebForms it might be worth asking what platform they're running on in the issue template (mobile, desktop, webforms, asp.net, asp.net core, etc.).

**Comment by startechsoftwares** [comment]
Hi @thinkingserious ,

I have got into same problem, i am shooting out around (50-100) emails at a time, i want to do some post-processing on results of email status, for example, i have a field in my database called HasMailSent, i want to mark it true if it has went through or false if it hasn't. However after i read the response from the var response = await client.SendEmailAsync(msg) i gets Accepted, but how to ensure which emails has went through, or it could be that this response comes if all the emails are accepted, but my concern is i want the response about individual emails.

Please help me on this.

Thanks,
Abbas
