### ISSUE TITLE
Always get Bad Request

### ISSUE THREAD

**Issue by sepptruetsch** [sendgrid/sendgrid-csharp#469]
Hello

I'm trying to send an email using the latest version of the NuGet (v9.4.1) and the new API. Copying any of the examples on the page and from here on GitHub results in a Bad Request response. The erros variy but the reccurring theme is "Additional property $id is not allowed.". Which leaves me stumped as there is no Id added.  Which $id is the issue here? The api key works for sending emails over SMTP, so this doesn't seem to be the issue. 

#### Example error message:
```
{"errors":[
   {"message":"Additional property $id is not allowed.","field":"$id","help":null},
   {"message":"Invalid type. Expected: array, given: object.","field":"content","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content"},
   {"message":"Additional property $id is not allowed.","field":"from.$id","help":null},{"message":"Invalid type. Expected: array, given: object.","field":"personalizations","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Personalizations-Errors"}]}
```

#### Examples used
Examples from https://sendgrid.com/docs/Integrate/Code_Examples/v3_Mail/csharp.html 

```
   static async Task Execute()
        {
            var apiKey = "valid api key here";
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("test@example.com", "Example User");
            var subject = "Sending with SendGrid is Fun";
            var to = new EmailAddress("test@example.com", "Example User");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }
```

or  https://github.com/sendgrid/sendgrid-csharp/blob/master/ExampleNet45Project/Example.cs

```
            // Send a Single Email using the Mail Helper
            var from = new EmailAddress("test@example.com", "Example User");
            var subject = "Hello World from the SendGrid CSharp Library Helper!";
            var to = new EmailAddress("test@example.com", "Example User");
            var plainTextContent = "Hello, Email from the helper [SendSingleEmailAsync]!";
            var htmlContent = "<strong>Hello, Email from the helper! [SendSingleEmailAsync]</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);

```

#### Technical details:

* sendgrid-csharp Version: 9.4.1
* .NET Version: 4.6.1

**Comment by thinkingserious** [comment]
Hi @sepptruetsch,

Can you please provide the exact code you are testing? I can not reproduce the error with those samples.

Thanks!

With Best Regards,

Elmer

**Comment by sepptruetsch** [comment]
Hi @thinkingserious 

I'm using the exact code I've pasted into my original question (with differend email and api key). Using it in a new console application works great! But exactly the same sample (and api key) doesn't work in our MVC project. 

Any ideas what might be wrong? Which $id is meant by the message? What more information can I provide?

Thanks!

**Comment by thinkingserious** [comment]
In your MVC project, could you please provide the output of `msg.Serialize()`?

**Comment by sepptruetsch** [comment]
Thanks for the quick response!

This led me to the culprit. We have PreserveReferencesHandling enabled for our JSON serialization which results in the $id added in the MVC project by the JSON.Net serializer.

I'm trying to figure out how to prevent this for the SendGrid message besides adding the JSON.Net attributes to the object... Will post once I have a solution!

**Comment by thinkingserious** [comment]
Thanks for the update, I'm looking forward to the solution :)

**Comment by sepptruetsch** [comment]
Hello Elmer

With help from [StackOverflow](https://stackoverflow.com/questions/44515823/disable-json-net-preservereferenceshandling-for-single-external-type/44518216#44518216) I managed to exclude the SendGrid objects from the reference handling. The solution was to register a custom contract resolver to exclude the SendGrid classes.

Could I suggest to do this in SendGrid using the `[JsonObject]` attribute directly for the future? The SendGrid NuGet has a reference to Newtonsoft.Json already, so this should be not much trouble. Thanks!

**Comment by thinkingserious** [comment]
That sounds like a great idea @sepptruetsch. Would you be interested in submitting a PR? If not, could you provide sample code demonstrating the solution?

Thank you!

**Comment by umyhacker** [comment]
Use
var apiKey = "NAME_OF_THE_ENVIRONMENT_VARIABLE_FOR_YOUR_SENDGRID_KEY";
Instead of 
var apiKey = Environment.GetEnvironmentVariable("NAME_OF_THE_ENVIRONMENT_VARIABLE_FOR_YOUR_SENDGRID_KEY");

**Comment by thinkingserious** [comment]
Hi @umyhacker,

[Here](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#environment) is a description of the issue. Thanks!

**Comment by thinkingserious** [comment]
Hi @sepptruetsch,

If you would be interested in submitting a PR, this would be a great time since it's [Hacktoberfest](https://sendgrid.com/blog/announcing-hacktoberfest-2017) :)

With Best Regards,

Elmer
