### ISSUE TITLE
multiple emails on reply-to

### ISSUE THREAD

**Issue by ylaguna** [sendgrid/sendgrid-csharp#472]
Hello!

Is there a way to send a e-mail with multiples reply-to ?

I have read somewhere that I can do this via Headers (comma separated) on SendgridMessage.. but, when i try this

```
 string json = JsonConvert.SerializeObject(new
            {
                Email =  "test@foo.com"
            });

  msg.AddHeader("Reply-To", json);
```

I'm getting _BadRequest_ on StatusCode

**Edit:** I i'm doing this with just one, just for testing.. cuz if it was comma separeted I would just add more

**Comment by thinkingserious** [comment]
Hello @ylaguna,

This is not a supported feature. 

I have passed along your feedback to our product team.

Thank you!

Elmer
