### ISSUE TITLE
Missing EmailAddress.cs

### ISSUE THREAD

**Issue by SunilAnthony** [sendgrid/sendgrid-csharp#473]
#### Issue Summary

I keep getting an error message "Ooops , retry ninja" when running ExampleNet45ASPNetProject.  I debug and find the error message "Unauthorized".  I step into the controller and realized that I'm missing the EmailAddress.cs file.  It is looking in a local user path called "Elmer" for this file from the Models folder.

#### Steps to Reproduce

1. Open SendGrid.ASPSamples.sln
2. Restore nuget packages and install "SendGrid" nuget package "Install-Package Sendgrid -Version 9.1.1"
3. Update the API Key in webconfig.
4. Change  private string apiKey = Environment.GetEnvironmentVariable("SendGridApiKey");
5. Place a step into code in the controller.

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hi @SunilAnthony,

Can you please try upgrading to v9.4.1?

**Comment by SunilAnthony** [comment]
Just upgrade to v9.4.1 and still get the error message. When I step into the code, this is the file it looking for:
C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\Helpers\Mail\Model\EmailAddress.cs

**Comment by SunilAnthony** [comment]
![image](https://user-images.githubusercontent.com/25254958/27131645-8d9c44d8-50d9-11e7-8758-88940e766843.png)

**Comment by SunilAnthony** [comment]
![capture](https://user-images.githubusercontent.com/25254958/27133938-f4229aba-50e1-11e7-87c3-13d518f17f60.JPG)

**Comment by SunilAnthony** [comment]
I keep getting an "Unauthorized" error message now.  I got a valid API key but not sure what wrong I'm doing.

**Comment by SunilAnthony** [comment]
Ok...I got it now.  I just take the API Key and place it directly into code and it work.

**Comment by thinkingserious** [comment]
Hi @SunilAnthony,

Thanks for the follow up!

While that solution works, we do not recommend it. Credentials should not be stored directly in your app, rather they should be stored in environment variables.

With Best Regards,

Elmer

**Comment by xt0rted** [comment]
[SendGridEmailService.cs#L15](https://github.com/sendgrid/sendgrid-csharp/blob/bbe5dca489e89cf14cf6ddbe54bab17e51e1d6de/ExampleNet45ASPNetProject/SendGrid.ASPSamples/Service/SendGridEmailService.cs#L15) should be updated to use `ConfigurationManager.AppSettings["SendGridApiKey"]`. AppSettings aren't loaded into environment variables, and you most likely don't have one set for `SENDGRID_API_KEY`, which is why it's failing as-is.

**Comment by thinkingserious** [comment]
Thanks @xt0rted! I'll refer to this comment when I update the README here: https://github.com/sendgrid/sendgrid-csharp/issues/243

**Comment by B-Bilguun** [comment]
![image](https://user-images.githubusercontent.com/5731466/63313318-995a6800-c336-11e9-9f71-ce0d4ac29f0b.png)
I have an issue with Sendgrid 9.0.4 VS2019 asp.net mvc 5
