### ISSUE TITLE
How to reply to a previous email (thread)

### ISSUE THREAD

**Issue by clement911** [sendgrid/sendgrid-csharp#479]
I'm sending an email with the API and I want to send another email to the same recipient but I want this email to be in the same "thread".

After reading a bit, I believe this must be accomplished with the _Message-ID_ header somehow.
I found [this post](https://stackoverflow.com/questions/35521459/send-email-as-reply-to-thread) but I couldn't get it working.

Is there a working sample somewhere or could someone post how to do it?

* sendgrid-csharp Version: nuget package 9.1.1
* .NET Version: 4.6.1

**Comment by thinkingserious** [comment]
Hello @clement911,

To add the Message-ID header: 

```csharp
var msg = new SendGridMessage();
msg.AddHeader("Message-ID", messageID);
msg.AddHeader("In-Reply-To", string.Format("<{0}>", previousMessageId));
```

To retrieve the headers:
```csharp
var response = await client.SendEmailAsync(msg);
Console.WriteLine(response.Headers);
```

I hope that helps!

With Best Regards,

Elmer

**Comment by clement911** [comment]
I tried this but I can't get it working:

```
var msg = MailHelper.CreateSingleEmail(from, to, uniqueSubject, "Text", "Html");
var messageId = Guid.NewGuid().ToString();
msg.AddHeader("Message-ID", messageId);
var response = client.SendEmailAsync(msg).GetAwaiter().GetResult();
```

When I click 'Show original' in Gmail it always shows a broken message id:

`Message-ID: <594baf9c.d402620a.da7dc.5b2aSMTPIN_ADDED_BROKEN@mx.google.com>`

**Comment by clement911** [comment]
Also the message id in the header is different:
Something like `koivbZz_SPuguBQ5qQLIdA`

**Comment by clement911** [comment]
Ah it work once I changed the messageId to be like `<something@domain.com>`.

**Comment by thinkingserious** [comment]
Awesome, thanks for following up!
