### ISSUE TITLE
Sendgrid attachment missing when filename has utf-8 characters

### ISSUE THREAD

**Issue by Brice100** [sendgrid/sendgrid-csharp#484]
Issue Summary

When using SendGridMail 5.1.0.0 on a web application, in an attachment if a filename has especial characters, the email will be delivered without attachment.

No errors logged, just the email arriving without the attachment.

Steps to Reproduce

For example:
myMessage.AddAttachment(file, "test… .pdf"); // won't work, "…" is ellipsis
myMessage.AddAttachment(file, "test... .pdf"); // will work, "..." is three separate dots.

Technical details:

sendgrid-csharp Version: 5.1.0.0
.NET Version: 4.5.1

Is there anything to do to make it works? I don't want to update SendGrid since much effort to do.
Thanks.

**Comment by thinkingserious** [comment]
Hello @Brice100,

I am not aware of any fix to make this work. 

Since we do not support that version of this SDK anymore, I will not be able to debug it. 

If you choose to upgrade to the latest version of the SDK, I will be happy to help. 

With Best Regards,

Elmer

**Comment by Brice100** [comment]
@thinkingserious , Thanks for your support.

**Comment by thinkingserious** [comment]
Here is how to handle attachments with the latest version of this SDK: https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#attachments
