### ISSUE TITLE
Retry Options not available

### ISSUE THREAD

**Issue by vinoddamupatil** [sendgrid/sendgrid-csharp#491]
#### Issue Summary
Retry Options not available

Sendgrid  should provide retry options which client can configure as per there needs or can provide default retries

#### Steps to Reproduce
NA

#### Technical details:
Retry options.

Thanks,
Vinod Patil

**Comment by thinkingserious** [comment]
Hi @vinoddamupatil,

Thanks for the suggestion! I've added this to our backlog.

Comments on this issue and/or pull requests will help it gain priority.

With Best Regards,

Elmer

**Comment by dylan-asos** [comment]
@thinkingserious  - would you consider taking a dependency on the Polly package? https://github.com/App-vNext/Polly. Would make this feature pretty simple to implement.

**Comment by thinkingserious** [comment]
Hi @dylan-asos,

That package looks solid and does not introduce any conflicting dependencies. A PR would be amazing :)

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Please see [here](https://github.com/sendgrid/sendgrid-csharp/pull/509).

**Comment by vinoddamupatil** [comment]
Thanks
