### ISSUE TITLE
Error: The project could not be loaded (when opening in Visual Studio 2010)

### ISSUE THREAD

**Issue by danielzook** [sendgrid/sendgrid-csharp#492]
#### Issue Summary

I downloaded the C# library and opened it in Visual Studio 2010.  All of the project files failed to load.  They show "The project could not be loaded" in the solution explorer.

![image](https://user-images.githubusercontent.com/30128768/28138801-079536da-6720-11e7-823b-66cd65709bb0.png)

If I try to reload one an error message appears: C:\Users\zookdj\Desktop\sendgrid-csharp-master\src\SendGrid\SendGrid.csproj : error  : Value cannot be null.

Parameter name: url

I was planning to sign-up for one of the paid plans, but if I can't get this to work then I'll look for a different provider.

Thanks for your help.

#### Steps to Reproduce

1. Expand the zip file
2. Open the solution file in Visual Studio

#### Technical details:
Visual Studio 2010 with all updates
.NET Version: 4.5.2
sendgrid-csharp Version: master (Just downloaded yesterday)

**Comment by thinkingserious** [comment]
Hello @danielzook,

Could you please tell me a bit about your use case?

Are you trying to open the source files because you need to make some customizations unique to your project? If so, what functionality is missing? Or are you attempting to make a PR?

With Best Regards,

Elmer

**Comment by danielzook** [comment]
I need to open the C# source files in Visual Studio 2010 in order to load the solution into Dynamics AX 2012 R2, which will allow me to call those classes from within AX.
 
Thanks,
 
djz

**Comment by thinkingserious** [comment]
Thanks for the clarification @danielzook,

Could you please try [this version](https://github.com/sendgrid/sendgrid-csharp/tree/bc34d77d449e46670520270f8d8b08ddbf585bca)? Thanks!

With Best Regards,

Elmer

**Comment by danielzook** [comment]
Thanks for the suggestion.  Unfortunately, when I open the solution in Visual Studio 2010, this error message appears:
 
 
“SendGrid.xproj cannot be opened because its project type (.xproj) is not supported by this version of the application.”
 
Does this mean that the sendgrid-csharp GitHub project has a minimum Visual Studio requirement?  If so, please add that to the list of requirements in the ReadMe.
 
Thanks,
 
djz

**Comment by danielzook** [comment]
I figured out a work around.  AX supports using .NET objects, and so I figured out how to call SendGrid’s webservice directly.  It is going to be a bit more work, but I just wanted to let you know that I have a work around, and so you don’t need so spend more time on the below problem if you don’t want to.
 
Thanks,
 
djz
 
From: Daniel J. Zook [mailto:daniel.zook@lehmans.com] 
Sent: Friday, July 14, 2017 8:51 AM
To: 'sendgrid/sendgrid-csharp' <reply@reply.github.com>; 'sendgrid/sendgrid-csharp' <sendgrid-csharp@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [sendgrid/sendgrid-csharp] Error: The project could not be loaded (when opening in Visual Studio 2010) (#492)
 
Thanks for the suggestion.  Unfortunately, when I open the solution in Visual Studio 2010, this error message appears:
 
 
“SendGrid.xproj cannot be opened because its project type (.xproj) is not supported by this version of the application.”
 
Does this mean that the sendgrid-csharp GitHub project has a minimum Visual Studio requirement?  If so, please add that to the list of requirements in the ReadMe.
 
Thanks,
 
djz

**Comment by thinkingserious** [comment]
Thanks @danielzook,

That's great feedback. I've updated our [CONTRIBUTING guidelines](https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#improvements-to-the-codebase) to reflect the minimum Visual Studio requirement.

Otherwise, you should be able to just use the .dll's directly through Nuget.

Thanks for circling back to share your workaround :)

With Best Regards,

Elmer
