### ISSUE TITLE
VSTS build error: Index source information could not be retrieved.

### ISSUE THREAD

**Issue by murraybiscuit** [sendgrid/sendgrid-csharp#494]
#### Issue Summary

I've got a C# MVC 5 app with Sendgrid 9.5.0 installed via nuget. Build is happening online via VSTS (Visual Studio 2017 build agent). Everything compiles ok, but the build throws an error getting symbol indexes from Sendgrid.pdb. Error as follows:

`Indexed source information could not be retrieved from 'd:\a\3\s\<ProjectName>\bin\SendGrid.pdb'. Symbol indexes could not be retrieved.`

Running symchk I get the same error as the OP in this thread, so perhaps it's the same cause.
https://github.com/JoshClose/CsvHelper/issues/535

#### Steps to Reproduce

1. Add deps to MVC project, build and publish symbols on TFS
2. Project compiles but build throws error.

Sendgrid HTTP Client doesn't throw the same error for me.

#### Technical details:

* sendgrid-csharp Version: master (latest commit: 9.5.0)
* .NET Version: 4.7

**Comment by thinkingserious** [comment]
Thanks for the heads up @murraybiscuit along with the link to the fix. I have added this to our backlog.

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

**Comment by murraybiscuit** [comment]
@thinkingserious thanks for the quick response. It's not a blocker my side so backlog is fine. Just putting it on the board.

**Comment by codeBoarder** [comment]
+1

**Comment by akdurmus** [comment]
having the same problem. 
Just notice one thing that File version still stays as 9.4.1.0 in version 9.5.0. Not sure whether this might cause the problem or not.

**Comment by thinkingserious** [comment]
Ah, thanks for the tip @akdurmus. I'll let you know if this was the issue.

**Comment by Niladri24dutta** [comment]
I can't say its similar but i am having a strange issue like this in VSTS Azure build definition . The build fails every time the "dotnet restore" command runs in the VSTS build definition. The error message is something like below - 
"Unable to resolve Sendgrid(>=9.5.0) for .NETCoreApp1.0" .
Not sure if this is an issue with Nuget cache or VSTS build definition because all other nuget packages are restored perfectly. The strange thing is that in my local system i am able to build the solution perfectly with .NET Core 1.0. The issue only occurs in VSTS build during dotnet restore. Any help would be great.

**Comment by thinkingserious** [comment]
[This issue](https://github.com/moq/moq4/issues/428) makes me think it's definitely a pdb issue. I'm going to push a new release soon with an updated pdb.

**Comment by thinkingserious** [comment]
I'm hoping v9.5.1 fixes this. Please let me know how it goes, thanks! (might take a few minutes for the release to appear on Nuget)

**Comment by murraybiscuit** [comment]
I've tested and it's giving the same error on VSTS. [I've done some digging and it seems that netcore defaults to portable pdb format which isn't readable by the 4.5 framwework](https://github.com/dotnet/sdk/issues/1238). It is readable by VS Code IDE and .net framework > 4.7.1 apparently. So DebuggerType on .net 4.5 needs to be set to "full" as the workaround. 

[I'm trying to set a conditional `DebugType` prop](https://msdn.microsoft.com/en-us/library/ms171481.aspx) on the SendGrid csproj file to try to force the 4.5 compile to use `full` debug. Will let you know if I have any success...

**Comment by murraybiscuit** [comment]
@Niladri24dutta I saw somebody else mention a versioning issue with 9.5.0 - I'm not using the netcore package - is it possible that your local package has been cached or not updated and the TFS one is trying to compile the newer (broken) one? Perhaps try manually deleting or uninstalling the nuget package locally, do a nuget auto restore / reinstall to ensure you have the latest version locally and then try rebuilding. The issue in this thread isn't about package restore, it's about debug symbols on the .net452 target specifically.

**Comment by Niladri24dutta** [comment]
@murraybiscuit Yes i agree that it might be a VSTS issue with Nuget restore, because it's not able to resolve another similar package (which I used before Sendgrid) which was newly added to project.json. But the strange thing is that it's restoring the building the project fine in my local environment but not in VSTS dotnet restore

**Comment by murraybiscuit** [comment]
Sure. So to replicate the issue, I’m saying try kill your local package and let nuget restore it. If you get a nuget resore error locally, then you know the problem lies with the latest Sendgrid nuget package. Alternatively upgrade your sendgrid nuget package locally to 9.5.1 (this will clear the local cached version) and try rebuild.

**Comment by mjfaga** [comment]
I installed 9.5.1 fresh into my project and started having this same issue as well.

**Comment by murraybiscuit** [comment]
@thinkingserious I've updated code in a fork ([diff here](https://github.com/sendgrid/sendgrid-csharp/compare/master...murraybiscuit:iss494)). Tests all run fine locally. Build on VSTS is no longer throwing error for me either. Not sure if I need to update version numbers or if you need to do that...

**Comment by thinkingserious** [comment]
That's awesome @murraybiscuit! I'll try that and push up 9.5.2 for testing.

**Comment by thinkingserious** [comment]
@murraybiscuit,

Just pushed up your fix to Nuget as version 9.5.2. Please let me know how it goes. Also, please fill out [this form]( https://dx.sendgrid.com/swag) so that we can send you some swag :)

With Best Regards,

Elmer

**Comment by mjfaga** [comment]
Verified in my latest build after updating that this fixed worked! Thanks!

**Comment by murraybiscuit** [comment]
@thinkingserious Thanks for the quick turnaround. Builds are fixed for me. @Niladri24dutta - have you tried a rebuild with the new version?

**Comment by Niladri24dutta** [comment]
Ok sure I will try at my end with this current version and let you know.
