### ISSUE TITLE
Sendgrid.pdb corrupted in 9.5.0 release

### ISSUE THREAD

**Issue by epot** [sendgrid/sendgrid-csharp#495]
I am having troubling publishing the symbols since I updated to 9.5.0. You can see that there is an issue with the pdb file by using tool from Debugging Tools:

    Dbh.exe SendGrid.pdb dump

That returns:

    “error 0x2 loading SendGrid.pdb.”

**Comment by thinkingserious** [comment]
Thanks for the heads up! Please follow progress on this issue here: https://github.com/sendgrid/sendgrid-csharp/issues/494
