### ISSUE TITLE
BadRequest when sending BCC

### ISSUE THREAD

**Issue by kmthomas907** [sendgrid/sendgrid-csharp#498]
The current version of the SG C# API (v9.5) will throw a BadRequest when calling SendEmailAsyc without a To address, even though it has a BCC address.  If I add a To address, the email sends fine.  We have scenarios where a To address isn't present -- for example, a customer can optionally request a transaction receipt, but a person in our accounting dept always wants a BCC copy of the email regardless whether the customer requested a receipt or not.  This scenario works fine when using the regular .NET SmtpClient/MailMessage classes.  Can this be fixed in the SG library?

Thanks,
-Kent Thomas

**Comment by thinkingserious** [comment]
Hello Kent!

Cool last name ;)

Our API does not support excluding a to address. My suggestion would be to use some generic to address that you filter out client side. You can find all of the required parameters [here](https://sendgrid.com/docs/API_Reference/api_v3.html).

With Best Regards,

Elmer

**Comment by kmthomas907** [comment]
Hi Elmer,
Thanks for your quick reply.  We do have a workaround, but just thought
that handling is inconsistent, since sending emails direct through
smtp.sendgrid.net allows this with no problem.

-Kent

**Comment by thinkingserious** [comment]
Thanks for the follow up @kmthomas907! I will send your feedback over to our product team.
