### ISSUE TITLE
Email Not Sent When Non-Unique From, To, and CC Used

### ISSUE THREAD

**Issue by eriksendc** [sendgrid/sendgrid-csharp#503]
#### Issue Summary

We have a help form at https://getyourpet.com/help-request. When a user submits the form, we send an email to ourselves. To make things less error-prone, we want a "Reply All" on the email received to reply to open a new email that is To the user who submitted the request and CC our support email address (support@getyourpet.com). Here's the code that DOES NOT work:

    var msg = new SendGridMessage()
    {
        From = new EmailAddress("support@getyourpet.com"),
        Subject = subject,
        PlainTextContent = message,
        ReplyTo = new EmailAddress(replyToEmailAddress, replyToName)
    };

    msg.AddTo(new EmailAddress("support@getyourpet.com"));
    msg.AddCc(new EmailAddress("support@getyourpet.com"));

    var client = new SendGridClient(_messageSenderOptions.SendGridApiKey);

    await client.SendEmailAsync(msg);

Note that near the bottom of Issue 388 (https://github.com/sendgrid/sendgrid-csharp/issues/388) you'll see that someone else already reported this issue with uniqueness of the email addresses.

#### Steps to Reproduce

1. Execute the above code.

Expected: An email is received at the support@getyourpet.com email, and a reply to that email will auto populate the To field of the resulting new email with the replyToEmailAddress and support@getyourpet.com will be CCd.

Actual: No email is ever received.

#### Technical details:

* sendgrid-csharp Version: 9.5.2
* .NET Version: 4.6.1

**Comment by thinkingserious** [comment]
Hello @eriksendc,

We do not have any plans to allow for duplicate emails at the API level, but I'll forward your use case to our product team.

There is [this thread](https://github.com/sendgrid/sendgrid-csharp/issues/425) on a solution at the library level that might be useful to you.

With Best Regards,

Elmer

**Comment by kinetiq** [comment]
Just wanted to weigh in and say that you should at least be throwing an exception here. Failing silently, without even a record in the Activity log, is beyond frustrating. 

As someone who is dealing with this issue, it definitely makes me trust the API less. I wonder what other delights await.

**Comment by thinkingserious** [comment]
HI @kinetiq,

Thanks for taking the time to express your frustration. 

I think we have a good fix in the works. Please follow the solution on [this thread](https://github.com/sendgrid/sendgrid-csharp/issues/425). We hope to have the fix for this deployed soon. I have added your vote to the issue to help increase it's priority in our backlog.

With Best Regards,

Elmer
