### ISSUE TITLE
Messages appear to be dropped by Sendgrid even after getting 2XX response from API

### ISSUE THREAD

**Issue by plaisted** [sendgrid/sendgrid-csharp#506]
#### Issue Summary

We are sending messages with Sendgrid that have attachments. We check the returned response from `SendEmailAsync()` to ensure the result was successful. Looking at the logs we are definitely getting a "Ok" or "Accepted" from the Sendgrid library as the "SendGridSuccess" is logged and no exception was thrown. See the pertinent code below:

```
var response = await client.SendEmailAsync(msg);
if (response.StatusCode != System.Net.HttpStatusCode.OK && response.StatusCode != System.Net.HttpStatusCode.Accepted)
{
    var result = await response.Body.ReadAsStringAsync();
    var headers = response.Headers.ToString();
    _logger.LogError("[{EventName:l}] {File} send error: {Result} - {@Headers).", "SendGridError", fileName, result, headers);
    throw new EmailSendException("Msg send failed: " + result);
}
_logger.LogInformation("[{EventName:l}] {File} sent to {@Emails}.", "SendGridSuccess", fileName, config.ToEmails);
```
Based on the Sendgrid API (200 OK or 202 Accepted) should mean success and message was queued property. However users report they never received the emails and looking at Sendgrid they do not appear in the message history. Each message is tagged with a GUID arg before sending so it to see that the particular GUID does not exist in sendgrid logs. We also BCC an internal email and did not receive them either. This has been documented to have occurred 3 times now (out of probably a few thousand for this application) although it could have been more and not reported.

How can I go about troubleshooting this? Losing emails / silently failing is not acceptable in our use case.

#### Steps to Reproduce

I can not consistently reproduce this. It happens very sporadically.

#### Technical details:

* sendgrid-csharp Version: 9.4.1
* .NET Version: 4.6.1

**Comment by thinkingserious** [comment]
Hello @plaisted,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
