### ISSUE TITLE
Updating to .NETCore 2 fails

### ISSUE THREAD

**Issue by CharlBest** [sendgrid/sendgrid-csharp#507]
#### Issue Summary

When I updated to .net core 2 I'm getting these errors.
![image](https://user-images.githubusercontent.com/6147400/29315220-4da66ec0-81c2-11e7-8f96-f08921cacd30.png)

#### Steps to Reproduce

Update to .net core 2

#### Technical details:

* SendGrid.NetCore 1.0.0-rtm-00002
* .NETCore 2.0

**Comment by CharlBest** [comment]
This is not SendGrid's problem. The issue is with System.Net.Mail I think

**Comment by thinkingserious** [comment]
Thanks for the update @CharlBest!

**Comment by CharlBest** [comment]
Hi @thinkingserious I opened an issue here https://github.com/dotnet/corefx/issues/23246 and got the response that in .net core 2 System.Net.Mail is included and don't need to be referenced. I'm not sure how removing it would just make it work if its not working now.

**Comment by Niladri24dutta** [comment]
@CharlBest  can you change your code like below and try 
`myMessage.From = new EmailAddress("help@xyz.com","help");` 

`myMessage.From` accepts an Object of type `EmailAddress `

**Comment by CharlBest** [comment]
Hi @Niladri24dutta thanks for the reply. I found the problem.
So I had installed this: 
![image](https://user-images.githubusercontent.com/6147400/29412594-c0453356-8359-11e7-918e-c901d7b02dac.png)
Rather than the normal Sendgrid nuget package.

Man I'm stupid. haha. Thanks for your time.

**Comment by thinkingserious** [comment]
Thanks for following up @CharlBest!

Thanks to @Niladri24dutta for jumping in and helping!
