### ISSUE TITLE
dynamic response = await sg.SendEmailAsync(anEmail); // hangs waiting for response

### ISSUE THREAD

**Issue by jrkcoder** [sendgrid/sendgrid-csharp#512]
#### Issue Summary

A few days ago, around Aug 25, 2017, I updated to all newest SendGrid code.  First found out I had to modify my source code (not happy about that -- oh well).  I follow example.  I'm running C#, .NET Version: 4.5.2.

#### Steps to Reproduce

My code is this:
```csharp
// =============
static async Task Execute(MailAddress fromEmail, MailAddress toEmail, string subject, string inHtmlContent, string inTextContent) {
            SendGrid.Helpers.Mail.SendGridMessage anEmail = MailHelper.CreateSingleEmail(new EmailAddress(fromEmail.Address,fromEmail.DisplayName), new EmailAddress(toEmail.Address, toEmail.DisplayName), subject, inTextContent, inHtmlContent);
            bool sendMail = false;
            if (inTextContent.Length > 0) {
                sendMail = true;
            }
            if (inHtmlContent.Length > 0) {
                sendMail = true;
            }
            if (sendMail) {
                dynamic sg = new SendGridClient(xxxxxxxxxxx);
                dynamic response = await sg.SendEmailAsync(anEmail); // get hang here waiting, seemingly forever
                string resp1 = response.StatusCode.ToString();
                string resp2 = response.Body.ReadAsStringAsync().Result.ToString();
                string resp3 = response.Headers.ToString();
                int x = 1; // so I can break here to see response
            }
        }
// =============
```

Above code sent emails fine, but UI was blocked waiting for response.

I later modified my code so I did not wait for response.  Emails would send fine.

Yesterday I tried to send.  Emails would not send.  Later, with same code, emails would send.

I think when response hangs you have tasks accumulate and eventually take your server down.
#### Technical details:

* I am running
SendGrid - Web API v3 v9.9.0
SendGrid.CSharp.HTTP.Client v3.3.0
SendGrid.Net40 v5.1.0
SendGrid.SmtpApi v1.3.3
 .NET Version: 4.5.2
Building on Microsoft Visual Studio 2017
I note that this looks very much like a problem you had in older code about a year ago:
https://github.com/sendgrid/sendgrid-csharp/issues/235
https://github.com/sendgrid/sendgrid-csharp/issues/453

**Comment by thinkingserious** [comment]
Hello @jrkcoder,

It looks like you are still using a mix of older code (we no longer use dynamic). Currently, you only need `SendGrid - Web API v3 v9.9.0` and here is the [documentation on how to use the current library](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md).

Please give it a try and let me know if you still run into trouble.

With Best Regards,

Elmer

**Comment by jrkcoder** [comment]
I look at your documentation link and with examples.  Only change I can see to make is change "dynamic" to "var".  I'm not sure what else you are saying.  I change to "var" and still get hang waiting for response.

I don't know what other "old" code you think I'm using.

**Comment by thinkingserious** [comment]
@jrkcoder,

Could you please try replacing:

`dynamic response = await sg.SendEmailAsync(anEmail);`

with

`var response = await sg.SendEmailAsync(anEmail).Result;`

It looks like be within an ASP.NET project, in which case this [example](https://github.com/sendgrid/sendgrid-csharp/tree/master/ExampleNet45ASPNetProject) might be useful.

With Best Regards,

Elmer

**Comment by jrkcoder** [comment]
Seems like your example is for ASP.  I'm using MVC.

I try to use
var response = sg.SendEmailAsync(anEmail).Result;
but Visual Studio won't let me -- get build error
'Response' does not contain a definition for 'GetAwaiter' and the best extension method overload 'AwaitExtensions.GetAwaiter(Task)' requires a receiver of type 'Task'

But something else came to mind.

If I do
SendGridMessage email2 = new SendGridMessage();
I get a build error from Visual Studio telling me there is ambiguity between
SendGrid.Helpers.Mail.SendGridMessage and SendGrid.SendGridMessage.
To get around that I put the full qualifier SendGrid.Helpers.Mail.
Why do I get this ambiguity?  Do I still have some old piece of SendGrid in my library that NuGet didn't remove?

I was following example in
https://github.com/sendgrid/sendgrid-csharp#quick_start
which uses MailHelper.CreateSingleEmail which gives SendGrid.Helpers.Mail.SendGridMessage.

**Comment by thinkingserious** [comment]
Ah, you might be on to something with the ambiguity. 

Could you please remove the following from your project:
SendGrid.CSharp.HTTP.Client v3.3.0
SendGrid.Net40 v5.1.0
SendGrid.SmtpApi v1.3.3

**Comment by jrkcoder** [comment]
I uninstalled all the SendGrid items I could find -- four packages.  Then searched for anything SendGrid -- removed remaining dlls in bin and debug and some other things.  Reinstalled SendGrid version 9.9.0 only.
This builds fine.  No longer have SendGridMessage email2 = new SendGridMessage(); ambiguity.

Still hang at
var response = await sg.SendEmailAsync(anEmail);
.

**Comment by jrkcoder** [comment]
With this last change, emails are not sent.  Emails were sending fine before, but UI was stuck.

**Comment by jrkcoder** [comment]
I can modify my code so that it does not wait for a response.  When I tried this before, SendGrid sent emails fine for a bit, then not.

**Comment by thinkingserious** [comment]
@jrkcoder,

Seems this might be your solution: https://github.com/sendgrid/sendgrid-csharp/issues/462

Please let me know. Thanks!

**Comment by jrkcoder** [comment]
It will take me some time to digest this, I hope today.  It looks nothing like any example I could find for usage.

**Comment by jrkcoder** [comment]
I use same call, just put
.ConfigureAwait(false)
at end. 
So now it is
SendGrid.Response response = await sg.SendEmailAsync(anEmail).ConfigureAwait(false); 
It works!
Looking at 
response.Headers.ToString()
I get
nX-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
.  I'm now trying to understand if I have a security issue with my code.  I don't think so.
It's taken me some days to get to this point.
I didn't know I was supposed to use only SendGrid, not the other 3 libraries.
I knew nothing about
.ConfigureAwait(false)
.
How should I have known?

**Comment by thinkingserious** [comment]
Hello @jrkcoder,

Thanks for following up!

The `X-No-CORS-Reason` header is just a notice that we do not allow CORS. It does not mean that you have a security issue with your code.

Here are our [installation instructions](https://github.com/sendgrid/sendgrid-csharp#install-package) and we have now [added a section](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#ui-requests-are-failing) to help others who run into this issue.

Please let me know if you have any other suggestions to make this process smoother.

With Best Regards,

Elmer

**Comment by jrkcoder** [comment]
What happens in SendGrid server when ConfigureAwait(false) is not used?  Is it stuck tying up resources?

**Comment by thinkingserious** [comment]
HI @jrkcoder,

No, our resources would not be tied us, the issue is on the client side. [This post](https://stackoverflow.com/questions/13489065/best-practice-to-call-configureawait-for-all-server-side-code/13494570#13494570) has a great explanation.

With Best Regards,

Elmer

**Comment by Korijn** [comment]
@jrkcoder If you are using only one function I recommend implementing the rest api call yourself instead of using the client package. I had the same issue and other side effects. My own HTTP call was super easy to implement and mega-reliable. It wad an effective way to avoid getting to grips with all the weird tricks this client package pulls with synchronization context configuration.

**Comment by startechsoftwares** [comment]
Hi @thinkingserious ,

I have got into same problem, i am shooting out around (50-100) emails at a time, i want to do some post-processing on results of email status, for example, i have a field in my database called HasMailSent, i want to mark it true if it has went through or false if it hasn't. However after i read the response from the var response = await client.SendEmailAsync(msg) i gets Accepted, but how to ensure which emails has went through, or it could be that this response comes if all the emails are accepted, but my concern is i want the response about individual emails.

Please help me on this.

Thanks,
Abbas
