### ISSUE TITLE
Sending different mail content to same recipient does not work well

### ISSUE THREAD

**Issue by SRossi77** [sendgrid/sendgrid-csharp#520]
#### Issue Summary

I am using a send grid method to send multiple files to same recipient by using substitutions tags.
I need this to work because sometimes i need to send multiple emails with different content to same recipient.

I am using Rest Request: 
 IRestResponse response = new RestClient(SendGridClientUrl).Execute(request);

Request Object:( Custom Request for send grid )
            EmailAddress fromMail = new EmailAddress("no-reply@test.com", "");
            List<EmailAddress> emails = new List<EmailAddress>()
            {
                new EmailAddress("skhatiwada@test.com","Sujit Tester"),
                new EmailAddress("skhatiwada@test.com","Sujit Tester")
            };
            var subjects = new List<string> { "Test for -name-.", "Test for -name-."};
            var plainTextContent = "Hello -name-. We are ready to use -Sample-.";
            var htmlContent = "Hello -name-. We are ready to use -Sample-.";
            var substitutions = new List<Dictionary<string, string>>
            {
                new Dictionary<string, string>() {{"-name-", "Sujit Tester"},{"-Sample-","If you are Tester then, 
                 this test is working fine." } },
                new Dictionary<string, string>() {{"-name-", "Sujit Developer"}, { "-Sample-", "If you are 
                 Developer then, this test is working fine." } }
             };
            SendGridMessage sendGridMessage = MailHelper.CreateMultipleEmailsToMultipleRecipients(
                                                                      fromMail,
                                                                      emails,
                                                                      subjects,
                                                                      plainTextContent,
                                                                      htmlContent,
                                                                      substitutions);
           SendBulkEmail(sendGridMessage);

#### Steps to Reproduce

The problem here is that, i am not able to get both the mails under  a single recipient in my outlook mail. At times i get the first substituted mail and other times i get the second substituted mail. I tried this and some cases it sent both mails with different mail contents as well, but this is not trustworthy.

#### Technical details:

* sendgrid-csharp : [v3/Send ]
* Platform (ASP.NET)
* .NET Version: 4.5

**Comment by Niladri24dutta** [comment]
What is the function of `SendBulkEmail(sendGridMessage);` here ? it is a custom method?as per the V3 documentation we need to use `var client = new SendGridClient(apiKey);` to send the email . Take a look at this link 
[Use case for sending email](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#kitchen-sink---an-example-with-all-settings-used)

**Comment by thinkingserious** [comment]
Thanks for jumping in and trying to help @Niladri24dutta!

@SRossi77,

Have you reviewed our [templating use case](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional_templates)? It's very similar to what you are trying to do.

Also, duplicate emails are not allowed. That may a source of error also.

With Best Regards,

Elmer
