### ISSUE TITLE
Email address formatting issue in SendGridMessage.AddTo method

### ISSUE THREAD

**Issue by anantbara** [sendgrid/sendgrid-csharp#524]
I'm using SendGrid API in a ChatBot application powered by Microsoft Botframework. When this project is deployed in Azure, SendGridMessage.AddTo method adding some absurd characters. The serialized mail is shown below-

`{
	"from": {
		"name": "XYZ Care Team",
		"email": "xyz@abc.com"
	},
	"personalizations": [
		{
			"to": [
				{
					"email": "<a href=\"mailto:anant.rajee@abc.com\">anant.rajee@abc.com</a>"
				}
			],
			"subject": "Appointment confirmed"
		}
	],
	"content": [
		{
			"type": "text/plain",
			"value": "Hi anant,\n\nCongrats, Your appointment is confirmed. Please find the appointment details below.\n\n\t Name : anant\n\n\t Contact : 1122334455\n\n\t Appointment Time : 10/6/2017 2:00:00 PM\n\n\t Appointment number : 1064455\n\n\t Purpose : general\n\nWe are happy to serve you. Have a nice day."
		}
	],
	"reply_to": {
		"email": "xyz@abc.com"
	}
}`

This is the code I have used:
`var apiKey = WebConfigurationManager.AppSettings["SENDGRID_APIKEY"];

                                var client = new SendGridClient(apiKey);

                                SendGridMessage mail = SendGridEmailService.ConfigureEmail();

                                mail.AddTo(new EmailAddress("anant.rajee@abc.com"));
                                mail.SetReplyTo(new EmailAddress("xyz@abc.com"));
                                mail.SetSubject("Appointment confirmed");
                                string bodyText = $"Hi {state.Name}," +
                                    $"\n\nCongrats, Your appointment is confirmed. Please find the appointment details below." +
                                    $"\n\n\t Name : {state.Name}" +
                                    $"\n\n\t Contact : {state.ContactNumber}" +
                                    $"\n\n\t Appointment Time : {state.Date}" +
                                    $"\n\n\t Appointment number : {appointment_id}" +
                                    $"\n\n\t Purpose : {state.Purpose}" +
                                    $"\n\nWe are happy to serve you. Have a nice day.";
                                mail.AddContent(MimeType.Text, bodyText);
                                client.SendEmailAsync(mail).Wait();`

I am using the SendGrid version 9.9.0. 
Note : This is working fine locally. It is creating problem when we deploy this app in Azure.

**Comment by Niladri24dutta** [comment]
Can you use the below line of code instead of  
`SendGridMessage mail = SendGridEmailService.ConfigureEmail();`

Replace the above line with `SendGridMessage mail = new SendGridMessage();` and then try again. Please note that you are using `client.SendEmailAsync(mail).Wait();` which will synchronously block until the task completes. So the current thread is literally blocked waiting for the task to complete. Hence it's better not to block the sync task and use `await client.SendEmailAsync(mail)`  to avoid deadlock.

**Comment by anantbara** [comment]
Thanks Niladri for the reply.
Still getting the same error. It is working fine while running this app locally but still getting formatting issue after deploying it to Azure..

**Comment by Niladri24dutta** [comment]
@anantbara  this looks like a formatting issue with Azure where your mail addresses are by default converted to hyperlink `mailto:test@abc.com`

**Comment by thinkingserious** [comment]
Hello @anantbara,

My advice is that you consult with Azure on this one. There is nothing on SendGrid's side that would convert your email address to a hyperlink.

With Best Regards,

Elmer
