### ISSUE TITLE
HELP: sending an calendar invite

### ISSUE THREAD

**Issue by hepple** [sendgrid/sendgrid-csharp#525]
Hi, I'm trying to send an calendar invite using c# but cannot find any docs to match?

I need to send the email so it shows up as an invite not an attachment.

**Comment by thinkingserious** [comment]
Hello @hepple,

Please follow this [example](https://github.com/sendgrid/sendgrid-python/issues/345#issue-260155034), and also [pass in the `type`](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L995), which is likely "text/calendar". 

With Best Regards,

Elmer

**Comment by amendoza4** [comment]
@thinkingserious I do not understand how the link you specified relates to the issue. The problem was to send a **calendar invite** . What you linked was to get the statistics. BTW, I am having the same problem, I have found numerous solution on how to send invites but all of it was to send it as attachment. I wanted to send it as an **actual** invite.

**Comment by asaeed** [comment]
@thinkingserious - the example link seems to be something unrelated. is there an example of sending an email that shows up as a calendar invite instead of attachment?

**Comment by amendoza4** [comment]
Hi, @asaeed . I have solved this problem. The thing is, you can send either a calendar appointment or a PlainTextContent/HtmlContent.

To send an email appointment as an actual appointment and not as an attachment:
`msg.AddContent("text/calendar", calendarContent);`
![2019-09-16_9-02-55](https://user-images.githubusercontent.com/50126233/64930250-a39e5200-d861-11e9-969a-5ab45316fe38.jpg)

**Comment by amendoza4** [comment]
Hello @thinkingserious . I tried sending a calendar appointment using the solution above AND a PlainTextContent/HtmlContent at the SAME TIME. However, I only received the email as PlainTextContent/HtmlContent and there is no calendar appointment. Is it a problem on my implementation or we really cannot do this at the same time?
`msg.AddContent("text/calendar", calendarContent);`
`msg.PlainTextContent = emailMessage.TextContent;`
`msg.HtmlContent = emailMessage.HtmlContent;`

**Comment by grpkarunathilaka** [comment]
@amendoza4 do you mind to share the format/content of the calendarContent variable. Is it plain text or VCALENDAR?
