### ISSUE TITLE
Campaign Status

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#526]
When making a HTTP GET request to `/campaigns/{campaign_id}`, we get a JSON string that contains, among other things, a property called `status`. The [documentation](https://sendgrid.com/docs/API_Reference/api_v3.html) simply says that this property represents "The status of your campaign" but does not describe the possible values.

From experience, I know that some of the possible values are `draft`, `scheduled` and `sent` but I was wondering if all possible values were known and/or documented somewhere?

Someone recently [reported](https://github.com/Jericho/StrongGrid/issues/194) a value I had never encountered before: `In Progress`. This particular value is surprising to me because I don't remember ever seeing a value for a property with a defined set of possible values returned from the SendGrid API with some upper case letters and with a space.

**Comment by thinkingserious** [comment]
@mbernier

**Comment by Duikmeester** [comment]
The campaign page shows the following filters: Sent, Draft, In Progress, Canceled, Scheduled.

**Comment by Jericho** [comment]
Thank you for this information but where did you find it? I looked [here](https://sendgrid.api-docs.io/v3.0/campaigns-api/retrieve-a-single-campaign), [here](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/campaigns.html), [here](https://sendgrid.com/docs/Classroom/Basics/Marketing_Campaigns/marketing_campaigns_faqs.html) and even [googled it](https://www.google.ca/search?q=sendgrid+campaign+status) but I couldn't find this information.

**Comment by Duikmeester** [comment]
https://sendgrid.com/marketing_campaigns/ui/campaigns
Filter By Status
- All
- Sent
- Draft
- In Progress
- Canceled
- Scheduled

**Comment by Jericho** [comment]
Thank you
