### ISSUE TITLE
Auto Generate Plain Text Content from HTML

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#536]
We require both HTML and Plain Text content for improved deliverability. In some cases, only HTML may be available. We need a function that automatically converts a given HTML string to the Plain Text equivalent.

**Comment by dfu3** [comment]
Could you give a brief input/output example of the content supplied and desired please?

**Comment by thinkingserious** [comment]
Hi @dfu3! 

Input:
<strong>Hello Email</strong>! Please visit our new website <a href="www.example.com">here</a>.

Possible Output (Markdown):
**Hello Email**! Please visit our new website [here](www.example.com)

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
See #643
