### ISSUE TITLE
Weblink tag not rendering

### ISSUE THREAD

**Issue by barryjmay** [sendgrid/sendgrid-csharp#549]
#### Issue Summary

I'm using this app to send emails to sendgrid via smtp. My email list is stored in a local database. My emails are being stored as an embedded resource within the app. When they are sent the weblink tag is not rendering correctly.

The tag appears a s follows in the html: 
<td valign="top" style="font-size: 12px; color: #999999; font-family: Arial, Helvetica, sans-serif; line-height:22px; padding: 0 10px 0;" class="center">
                                                                If you are having trouble viewing this email, please <a href="[Weblink]" style="text-decoration: underline; color: #00acec;" target="_blank" >click here</a> 

But renders as follows: 

If you are having trouble viewing this email, please [[Weblink]]click here

Any ideas of how to resolve?

#### Technical details:

* Platform (ASP.NET)
* .NET Version: 4.5.2

**Comment by Niladri24dutta** [comment]
@barryjmay  can you post your code which you are using to send it as `Weblink`

**Comment by mbernier** [comment]
@barryjmay I believe the weblink functionality is available through the Marketing Campaigns tool, but not through SMTP.
