### ISSUE TITLE
Add support for .NET Standard 2.0

### ISSUE THREAD

**Issue by matthijskoopman** [sendgrid/sendgrid-csharp#550]
We've recently moved our entire infrastructure to .NET Core 2.0 (and .NET Standard 2.0) and we were wondering when the sendgrid library will be targeting .NET Standard 2.0

**Comment by thinkingserious** [comment]
Great idea @matthijskoopman,

I've added this to our backlog and to our [Hacktoberfest](https://sendgrid.com/blog/announcing-hacktoberfest-2017/) event.

With Best Regards,

Elmer

**Comment by omaraloraini** [comment]
SendGrid already targets .NET Standard 1.3. You could use it in a .NET Core 2.0 project with no problems.

**Comment by thinkingserious** [comment]
That's true @omaraloraini,

I do hope that we can also update our .NET Standard targeting to 2.0.

**Comment by NtFreX** [comment]
I could take care of this. Should I update the netstandard1.3 target or add the netstandard2.0 target?

**Comment by danjagnow** [comment]
As a general rule, you should target the lowest possible version of the .NET Standard that has the features your library needs.  That maximizes the number of places where it can run.  Unless you are leveraging new features of .NET Standard 2.0, it's better to leave it targeting 1.3.  A .NET Core 2.0 app can use a .NET Standard 1.3 library.  See [Which .NET Standard version to target](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target), but here is the key advice:
> In general, we recommend you to target the *lowest* version of .NET Standard possible.
