### ISSUE TITLE
can't install sendgrid 9.9.0 on a project target to .net framework 4.5

### ISSUE THREAD

**Issue by fernandolguevara** [sendgrid/sendgrid-csharp#551]
can't install sendgrid 9.9.0 on a project target to .net framework 4.5

the message error 
`
Could not install package 'Sendgrid 9.9.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			
`

**Comment by thinkingserious** [comment]
Hello @fernandolguevara,

This library only supports [v4.5.2+](https://github.com/sendgrid/sendgrid-csharp#prerequisites).

You may be able to download the source and compile for v4.5, but that is not supported, since Microsoft no longer supports v4.5.

With Best Regards,

Elmer
