### ISSUE TITLE
SendGrid Event Webhook consumer

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#572]
The SendGrid event webhook will send email events to a URL of your choosing. Add functionality that will consume event webhook events posted 
to your server by SendGrid. Documentation: https://sendgrid.com/docs/API_Reference/Webhooks/event.html

**Comment by paritoshmmmec** [comment]
@thinkingserious Here are my understanding currently webhook for Sendgrid. It send all email events at particular URL . Now we want to multiplex events at webhook handler side or we want write webhook handler helper which consume email event. is that correct?
