### ISSUE TITLE
Allows users to submit rfc822 formatted email addresses

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-csharp#577]
#### Issue Summary

Similar to: https://github.com/sendgrid/sendgrid-python/pull/348

Where the user can submit email addresses as:
`example@example.com`
or 
`example example <example@example.com>`

**Comment by brandon93s** [comment]
Looks like there is already an [implementation](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/MailHelper.cs#L137-L148) in `MailHelper` that is available to consumers, but not called automatically anywhere.  

The [constructor](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/Model/EmailAddress.cs#L28-L32) for EmailAddress could be updated to call this method, adding support:

```cs
/// <summary>
/// Initializes a new instance of the <see cref="EmailAddress"/> class.
/// </summary>
/// <param name="email">The email address of the sender or recipient.</param>
/// <param name="name">The name of the sender or recipient.</param>
public EmailAddress(string email, string name = null)
{
    if (name == null)
    {
        var address = MailHelper.StringToEmailAddress(email);
        this.Email = address.Email;
        this.Name = address.Name;
    }
    else
    {
        this.Email = email;
        this.Name = name;
    }
}
```

Thoughts?

**Comment by Niladri24dutta** [comment]
@thinkingserious  I can submit a PR with the change suggested above regarding `MailHelper.StringToEmailAddress`. Let me know if it's fine.

**Comment by thinkingserious** [comment]
That would be great, thanks @Niladri24dutta!

**Comment by thinkingserious** [comment]
How about factoring out this part:

```
var email = match.Groups[EmailGroup].Value.Trim();
var name = match.Groups[NameGroup].Value.Trim();
```

Then you could just call the factored method internally without the cyclic dependency.

With Best Regards,

Elmer

**Comment by Niladri24dutta** [comment]
@thinkingserious  Then,do we need to create a new helper method in `Mailhelper` class to include the above code you mentioned or should we refactor the existing `StringToEmailAddress` method. Because I can see when the email id is not matched then also the `EmailAddress` class constructor is called as seen below -

    var match = Rfc2822Regex.Match(rfc2822Email);
        if (!match.Success)
        {
            return new EmailAddress(rfc2822Email);
         }
https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/MailHelper.cs#L139 

However,we can change the return type of the `StringToEmailAddress` to return a `Dictionary<string>` which can contain the `email` and `name` as key value pair.

**Comment by thinkingserious** [comment]
I think you can encapsulate that check into a utility function, for example, maybe `isRfc2822Email(email)`. We should try to not change `StringToEmailAddress`'s function signature to avoid any breakage. Unless you want to overload the function.
