### ISSUE TITLE
UI displays incorrect Api Key privileges

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#587]
When a new Api Key is created with the `mail_settings.bounce_purge.read` scope, SendGrid's UI incorrectly displays that the key has "full access". Here's a screenshot demonstrating what it looks like in the UI:

![image](https://user-images.githubusercontent.com/112710/31866236-9a584118-b74a-11e7-9f34-f5f59bbf5017.png)

To reproduce, you simply need to issue the following HTTP request:

```
POST https://api.sendgrid.com/v3/api_keys HTTP/1.1
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Accept: application/json, text/json, application/xml, text/xml, application/x-www-form-urlencoded
Authorization: Bearer <... my api key ...>
Content-Length: 99
Host: api.sendgrid.com

{"name":"New Api Key","scopes":["mail_settings.bounce_purge.read"]}
```

**Comment by Jericho** [comment]
I have contacted support and opened ticket request 1274724 .

**Comment by mbernier** [comment]
Oh damn. Nice catch. I will pass this to the PM. Thank you!!

**Comment by thinkingserious** [comment]
Hello @Jericho,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by mbernier** [comment]
Reported to the PM who owns this!  Please ignore that auto-support message I just accidentally sent. :)

**Comment by Jericho** [comment]
Thanks Matt. I also received a reply from a support engineer who asked that I report this issue by clicking the "feedback" button on my dashboard so I did.

**Comment by mbernier** [comment]
Perfect! Thank you so much, we really do appreciate it when you share this stuff with us!!
