### ISSUE TITLE
Building App using .Net 4.0

### ISSUE THREAD

**Issue by adinanistor** [sendgrid/sendgrid-csharp#61]
Hello everyone.
I am not sure of this is an issue, but I was wondering if we currently still support .Net 4.0 for this current SendGrid C# library.

I am unable to build an application using this SendGrid library with .Net 4.0.
It works when building it using .Net 4.5 , but when I am building it using .Net 4.0, the following error occurs:

""The type or namespace name 'SendGridMail' could not be found (are you missing a using directive or an assembly reference?) "

Visual Studio 2012 is being used for building with both .Net 4.0 and .Net 4.5.

Please let me know if further information is needed in order to investigate this further.
Thank you.

**Comment by ccemeraldeyes** [comment]
What was your environment issue? I'm seeing this same problem!

**Comment by adinavornicu** [comment]
Hello @ccemeraldeyes ,

In my case, I could not really point to what was not working ( I personally blamed it on the DLL compiling that may have gone badly ). I did a fresh reinstallation of Visual Studio ( using the same .Net 4.0 ) and I reinstalled the library and it worked.

I'm afraid at this moment I no longer use Windows / Visual Studio as I migrated my testing and working environments to Gnu/Linux ( and away from C# ) but if there are any other details I can help with, please let me know.
Cheers!
