### ISSUE TITLE
Hacktoberfest: SendGrid Current Status

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-csharp#616]
## SendGrid DX team current status:
- Wow
- OMG
- THANK YOU

Hacktoberfest 2017 has completely blown us away. We have had over 900 pull requests from over 300 contributors all in the last 30 days. That is more PRs than we normally get in 2 years! 
We are actively working to review, comment, and/or merge as many PRs as we possibly can as quickly as we can.

We are currently working on “intaking” all the PRs that have come in, oldest first (we have about 400 remaining to go through). We are making sure that each PR we review is one we have a chance of merging - there have been a couple spammy items that came through. Due to the massive influx of requests so far, @thinkingserious and @mbernier have been working nights and weekends all month just to keep up! We’re not even mad, this is amazing!  
## Hey, that’s great for you - but what about my shirt!
If you have signed the CLA before 11/1, but haven’t had a PR merged yet, do not despair! We know we are behind on even just commenting on every PR to show you that we received it (something we typically do). If you submitted a mergeable (non-spam, actually adds value to the project) PR during October 2017, we will grant access to [this page](https://dx.sendgrid.com/swag) to redeem your shirt, sticker, and hacker pin. Next year, we will be sure to communicate this information sooner. We are sorry for any confusion we have caused. We appreciate those of you who have reached out to find out what’s going on! 

## What can I do to help move things along?
**Have you signed the CLA yet?** 
We can only merge items from contributors who signed the CLA

**Can you help another contributor?** 
If you can identify potential problems, add suggestions, or even leave a comment with your review of another PR (Looks good to me! Or I approve this change), that would help us review those PRs much faster, making it easier to get to your PR.

**Do you even write tests, friend?** 
If you see a place where we could have a test to validate a piece of functionality, add it in. We know We know! It’s just another PR we have to review and merge. You’re right, it is! However, the more tests we have, the earlier our CI tool can catch issues, saving us a review as well as back and forth time. 

@adlan, @anveshc05, @duartefq, @erickgirard, @felipeleusin, @FireEater64, @ganchito55, @ImbaKnugel, @kostyaHrytsyuk, @meMuszr, @mptap, @mywolfislost, @NtFreX, @petmat, @rionmonster, @SaiKai, @teabaggs, @thepriefy, @VitorBarbosa, @zchaudhry11

**Comment by duartefq** [comment]
Just got my swag! Thank you!
