### ISSUE TITLE
Style being removed from HTML email

### ISSUE THREAD

**Issue by aaronhoffman** [sendgrid/sendgrid-csharp#62]
I am having an issue with SendGrid stripping the style out of an HTML email I am trying to send. I am using the code provided in the ReadMe.md

I contacted SendGrid support and they advised that I open an issue here. (I think opening a ticket here seems incorrect because I do not believe this is an issue with the code in this package.)

Please provide guidance on how to debug this issue. Thanks.

Aaron

**Comment by StrangeWill** [comment]
@brandonmwest having the same issue, using templates configured on the SendGrid site. Testing using the SendGrid site will send with all the including styles, sending via the API strips out all styles and tables.

Validated HTML, fixed some minor issues but didn't change the behavior. I'm going to attempt to send the template straight over the API, and try to send it via curl and get back to you...

**Comment by StrangeWill** [comment]
Sending the template body to the web service instead of using the template name fixes the missing DOM (tables specifically) issue, however I'm missing a base64 encoded image (shows as "background-image:url('') in the source of the e-mail).

**Comment by jarvisjohnson** [comment]
Anyone still getting to this - make sure you are sending the email content to Sendgrid as 'text/html' rather than 'text/plain'

**Comment by thinkingserious** [comment]
Thanks @jarvisjohnson!
