### ISSUE TITLE
SendGrid C# library install in production computer does not work

### ISSUE THREAD

**Issue by juafevillca** [sendgrid/sendgrid-csharp#639]
#### Issue Summary

I have a dll in C# built in VS2015 MS in Windows 7 that sends email using the SendGrid C# library. During development I had a reference in Access vba to the bin folder created by VS2015. It works as required. Next, I built an installer with VB2015, installed it in the same development computer, and changed the Access vba reference to the .tlb file in the installed directory. The Access application in the development computer continues working as required.  

Now, in the Windows 8 production computer  the installer runs with no problems and the reference to the .tlb in Access vba compiles. However when the functions depending on the SendGrid C# library are called, Access vba shows an error 429 ActiveX Object can't be created.

#### Steps to Reproduce

1.  Code for sending email, coming from your examples, this is part of a class named email. It works fine.

```
public static async Task ExecuteVarios(string from_no_responder, dynamic destinatario, string asunto, string contenido, string apiKey)
        {
            var primero = "";
            foreach (var row in destinatario)
            {
                // Get first subscriptor
                primero = row.email;
                break;
            }
            Email to = new Email(primero);
            dynamic sg = new SendGridAPIClient(apiKey);
            Email from = new Email(from_no_responder);
            string subject = asunto;

            Content content = new Content("text/plain", contenido);
            Mail mail = mail = new Mail(from, subject, to, content);
            foreach (var row in destinatario)
            {
                // Get other subscriptors.
                var otro = new Email(row.email);
                if (otro != to)
                {
                    mail.Personalization[0].AddTo(otro);
                }

            }

            dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());

        }
```
2. Build code and get the dll, using the COM option in VS2015
3. Reference to the dll (really the corresponding .tlb) in the bin/release folder in the References of Access vba. Works great!!
4. Create an installer for the dll using the  VS2015 installer extension template. 
5. Install the dll in the development computer.
6. Change the reference in Access vba to the .tlb from the installer. It compiles. The application works as in the step 3. Ok.
7. Install the dll in production computer.
8. Reference the  in Access vba to the .tlb from the installer. It compiles but when when the functions depending on the SendGrid C# library are called, Access vba shows an error 429 ActiveX Object can't be created.

#### Technical details:

*sendgrid version: 8.0.1
* sendgrid.CSharp.Http.Client version: 3.3.0
* Platform Windows 7, 8
* .NET Version: 4.5.2

![image](https://user-images.githubusercontent.com/33598431/32702133-1e8b1cce-c7b0-11e7-8741-cf93f6d61835.png)

Thanks for your help.

**Comment by thinkingserious** [comment]
Hello @juafevillca,

Could you please try removing SendGrid.CSharp.HTTP.Client.dll and SendGrid.dll, then installing the latest SDK (currently v9.9.0)?

The README in this repo contains the latest documentation on this latest version of the SDK.

Thank you!

With Best Regards,

Elmer
