### ISSUE TITLE
Email as attachment

### ISSUE THREAD

**Issue by williamg-redplanetsoftware** [sendgrid/sendgrid-csharp#641]
Hi,

We are trying to send an email using sendgrid and the email we are sending has an attachment. The attachment is a separate email.

SendGrid successfully sends the email but not the attachment. We are receiving an empty attachment.

We already tried some other approach but not succeed. One was the below:

var bytes = File.ReadAllBytes("/Users/username/message.eml");
var file = Convert.ToBase64String(bytes);
msg.AddAttachment("message.eml", file);
var response = await client.SendEmailAsync(msg);

Please advise on how to resolve this issue.

Thanks and best regards,
weeco

**Comment by thinkingserious** [comment]
Hello @williamg-redplanetsoftware,

I think you might need to specify the `Attachment` `Type`, like [so](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#kitchen-sink---an-example-with-all-settings-used). In your case, I think it might be `message/rfc822`.

With Best Regards,

Elmer

**Comment by williamg-redplanetsoftware** [comment]
Hi Elmer,

Thank you for your reply.

We’ve also done that but still we are getting an empty attachment.


[redplanet_logo200]

William M. Gueco
Developer
E: williamg@redplanetsoftware.com<mailto:williamg@redplanetsoftware.com>




Red Planet Software Pty Ltd | www.redplanetsoftware.com<http://www.redplanetsoftware.com/>
Address: Level 26, 44 Market St, Sydney, NSW, 2000, AUSTRALIA | ABN: 52 104 371 280
Follow us on:
[FB-f-Logo__blue_29]<https://www.facebook.com/RedPlanetSoftware>  [twitter_20] <https://twitter.com/RedPlanetSW>   [linkedin20] <http://www.linkedin.com/company/2992834?trk=tyah>   [Google Plus] <https://plus.google.com/+Redplanetsoftware>

**Comment by thinkingserious** [comment]
Could you please send a sample attachment to dx@sendgrid.com so that we may try to reproduce?

Thanks!

**Comment by williamg-redplanetsoftware** [comment]
Sorry but we can't provide you with the attachment. It's basically an email saved to a local directory then takes that saved email and attach it to sendgrid.

something like this:

string saveMailFolder = @"C:\Temp";
string filePath = Path.Combine(saveMailFolder, "Message.eml");
MailMessageExt.Save(serializedMessage, filePath);
var attachmentSource = new FileAttachmentSource("Message.eml", "message/rfc822");
var attachment = await AttachmentHelper.CreateAttachmentAsync(attachmentSource);
msg.AddAttachments(new List<SendGridAttachment.Attachment>() { attachment });
var response = await client.SendEmailAsync(msg);

**Comment by thinkingserious** [comment]
Hi @williamg-redplanetsoftware,

Can you add a step in your code to verify the existence of the saved email? I'm guessing there could be a problem with the step: "an email saved to a local directory". Maybe it's not getting saved properly or with an alternate name.

With Best Regards,

Elmer

**Comment by williamg-redplanetsoftware** [comment]
Hi Elmer,

Hope you're well.

Have done what you've asked and the file does exist however the attachment still does not show.
Have emailed you a sample email attachment.

Best regards,
weeco

**Comment by thinkingserious** [comment]
Thank you @williamg-redplanetsoftware,

I have received the sample attachment and I have this issue in our backlog for further review.

**Comment by dtornow** [comment]
Hello SendGrid Team,

I am facing the same issue. I checked the outlined checklist, still the email-as-attachment is empty. I am using the SendGrid python library, however since I'm facing the same problems I guess it's not a library issue.

Thanks and best,
Dominik

**Comment by childish-sambino** [comment]
Been a while so checking-in to see if this is still an issue.
