### ISSUE TITLE
sendgrid not working in .Net 4.0

### ISSUE THREAD

**Issue by Gopigg** [sendgrid/sendgrid-csharp#642]
sendgrid not working in .Net 4.0

#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @Gopigg,

This library only supports 4.5.2 and higher, since those are the versions that Microsoft continues to support.

With Best Regards,

Elmer
