### ISSUE TITLE
SendGrid.SmtpApi : 1.3.1 to 1.3.3 issue

### ISSUE THREAD

**Issue by viveklp** [sendgrid/sendgrid-csharp#644]
I have updated following packages for sendgrid email functionality

 1) SendGrid
 2) SendGridMail
 3) SendGrid.SmtpApi

While I updated the packages my email functionality not work properly. 

 myMessage.Header.SetTo methods are not exist in updated version of SendGrid.SmtpApi

**Comment by thinkingserious** [comment]
Hello @viveklp,

The SendGrid.SmtpApi package is stand alone. Please remove SendGrid and SendGridMail.

The repo for SendGrid.SmtpApi is [here](https://github.com/sendgrid/smtpapi-csharp).

I hope that helps.

With Best Regards,

Elmer

**Comment by vinesh1993** [comment]
I have remove SendGrid and SendGridMail packages, but error comes 
 SendGridMessage myMessage = new SendGridMessage();
 
My code is like below 
  
                string userName = string.Empty, pswd = string.Empty, templateId = string.Empty;
                // Setup the email properties.
                SendGridMessage myMessage = new SendGridMessage();

                if (string.IsNullOrEmpty(from))
                    myMessage.From = new MailAddress("info@erecall.net");
                else
                    myMessage.From = new MailAddress(from);

                myMessage.AddTo(recipientsEmailAddr);

                if (htmlContent)
                    myMessage.Html = " "; // "Hi -ClientName- <br><br>-RecallSubject-<br/><br/>Regards,<br />The eRecall Team<br />";
                else
                    myMessage.Text = " "; // "RecallSubject";
                myMessage.Subject = subject;

                for (int i = 0; i < substitueVariables.Count; i++)
                {
                    myMessage.AddSubstitution(substitueVariables.Keys.ElementAt(i), substitueVariables.Values.ElementAt(i));
                }

                var header = new SendGrid.SmtpApi.Header();
                header.SetTo(recipientsEmailAddr);

                //myMessage.Header.SetTo(recipientsEmailAddr);
                //myMessage.Headers.Add("X-SMTPAPI", myMessage.Headers.ToString());

                bool usePoductionKeys = false;

                if (!bool.TryParse(ConfigurationManager.AppSettings["SendGridPrdCredentials"], out usePoductionKeys))
                {
                    usePoductionKeys = false;
                }

                userName = Helper.LoadConfigurationByKey(Constants.PK_SENDGRID_USERNAME);
                pswd = Helper.LoadConfigurationByKey(Constants.PK_SENDGRID_PASSWORD);

                if (usePoductionKeys)
                {
                    templateId = Helper.LoadConfigurationByKey(Constants.PK_SENDGRID_TEMPLATE_ID);
                }
                else
                {
                    templateId = Helper.LoadConfigurationByKey(Constants.DEV_SENDGRID_TEMPLATE_ID);
                }

                // Use SendGrid Template by template id
                if (!string.IsNullOrEmpty(templateId))
                {
                    myMessage.EnableTemplateEngine(templateId);
                }
                else
                {
                    Helper.LogError("eRecall Guard", "Template Id is missing");
                }

                if (!string.IsNullOrEmpty(userName) && !string.IsNullOrEmpty(pswd))
                {
                    // Create credentials, specifying your user name and password.
                    var credentials = new NetworkCredential(userName, pswd);
                    // Create an Web transport for sending email.
                    var transportWeb = new Web(credentials);
                    // Send the email 
                    transportWeb.DeliverAsync(myMessage);

                    emailStatus = true;
                }

            }
            catch (Exception ex)
            {
                emailStatus = false;
                Helper.LogError("SendGridApi.cs>SendMail", ex.Message + ex.InnerException + ex.StackTrace);
            }

            return emailStatus;

**Comment by thinkingserious** [comment]
Hi @vinesh1993,

`SendGridMail` does not exist in that package. Please see [here](https://github.com/sendgrid/smtpapi-csharp#quick-start) for documentation.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
I think you may be using an old version of this SDK, in that case, the documentation is [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#v2).

**Comment by vinesh1993** [comment]
Hello thinkisgserious,
Thank you for your reply 

As per document I install packages SendGrid version 9.9.0 but 
then SendGridMessage class available in SendGrid.Mail.Helper library so I include this library at the top of the class.

then after in below code
      
       SendGridMessage myMessage = new SendGridMessage();

      if (string.IsNullOrEmpty(from))
            myMessage.From = new MailAddress("info@erecall.net");
      else
            myMessage.From = new MailAddress(from);

new MailAddress("") method are not exist

While I install packages  SendGrid version 6.3.4 then I see the following error .

"Could not load file or assembly 'SendGrid.SmtpApi, Version=1.3.1.0, Culture=neutral, PublicKeyToken=2ae73662c35d80e4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

I had installed packages SendGrid.SmtpApi Version= 1.3.3

**Comment by viveklp** [comment]
required your comment Thinkingserious...would be very helpful

**Comment by thinkingserious** [comment]
Hello @viveklp,

If you want to use the most current version of the SendGrid C# SDK. I suggest you remove all SendGrid packages and start over, following the instructions on this page: https://github.com/sendgrid/sendgrid-csharp/blob/master/README.md

With Best Regards,

Elmer
