### ISSUE TITLE
BCC Recipients don't receive substitution values in emails

### ISSUE THREAD

**Issue by RyKilleen** [sendgrid/sendgrid-csharp#645]
#### Issue Summary

When BCCing someone, the bcc'd email does not contain Substitutions.

#### Steps to Reproduce

1. Add a To and a BCC recipient
2. Add substitutions to message
3. Send Email

Ideally, the message sent to BCC recipient should be identical to the original recipient.
```
var message = new SendGridMessage();
message.From = new MailAddress("website@domain.com");
message.AddTo(address);
message.From = new MailAddress("website@domain.com", "Friendly From Name");
message.Bcc = bccArray.Select(addr => new MailAddress(addr)).ToArray();
message.EnableTemplateEngine("........................");
message.AddSubstitution("%userName%", new List<string> { name });
message.AddSubstitution("%productKey%", new List<string> { uniqueCode });
var transportWeb = new Web(ConfigurationManager.AppSettings["SendGridAPIKey"]);
await transportWeb.DeliverAsync(message);
```
#### Technical details:

* sendgrid-csharp Version: 6.3.4
* Platform: .NET MVC 5.2.3
* .NET Version: 4.6

Thanks for taking the time!

**Comment by thinkingserious** [comment]
Hello @RyKilleen,

It appears that you are using a non-supported version of this SDK. 

Have you tried updated to v9?

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @RyKilleen,

It appears that you are using a non-supported version of this SDK. 

Have you tried updating to v9?

With Best Regards,

Elmer

**Comment by RyKilleen** [comment]
That would certainly do it. Off the top of your head @thinkingserious is there any extreme breaking changes I should look out for? I know 3 versions is a big jump, and too much for anyone to keep in their head.

**Comment by thinkingserious** [comment]
My recognition would be to start fresh [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/README.md).

For deeper insight into the upgrade, [this documentation](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html) may help.

**Comment by RyKilleen** [comment]
@thinkingserious thanks so much, I think you're probably right. Luckily my implementation is pretty isolated and not too complex. Thanks for the time

**Comment by thinkingserious** [comment]
Awesome! If you run into any issues with the integration, please do reach out. Thanks!
