### ISSUE TITLE
Sending Email with sendGrid

### ISSUE THREAD

**Issue by Peternomous** [sendgrid/sendgrid-csharp#647]
#### Issue Summary

I want to use SendGrid to authenticate users credential. I want email to be sent to users to confirm their credentials. 
The following errors came up:

The type or namespace name 'SendMessage' could not be found (are you missing a using directive or an assembly reference?)	AppUser	C:\Users\Adee\Documents\Visual Studio 2017\Projects\AppUser\AppUser\App_Start\IdentityConfig.cs	37	Active

 **AND**

The type or namespace name 'Web' could not be found (are you missing a using directive or an assembly reference?)	AppUser	C:\Users\Adee\Documents\Visual Studio 2017\Projects\AppUser\AppUser\App_Start\IdentityConfig.cs	53	Active

**I will like to add my code for appropriate understanding:**

using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin;
using Microsoft.Owin.Security;
using AppUser.Models;
using SendGrid;
using System.Net;
using System.Configuration;
using System.Diagnostics;
using System.Net.Http;
using System.Net.Mail;

namespace AppUser
{
    public class EmailService : IIdentityMessageService
    {
        public async Task SendAsync(IdentityMessage message)
        {
            

        // Plug in your email service here to send an email.
        await ConfigSendGridasync(message);
        }

        // Use NuGet to install SendGrid (Basic C# client lib) 
        private async Task ConfigSendGridasync(IdentityMessage message)
        {
            var myMessage = new SendMessage();
            myMessage.AddTo(message.Destination);
            myMessage.From = new System.Net.Mail.MailAddress(
                                "adlecon4u2@gmail.com", "Adesola Adeniyi Peteru");
            myMessage.Subject = message.Subject;
            myMessage.Text = message.Body;
            myMessage.Html = message.Body;

            var credentials = new NetworkCredential(
                       ConfigurationManager.AppSettings["mailAccount"],
                       ConfigurationManager.AppSettings["mailPassword"]
                       );

            //Create a Web transport for sending email.

           var transportWeb = new Web(credentials);

           // Send the email.
                if (transportWeb != null)
            {
                await transportWeb.DeliverAsync(myMessage);
            }
            else
            {
                Trace.TraceError("Failed to create Web transport.");
                await Task.FromResult(0);
            }
        }

    }

        internal class SendGridMessage
    {
        public SendGridMessage()
        {
        }
    }

    public class SmsService : IIdentityMessageService
    {
        public Task SendAsync(IdentityMessage message)
        {
            // Plug in your SMS service here to send a text message.
            return Task.FromResult(0);
        }
    }

    // Configure the application user manager used in this application. UserManager is defined in ASP.NET Identity and is used by the application.
    public class ApplicationUserManager : UserManager<ApplicationUser>
    {
        public ApplicationUserManager(IUserStore<ApplicationUser> store)
            : base(store)
        {
        }

        public static ApplicationUserManager Create(IdentityFactoryOptions<ApplicationUserManager> options, IOwinContext context) 
        {
            var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context.Get<ApplicationDbContext>()));
            // Configure validation logic for usernames
            manager.UserValidator = new UserValidator<ApplicationUser>(manager)
            {
                AllowOnlyAlphanumericUserNames = false,
                RequireUniqueEmail = true
            };

            // Configure validation logic for passwords
            manager.PasswordValidator = new PasswordValidator
            {
                RequiredLength = 6,
                RequireNonLetterOrDigit = true,
                RequireDigit = true,
                RequireLowercase = true,
                RequireUppercase = true,
            };

            // Configure user lockout defaults
            manager.UserLockoutEnabledByDefault = true;
            manager.DefaultAccountLockoutTimeSpan = TimeSpan.FromMinutes(5);
            manager.MaxFailedAccessAttemptsBeforeLockout = 5;

            // Register two factor authentication providers. This application uses Phone and Emails as a step of receiving a code for verifying the user
            // You can write your own provider and plug it in here.
            manager.RegisterTwoFactorProvider("Phone Code", new PhoneNumberTokenProvider<ApplicationUser>
            {
                MessageFormat = "Your security code is {0}"
            });
            manager.RegisterTwoFactorProvider("Email Code", new EmailTokenProvider<ApplicationUser>
            {
                Subject = "Security Code",
                BodyFormat = "Your security code is {0}"
            });
            manager.EmailService = new EmailService();
            manager.SmsService = new SmsService();
            var dataProtectionProvider = options.DataProtectionProvider;
            if (dataProtectionProvider != null)
            {
                manager.UserTokenProvider = 
                    new DataProtectorTokenProvider<ApplicationUser>(dataProtectionProvider.Create("ASP.NET Identity"));
            }
            return manager;
        }
    }

    // Configure the application sign-in manager which is used in this application.
    public class ApplicationSignInManager : SignInManager<ApplicationUser, string>
    {
        public ApplicationSignInManager(ApplicationUserManager userManager, IAuthenticationManager authenticationManager)
            : base(userManager, authenticationManager)
        {
        }

        public override Task<ClaimsIdentity> CreateUserIdentityAsync(ApplicationUser user)
        {
            return user.GenerateUserIdentityAsync((ApplicationUserManager)UserManager);
        }

        public static ApplicationSignInManager Create(IdentityFactoryOptions<ApplicationSignInManager> options, IOwinContext context)
        {
            return new ApplicationSignInManager(context.GetUserManager<ApplicationUserManager>(), context.Authentication);
        }
    }
}

Can someone help me out?

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @Peternomous,

What version of this SDK do you have installed from Nuget?

With Best Regards,

Elmer

**Comment by Peternomous** [comment]
@Elmer, 
I installed 
EntityFramework.SqlServer
and
Sendgrid

**Comment by thinkingserious** [comment]
HI @Peternomous,

Is this the Nuget package you installed: https://www.nuget.org/packages/SendGrid

If so, what version?

Thank you!
