### ISSUE TITLE
Email Messages being dropped after receiving an "Accepted" or "Ok" response.

### ISSUE THREAD

**Issue by engineeringecomdash** [sendgrid/sendgrid-csharp#651]
#### Issue Summary

We are experiencing the exact same issue as case number: #506 
However, this happens consistently for one specific email. That email is: mike@jewelrytrends.com 

I have provided our SendEmail method below for you to examine. If we receive an "Accepted" or "Ok" response back from our call, it is my understanding that the email should be queued up in send grid to be sent. However, when we go to send grid to check, there is no email to be found for the email address: mike@jewelrytrends.com  

The only thing we see in send grid under the drops folder is an email with a value of: jewelry 

Which is not the email we are sending over. We have already reached out to the general support team about this and our case number was: 1335524. They pointed us to the library to create an issue with you guys. 

In addition we have created unit tests on our end to specifically investigate the email above that is having issues. We created a unit test to pull the value out of our database and compare it character by character to a typed out string of the email address. No differences were found and the lengths match exactly. 

It should be noted that our call works fine for most people's email address'. There seem to be a few like the one above that are being stripped or tampered with after the request is made. 

I have attached our code to this issue and your help resolving this issue would be greatly appreciated. 
[SendEmailASync.txt](https://github.com/sendgrid/sendgrid-csharp/files/1592210/SendEmailASync.txt)

[SendEmail.txt](https://github.com/sendgrid/sendgrid-csharp/files/1592207/SendEmail.txt)

#### Steps to Reproduce
The only way to reproduce it would be to make the same call we are making using the same nuget package and see that no email gets queued up in send grid for the email above. 

#### Technical details:

* sendgrid-csharp Version: version 9.9 of the nuget package by Elmer Thomas, SendGrid DX Team
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.6.2

**Comment by thinkingserious** [comment]
Hello @engineeringecomdash,

I will circle back with support on your behalf as this appears to not be a SDK issue.

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @engineeringecomdash,

Were you able to find a resolution? This appears to be a server side issue.

With Best Regards,

Elmer
