### ISSUE TITLE
Investigate DLL / Nuget Mismatch

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#652]
#### Issue Summary

Report from customer: 

> I realized that according to Nuget, I am referencing 9.9.0 of the sendgrid client. The weird part is that the version of the dll is 9.8.0 but the path it is referenced from is C:\XXXX\Sendgrid.9.9.0\lib\net452\SendGrid.dll. Not sure if that is significant. Did they just forget to up the version number on the dll, or did the nuget package actually contain the wrong dll??

**Comment by danjagnow** [comment]
The easiest way to investigate this is to install [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer), which you can download from the [Microsoft Store](https://www.microsoft.com/store/apps/9wzdncrdmdm3).  After installing that, you can double-click **sendgrid.9.9.0.nupkg**.  Expand the tree in the **Package contents** pane, and double-click **SendGrid.dll** under **net452** or **netstandard1.3**.  You'll notice that the **AssemblyInformationalVersion** shows as 9.9.0, but the **AssemblyFileVersion**, **Full Name**, and **Strong Name** show 9.8.0.0.  Note that at this time, some of the version information is specified in the project file, and some is in the **AssemblyInfo.cs** file, which should probably be removed.

**Comment by thinkingserious** [comment]
Fixing with the next release shortly.
