### ISSUE TITLE
In Version 9.9.0 - there is no AddAttachment method that takes a stream

### ISSUE THREAD

**Issue by ericpopivker** [sendgrid/sendgrid-csharp#654]
Today I downloaded NuGet package v9.9.0, but when I was testing sending an email, I didn't find a method that would let me add an Attachment to message using Stream.

In your documentation I found example here:
https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md

```
            using (var fileStream = File.OpenRead("/Users/username/file.txt"))
            {
                msg.AddAttachment("file.txt", fileStream);
                var response = await client.SendEmailAsync(msg);
            }

```

But it doesn't work for me with 9.9.0.

Also I found some examples on StackOverflow:
https://stackoverflow.com/questions/29122352/addattachment-from-memorystream
But those examples do not work either.

The only method I have available is:
public void AddAttachment(string filename, string content, [string type = null], [string disposition = null], [string content_id = null])

https://www.screencast.com/t/3OXwDC57c

Did the method that took Stream exist and it was depreciated? Or it is still being planned for the future?

If not, are there some examples for converting Stream to Base64 Content?

**Comment by thinkingserious** [comment]
Hello @ericpopivker,

I think [this example](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#attachments) is what you need. Please let me know if that's not the case.

With Best Regards,

Elmer

**Comment by ericpopivker** [comment]
Hi,

I tried the second example, but FileStream is not available as argument.

I don't have any of the files stored in file storage, most are rendered on the fly.

Eric

**Comment by thinkingserious** [comment]
Hi @ericpopivker,

Ah, looks like our documentation may be out of date. I think [this](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L1000) is the function you need.

Please let me know if that works for you and I can either update the docs, or if you like, we accept PRs :)

With Best Regards,

Elmer

**Comment by ericpopivker** [comment]
Hi Elmer,

I appreciate your prompt response.

Unfortunately I don't see such function in the list of methods in SendGridMessage:
https://www.screencast.com/t/xHTwGKhjp

I do see that it is in the GitHub code, so it is a bit bizzare.  Is this function included in 9.9.0?

Eric

**Comment by thinkingserious** [comment]
@ericpopivker,

I see what happened, that code was merged but not deployed. I'm not sure when it will be deployed because we currently have a very large backlog we are trying to work through after receiving over 1,000 PRs during Hacktoberfest. 

If you sign up for our [release notifications](https://dx.sendgrid.com/newsletter/csharp) newsletter, you will receive an email when the updates are deployed.

As a workaround, you can also download the source code and build the dll yourself or you can create that function yourself, using the source code in the link above.

I hope that helps.

With Best Regards,

Elmer

**Comment by Jericho** [comment]
@ericpopivker you might be interested in [StrongGrid](https://github.com/Jericho/StrongGrid) (disclaimer: I'm the author). The reason I mention it because it allows you to create attachments from a file, from a byte array or from a stream. Here's an example:

```csharp
var from = new MailAddress("test@example.com", "John Smith");
var to = new MailAddress("recipient@example.com", "Recipient1");
var subject = "Dear friend";
var textContent = "Hello world!";
var htmlContent = "<html><body>Hello <b><i>world!</i></b><br/></body></html>";
var attachments = new[]
{
	SendGridAttachment.FromLocalFile(@"c:\temp\myfile.txt"),
	SendGridAttachment.FromBinary(new byte[] { ... }, "MyBinaryFile.bin"),
	SendGridAttachment.FromStream(myStream, "MyFile.xxx")
};

var apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY");
var client = new StrongGrid.Client(apiKey);
var messageId = await client.Mail.SendToSingleRecipientAsync(
	to,
	from,
	subject,
	htmlContent,
	textContent,
	attachments: attachments)
.ConfigureAwait(false);
```

**Comment by thinkingserious** [comment]
@ericpopivker,

I can second @Jericho's recommendation, StrongGrid is a solid SDK.

**Comment by ericpopivker** [comment]
I will copy the code from here:
https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L1000
to my project for now.

StrongGrid sounds great, but I got burned too many times on using non-official libs that became not supported.  I am actually swtiching from SendGridPlus which lost developer support 3 years ago.

Thank you.
