### ISSUE TITLE
Intermittent HTTP500 response from API

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#655]
In the last few days I have bee getting a lot of HTTP 500 responses from SendGrid API. What's more confusing is that these exception seem random: what I mean is that sometimes a given HTTP request will work fine but repeating the _exact same_ HTTP request a few seconds later results in a HTTP 500 response.

I didn't worry about it at first because it seemed like these exceptions started occurring around the time that SendGrid disclosed a [technical issue](http://status.sendgrid.com/incidents/w63q8zhgl36t) which was followed by a [scheduled maintenance](http://status.sendgrid.com/incidents/7wlprsgm4h8q). Both incidents have been resolved and I continue to experience the HTTP500 exceptions so I'm starting to worry about it.

Sometimes, the response looks like this:
```
HTTP/1.1 500 INTERNAL SERVER ERROR
{"errors":[{"message":"Sorry, some unexpected error occurred."}]}
```

but most of the time the response looks like this:
```
HTTP/1.1 500 INTERNAL SERVER ERROR
{"errors": [{"field": null, "message": "internal server exception"}]}
```

Sometimes I'm getting this exception when issuing a very simple HTTP GET such as:
```
GET https://api.sendgrid.com/v3/user/profile
or
GET https://api.sendgrid.com/v3/tracking_settings?limit=25&offset=0
```

and sometimes I'm getting this exception when issuing a more complex HTTP POST such as:
```
POST https://api.sendgrid.com/v3/templates/af51921e-f942-4477-8a1b-95044b092108/versions 
{"name":"StrongGrid Integration Testing: version 2","subject":"My second Subject <%subject%>","html_content":"<html<body>Qwerty<br/><%body%></body></html>","plain_content":"Qwerty <%body%>","active":1}
```

Here's a trace captured in Fiddler showing the exact same HTTP GET call repeated 4 times only a few seconds apart. As you can see, it failed the first three times and it finally succeeded on the fourth attempt:
![image](https://user-images.githubusercontent.com/112710/34909187-1e8db7e6-f86a-11e7-986d-49097ed8895b.png)

So far I haven't been able to detect any pattern and the fact that my HTTP calls sometimes work and sometimes fail leads me to believe my calls and/or the data posted in my calls is most likely not the culprit (although I'm keeping an open mind).

I know this is not a C# client issue so I have already contacted SendGrid support (ticket number 1348907) about this, but I figured I would post here in case someone else is experiencing the same problem.

**Comment by thinkingserious** [comment]
Thanks for the detailed report @Jericho! I have provided some guidance internally as to who is the best team to troubleshoot this.

**Comment by thinkingserious** [comment]
I see that there is now an issue created (1348907) that our support team is looking into. I've added this information for future reference to help ensure this gets resolved.

**Comment by Jericho** [comment]
The ticket you are referring to is the one I created when I first discovered this issue on January 13.

The support person I have been communicating with said:

> I am going to report this issue to our Senior Engineering team so that we can begin tracking this error and report it to our Engineering team if necessary.

I have offered to get on a screen sharing session with the engineering team to demonstrate what I have discovered. I strongly suspect these HTTP 500 errors occur when I exceed some quota which is surprising to me because the API is supposed to return HTTP 429 when that happens. Anyway, I'll keep you updated if the engineering team takes me up on my offer to demonstrate what I am witnessing.

**Comment by thinkingserious** [comment]
Perfect, I have advised them to take you up on the offer.

**Comment by Jericho** [comment]
I was contacted on Thursday and told that the team is now able to reproduce the issue and that the ticket was escalated to the Ops team.

**Comment by thinkingserious** [comment]
Nice! Please let me know if there is no response within a few days.

**Comment by Jericho** [comment]
Just FYI: I haven't heard anything since Feb 10.

**Comment by thinkingserious** [comment]
What is the ticket number for the most recent request?

**Comment by Jericho** [comment]
1362778

In the mean time, I heard from Kyle:  he says the Ops team is still investigating and they asked him for additional information. His latest theory is that this is related to HTTP DELETE calls but I replied to him that I am able to reproduce even when eliminating DELETE calls from my testing script.

**Comment by Jericho** [comment]
Two more weeks have gone by and I haven't heard anything. I reached out to Kyle earlier today and he responded that the Ops team "_will be digging into the issue, but it has been a lower priority in comparison to some other issues that have come up_".

I'm pretty discouraged to hear that a demonstrable server-side API problem is considered low priority and remains unresolved over 2 months later. 😢

**Comment by Jericho** [comment]
@thinkingserious any chance you can check on my ticket (1362778)? I've been patiently waiting for almost three months and the problem persists.

**Comment by thinkingserious** [comment]
Hi @Jericho,

There will be a response to your ticket from support coming shortly. Thanks!

With Best Regards,

Elmer

**Comment by Jericho** [comment]
Another two weeks has gone by, still no progress.

**Comment by Jericho** [comment]
Another 3 weeks has gone by, no update.

**Comment by Jericho** [comment]
Another 2 weeks, still no update.

Is it a normal situation at SendGrid for a support case to linger for more than 4 months without any progress?

**Comment by thinkingserious** [comment]
Hello @Jericho,

As far as I know the average support response time for SendGrid is above average in our industry. 

The delay with your particular case is one of priority, mainly because there are very few others (maybe none) reporting this issue and that there is a workaround.

In any case, the correct venue for this particular issue is our support team as GitHub is reserved for issues relating to the SDK. My apologies that I can not help further here :(

With Best Regards,

Elmer

**Comment by Jericho** [comment]
I was not aware that someone had found a workaround. Can you give me some details?

**Comment by thinkingserious** [comment]
I believe your [SendGridRetryStrategy](https://github.com/Jericho/StrongGrid/blob/6ef28cf9b8929344df6d4e47d7a2d7b331580e8c/Source/StrongGrid/Utilities/SendGridRetryStrategy.cs) class should do the trick. Not ideal of course, but it's a bandaid that should keep you functional for now. Please let me know if this is an incorrect assumption. Thanks!

**Comment by Jericho** [comment]
I don't think what you are suggesting is a reasonable workaround, for several reasons:

1. When the API starts throwing `HTTP 500` exceptions, it continues to do so for a few minutes (roughly 2-4 minutes, in my experience). I don't think it's reasonable for an API call to take a few minutes to complete.
2. My retry strategy class expects status code `HTTP 429` to know that the developer has exceeded a rate limit and to retry the request after a brief interval. In this case, the status code is `HTTP 500` which is not a code indicating that a rate limit was exceeded according to the [SendGrid documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/rate_limits.html).
3. My retry strategy class uses the `X-Ratelimit-Reset` header, as indicated in SendGrid documentation, to figure out how long to wait before retrying. Unfortunately, when the SendGrip API throws a HTTP 500 exception, this header is omitted from the response and therefore my retry strategy can't figure out how long to wait.
4. We don't know that the underlying problem has anything to do with a rate limit having been exceeded. At least, nobody has confirmed that to me. It's a theory I mentioned back in January when I first reported this problem but it's just a theory.

**Comment by thinkingserious** [comment]
Thank you for the updated information, I appreciate the extra level of detail! I will note internally that there is not currently an acceptable workaround for this issue.

**Comment by Jericho** [comment]
@thinkingserious I have been patiently waiting for 8 months and there is still no progress. As far as I know, nobody in the engineering team has looked at this case or investigated it. Every time I speak up and ask for help or for an update, I am told that my case is low priority and an engineer will look into it whenever their schedule allows it. I have a hard time believing that nobody has had a chance to investigate this reproducible issue in over 8 months!!!

**Comment by thinkingserious** [comment]
Hello @Jericho,

I have put in a request for a review and I will update you here once I learn more. And thanks for your patience, I'm sure the slow turn around must be painful and I hope we can find a resolution.

With Best Regards,

Elmer

**Comment by davidmwilliams** [comment]
Did this ever get resolved? We're getting curious "Internal server error" failures from SendGrid too.

**Comment by Jericho** [comment]
@davidmwilliams I raised this issue and opened a case with SendGrid's support team over two years ago and nobody ever got back to me. Last time I contacted support to ask for an update was in September 2018 and I was told that my case `has not been high enough priority` and that `other issues with more priority have been keeping it from being worked on`. Soon after that the case was closed without an explanation.

The `HTTP 500` errors have slowly subsided over time and as of today I am no longer experiencing these errors but I have no idea why.

I hope that SendGrid support takes you more seriously than they did me when I reported the problem and that you get a resolution in a more reasonable time frame. Good luck!

**Comment by childish-sambino** [comment]
For transparency, the SendGrid support team does not monitor issues created against this repo; it's just the community and the engineers responsible for maintaining the repo. Since the issue you're seeing does not appear to be something that can be resolved by this library and is an issue with the backing API implementation, the proper course of action is to engage support.

**Comment by thinkingserious** [comment]
Hello @Jericho,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Jericho** [comment]
@childish-sambino I guess you didn't take the time to review this issue because you would have noticed that I opened a case with SendGrid support more than two years ago! To be frank with you, I gave up in September 2018 when I was told by SendGrid's support that the repeatable issue I was experiencing was not high enough priority to warrant someone investigating it (I invite you to review case number 1362778 if you are interested in more details).
