### ISSUE TITLE
Look up quota

### ISSUE THREAD

**Issue by onionhammer** [sendgrid/sendgrid-csharp#657]
We have a healthcheck, which runs every 5 minutes to determine if our application is healthy, one aspect of our application's health is whether SendGrid is available and we have not exceeded our monthly email quota.

I see that we are able to pull `/stats?aggregate_by=month` to retrieve the number of `requests` for the month thus far, but it does not indicate what the quota is. It would be nice if there was a way I could determine if sendgrid will send emails before they start to error out when I actually try sending them.

I'm aware the owner of the account can get notifications if 90% of the quota is met, but we have a separate health checking system that is used by application insights

**Comment by thinkingserious** [comment]
Hi @onionhammer,

This is a question for our [support team](https://support.sendgrid.com), would you mind opening a ticket with them? 

Please do share the results with us as this may be a good feature to add to the library.

Thanks!

With Best Regards,

Elmer

**Comment by onionhammer** [comment]
Hmm, last time I contacted support i dont know if I ever got a reply lol. But I'll give it a shot

**Comment by thinkingserious** [comment]
Hi @onionhammer,

If you have trouble getting a response, please provide me with the ticket number. Thanks!

**Comment by onionhammer** [comment]
@thinkingserious Got the ol' runaround from support - they're telling me to fill in a 'feedback' form now

**Comment by Jericho** [comment]
+1

I think this would be a great enhancement to the SendGrid API. Maybe @mbernier can weigh in?

**Comment by thinkingserious** [comment]
@onionhammer, 

I believe this means that your idea will bubble up to the product team for consideration. 

Do you have a link to the feedback form support gave you? 

@Jericho,

Agreed, I'll get your vote added to @onionhammer's request.

Thanks!

**Comment by onionhammer** [comment]
@thinkingserious no link was provided, just a vague direction to look for a blue link. Couldn't find it

**Comment by thinkingserious** [comment]
@onionhammer,

Could you please share the support ticket number?

**Comment by onionhammer** [comment]
@thinkingserious 1357664

**Comment by thinkingserious** [comment]
Hi @onionhammer,

I have submitted your feedback along with @Jericho's +1. Thanks!

**Comment by Jericho** [comment]
@onionhammer I received similar vague direction to look for a blue button to provide feedback on an unrelated issue. Turns out, what they mean is this "feedback" button on the right side of your screen when you look at your dashboard:

![image](https://user-images.githubusercontent.com/112710/35463349-2ee03002-02be-11e8-89ae-6aa766da6706.png)

**Comment by onionhammer** [comment]
Ahh - you know what? If I disable my ad blocker I see it ;)

**Comment by Jericho** [comment]
It just occurred to me that there is already an [API endpoint](https://sendgrid.com/docs/API_Reference/Web_API_v3/user.html#GET-User-Credits-GET) to retrieved information about your monthly quota. Dispatching a GET request to this endpoint will return the following information such as: how many credits you have during a given billing period, how many credits you have used so far in the current billing period, start date of the curent billing period, etc.

In fact (and shame on me for not remembering this) the StrongGrid library has a convenient method to help you retrieve this information:

```csharp
var apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY");
var client = new StrongGrid.Client(apiKey);
var userCredits = await client.User.GetCreditsAsync(null, cancellationToken).ConfigureAwait(false);
await log.WriteLineAsync($"You have used  {userCredits.Used} credits out of {userCredits.Total} during the current billing period").ConfigureAwait(false);
```

**Comment by thinkingserious** [comment]
@Jericho to the rescue once again!

[Here](https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md#retrieve-your-credit-balance) is how to grab that data in this SDK. You will want to use Jericho's excellent StrongGrid if you want the convenience method. It will take some time before we implement that.

With Best Regards,

Elmer

**Comment by onionhammer** [comment]
Excellent! I will look into this next week, thanks @jericho and @thinkingserious

Is there any reason why I wouldn't want to incorporate this kind of check into a periodic health check? Are there rate limits for how often I can check?

**Comment by Jericho** [comment]
Yes there are rate limits but as far as I know SendGrid has not officially published what they are. Based on my observations, the limit seems to generally be 600 calls per minute per endpoint but some endpoints have different limit: 
- the "stat" endpoint has a limit of 25 calls per minute
- the "whitelabel" endpoint has a limit of 20 calls per minute
- the "api_keys" endpoint has a limit of one call per 4 seconds
- the "mail/send" endpoint does not seem to have any limit whatsoever

These numbers are based on my reading of the `X-Ratelimit-Limit` and the `X-Ratelimit-Reset` headers that SendGrid includes with each response.

**Comment by Jericho** [comment]
_Side note regarding rate limits_: something doesn't seem right with the way they are enforced. This used to work just fine but I noticed in early January that I was getting a generic HTTP 500 error instead of the expected HTTP 429. I opened issue #655 to talk about it and I also contacted support. They told me a few days ago that the issue has been escalated to their engineering team but so far I haven't heard back from anybody in that group. I will post updates on issue 655 when I have more information.

This is important to me because I have logic in the StrongGrid library to retry requests whenever a HTTP 429 is detected and this logic is currently broken.

**Comment by onionhammer** [comment]
Hmm.. unable to access users/credits (via https://sendgrid.com/docs/API_Reference/api_v3.html ) even with an API Key with full access I get 'access denied'.

**Comment by thinkingserious** [comment]
@onionhammer,

My apologies, I have found that you must make an API call to set the permission you need to access that endpoint.

You will need to do a [PUT](https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/index.html) to update the `user.credits.read` [scope](https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/api_key_permissions_list.html#User-Settings).

I hope that helps!

I will leave this issue open so that we can create a USE_CASES.md entry for this. If you like, PRs are always welcome :)

With Best Regards,

Elmer

**Comment by onionhammer** [comment]
Getting this

```
      "field": null,
      "message": "unauthorized scopes: [user.credits.read]"
```

**Comment by thinkingserious** [comment]
@onionhammer,

It turns out that you need to use [Basic auth](https://sendgrid.com/blog/magic-behind-basic-http-authentication/) like so:

```bash
curl -X PUT \
  https://api.sendgrid.com/v3/api_keys/{api_key_id} \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic {base64encoded}' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
	"name": "Credit Test",
    "scopes": [
    	"user.credits.read",
        "alerts.create",
        "alerts.read",
        "alerts.update",
        "alerts.delete",
        "asm.groups.create",
        "asm.groups.read",
        "asm.groups.update",
        "asm.groups.delete",
        "ips.warmup.create",
        "ips.warmup.read",
        "ips.warmup.update",
        "ips.warmup.delete",
        "ips.pools.create",
        "ips.pools.read",
        "ips.pools.update",
        "ips.pools.delete",
        "ips.pools.ips.create",
        "ips.pools.ips.read",
        "ips.pools.ips.update",
        "ips.pools.ips.delete",
        "ips.assigned.read",
        "ips.create",
        "ips.read",
        "ips.update",
        "ips.delete",
        "mail.send",
        "mail_settings.bcc.read",
        "mail_settings.bcc.update",
        "mail_settings.address_whitelist.read",
        "mail_settings.address_whitelist.update",
        "mail_settings.footer.read",
        "mail_settings.footer.update",
        "mail_settings.forward_spam.read",
        "mail_settings.forward_spam.update",
        "mail_settings.plain_content.read",
        "mail_settings.plain_content.update",
        "mail_settings.spam_check.read",
        "mail_settings.spam_check.update",
        "mail_settings.bounce_purge.read",
        "mail_settings.bounce_purge.update",
        "mail_settings.forward_bounce.read",
        "mail_settings.forward_bounce.update",
        "partner_settings.new_relic.read",
        "partner_settings.new_relic.update",
        "partner_settings.sendwithus.read",
        "partner_settings.sendwithus.update",
        "tracking_settings.click.read",
        "tracking_settings.click.update",
        "tracking_settings.subscription.read",
        "tracking_settings.subscription.update",
        "tracking_settings.open.read",
        "tracking_settings.open.update",
        "tracking_settings.google_analytics.read",
        "tracking_settings.google_analytics.update",
        "user.webhooks.event.settings.read",
        "user.webhooks.event.settings.update",
        "user.webhooks.event.test.create",
        "user.webhooks.event.test.read",
        "user.webhooks.event.test.update",
        "user.webhooks.parse.settings.create",
        "user.webhooks.parse.settings.read",
        "user.webhooks.parse.settings.update",
        "user.webhooks.parse.settings.delete",
        "stats.read",
        "stats.global.read",
        "categories.stats.read",
        "categories.stats.sums.read",
        "devices.stats.read",
        "clients.stats.read",
        "clients.phone.stats.read",
        "clients.tablet.stats.read",
        "clients.webmail.stats.read",
        "clients.desktop.stats.read",
        "geo.stats.read",
        "mailbox_providers.stats.read",
        "browsers.stats.read",
        "subusers.stats.read",
        "subusers.stats.sums.read",
        "subusers.stats.monthly.read",
        "user.webhooks.parse.stats.read",
        "subusers.create",
        "subusers.read",
        "subusers.update",
        "subusers.delete",
        "subusers.monitor.create",
        "subusers.monitor.read",
        "subusers.monitor.update",
        "subusers.monitor.delete",
        "subusers.credits.create",
        "subusers.credits.read",
        "subusers.credits.update",
        "subusers.credits.delete",
        "subusers.credits.remaining.create",
        "subusers.credits.remaining.read",
        "subusers.credits.remaining.update",
        "subusers.credits.remaining.delete",
        "subusers.reputations.read",
        "subusers.summary.read",
        "templates.create",
        "templates.read",
        "templates.update",
        "templates.delete",
        "templates.versions.create",
        "templates.versions.read",
        "templates.versions.update",
        "templates.versions.delete",
        "templates.versions.activate.create",
        "user.timezone.read",
        "user.timezone.update",
        "user.settings.enforced_tls.read",
        "user.settings.enforced_tls.update",
        "api_keys.create",
        "api_keys.read",
        "api_keys.update",
        "api_keys.delete",
        "email_activity.read",
        "categories.create",
        "categories.read",
        "categories.update",
        "categories.delete",
        "mail_settings.template.read",
        "mail_settings.template.update",
        "marketing_campaigns.create",
        "marketing_campaigns.read",
        "marketing_campaigns.update",
        "marketing_campaigns.delete",
        "mail.batch.create",
        "mail.batch.read",
        "mail.batch.update",
        "mail.batch.delete",
        "user.scheduled_sends.create",
        "user.scheduled_sends.read",
        "user.scheduled_sends.update",
        "user.scheduled_sends.delete",
        "access_settings.whitelist.create",
        "access_settings.whitelist.read",
        "access_settings.whitelist.update",
        "access_settings.whitelist.delete",
        "access_settings.activity.read",
        "whitelabel.create",
        "whitelabel.read",
        "whitelabel.update",
        "whitelabel.delete",
        "suppression.create",
        "suppression.read",
        "suppression.update",
        "suppression.delete"
        ]
}'
```

**Comment by onionhammer** [comment]
Yeah I was doing basic auth, I'll try it again but that looks like exactly what I was doing, except with postman

**Comment by thinkingserious** [comment]
Thanks @onionhammer,

Please let me know how it goes.

**Comment by thinkingserious** [comment]
@Jericho,

Did you run into any authentication issue for that endpoint?

**Comment by Jericho** [comment]
I remember having access issues with `user/profile` and I remember others also having access issues but I don't remember any issue with `user/credits` specifically. The access issues I experienced are described [here](https://github.com/sendgrid/sendgrid-csharp/issues/185).

One thing that trips me every time is that SendGrid's UI allows you to create "Full Access" API Keys which gives your the false impression that the key is granted all permissions but that's not so. To create an API key that truly has all permissions you need to do it yourself by issuing an HTTP POST to `https://api.sendgrid.com/v3/api_keys` and specify the desired permisions (that's what @thinkingserious demonstrated in his [previous comment](https://github.com/sendgrid/sendgrid-csharp/issues/657#issuecomment-362034241)). Not only that, but you need to make sure that you are connected using your username+password (AKA basic authentication) in order to ensure you are authorized to create an API Key with all permissions. Also, @thinkingserious 's code sample has hard-coded the desired permissions but I personally try to avoid that and instead my preferred logic is to fetch the permissions granted to the current user and to use those when creating the new Api Key (FYI:  a few months ago someone was working on improving the SendGrid C# client to make it easier to manage permissions and I gave him [the same advice](https://github.com/sendgrid/sendgrid-csharp/issues/555#issuecomment-338490002) but I don't know the status of his effort).

The StrongGrid library simplifies this whole situation by making it easy to connect using "basic auth" and with a convenient `CreateWithAllPermissionsAsync` method to create a new API Key with all permissions. Like so:

```csharp
// STEP 1: use basic auth to authenticate
var username = "MyUser";
var password = "MySecretP@ssw0rd";
var clientWithBasicAuth = new StrongGrid.Client(username, password);

// STEP 2: create a new Api Key with all permissions
var newApiKey = await clientWithBasicAuth.ApiKeys.CreateWithAllPermissionsAsync("My new key with all permisssions").ConfigureAwait(false);

// Step 3: use the newly created key to connect
var client = new StrongGrid.Client(newApiKey.Key);

// Step 4: issue whatever request you want and there shouldn't be any 'access denied' problems
var userCredits = await client.User.GetCreditsAsync().ConfigureAwait(false);
await log.WriteLineAsync($"Usage: {userCredits.Used}/{userCredits.Total}. Next reset: {userCredits.NextReset}").ConfigureAwait(false);
```

**Comment by thinkingserious** [comment]
Thanks for the detailed response @Jericho!

**Comment by onionhammer** [comment]
Sorry guys - I've been slammed and havent had a chance to get back to this until now.

@thinkingserious @Jericho 
Thanks for this, but I'm not sure it helps me in this specific circumstance because I dont even have a username + password for sendgrid; that's all managed via Azure. I can manage our sendgrid subscription by clicking through to Azure, but all the authentication is done seamlessly.

**Comment by thinkingserious** [comment]
@onionhammer,

I don't think [this document](https://docs.microsoft.com/en-us/azure/sendgrid-dotnet-how-to-send-email) is completely up to date, but I'm hoping it points you in the right direction regarding finding your username and password inside of the Azure portal.

**Comment by onionhammer** [comment]
@thinkingserious is there any update on when this will be available through the standard sendgrid permission system?

**Comment by thinkingserious** [comment]
Hi @onionhammer,

Unfortunately, I don't have any update. What helps is additional +1's and comments. Thanks!

With Best Regards,

Elmer

**Comment by branditodesign** [comment]
+1 for this
