### ISSUE TITLE
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by florydev** [sendgrid/sendgrid-csharp#659]
#### Issue Summary

I have a website that is hosted and am using the API (v9.9.0 from Nuget).  It works fine in every environment but the hosting provider.  

I get this for every call:
[SocketException (0x274c): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 159.122.219.36:443]

For example: 
            var response = await Client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "campaigns/" + campaignId + "/schedules");

Although I suspect that the problem is on my host, I want to understand what the problem is.

**Comment by florydev** [comment]
I setup a proxy and it worked just fine.

**Comment by thinkingserious** [comment]
Thanks for the update!
