### ISSUE TITLE
How to add return-path header?

### ISSUE THREAD

**Issue by Mikarus** [sendgrid/sendgrid-csharp#661]
Hello,

When i try to add an header wil mail.headers.add("return-path",xxxxx); I've got an error.
Then I tried thru personnsalization and the email is not sent.
What is the proper way to add the return path to an email?

Thanks

Michael

**Comment by thinkingserious** [comment]
Hello @Mikarus,

I believe you need `mail.AddHeader("return-path",xxxxx)`, assuming `mail` is a `SendGridMessage()` object.

Please see [this example](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#kitchen-sink---an-example-with-all-settings-used).

With Best Regards,

Elmer
