### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by maxbeaudoin** [sendgrid/sendgrid-csharp#662]
#### Issue Summary

Calling the SendGrid Web API over HTTPS from ASP.NET result in `Authentication failed because the remote party has closed the transport stream`.

We debugged for hours. It works within a console app or IIS site when the user is admin. Otherwise, we get the `IOException` above.

We tried setting `ServicePointManager.SecurityProtocol` without success.

It seems it has to do with permissions. I think AppPoolIdentity can't read the appropriate certificate but I don't how to fix this. Any idea?

#### Technical details:

* sendgrid-csharp Version: 9.9.0
* Platform (Windows Server 2012 R2, IIS 8.5)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
I'm sorry to hear about this :(

Have you [tried the solutions](https://stackoverflow.com/questions/30664566/authentication-failed-because-remote-party-has-closed-the-transport-stream) offered here?

**Comment by sareenkumar** [comment]
I am facing the same issue , even after adding the above Solution (  tried the solutions  )

**Comment by thinkingserious** [comment]
Hello @sareenkumar,

Can you please open a ticket with our [support team](https://support.sendgrid.com)? Thank you!

With Best Regards,

Elmer
