### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by warrenkc** [sendgrid/sendgrid-csharp#664]
How can I send an email to multiple email addresses and in the body of the message show their email address?
Is this possible with the "Mail Helper Class"?

Thanks!

**Comment by thinkingserious** [comment]
Hi @warrenkc,

I think the [use cases](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#table-of-contents) here should help. 

Thanks!

With Best Regards,

Elmer

**Comment by warrenkc** [comment]
Thanks.
