### ISSUE TITLE
Investigate Creating Non-Async SendEmail Method

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#666]
#### Issue Summary

Add a warning to the TROUBLESHOOTING file regarding this code:

```visualbasic
Dim bSuccess As Boolean = client.SendEmailAsync(msg).Wait(10000)
```
This will return true on failure.

Instead, you should examine the text generated from the Body, the value of the `System.Net.Http.StreamContent` object that `client.SendEmailAsync` returns, like [this](https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh781239(v=win.10)). A status of 202 with an empty body indicates success.

**Comment by Jericho** [comment]
Why do you feel that you need to warn VB developers about their incorrect code? The `SendEmailAsync` method __does not__ return a Boolean value, therefore attempting to assign the result of this method to a Boolean variable will have unpredictable result. In fact, I'm surprised Visual Studio allows this code. There must be some implicit conversion between the `Response` class and `bool`.

**Comment by thinkingserious** [comment]
After circling back with the customer, the real ask is to provide a non-async implementation, `SendEmail`.

**Comment by SynerSoft** [comment]
The code line was taken from the provided sample code:
Dim bSuccess As Boolean = client.SendEmailAsync(msg).Wait(10000)
Which appeared to be the onlysample which did not require Async/Await contamination.

The Boolean is returned by the .Wait and not the .SendEmailAsync so it does not apply to the success of SendEmailAsync.

The ask if for a **non-async** example which returns a useful status result.

**Comment by thinkingserious** [comment]
Thanks for the clarifying comment @SynerSoft!

**Comment by danhowelldev** [comment]
Is someone able to clarify why awaiting the client.SendEmailAsync call doesn't return a result? 

eg: var result = await client.SendEmailAsync(msg);

**Comment by SynerSoft** [comment]
In order to use Await, I had to convert my function to Asynchronous.  And the page itself, and the function which called it.  and any which called those.  Results in a bunch of duplicate routines.  

Hence the term "Async/Awate Code Contamination"  It spreads like a virus.

It was manageable for a simple 'Password Reminder' ASP.Net page, but when I tried to implement a similar approach to an 'Order Acknowledgement' email at the end of a longer chain of business logic...  then I was duplicating much more than some utility routines..  I'm new to Async programming, and was hoping I'd missed something that this group could point out.  

The one non-async call I found in the SendGrid sample code involved the addition of ".Wait(10000)" to the end of the call as: 

``

**Comment by samip5** [comment]
What is the current status of this as of 2019?

**Comment by childish-sambino** [comment]
Given that `SendEmailAsync` _and_ `RequestAsync` both use `.ConfigureAwait(false);`, is the answer here to just access the result so it blocks safely until there is a result ([reference](https://stackoverflow.com/a/22629216/1660457))? E.g.,

```c#
var result = client.SendEmailAsync(msg).Result;
```

**Comment by warrenkc** [comment]
I also would like to know the correct way to send an email with SendGrid's c# library from a Synchronous method. 🤔

Which of the three methods below is correct? Which one will not crash my Asp.net WebForms App that is using Synchronous methods?
`static void SendSampleEmailSync()
        {
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("123@sink.sendgrid.net", "example user");
            var subject = "Sending with Twilio SendGrid is Fun";
            var to = new EmailAddress("123@sink.sendgrid.net", "example user");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);

            // Method 1
            var task = Task.Run(() => client.SendEmailAsync(msg));
            var result = task.Result;

            // Method 2
            var result2 = client.SendEmailAsync(msg).Result;

            // Method 3
            _ = client.SendEmailAsync(msg);
        }`

**Comment by childish-sambino** [comment]
@warrenkc See my [comment above](https://github.com/sendgrid/sendgrid-csharp/issues/666#issuecomment-672142544).

**Comment by warrenkc** [comment]
@childish-sambino  Thank you. Is that the correct way? Your comment ends in a question mark leading me to believe you are not sure if it is correct.
Quote:
Given that SendEmailAsync and RequestAsync both use .ConfigureAwait(false);, is the answer here to just access the result so it blocks safely until there is a result (reference)**?** E.g.,

**Comment by childish-sambino** [comment]
@warrenkc AFAIK, that's the proper way. This is a general C# question and not something specific to this library.

**Comment by warrenkc** [comment]
Awesome. Thank you.
