### ISSUE TITLE
Creating Transactional Templates results in a bad request malformed json

### ISSUE THREAD

**Issue by 06needhamt** [sendgrid/sendgrid-csharp#668]
#### Issue Summary

Creating a transactional template version with the following code results in a malformed json error

``` c#
string data = @"{
  'active': 1, 
  'html_content': '<%body%> <p> Test </p>' , 
  'name': 'example_version_name', 
  'plain_content': '<%body%> Test', 
  'subject': '<%subject%> Test Subject', 
  'template_id': 'guid'
}";
var json = JsonConvert.DeserializeObject<Object>(data);
data = json.ToString();
var template_id = "guid";
var response = await client.RequestAsync(method: SendGridClient.Method.POST, urlPath: "templates/" + template_id + "/versions", requestBody: data);
Console.WriteLine(response.StatusCode);
Console.WriteLine(response.Body.ReadAsStringAsync().Result);
Console.WriteLine(response.Headers.ToString());
Console.ReadLine();
```

#### Steps to Reproduce

1. Perform this Request
2. Malformed json response is returned

Expected template version to be successfully created

#### Technical details:

* sendgrid-csharp Version: 9.9.0
* Platform ASP.NET
* .NET Version: 4.6.2

**Comment by thinkingserious** [comment]
Hi @06needhamt,

Can you please take a look at [this example](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates)? Hopefully that's the use case you need.

With Best Regards,

Elmer

**Comment by 06needhamt** [comment]
I've created PR #669 to fix the documentation as per support request https://support.sendgrid.com/hc/en-us/requests/1382463?flash_digest=6a468b8f19e66f1d040d6363d45d233430c64c03

**Comment by thinkingserious** [comment]
Thanks @06needhamt!
