### ISSUE TITLE
SendgridClient constructor issue

### ISSUE THREAD

**Issue by vlmironoff** [sendgrid/sendgrid-csharp#670]
I'm trying to provide a DI controlled HttpClient object (singleton) to the constructor of SendgridClient to overcome known socket exhausting issue by reusing the instance of the aforementioned HttpClient.
The first email sends just fine, however the second one fails with this exception:

> InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.

Having done additional research I figured that a single instance of HttpClient allows changing its configuration properties (BaseAddress in particular) only before the 1st connection is made with this instance. Trying to modify BaseAddress property after HttpClient was used causes this exception to be thrown.
Referenced SO post: 
https://stackoverflow.com/questions/42235677/httpclient-this-instance-has-already-started

I went to the source code of SendgridClient and found out that the constructor of SendGridClient calls InitiateClient function which resets the BaseAddress of the underlying HttpClient object every time the SengridClient instance is created:
https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGridClient.cs
Line: 157

On one hand one can register an instance of SendgridClient in a DI container, but it defies the intended purpose of having such constructor overload in SendgridClient class, allowing to provide the existing instance of HttpClient.

One way to fix it could be checking if the provided instance of HttpClient already has its params configured and not overwrite them if so.

**Comment by thinkingserious** [comment]
Thanks for reporting this with such detail!

I have added this to our backlog for further investigation.

With Best Regards,

Elmer

**Comment by petmat** [comment]
I have a proposition for how to fix this:

If I'm not mistaken you can get this error only when using the following constructor:
```csharp
public SendGridClient(HttpClient httpClient, string apiKey, string host = null, Dictionary<string, string> requestHeaders = null, string version = "v3", string urlPath = null)
```

It ends up calling the InitializeClient method with the host parameter.

I think there are two ways to fix this:

1. Do not set the BaseAddress if it is already set.
2. Throw an exception if the BaseAddress is already set and is not the same as the host string

Do you have an opinion on which way would be better @thinkingserious ? Can I try to fix this?
