### ISSUE TITLE
Visual Studio 2015 - The default XML namespace of the project must be the MSBuild XML namespace. 

### ISSUE THREAD

**Issue by Saritha535** [sendgrid/sendgrid-csharp#671]
I am trying to add exsiting project to my source project in VS2015 then am getting error like this below.

**Visual Studio 2015 - The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add 
xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. if the project has been authored  in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 fromat.**

Please can anyone help me out of this problem.

#### Technical details:

* VS2015,
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @Saritha535,

I don't know the answer here, but I've added this to our backlog for further investigation.

Thanks for letting us know!

With Best Regards,

Elmer

**Comment by Jericho** [comment]
This question doesn't seem to have anything to do with SendGrid.

@Saritha535 can you explain how your question relates to SendGrid's C# client?

**Comment by xt0rted** [comment]
I think they're trying to add the SendGrid source to their own project, but because it uses the new csproj format VS2015 won't load it (needs VS2017+).

**Comment by thinkingserious** [comment]
Thanks for the clarification @xt0rted!
