### ISSUE TITLE
Substitutions not working as expected

### ISSUE THREAD

**Issue by TomGullen** [sendgrid/sendgrid-csharp#672]
#### Issue Summary

I have two users in my test environment, and am confirming through logging it's sending to two recipients in the below example.

No matter what I do, the HTML in both delivered emails reads:

> Goodbye Name1

I am expecting one to read "Goodbye Name1" and the other to read "Goodbye Name2".

```
    // Subject
    var subject = new List<string>{"Subject -name-"};

    // Content
    var plainTextContent = "Hello -name-";
    var htmlContent = "Goodbye -name-";

    // Substitutions
    var substitutions = new List<Dictionary<string, string>>
    {
        new Dictionary<string, string> {{"-name-", "Name1"}},
        new Dictionary<string, string> {{"-name-", "Name2"}}
    };

    var msg = MailHelper.CreateMultipleEmailsToMultipleRecipients(from,
        tos,
        subject,
        plainTextContent,
        htmlContent,
        substitutions
    );

    // Send, fire and forget
    Task.Run(() => sg.SendEmailAsync(msg));
```

#### Steps to Reproduce

1. Use above code
2. Run for 2 recipients
3. Observe both delivered emails have same substitution

#### Technical details:

* sendgrid-csharp Version:  9.9.0
* ASP.net webforms
* .NET Version: 4.7.0

**Comment by TomGullen** [comment]
Using this method works correctly:

```
    // To details
    var tos = new List<EmailAddress>(
        userDetails.Select(c=> new EmailAddress(c.Item2, c.Item1))
    );
                
    var subject = "-name-, hello!";
    var plainTextContent = "Your name is -name-";
    var htmlContent = "<p>Your name is -name-</p>";

    var msg = MailHelper.CreateSingleEmailToMultipleRecipients(from,
        tos,
        subject,
        plainTextContent,
        htmlContent,
        false
    );

    var pIndex = 0;
    foreach (var userDetail in userDetails)
    {
        msg.AddSubstitution("-name-", userDetail.Item1, pIndex);
        pIndex++;
    }

    Task.Run(() => sg.SendEmailAsync(msg));
```
I see now that the personalisation is per email, and not indexable using the `CreateMultipleEmailsToMultipleRecipients` method.

**Comment by thinkingserious** [comment]
Thanks for circling back with the solution @TomGullen!

**Comment by digitalgym** [comment]
Is there a proper solution for substitutions yet? SendGrid has moved all new templates to handlebars notation.

**Comment by thinkingserious** [comment]
Hello @digitalgym,

Yes! Please follow progress [here](https://github.com/sendgrid/sendgrid-csharp/issues/716).

With Best Regards,

Elmer
