### ISSUE TITLE
Performing SendGrid health check using API

### ISSUE THREAD

**Issue by danhowelldev** [sendgrid/sendgrid-csharp#673]
More of a question than an issue. I am integrating with SendGrid, and would like to create a service "health check" so that I can be aware if there are any issues connecting to SendGrid.

My question is, what is the most suitable endpoint to call to do a status check like so. I have searched the API spec here (https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md), and was considering the /stats endpoint, because I couldn't see any sort of "health" related endpoint.

Any suggestions are greatly appreciated.

#### Technical details:

* sendgrid-csharp Version: Sendgrid 9.9.0 Elmer Thomas
* Platform (ASP.NET Web Api)
* .NET Version: 4.6.2

**Comment by thinkingserious** [comment]
HI @danhowelldev,

Here are a few options:

1. [Official Status Page](http://status.sendgrid.com/) (no API though, but you can subscribe to various alerts at the upper right)
2. You could send an email with [SandBox Mode](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/sandbox_mode.html) turned on.
3. You could also hit one of our other [non mail/send endpoints](https://sendgrid.com/docs/API_Reference/api_v3.html).

I hope that helps!

With Best Regards,

Elmer
