### ISSUE TITLE
Sendgrid throwing 400 bad request intermittently

### ISSUE THREAD

**Issue by kiran00916** [sendgrid/sendgrid-csharp#674]
#### Issue Summary
Sendgrid is throwing 400 bad request 

Send grid response reported an error 
```javascript
{"StatusCode":400,"Body":{"Headers":[{"Key":"Content-Length","Value":["204"]},{"Key":"Content-Type","Value":["application/json"]}]},"Headers":[{"Key":"Connection","Value":["keep-alive"]},{"Key":"Access-Control-Allow-Origin","Value":["https://sendgrid.api-docs.io"]},{"Key":"Access-Control-Allow-Methods","Value":["POST"]},{"Key":"Access-Control-Allow-Headers","Value":["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"]},{"Key":"Access-Control-Max-Age","Value":["600"]},{"Key":"X-No-CORS-Reason","Value":["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]},{"Key":"Date","Value":["Sun, 11 Mar 2018 21:00:01 GMT"]},{"Key":"Server","Value":["nginx"]}]}
```

#### Steps to Reproduce
Calling the api with specific method CreateSingleEmail

#### Technical details:

Send grid response reported an error 

```javascript
{"StatusCode":400,"Body":{"Headers":[{"Key":"Content-Length","Value":["204"]},{"Key":"Content-Type","Value":["application/json"]}]},"Headers":[{"Key":"Connection","Value":["keep-alive"]},{"Key":"Access-Control-Allow-Origin","Value":["https://sendgrid.api-docs.io"]},{"Key":"Access-Control-Allow-Methods","Value":["POST"]},{"Key":"Access-Control-Allow-Headers","Value":["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"]},{"Key":"Access-Control-Max-Age","Value":["600"]},{"Key":"X-No-CORS-Reason","Value":["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]},{"Key":"Date","Value":["Sun, 11 Mar 2018 21:00:01 GMT"]},{"Key":"Server","Value":["nginx"]}]}
```

**Comment by thinkingserious** [comment]
Hi @kiran00916,

Thanks for letting us know!

I have a few more questions to help figure out the problem:

* Have you been able to send any emails successfully?
* Do you mind sharing the source code that generated that error?

Thanks!

With Best Regards,

Elmer

**Comment by kiran00916** [comment]
public class SendGridEmailClient : ISendGridProvider
    {
        private readonly SendGridClient _client;
        private static readonly string FromEmailAddress = ConfigurationManager.AppSettings["Notifications.EmailFromAddress"];
        private readonly TelemetryClient _telemetryClient;
        public SendGridEmailClient(string apiKey, TelemetryClient telemetryClient)
        {
            if (string.IsNullOrWhiteSpace(apiKey))
                throw new ArgumentException("Value cannot be null or whitespace.", nameof(apiKey));
            this._telemetryClient = telemetryClient;
            _client = new SendGridClient(apiKey);
        }

        public async Task SendEmailAsync(string to, string cc, string bcc, string subject, string body)
        {
            if (string.IsNullOrEmpty(to))
            {
                this._telemetryClient?.TrackTrace($"Value cannot be null or empty.{ nameof(to)}");
                throw new ArgumentException($"Value cannot be null or empty.{ nameof(to)}");
            }

            if (string.IsNullOrWhiteSpace(subject))
            {
                this._telemetryClient?.TrackTrace($"Value cannot be null or empty.{ nameof(subject)}");
                throw new ArgumentException($"Value cannot be null or empty.{ nameof(subject)}");
            }
            if (string.IsNullOrWhiteSpace(body))
            {
                this._telemetryClient?.TrackTrace($"Value cannot be null or empty.{ nameof(body)}");
                throw new ArgumentException($"Value cannot be null or empty.{ nameof(body)}");
            }
            var msg = MailHelper.CreateSingleEmailToMultipleRecipients(new EmailAddress(FromEmailAddress) , new List<EmailAddress>(){ new EmailAddress(cc) , new EmailAddress(to) }, subject, null, body);

            var response = await _client.SendEmailAsync(msg);

            if (response.StatusCode != HttpStatusCode.Accepted)
            {
                this._telemetryClient?.TrackTrace($"Send grid response reported an error { JsonConvert.SerializeObject(response)}");
                throw new Exception("Error sending email using sendgrid.");
            }
        }
    }

Here is the code.

**Comment by thinkingserious** [comment]
Hi @kiran00916,

Can you please try [retrieving the specific error message](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error)?
