### ISSUE TITLE
Found conflicts between different versions of "Microsoft.AspNetCore.Http.Abstractions"

### ISSUE THREAD

**Issue by juniormayhe** [sendgrid/sendgrid-csharp#675]
#### Issue Summary

Added Sendgrid to NET Standard project and Visual Studio shows 

```
1>------ Rebuild All started: Project: MyProject, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Http.Abstractions" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Http.Features" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>MyProject -> c:\projects\MyProject\bin\Debug\netstandard2.0\MyProject.dll
1>Done building project "MyProject.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

#### Steps to Reproduce

1. Create a new NET Standard 2.0 project
2. Add a project with a static class and a extension method with these arguments 
```
public static class MyServiceExtension
    {
        private static ILogger<EmailService> _logger;
        public static IServiceCollection AddEmailService(this IServiceCollection services,
            IHostingEnvironment hostingEnvironment,
            IConfiguration configuration)
            services.Configure<EmailSettings>(configuration.GetSection("MySettings"));//this comes from calle's appsettings.json
            //some dummy code
            ...
```
2. Add Nuget package for Microsoft.Extensions.Options.ConfigurationExtensions for services.Configure method
3. Add assembly Microsoft.AspNetCore.Hosting.Abstractions for IHostingEnvironment
4. Add assembly Microsoft.Extensions.Configuration.Abstractions for IConfiguration
5. Add assembly Microsoft.Extensions.Logging.Abstractions for ILogger
6. Add assembly Microsoft.Extensions.DependencyInjection.Abstractions for IServiceCollection

3. Build project and check build output or Error List tab

Two warnings appear:

warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Http.Abstractions"
warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Http.Features" 

#### Technical details:

* sendgrid-csharp Version: 9.9.0
* Platform .NET Standard
* .NET Version: 2.0
* Visual Studio 2017 15.5.7
* Windows 10.0.16299.125

**Comment by thinkingserious** [comment]
Hello @juniormayhe,

Thanks for reporting this!

Does the project still build?

With Best Regards,

Elmer

**Comment by juniormayhe** [comment]
Yes it is building fine. Just worried about these warnings

**Comment by thinkingserious** [comment]
OK, thanks for the clarification. I've added this to our backlog for further investigation.

**Comment by RodDaSilva** [comment]
Has there been any update on this bug?  I am getting it as well with version 9,10 of SendGrid librarty.

**Comment by jwisener** [comment]
Same here, we are getting this as well.

**Comment by nhustak** [comment]
Yeah I have 7 warnings that always come up like this still.  Compiles fine but it clouds the water on looking for real warnings.

**Comment by childish-sambino** [comment]
I've been unable to recreate the issue locally, but I believe it was fixed by https://github.com/sendgrid/sendgrid-csharp/pull/754
