### ISSUE TITLE
Question: Substitution Tags vs Section Tags

### ISSUE THREAD

**Issue by a-tok** [sendgrid/sendgrid-csharp#677]
Hello, 

I have a series of messages that I pass for substitution:

`List<String> messages = new List<String>(){
       "Message 1",
       "Message 2",
       "Message 3"
}`

`StringBuilder messageBuilder =....`
`foreach(String message in messages)`
` messageBuilder.Append(message).Append("\n");`

`sendGridMessage.AddSubstitution("-messages-", messageBuilder.ToString());`
...
`
In the transactional template I created this substitution tag:
-messages-

I was hoping that the end result in the email would be:
...
Message 1
Message 2
Message 3
...
However the end result is, Message 1 Message 2 Message 3 (no line breaks). Would the section tags do the trick? How do I make sure that there are line breaks after each message no matter which email client I use? 
Any suggestions?

Thank You,
Alex

**Comment by thinkingserious** [comment]
Hi @a-tok!

Are these HTML messages? In that case, you would want to use <br /> tags.

With Best Regards,

Elmer

**Comment by a-tok** [comment]
Hi Elmer, 
Yes they are, and `<br />`s work like a charm.

Thanks!!!!
