### ISSUE TITLE
BadRequest if same email address is in the To & BCC fields.

### ISSUE THREAD

**Issue by TolchinJ** [sendgrid/sendgrid-csharp#678]
In our code, we don't know how many To's there will be because it varies.  So, we make a list of To's built from a semi-colon separated string list.  Same with CC and BCC.

```
Dim msg As Helpers.Mail.SendGridMessage
Dim Tos As New List(Of Helpers.Mail.EmailAddress)
For Each addr In EmailTo.Split({";"}, StringSplitOptions.RemoveEmptyEntries)
	Tos.Add(New Helpers.Mail.EmailAddress() With {.Email = addr})
Next

msg = Helpers.Mail.MailHelper.CreateSingleEmailToMultipleRecipients(from, Tos, subject, PlainTextContent, HTMLContent)

			' Add CC addresses
			If CC IsNot Nothing Then
				For Each addr In CC.Split({";"}, StringSplitOptions.RemoveEmptyEntries)
					msg.AddCc(addr)
				Next
			End If

			If BCC IsNot Nothing Then
				For Each addr In BCC.Split({";"}, StringSplitOptions.RemoveEmptyEntries)
					msg.AddBcc(addr)
				Next
			End If

			Dim client As New SendGridClient(ApiKey)
			Dim Response As SendGrid.Response = Await client.SendEmailAsync(msg)
```
Response comes back as BadRequest, but there is no information as to WHY it failed.  It was just through couple hours of trial and error that I found this out.

Why in the heck is it failing just because the same email address is in the TO and BCC line?

I tested by having a single TO address and a single BCC address that matches.  Then I get the error.
It works fine without a BCC and it works fine if the addresses are different.

**Comment by thinkingserious** [comment]
Hi @TolchinJ,

Thanks for reaching out and I’m sorry about the frustration.

[Here](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error) is how to view error messages returned by the API. We are definitely open to suggestions on how to make that process better.

[Our API](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html) does not allow for duplicate emails among the to, cc and bcc fields.

I hope that helps!

With Best Regards,

Elmer

**Comment by MohammedMubeen** [comment]
Hi @thinkingserious ,

Sendgrid using send through the mail - return Bad request, for that reason mail not receiving the end user., after I analyzed, To and BCC same email address is I given. after reading your reference link, In that case, sendgrid does not allow to send duplicate mail.

Please help, at least it's possible to reach mail to end-user, like Gmail. 

eg: for Gmail to, cc, bcc same email address, Gmail consider one email to end-user reach the mail, its possible sendgrid?

**Comment by ct-ferozakbar** [comment]
@thinkingserious hi there, im using v3 rest api, the mail which im tryting to send is having same email in both TO and CC , but when i checked the sendgrid acitvity logs in web but no mails were sent to any of the user (to/cc). can please tell us why?

**Comment by mikemad** [comment]
Why is it not allowed to have the same email on TO and CC/BCC. I'm not aware that this is disallowed in any specification.

**Comment by childish-sambino** [comment]
From https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html:
> Each unique email address in the personalization block should only be included once.

I don't know _why_ that's the case, but it is.

Closing as this is a limitation of the API that cannot be overcome in this repo.

**Comment by micktion** [comment]
@thinkingserious this is completely artificial limitation SendGrid is creating.  Email normally doesn't have limitations like this.  I would imagine there are many systems out there that allow users to enter the same email address for multiple users in the system and when posting emails would trip over a limitation like this.  It also seems rather inconsistent as you seem to allow an email address to repeated many times in either the To or CC fields, if I'm understanding the issue exactly the SendGrid API only returns this error when the same email address is in both the To and CC/BCC fields?

**Comment by vgofaizen** [comment]
This limitation makes no sense

**Comment by brodyhoskins** [comment]
Suffering from this issue in 2021.
