### ISSUE TITLE
SendEmailAsync throws Aggregate Exception when awaited

### ISSUE THREAD

**Issue by OmegaAphex** [sendgrid/sendgrid-csharp#679]
#### Issue Summary

Upon using the SendEmailAsync and awaiting the response, an AggregateException: Error while copying content to a stream. is thrown. I have managed to reproduce this.

This issue occurs when the API key is invalid while trying to send an email.

`1 - var response = client.SendEmailAsync(msg).Result;`
`2 - if (!response.StatusCode.Equals(System.Net.HttpStatusCode.Accepted))`
`3 - {`
`4 -      throw new SendGridException(response.Body.ReadAsStringAsync().Result, response.StatusCode);`
`5 - }`
`6 - else`
`7 - {`
`8 -      return response.Headers.GetValues("X-Message-Id").FirstOrDefault();`
` 9 - }`

**Scenario 1** (Works as expected)
Api Key is invalid, body is text/plain. Aggregate exception is not thrown and it continues to line 4 as expected with the result code equal to Unauthorized

**Scenario 2** (Where the issue is generated)
Api Key is invalid, body is text/html. Aggregate exception is thrown on line 1.

Error message: One or more errors occurred.Error while copying content to a stream.  Unable to read data from the transport connection: The connection was closed.  

#### Technical details:

* sendgrid-csharp Version: 9.9.0
* Platform (ASP.NET)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Thanks for reporting this @OmegaAphex, I've added this to our backlog for a fix.

**Comment by Jericho** [comment]
Exception thrown when attempting to read the body of response from Sendgrid when the request contains an invalid API key???

This sounds an awful lot like issue #648 which is caused by a mismatched between the `Content-Length` header and the actual content of the response.

**Comment by thinkingserious** [comment]
Thanks for pointing us in the right direction @Jericho!

**Comment by OmegaAphex** [comment]
Thanks for the information, will take a look at issue #648

**Comment by OmegaAphex** [comment]
I have gone through issue #648 and it seems that this issue is seamlessly identical @thinkingserious do you have an estimate when this issue shall be tackled?

**Comment by thinkingserious** [comment]
Hello @OmegaAphex,

As it stands currently, I don't have a clear estimate. However, that issue can get prioritized much faster if a PR were to be created. Also, additional +1's and comments help make the issue rise in our backlog. Your best bet right now regarding status updates is to follow #648 for updates. 

With Best Regards,

Elmer

**Comment by Jericho** [comment]
@thinkingserious does the API team intend to fix the underlying issue which the mismatch between the value in the `Content-Length` header and the actual size of the response content?

@OmegaAphex I suggest you switch to [StrongGrid](https://www.nuget.org/packages/StrongGrid/) which is an alternative to SendGrid's C# client. The reason why I suggest it is because it does not suffer from this issue (disclaimer: I'm the author).

**Comment by thinkingserious** [comment]
@Jericho,

It's on their radar, but I don't have a ETA. 

Every time there is a new request for this issue, that helps with priority.

**Comment by OmegaAphex** [comment]
@Jericho thanks for your suggestion, will discuss this with my team. In the mean time I will follow #648 as @thinkingserious suggested.

**Comment by thinkingserious** [comment]
Please see issue #648.
