### ISSUE TITLE
The API doesn't return async call - SendGrid C#

### ISSUE THREAD

**Issue by alexsanderauvo** [sendgrid/sendgrid-csharp#680]
#### Issue Summary

I'm developing an integration with sendgrid using the C#'s sendgrid library, when I call SendGridClient.SendEmailAsync(), the method doesn't return any result, and the code on mode debug dont continue.

below is a snippet of code

**method for populing the message**
![image](https://user-images.githubusercontent.com/37444759/37522269-2ec292da-2902-11e8-9e88-9d0de25de142.png)

**Execute()**
![image](https://user-images.githubusercontent.com/37444759/37522363-6b59a6a2-2902-11e8-956b-e6577633a137.png)

#### Steps to Reproduce

1. Fill the message's variable
2. Call execute()
3. Note that debugging does not continue

#### Technical details:

* sendgrid-csharp Version: Last version. Installed on 16/03/2018 or 03/16/2018
* Platform ASP.NET MVC 5
* .NET Version: 4.6.1

**Comment by thinkingserious** [comment]
Please try:

`var result = Execute().Wait();`

**Comment by xt0rted** [comment]
You should use `.GetAwaiter().GetResult()` to call an `async` function synchronously but you should avoid doing that if possible. Changing the calling methods to also be `async` is the best fix.

**Comment by thinkingserious** [comment]
Hello @alexsanderauvo,

Were you able to get up and running?

**Comment by guscar** [comment]
Hi, I was having the exact same problem and @xt0rted 's answer fixed it in my case, the emails now get sent.

Just thought I'd give you guys an update since the issue opener didn't respond any further.
