### ISSUE TITLE
Unauthorized response when attempting to send email c#

### ISSUE THREAD

**Issue by AMSLimited** [sendgrid/sendgrid-csharp#683]
#### Issue Summary
I am always getting unauthorized response code

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

Running the code below to test SendGrid:

var ApiKey = WebConfigurationManager.AppSettings["SendGridApiKey"];
                var client = new SendGridClient(ApiKey);
                var from = new EmailAddress("test@example.com", "Example User");
                var subject = "Sending with SendGrid is Fun";
                var to = new EmailAddress("someemail@gmail.com", "Example User");
                var plainTextContent = "and easy to do anywhere, even with C#";
                var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
                var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
                var response = await client.SendEmailAsync(msg);

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @AMSLimited,

This likely means that either your `ApiKey` is not being set properly. Can you verify the value of `ApiKey` before you pass it into `SendGridClient`? Thanks!

With Best Regards,

Elmer

**Comment by MarcoNicolodi** [comment]
Same here:

```csahrp
public class SendGridSender : IEmailSender
    {
        private readonly SendGridClient _client;
        private readonly IMapper _mapper;

        public SendGridSender(string apiKey, IMapper mapper)
        {
            _client = new SendGridClient(apiKey);
            _mapper = mapper;
        }
        
        public async Task SendAsync(EmailDTO email)
        {
            var message = _mapper.Map<SendGridMessage>(email);
            message.AddTo(email.To.ToString());
            await  _client.SendEmailAsync(message);
        }
    }
``` 

I tried both setting the API Key through the application and env variables. 

SO: Ubuntu 18.04 LTS
SendGrid package: 9.9.0
Framework: dotnet core 2.1.301

**Comment by AMSLimited** [comment]
Got it to work now. 

Thanks.

**Comment by lilhamad** [comment]
It worked when used my api directly without using environment variable 
like this
string apiKey = "SG....."

**Comment by magnuskarlssonhm** [comment]
Had the same error, noted that the API key get some escape characters when you paste into the config file. Like this "SendgridApiKey": "/"SG.sgha8327h
