### ISSUE TITLE
Feedback: Email Activities API

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#685]
I have been experimenting with the new Email Activities for a few days and I have a few observations.

**1. Poor performance**
Generally speaking, SendGrid's API performs quite well and we receive a response within a few milliseconds but this endpoint is by far the slowest endpoint of the entire API. For example, a simple request to get the most recent email activities `GET https://api.sendgrid.com/v3/messages?limit=20&query= HTTP/1.1` takes about 7 seconds to return the result (timing calculated by Fiddler):

```
Request Count:   1
Bytes Sent:      438		(headers:438; body:0)
Bytes Received:  2,385		(headers:793; body:1,592)

ACTUAL PERFORMANCE
--------------

This traffic was captured on Sunday, April 8, 2018.

ClientConnected:	19:03:07.502
ClientBeginRequest:	19:03:07.768
GotRequestHeaders:	19:03:07.768
ClientDoneRequest:	19:03:07.768
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	19:03:07.596
FiddlerBeginRequest:	19:03:07.768
ServerGotRequest:	19:03:07.769
ServerBeginResponse:	19:03:14.790
GotResponseHeaders:	19:03:14.790
ServerDoneResponse:	19:03:14.790
ClientBeginResponse:	19:03:14.790
ClientDoneResponse:	19:03:14.791

	Overall Elapsed:	0:00:07.022
```

Retrieving the email activities for a specific message also take about 7 seconds:

```
Request Count:   1
Bytes Sent:      481		(headers:481; body:0)
Bytes Received:  1,841		(headers:793; body:1,048)

ACTUAL PERFORMANCE
--------------

This traffic was captured on Sunday, April 8, 2018.

ClientConnected:	19:03:07.502
ClientBeginRequest:	19:03:23.172
GotRequestHeaders:	19:03:23.172
ClientDoneRequest:	19:03:23.172
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	19:03:07.596
FiddlerBeginRequest:	19:03:23.172
ServerGotRequest:	19:03:23.172
ServerBeginResponse:	19:03:29.867
GotResponseHeaders:	19:03:29.867
ServerDoneResponse:	19:03:29.867
ClientBeginResponse:	19:03:29.867
ClientDoneResponse:	19:03:29.867

	Overall Elapsed:	0:00:06.695
```

**2. Missing response schema documentation**
There was a clear effort to document this new endpoint (thank you for that!) but unfortunately there were a few critical omissions.

The most critical missing documentation is the response json schema for [Filter all messages](https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages) and [Filter messages by message ID](https://sendgrid.api-docs.io/v3.0/email-activity/filter-messages-by-message-id). The documentation currently says "No response body" which clearly is not accurate since these methods return data formatted as json.
![image](https://user-images.githubusercontent.com/112710/38484334-40c1a426-3ba4-11e8-9070-a4a586f9f1a2.png)

**3. Inconsistent event types**
The various event types are very clearly [documented](https://sendgrid.com/docs/API_Reference/Webhooks/event.html#-Event-Types) in the webhooks chapter on SendGrid's website therefore I expected that the event types in email activities would be the same. Unfortunately that's not always the case. The most obvious example of inconsistent event type is the type that represent an email that couldn't be sent (i.e. 'dropped'). 
- when the json data is sent in a webhook, the event type is `dropped`
- when the json data is returned from 'EmailActivities - Filter all messages', the event type is `not_delivered`
- when the json data is returned from 'EmailActivities - Filter messages by ID', the event type is `drop`

**4. Seemingly duplicate fields documented in 'Query reference'**
This [section](https://sendgrid.com/docs/API_Reference/Web_API_v3/Tutorials/getting_started_email_activity_api.html#-Query-reference) documents a field called `status` and another called `events`. The 'unencoded example' for both fields is the same: `status="processed"`. Is there a subtle difference between these two fields or is this just an inadvertant duplication?

**5. Unclear operator reference**
Most of the [keywords and operators](https://sendgrid.com/docs/API_Reference/Web_API_v3/Tutorials/getting_started_email_activity_api.html#-Keywords-and-Operator-reference) are self explanatory but there are some that puzzle me. For instance:
- Mathematical operators (-, +, /, *): all the fields documented in the Query reference contain `string` data therefore I don't see how we can execute mathematical calculations. *UPDATE 4/30/18* I figured out that there are two numerical fields: opens_count and clicks_count. 
- DateTime operators (YEAR, MONTH, DAY, HOUR, MINUTE, SECONDS). The only field containing a data that is documented in the Query Reference is `last_event_time` therefore I'm assuming these operators only apply to this field. Also there are no examples to demonstrate how to use these operators so, again, I am assuming they work like this: `YEAR(last_event_time) = 2018`. Does this look right?
- Boolean operators (TRUE, FALSE). I don't see any field containing boolean value listed in the Query reference so I don't know what's the use for these operators.
- Misc (INTERVAL, IS, IS NOT). How do we use the 'Interval' operator? How do we use the 'Is' and 'Is not' operators?

**6. Dubious english in the 'Keywords and Operator reference' section**
I'm sure this is just a draft that will be improved but I want to point out that the first paragraph of the [Keywords and Operator reference](https://sendgrid.com/docs/API_Reference/Web_API_v3/Tutorials/getting_started_email_activity_api.html#-Keywords-and-Operator-reference) section doesn't make much sense. Here's an example: "If the character used as the delimiter if it is found within the string."

**7. Incorrect documentation of 'Download CSV'**
The documentation says:

> Download the CSV that you requested with the POST Request a CSV.

Which leads you to believe that sending a `GET` request to `/messages/download/{download_uuid}` will download the CSV file. But that's not the case. Instead, you get json that looks like this: 

```
{
    "presigned_url":"https://sendgrid-rts-production-csv.s3.us-west-2.amazonaws.com/3ac2a6b0-d2d1-4b40-8c24-cf4d15c70466.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=<REDACTED>&X-Amz-Date=20180409T080918Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=f9c99cc3a03cb8edc3921f0882ac705986e03dcb9f2725ecdfb60666f06e00af"
}
```

As you can see, this json contains the URL where the file is located. You must write your own code to actually download the CSV file.

**8. Convoluted process to download the CSV**
After you made the request for your CSV file, you need to patiently wait for an email from SendGrid which looks like this:
![image](https://user-images.githubusercontent.com/112710/38486384-d8eae66c-3baa-11e8-8321-124d0dd33406.png)

As you can see, the UUID is not readily available in the content of the email. What you need to do is right-click on the blue 'Download' button and select 'Copy hyperlink' which will place a link in your clipboard that looks like this: `https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.sendgrid.com%2Femail_activity%2Fdownload%3Fdownload_uuid%3D87b9e3e1-dxa2-4x21-88x0-e1ba3741ea26%26utm_campaign%3Dwebsite%26utm_source%3Dsendgrid.com%26utm_medium%3Demail&data=02%7C01%7C%7C884cc3bc1cb245dcd63e08d59df0f087%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636588580504665993&sdata=AOHKitG%2BN95FJPVBr0OSBGiyZiabbnqhjI%2BONjv6PmQ%3D&reserved=0`. You then need to extract the value near 'download_uuid' taking great care to exclude encoded characers such as `%3D`, `%26`, etc. Now that you have your UUID, you can send a GET request to `/messages/download/{download_uuid}` which will return the URL of the csv file and finally you can write C# code to actually download the file.

This process is convoluted and, to make matters worse, involves some manual steps which means that downloading the csv file cannot be fully automated.

**Comment by thinkingserious** [comment]
This is fantastic feedback @Jericho! Thanks for taking the time to create such a detailed report. 

I'm going to get this visibility internally and follow up with you.

With Best Regards,

Elmer

**Comment by Jericho** [comment]
@ksigler7 can you help with the missing response schema in documentation?

(see my feedback number 2 above)

**Comment by Jericho** [comment]
@thinkingserious can you check with @ksigler7 if she can help regarding the missing information in documentation?

**Comment by ksigler7** [comment]
@Jericho thanks for all of this great feedback! I've added it to our backlog.

Oddly enough, the issue with feedback #2 is in our API docs deployment. The response schema is in the swagger spec, so I am not sure why it is not showing up in the end page. While I am troubleshooting this, here are the schemas:

`GET /messages`:
``` json
{
    "type": "object",
    "properties": {
        "messages": {
            "type": "array",
            "items": {
                "title": "Abbv. Message",
                "type": "object",
                "properties": {
                    "from_email": {
                        "type": "string"
                    },
                    "msg_id": {
                        "type": "string"
                    },
                    "subject": {
                        "type": "string"
                    },
                    "to_email": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string",
                        "enum": [
                            "processed",
                            "delivered",
                            "not_delivered"
                        ]
                    },
                    "opens_count": {
                        "type": "integer"
                    },
                    "clicks_count": {
                        "type": "integer"
                    },
                    "last_event_time": {
                        "type": "string",
                        "description": "iso 8601 format"
                    }
                },
                "required": [
                    "from_email",
                    "msg_id",
                    "subject",
                    "to_email",
                    "status",
                    "opens_count",
                    "clicks_count",
                    "last_event_time"
                ],
                "example": {
                    "from_email": "from@test.com",
                    "msg_id": "abc123",
                    "subject": "anim Duis sint veniam",
                    "to_email": "test@test.com",
                    "status": "processed",
                    "opens_count": 1,
                    "clicks_count": 2,
                    "last_event_time": "2017-10-13T18:56:21Z"
                }
            }
        }
    }
}
```

`GET /messages/{msg_id}`
``` json
{
    "title": "Message",
    "type": "object",
    "properties": {
        "from_email": {
            "type": "string",
            "pattern": "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
        },
        "msg_id": {
            "type": "string",
            "minLength": 5,
            "maxLength": 50,
            "pattern": "^[A-Za-z0-9]+"
        },
        "subject": {
            "type": "string",
            "minLength": 3,
            "maxLength": 255
        },
        "to_email": {
            "type": "string",
            "pattern": "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
        },
        "status": {
            "type": "string",
            "description": "Quick summary of the status of a message",
            "enum": [
                "processed",
                "not delivered",
                "delivered"
            ]
        },
        "template_id": {
            "type": "string",
            "format": "uuid"
        },
        "asm_group_id": {
            "type": "integer",
            "minimum": 1
        },
        "teammate": {
            "type": "string",
            "description": "Teammate's username",
            "minLength": 0,
            "maxLength": 64,
            "pattern": "^$|^[A-Za-z0-9]+"
        },
        "api_key_id": {
            "type": "string",
            "minLength": 3,
            "maxLength": 50,
            "pattern": "^[A-Za-z0-9]+"
        },
        "events": {
            "type": "array",
            "description": "List of events related to email message",
            "items": {
                "title": "Event",
                "type": "object",
                "properties": {
                    "event_name": {
                        "type": "string",
                        "description": "Name of event",
                        "enum": [
                            "bounced",
                            "opened",
                            "clicked",
                            "processed",
                            "dropped",
                            "delivered",
                            "deferred",
                            "spam_report",
                            "unsubscribe",
                            "group_unsubscribe",
                            "group_resubscribe"
                        ]
                    },
                    "processed": {
                        "description": "Date of when event occurred",
                        "minimum": 1292453589,
                        "maximum": 9999999999,
                        "type": "string"
                    },
                    "reason": {
                        "type": "string",
                        "description": "Explanation of what caused \"bounced\", \"deferred\", or \"blocked\". Usually contains error message from the server - e.g. message from gmail why mail was deferred",
                        "maxLength": 1024
                    },
                    "attempt_num": {
                        "type": "integer",
                        "description": "Used with \"deferred\" events to indicate the attempt number out of 10. One \"deferred\" entry will exists under events array for each time a message was deferred with error message from the server. ",
                        "minimum": 1,
                        "maximum": 10
                    },
                    "url": {
                        "type": "string",
                        "description": "Used with \"clicked\" event to indicate which url the user clicked.",
                        "pattern": "^((http[s]?|ftp):\\/)?\\/?([^:\\/\\s]+)((\\/\\w+)*\\/)([\\w\\-\\.]+[^#?\\s]+)(.*)?(#[\\w\\-]+)?$"
                    },
                    "bounce_type": {
                        "type": "string",
                        "description": "Use to distinguish between types of bounces",
                        "enum": [
                            "bounced",
                            "blocked",
                            "expired"
                        ]
                    },
                    "http_user_agent": {
                        "type": "string",
                        "description": "Client recipient used to click or open message"
                    },
                    "mx_server": {
                        "type": "string",
                        "description": "For example mx.gmail.com"
                    }
                },
                "required": [
                    "event_name",
                    "processed",
                    "url",
                    "bounce_type",
                    "http_user_agent",
                    "mx_server"
                ],
                "example": {
                    "event_name": "bounced",
                    "processed": "2017-10-13T18:56:21Z",
                    "reason": "some reason",
                    "url": "http://3LX,MU}N=B8'.....",
                    "bounce_type": "blocked",
                    "http_user_agent": "in tempor ex dolore est",
                    "mx_server": "quis proident"
                }
            }
        },
        "originating_ip": {
            "type": "string",
            "format": "ipv4",
            "description": "This is the IP of the user who sent the message."
        },
        "categories": {
            "type": "array",
            "description": "Categories users associated to the message",
            "items": {
                "type": "string"
            }
        },
        "unique_args": {
            "type": "string",
            "default": "Null",
            "description": "JSON hash of arbitrary key-value pairs"
        },
        "outbound_ip": {
            "type": "string",
            "description": "IP used to send to the remote MTA. Used by UI to display IP in detailed view",
            "format": "ipv4"
        },
        "outbound_ip_type": {
            "type": "string",
            "description": "Whether or not the outbound IP is dedicated vs shared",
            "enum": [
                "dedicated",
                "shared"
            ]
        }
    },
    "required": [
        "from_email",
        "msg_id",
        "subject",
        "to_email",
        "status",
        "template_id",
        "asm_group_id",
        "teammate",
        "api_key_id",
        "events",
        "originating_ip",
        "categories",
        "unique_args",
        "outbound_ip",
        "outbound_ip_type"
    ],
    "example": {
        "from_email": "test@test.com",
        "msg_id": "in aliquip id aliqua",
        "subject": "est incididunt adipisicing pariatur",
        "to_email": "send@test.com",
        "status": "not delivered",
        "template_id": "123e4567-e89b-12d3-a456-426655440000",
        "asm_group_id": 11376349,
        "teammate": "",
        "api_key_id": "sdfsdfsdf123",
        "originating_ip": "2.3.4.5",
        "events": [
            {
                "event_name": "bounced",
                "processed": 1492453589,
                "server_response": "some error message"
            }
        ],
        "categories": [
            "hi",
            "bye"
        ],
        "unique_args": "{'key': 'value'}",
        "outbound_ip": "1.2.3.4",
        "outbound_ip_type": "dedicated"
    }
}
```

**Comment by Jericho** [comment]
Thank you @ksigler7

**Comment by Jericho** [comment]
Has anybody looked at my feedback? 

@ksigler7 : I notice that the documentation issues I highlighted still haven't been fixed.

**Comment by ksigler7** [comment]
@Jericho - yep. It's still in our backlog :) Thanks for checking in about it though.

**Comment by ksigler7** [comment]
(closing since this isn't feedback directly on the C# library)

**Comment by laurence-myers** [comment]
Any update on the API docs? The schema and responses are still not shown for the message activity API endpoints. Which ticket is tracking this, and in which project?

![Screen Shot 2019-07-30 at 10 47 17 am](https://user-images.githubusercontent.com/6336048/62092138-7993cf00-b2b7-11e9-91a8-a58bd06e5f4c.png)

(I'm not using the C# client, but Google brought me here.)

**Comment by vstefanoxx** [comment]
After 1 year and half, all problems are still there.
Documentation is unclear and often plainly wrong.

The [Getting Started document](https://sendgrid.com/docs/for-developers/sending-email/getting-started-email-activity-api/) shows the following example (without url encoding for clarity):
`status="bounced"`
It doesn't work. You can't search bounced events in this way.
The email activity feed on web interface allows only "Delivered", "Not delivered" and "Processing" as status field: there is no bounced status. There is no consistency between the API and the web interface.

The [Email Activity API document](https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages) shows a different syntax for filtering events:
`query=(Contains(events,"processed"))`
It doesn't work as well!

I opened a support request and discovered that I can you the following syntax:
`query=(type="bounce")`
that is undocumented.

Also, in [Email Activity API](https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages) there is the following example:
`last_event_time%3D%E2%80%9C2017-11-07T23%3A13%3A58Z%E2%80%9D`

Why the sequence %3D%E2%80%9C??? It should be %3D%22, because double quotes are %22, while in the example there are the left and righe double quotes as “ and “.

And anyway, also if I use the corrent escape sequence, that query doesn't work and I receive the error:
`operator = is incompatible with DATETIME, STRING`

It is unclear how to join queries with logical operators: can I use parenthesis to build more complex expressions?

All the Email Activity API needs to be revised.

**Comment by PainChopper** [comment]
Hello,

Getting troubles with this as well.

Seems it can handle any quotes - single/double/left-right
spaces, equals are okay too.

> And anyway, also if I use the corrent escape sequence, that query doesn't work and I receive the error:
> `operator = is incompatible with DATETIME, STRING`
> 

I found this only working 
"last_event_time BETWEEN TIMESTAMP '2020-03-01T00:00:00.000Z' AND TIMESTAMP '2020-03-10T00:00:00.000Z'"
As described in https://sendgrid.com/docs/for-developers/sending-email/getting-started-email-activity-api/#filter-by-date-range

The next topic is about two parameters: https://sendgrid.com/docs/for-developers/sending-email/getting-started-email-activity-api/#filter-by-date-range

Probably if you will decode the string:
query=last_event_time BETWEEN TIMESTAMP '2020-03-01T00:00:00.000Z' AND TIMESTAMP '2020-03-10T00:00:00.000Z'AND to_email='send.me@mail.please'
this won't look too bad in your code.
(I haven't tried it yet. My next step ) )

**Comment by julianobach** [comment]
Hello,
I´m trying  call this url https://api.sendgrid.com/v3/messages?limit=1000, but only return forbiden to me., I give full access in my API KEY, when I tried to use the page https://sendgrid.com/docs/API_Reference/api_v3.html I had the same.

Can Someone help me?

Regards

**Comment by childish-sambino** [comment]
@julianobach Have you done this?
> In order to gain access to the Email Activity Feed API, you must purchase [additional email activity history](https://app.sendgrid.com/settings/billing/addons/email_activity).

https://sendgrid.api-docs.io/v3.0/email-activity

**Comment by julianobach** [comment]
> @julianobach Have you done this?
> 
> > In order to gain access to the Email Activity Feed API, you must purchase [additional email activity history](https://app.sendgrid.com/settings/billing/addons/email_activity).
> 
> https://sendgrid.api-docs.io/v3.0/email-activity

@childish-sambino I was reading but I didn´t find this option in send grid, in free and essencial plans have a description "3 Days of Email Activity History", do you know how can I do to check?

**Comment by childish-sambino** [comment]
@julianobach You must purchase _Extend Email Activity History_ for access to this _API_.

**Comment by gmatarbhog-cci** [comment]
@thinkingserious Is there a way to get the full response like @apigirl has posted by just passing the date range and not passing `{{msg_id}}` to the `GET /messages` API? I get few fields in the response if I don't pass the `{{msg_id}}` and if I pass only the date range

**Comment by childish-sambino** [comment]
@gmatarbhog-cci Best to reach out to support as this is not something specific to this library that can be answered.
