### ISSUE TITLE
Email replaced accents with an "i"

### ISSUE THREAD

**Issue by eduardoskeeled** [sendgrid/sendgrid-csharp#686]
We use sendgrid to send emails, and someone received an email (in french language) where the accents were replaced with an 'i'. For example "Vous avez été sélectionné" has become "Vous avez eìteì seìlectionneì". It was the first time and not very common, but I would like to fix it for future cases.

Is this a bug? If it is, can you help me please?

**Comment by thinkingserious** [comment]
Hello @eduardoskeeled,

Was this content in the subject or the body of the email?

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
I'm assuming you are using the latest version of this C# SDK.

Could you please help me verify that this is a SDK issue, by trying to send your email using our interactive docs? https://sendgrid.com/docs/API_Reference/api_v3.html (please use cURL).

Thanks!

**Comment by eduardoskeeled** [comment]
We are using NodeJS.

Yes we're using v3, I've tried the interactive docs, but I can't replicate the bug

**Comment by thinkingserious** [comment]
Hi @eduardoskeeled,

Are you saying you can't replicate the bug in both the SDK and the interactive docs? Or just the interactive docs?

**Comment by eduardoskeeled** [comment]
Hi @thinkingserious,

Yes, as I said earlier, it only happened once, we tried to replicate it on our end, but we couldn't, we checked our templates and everything on our end, but everything we had was showing the right content, except on the client side. And I couldn't replicate it either on the SDK and nteractive docs. It's a really weird one

**Comment by thinkingserious** [comment]
Hello @eduardoskeeled,

Do you know in what email client this happened in?

**Comment by eduardoskeeled** [comment]
Hello @thinkingserious 

No, we don't have that information only that on our templates and on chrome the text was absolutely correct.

Could it be a browser or email client issue?
