### ISSUE TITLE
Email Activities API: authorization required

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#689]
I am issuing the following request to the email activities endpoint:
```
GET https://api.sendgrid.com/v3/messages?limit=20&query= HTTP/1.1
Connection: Keep-Alive
Accept: application/json, text/json, application/xml, text/xml, application/x-www-form-urlencoded
Authorization: Bearer SG.<... omitted for security reasons ...>
User-Agent: StrongGrid/DEBUG (+https://github.com/Jericho/StrongGrid)
StrongGridDiagnosticId: 0edc34f972364f42981d9eab31374128
Host: api.sendgrid.com
```
and I receive the following response:
```
HTTP/1.1 400 BAD REQUEST
Server: nginx
Date: Tue, 01 May 2018 16:17:09 GMT
Content-Type: application/json
Content-Length: 50
Connection: keep-alive
X-Request-Id: 1b7d0ef6-9fd2-4443-b7f3-b96a47cc7562
X-Frame-Options: DENY, DENY
Access-Control-Allow-Methods: HEAD, GET, PUT, POST, DELETE, OPTIONS, PATCH
Access-Control-Max-Age: 21600
Access-Control-Expose-Headers: Link, Location
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: AUTHORIZATION, Content-Type, On-behalf-of, x-sg-elas-acl, X-Recaptcha
Content-Security-Policy: default-src https://api.sendgrid.com; frame-src 'none'; object-src 'none'
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000
X-Ratelimit-Remaining: 9
X-Ratelimit-Limit: 10
X-Ratelimit-Reset: 1525191600

{"errors":[{"message":"authorization required"}]}
```
This error is bizarre since my API key is included in the request. 

Please note that I double checked and I indeed have the `email_activity.read` permission so, as far as I know, I have the necessary permissions to query the email activity endpoint.

**Comment by Jericho** [comment]
I was just in a chat session with Johnny W. and he told me that "Email Activity Feed API" is out of beta and recently went live. which means that we lost access to this endpoint. He stated:

> My API docs state "In order to gain access to the Email Activity Feed API, you must purchase the enhanced storage addon"

This seems to be in contradiction with the billing on my account that says: _all plans include 3 days of email activity history. You can increase this limit for an additional charge_ as seen in this screenshot:

![image](https://user-images.githubusercontent.com/112710/39484859-0371604a-4d45-11e8-97b8-31da99ca5129.png)

Johnny told me:

> The bit you're quoting from the `Settings` > `Plan and Billing Details` menu can certainly be misleading, and I now see why there's confusion: the blub on the billing page is referring to the UI activity feed, rather than the Activity API.

So this means that we get access to 3 days of email activity history in the UI but we don't get any access via the API unless we purchase an addon. I think it's disappointing that that we don't get access to the same data via the API as we do in the UI.

**Comment by branditodesign** [comment]
I don't think your authorisation was correct.
The message I received was this:
`{[{"field":null,"message":"access forbidden"}]}`
The message you received was:
`{"errors":[{"message":"authorization required"}]}`

Although, I received that authorization required message when I had entered my API key incorrectly (didn't wrap it with <<API_KEY>>).

Although 100% agree the 3/30 day activity history is very misleading, we were not informed about the change at all before the changes went live, nor did we receive any notice the 3/30 day email activity thing was even going to happen, it just showed up as soon as they took the buggy new UI out of beta.
