### ISSUE TITLE
Remove multiple recipients from a list

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#690]
I'm noticing that the SendGrid documentation documents a way to [remove a single recipient from a list](https://sendgrid.api-docs.io/v3.0/contacts-api-lists/delete-a-single-recipient-from-a-single-list) but does not mention a way to remove multiple recipients from a list.

However, @hostr recently brought to my attention that issuing a `DELETE
/contactdb/lists/{list_id}/recipients` request and providing an array of contactIds in the body of the request works as you would expect: the recipients are indeed removed from the list.

Here's an example of the request that works fine:

```
DELETE https://api.sendgrid.com/v3/contactdb/lists/3668833/recipients HTTP/1.1
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Accept: application/json, text/json, application/xml, text/xml, application/x-www-form-urlencoded
Authorization: Bearer SG.<... omitted for security reasons ...>
User-Agent: StrongGrid/DEBUG (+https://github.com/Jericho/StrongGrid)
StrongGridDiagnosticId: 01f141454043438ab07c46901cfff14d
Content-Length: 55
Host: api.sendgrid.com

["ZHVtbXkxQGhvdG1haWwuY29t","ZHVtbXkyQGhvdG1haWwuY29t"]
```

@ksigler7 , @thinkingserious is the omission in the documentation simply an oversight or is there a reason we shouldn't use this method?

**Comment by ksigler7** [comment]
@Jericho sorry for the delay in response, I've been on vacation. 

This looks like an oversight to me! This is a great catch @hostr!! and thanks for bringing it to our attention @Jericho!!

I am adding this into the backlog to update our swagger documentation and closing the issue here since this is a docs issue and not specific to our C# library
