### ISSUE TITLE
Empty Cc field will be filled with the last valid Cc entry.

### ISSUE THREAD

**Issue by anbuDW** [sendgrid/sendgrid-csharp#692]
Hi all. Sorry if I am wrong here. The Sendgrid Support send me here...

#### Issue Summary

When a List<Personalization> is filled with personalization Objects from which some contain CC entries and some not, then Sendgrid will fill the E-Mail Header of the Mails without CC entry with the last one which was filled.

#### Steps to Reproduce

First I build my List<Personalization> Object with entries which I parsed from an csv file. The structure will be like this for each Personalization Object:
To - filled
Cc - maybe filled/maybe empty
Bcc - filled
Substitutions - filled with 5 entries
SendAt - filled

Then I build my SendGridMessage Object. This includes:
TemplateId, Subject, From, ReplyTo and the Personalizations  with the List Object from above.

After this, I use the SendGridClient with my APIKey and my SendGridMessage object to send everything to Sendgrid.

The first Email I get is filled correctly, but as soon as I come to one E-Mail which should have an empty Cc field and which was in my List object after an entry with filled Cc field, then I get the Cc entry from the E-Mail before.
I debugged my Console Program and the SendGridMessage Object seems to be filled correctly and also the Json Body which I inspected with Fiddler seems to be correct. Interestingly, the E-Mail with the wrong filled Cc field was not send to the E-Mail written in the Cc field. It just seems to be written in the E-Mail Header. But nevertheless this is a privacy problem, since the Customer sees an E-Mail Address he/she should not know.

#### Technical details:

sendgrid-csharp Version: NuGet Package Version 9.9.0
Platform: Simple Console Program
.NET Version: 4.6.1

Thanks in advance for any help.

Best regards,
Andreas

**Comment by thinkingserious** [comment]
Hello @anbuDW,

It looks like you may be running into [this issue](https://github.com/sendgrid/sendgrid-csharp/issues/480). Could you please take a look and let me know?

Thanks!

With Best Regards,

Elmer

**Comment by anbuDW** [comment]
Hi @thinkingserious,

Thanks for your reply. I don't think that it is the same issue. For each Personalization Object I am doing something like this:

`if (ccs != null)
                {
                    personalization = new Personalization()
                    {
                        Bccs = bccs,
                        Ccs = ccs,
                        Subject = subject,
                        Tos = new List<EmailAddress>() { new EmailAddress(csv.To.Trim()) },
                        Substitutions = substitutions,
                        SendAt = sendAt                    
                     };
                }
                else
                {
                    personalization = new Personalization()
                    {
                        Bccs = bccs,                        
                        Subject = subject,
                        Tos = new List<EmailAddress>() { new EmailAddress(csv.To.Trim()) },
                        Substitutions = substitutions,
                        SendAt = sendAt                    
                     };
                }`

So, normally I am not setting anything to the Cc field. I tried also to explicitly set `Ccs = null
` but it has the same result. 
The json output I get does look okay. The second E-Mail is the one without cc and the json output for it has no cc. Seems right for me. What do you think?

`{"from":{"email":"someEmail"},"subject":"someSubject","personalizations":[{"to":[{"email":"someEmail"}],"cc":[{"name":"","email":"someEmail"}],"bcc":[{"email":"someEmail"}],"subject":"someSubject","substitutions":{someSubstitutions},"send_at":1526035767},{"to":[{"email":"someEmail"}],"bcc":[{"email":"someEmail"}],"subject":"someSubject","substitutions":{someSubstitutions},"send_at":1526035777}],"template_id":"aTemplateId","reply_to":{"email":"someEmail"}}`

Best regards,
Andreas

**Comment by thinkingserious** [comment]
Hi @anbuDW,

It sounds like when you create the new Personalization object, it still retains the values set previously. It looks like you may be using Visual Basic, for which I'm not familiar, so my apologies if my suggestions are way off base. I would try explicitly destroying the object after use so that there is no chance that values are lingering in memory. Although, setting the ccs to null should have been sufficient. 

With Best Regards,

Elmer

**Comment by anbuDW** [comment]
Hi @thinkingserious,

I thought so at first, but the Visual Studio (I am using C#, not visual basic ;) ) debugger showed, that the List<Personalization> Object was filled correctly. Also the json output which was send to the sendgrid api (posted in my last post) seems to be build correctly. In my opinion, this could be a sendgrid backend problem. But I wanted to try it here to check if I or the c# library are doing something wrong.

My Workaround is, that my List<Personalization> Object will hold only one Personalization and I will call the SendEmailAsync() Method for each E-Mail I want to send separately. It is not a nice solution, but it works for me.

Thank you for your time. I think I can close this issue?

Best regards,
Andreas
