### ISSUE TITLE
Question - Sendgrid client - Singleton

### ISSUE THREAD

**Issue by alexmaie** [sendgrid/sendgrid-csharp#695]
Issue Summary

Question, is the SendGridClient thread safe? I see that internally, a new HttpClient is created for each SendGridClient object.  In theory, we should avoid creating too many HttpClients since this is could to socket exhaustion and also it's a documented [antipattern ](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/)

**Comment by thinkingserious** [comment]
Hi @alexmaie,

Please follow [this thread](https://github.com/sendgrid/sendgrid-csharp/issues/521). Thanks!

With Best Regards,

Elmer
