### ISSUE TITLE
mail not sent if subject different than "Sending with SendGrid is Fun"

### ISSUE THREAD

**Issue by vRITHNER** [sendgrid/sendgrid-csharp#696]
#### Issue Summary

I'm testing your API with a console app in which I copied your sample:
```
      var client = new SendGridClient(apiKey);
      var from = new EmailAddress("info@cnote.ch", "cnote");
      var subject = "Sending with SendGrid is Fun";
      var to = new EmailAddress("vrithner@gmail.com", "vrithner");
      var plainTextContent = "and easy to do anywhere, even with C#";
      var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
      var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
      var sendGridResponse = await client.SendEmailAsync(msg);
      sendGridResponse.Dump();
```
The mail is sent correctly with this settings
As soon as I change the subject with even 1 letter, the mail is not send.
Can you explain to me what is the trick here ?

#### Steps to Reproduce

1. Run this in LinqPad
2. Check gmail -> mail arrived
3. Add a '.' to the subject
4. Check gmail -> mail not arrived
5. Remove  '.' into the subject
6. Check gmail -> mail arrived

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (ASP.NET Core API 2.1.0-preview1-final)
 (tried also with with same issue)   * .NET Version: 4.5.2

**Comment by vRITHNER** [comment]
Bye the way, I even tested the same behavior with your ExampleCoreProject.
with :
`var subject = "Hello World from the SendGrid CSharp Library Helper!";`
no mail is sent
with :
` var subject = "Sending with SendGrid is Fun";`
the mail is sent correctly

**Comment by thinkingserious** [comment]
Hello @vRITHNER,

Thanks for reporting this issue!

I can not reproduce this in Visual Studio and I'm not familiar with LinqPad. I'm adding this to my backlog for further investigation.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @vRITHNER,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
