### ISSUE TITLE
Filter JSON requires 1/0 for Enable, but type is bool?. JsonConverter needed.

### ISSUE THREAD

**Issue by myahl** [sendgrid/sendgrid-csharp#698]
https://github.com/sendgrid/sendgrid-csharp/blob/29042f2779e3d14e556ab1a9f20daa40bb5c6e22/src/SendGrid/Helpers/Mail/Model/Ganalytics.cs#L19-L20

The API documentation regarding [filters](https://sendgrid.com/docs/API_Reference/SMTP_API/apps.html) states that "enable" must be 0 or 1. The problem is that `bool?` serializes to true/false, not 1/0. I borrowed the `BoolConverter` solution from [this SO answer](https://stackoverflow.com/questions/14427596/convert-an-int-to-bool-with-json-net/14428145#14428145), but I can't decorate the `Enable` property with `[JsonConverter(typeof(BoolConverter))]` unless I use some kind of wrapper class.
I'm quoting `Ganalytics` here because that's my current frustration, but I would suspect this is an issue in other classes as well.

**Comment by thinkingserious** [comment]
Thanks for reporting this @myahl! 

I have added this to our backlog. For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

**Comment by thinkingserious** [comment]
Hello @myahl,

The reference document you linked to is with respect to our SMTPAPI. For the Web API, please see [this reference](https://sendgrid.com/docs/api-reference).

Thanks!

With Best Regards,

Elmer
