### ISSUE TITLE
ADD BCC USING C#

### ISSUE THREAD

**Issue by matteoannibali** [sendgrid/sendgrid-csharp#703]
I needed to add BCC email inside my personalization element without using JSON notation data as exposed here: https://github.com/sendgrid/sendgrid-csharp/blob/master/examples/mail/mail.cs#L99 

I resolved the issue accessing to my msg class and adding this to the list :

msg.Personalizations[0].Bccs = new System.Collections.Generic.List<EmailAddress>();
msg.Personalizations[0].Bccs.Add(new EmailAddress("c***@****.com"));

Hoping this could be useful...

Best Regards 
Matteo

**Comment by thinkingserious** [comment]
Thanks @matteoannibali!
