### ISSUE TITLE
Microsoft.AspNetCore.Http.Abstractions is unneeded in references

### ISSUE THREAD

**Issue by jelical** [sendgrid/sendgrid-csharp#707]
Please, remove Microsoft.AspNetCore.Http.Abstractions from package references - it is unneeded and creates compatibility frictions

**Comment by thinkingserious** [comment]
Thanks @jelical!

I have added this to our backlog. For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.
