### ISSUE TITLE
200 status code in JAVA

### ISSUE THREAD

**Issue by Premasanthakumar** [sendgrid/sendgrid-csharp#709]
import com.sendgrid.*;
import java.io.IOException;
import com.sendgrid.Content;
import com.sendgrid.Email;
import com.sendgrid.Mail;
import com.sendgrid.Method;
import com.sendgrid.Request;
import com.sendgrid.Response;
import com.sendgrid.SendGrid;
import java.io.IOException;

public class SendEmail {
    public static void main(String[] args) throws IOException {
    Email from = new Email("techadmin@thesyndicate.tech");
    String subject = "Hello World from the SendGrid Java Library!";

    Email to = new Email("premas@thesyndicate.tech");
    Content content = new Content("text/plain", "");
    Mail mail = new Mail(from, subject, to, content);

    SendGrid sg = new SendGrid("SEND_GRID_API");
    Request request = new Request();
    try {

      request.setMethod(Method.GET);
      //request.setEndpoint("mail/send");
      request.setEndpoint("templates/52b06896-52f8-4210-b45c-e7b3775fea3e");
      request.setBody("");

      Response response = sg.api(request);
      System.out.println(response.getStatusCode());
      System.out.println(response.getBody());
      System.out.println(response.getHeaders());

    } catch (IOException ex) {
      throw ex;
    } 
  }
}

Output:
 200

**Comment by thinkingserious** [comment]
#708
