### ISSUE TITLE
The type or namespace name 'SendGrid' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by e2cByock** [sendgrid/sendgrid-csharp#71]
I used the provided sample code....
but I cannot compile...I am getting this error.....even if I have referenced the SendGrid.dll in the project and I have the SendGrid namespace in the using directive...

The type or namespace name 'SendGrid' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ccemeraldeyes** [comment]
I'm getting this error even on 3.0.0.0.0 version. Does anyone know of a solution?

**Comment by Kuldeepte** [comment]
Hi , I am facing the same issue and using .net framework 4.5.2. please help

**Comment by thinkingserious** [comment]
@Kuldeepte,

Could you please explain the steps you took to install? Thanks!

**Comment by robauer** [comment]
I am also experiencing this issue using .net 4.6.1 - do I need to use .net 4.5 to make this work?

**Comment by thinkingserious** [comment]
@robauer,

You can either use 4.5.2 or download and compile the source for 4.6.1.

We are working on a new version of the library which will support 4.5, 4.6 and .NET Core natively. To support that effort, please +1 this thread: https://github.com/sendgrid/sendgrid-csharp/issues/221

Thanks!
