### ISSUE TITLE
AddSubstitutions 

### ISSUE THREAD

**Issue by jitu027** [sendgrid/sendgrid-csharp#711]

**Comment by thinkingserious** [comment]
Hi @jitu027,

Could you please provide some context around the issue? How can we help?

Thanks!

With Best Regards,

Elmer

**Comment by jitu027** [comment]
Hi Elmer ,

Thank you for your response.

We are using Send Grid API to send bulk emails, While sending emails we are
using one tag in mail body and our requirement is to change the tag {*name*}
for different emails and we were unable to change the tag. And this is
working fine for single Email but unable to replace tag in bulk email case.
Please help us in this regard.

Also we are getting an error while creating a dictionary and passing
multiple keys and getting an error as "*In dictionary, you can add unique
key*"

**Comment by thinkingserious** [comment]
Hello @jitu027,

A few more questions to help get you started:

* Are you using [Legacy](https://sendgrid.com/templates) or [Transactional templates](https://sendgrid.com/dynamic_templates)?
* What version of this SDK are you using?

Thanks!

With Best Regards,

Elmer

**Comment by sarahannnicholson** [comment]
I believe the issue is that the Legacy templates used to support personalization/substitutions. 

Do the new Transactional templates support the same feature? I don't see it in the docs anywhere.

**Comment by thinkingserious** [comment]
Thanks for helping out @sarahannnicholson!

**Comment by thinkingserious** [comment]
@sarahannnicholson,

Please follow [this issue](https://github.com/sendgrid/sendgrid-csharp/issues/716) for progress. Thanks!
