### ISSUE TITLE
Special characters in transactional templates 

### ISSUE THREAD

**Issue by RoelVerhees** [sendgrid/sendgrid-csharp#714]
Hi, 

Im currently using SendGrid with transactional templates, and some of my templates have special characters in it, like:

>    vóór or  privé

In all of my templates i added the following line in the header:
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`

When using the nuget package of SendGrid the special characters are not correctly displayed and it outputs question marks in the email. The weird thing is when i'm using the "Send Test" button in the SendGrid portal above each template the special characters are correctly displayed in the email.

After this i used the HttpClient of C# and the Web API of SendGrid, but here i got the same result, question marks again..... 
 
Does anyone have the same problem or what am i doing wrong?

```
			SendGridClient sendGridClient = new SendGridClient("ApiKey");

			SendGridMessage sendGridMessage = new SendGridMessage();
			sendGridMessage.From = new EmailAddress("from@emailaddress.com", "Company name");
			sendGridMessage.TemplateId = "templateId";
			sendGridMessage.AddTo("to@emailaddress.com", "FullName");

			sendGridMessage.Personalizations[0].DynamicTemplateData = new
			{
				RegionHouseNumber = 0,
				EmployeeFirstName = "EmployeeFirstName ",
				ContactMailAddress = "contact@emailaddress.com",
				RegionName = "RegionName",
				RegionStreet = "RegionStreet",
				RegionPostalCode = "RegionPostalCode",
				Subject = "Subject"
			};

			Response response = await sendGridClient.SendEmailAsync(sendGridMessage);
```

**Comment by thinkingserious** [comment]
Hello @RoelVerhees,

Thanks for reporting this, I've added this to our backlog for further investigation.

With Best Regards,

Elmer

**Comment by andrelmp** [comment]
I have this issue and opened a ticket with sendgrid support.
u have to encode the strings on dynamic_template_data with ISO-8859-1 encoding. I know its a poor solution, but works.

**Comment by thinkingserious** [comment]
Thanks for sharing this @andrelmp,

I'll add this to the acceptance criteria to include in the helper.

**Comment by thinkingserious** [comment]
Hello @andrelmp,

I believe this issue is now fixed at the API level. Please let us know if you continue to experience any issues.

With Best Regards,

Elmer

**Comment by chapar-vill** [comment]
Special Characters of French being converted into **black diamond with question mark** into Email on **Server** but at **localhost** everything is ok

Example:- 
Real Word:- Converted into Mail
_d’avoir =     d�avoir
à =              �
procédure = proc�dure_

I have encoded my email body into **UTF-8** then being into **question mark(?)** from **black diamond question mark** as given below...
_d�avoir = d?avoir
à = ?
procédure = proc?dure_

### Following function is being used for encoding into **"UTF-8"**
public string convertUTF(string name)
{
   Encoding objISO = Encoding.GetEncoding("ISO-8859-1");
  Encoding objUTF = Encoding.UTF8;

  // Unicode string.
  string s_unicode = name;

  // Convert to ISO-8859-1 bytes.
  byte[] isoBytes = objISO.GetBytes(s_unicode);

  // Convert to UTF-8.
  byte[] utf8Bytes = Encoding.Convert(objISO, objUTF, isoBytes);

  string utf8str = objUTF.GetString(utf8Bytes);
  return utf8str;
}
