### ISSUE TITLE
Transactional Templates not found by SendGridClient Only Legacy Templates are returned...

### ISSUE THREAD

**Issue by Pieter-1337** [sendgrid/sendgrid-csharp#723]
I Set up a SendGridClient for a project in my company, I have a function which gets all the templates from my SendGridAccount and then picks the right one for a certain mail based on the name of the Template in the SendGridAccount. However SendGridClient only returns Legacy Templates but not the Transactional which I would like to use so I can utilize handlebars, if/else logic etc...

#### Steps to Reproduce
      //THIS METHOD SHOULD RETURN ALL TEMPLATES IN THE SENDGRID ACCOUNT BUT ONLY RETURNS LEGACY TEMPLATES--

public async Task<Dictionary<string, string>> GetTemplateIdsByNameAsync()
{

            var client = GetSendGridClient();
            
      
            var response = await client.RequestAsync(method: SendGrid.SendGridClient.Method.GET, urlPath: "templates");

            ThrowExceptionIfStatusIsNotOk(response);

            var content = await response.Body.ReadAsStringAsync();

            var anonymousTemplatesObject = new { Templates = new[] { new { Id = "", Name = "" } } };

            var templates = _genericJsonSerializer.DeserializeAnonymous(content, anonymousTemplatesObject);

            return templates.Templates.ToDictionary(x => x.Name, x => x.Id);
        }

I would expect the client to return all the templates ore is there a setting I have overlooked?

#### Technical details:

Asp.Net Core
Latest SendGrid Version

**Comment by kgehmlich** [comment]
For those who do not use legacy transactional templates, it suffices to use `https://api.sendgrid.com/v3/templates?generations=dynamic`

**Comment by thinkingserious** [comment]
Thanks for the clarification @kgehmlich!

**Comment by thinkingserious** [comment]
Hello @omissis,

I believe this is on the documentation team's backlog currently. (cc @ksigler7 @Whatthefoxsays)

Thanks!

Elmer

**Comment by alvis** [comment]
Thank you for pointing out. But 6 month+ for adding a small but essential description to the doc is too LONGGG!!!

**Comment by sendgrid-sucks-cocks** [comment]
Perhaps this will get the lazy and extremely overpaid people at SendGrid to pay attention?

SENDGRID SUCKS COCKS

What kind of a miserable company are you if you can't document a critical piece of API for MORE THAN A YEAR?

**Comment by childish-sambino** [comment]
Docs have been updated: https://sendgrid.com/docs/API_Reference/api_v3.html
