### ISSUE TITLE
Substitutions not working when calling the API

### ISSUE THREAD

**Issue by AdTarling** [sendgrid/sendgrid-csharp#725]
#### Issue Summary

I've created an Azuure function that calls a SendGrid template with expected substitutions, but no matter how I approach the substitution code (C# SendGrid library or JSON string) the email template either gets sent with empty substitutions or receives a Bad Request response.

#### Steps to Reproduce

This is the code that creates empty substitutions (JSON string approach):

    var client = new SendGridClient("SendGridAPIKey");
    string data = @"{
              'personalizations': [
                {
                  'dynamic_template_data':{
                      'subject': 'Lorem ipsum',
                      '{{Firstname}}': 'John'
                  },
                  'to': [
                    {
                      'email': 'john@test.com'
                    }
                  ],
                  'subject': 'Test subject'
                }
              ],
              'from': {
                'email': 'test@example.com'
              },
              'content': [
                {
                  'type': 'text/html',
                  'value': 'I\'m replacing the <strong>body tag</strong>'
                }
              ],
              'template_id': 'Template_Id'
            }";
            var json = JsonConvert.DeserializeObject<Object>(data);
            var response = await client.RequestAsync(method: SendGridClient.Method.POST,
                requestBody: json.ToString(),
                urlPath: "mail/send");

And this is the code that throw 400 Bad request (JSON string approach):

var client = new SendGridClient("SendGridAPIKey");
    string data = @"{
              'personalizations': [
                {
                  'substitutions': {
                     '{{Firstname}}': 'John'
                  },
                  'to': [
                    {
                      'email': 'john@test.com'
                    }
                  ],
                  'subject': 'Test subject'
                }
              ],
              'from': {
                'email': 'test@example.com'
              },
              'content': [
                {
                  'type': 'text/html',
                  'value': 'I\'m replacing the <strong>body tag</strong>'
                }
              ],
              'template_id': 'Template_Id'
            }";
            var json = JsonConvert.DeserializeObject<Object>(data);
            var response = await client.RequestAsync(method: SendGridClient.Method.POST,
                requestBody: json.ToString(),
                urlPath: "mail/send");

Pretty frustrating as everything is working other than the substitutions, which seem fragile.  Any help much appreciated.

**Comment by AdTarling** [comment]
Ok, so this is because if you want to use 'dynamic_template_data' you need to mark the templates up with handlebars notation, ie {{Firstname}}, but only specify the variable in the json string, ie Firstname.

**Comment by thinkingserious** [comment]
Hi @AdTarling,

Please [see this issue](https://github.com/sendgrid/sendgrid-csharp/issues/716) for progress on the addition of a helper for this functionality.

With Best Regards,

Elmer

**Comment by MuhammadTanveerAshraf** [comment]
I am facing the same problem and struggling from 2 days to solve it.
**Code:**
{
  "from": {
    "email": "fromEmailAddress"
  },
  "personalizations": [
    {
      "to": [
        {
          "email": "myEmail"
        }
      ],
      "substitutions": {
        "[SiteUrl]": "mySiteUrl"
      }
    }
  ],
  "content": [
    {
      "type": "text/Html",
      "value": "I/\u0027m replacing the \u003cstrong\u003ebody tag\u003c/strong\u003e"
    }
  ],
  "template_id": "templateid"
}
@thinkingserious Could you please take a look in the code above.
