### ISSUE TITLE
X-Message-ID missing from response header

### ISSUE THREAD

**Issue by soccerwiz13** [sendgrid/sendgrid-csharp#726]
#### Issue Summary

When we send email using the V3 end point in sendgrid C# library, we do not get the message ID in the response. Our response header looks like this:
Connection: keep-alive
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
Date: Fri, 17 Aug 2018 17:03:26 GMT
Server: nginx
The documentation states there should be an X-Messsage-ID in the header. What are we missing?

#### Steps to Reproduce

Define Email, send.
SendGridClient client = new SendGridClient(apiKey);
SendGridMessage message = new SendGridMessage();
...
Response response = client.SendEmailAsync(message).GetAwaiter().GetResult();

Response.Headers.ToString();
X-Message-ID is not in the header string! We expect to see it there!

#### Technical details:

* sendgrid-csharp Runtime Version: v4.0.30319
* Platform ASP.NET webservice
* .NET Version: 4.6.1

**Comment by DavidShukvani** [comment]
Hi, I think I have similar issue while trying to send from a transactional template :

BadRequest
Connection: keep-alive
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
Date: Mon, 20 Aug 2018 09:35:06 GMT
Server: nginx

My code:
var client = new SendGridClient(apiKey);
var msg = new SendGridMessage();
msg.SetFrom(new EmailAddress("my sender mail", "name"));
msg.AddTo(new EmailAddress("address to", "name"));
msg.SetTemplateId("template id");

msg.AddSubstitution("-someText-", "substitute");
msg.AddSubstitution("-AnotherText-", "substitute2");

var response = await client.SendEmailAsync(msg);
Console.WriteLine(response.StatusCode);
Console.WriteLine(response.Headers.ToString());
Console.WriteLine("\n\nPress any key to exit.");
Console.ReadLine();

I use 9.9.0 version, retrieved from NuGet.
.NET version: 4.6.1
Platform is ASP.NET MVC

I can supply more specific data if needed to resolve the issue.

Thanks in advance!

**Comment by thinkingserious** [comment]
Hello @soccerwiz13,

You are correct, that header should be present. I am currently in the process of updating the SDK to support #716, I'll look into a fix for this while I'm doing that. 

Hello @DavidShukvani,

I believe [this is the solution](https://github.com/sendgrid/sendgrid-csharp/issues/716) to your issue.

With Best Regards,s

Elmer

**Comment by alacardnightmare** [comment]
Hi @thinkingserious 

Has there been any update on this?

**Comment by thinkingserious** [comment]
Hello @alacardnightmare,

Could you please try v9.10.0 and see if the issue persists?

With Best Regards,

Elmer
