### ISSUE TITLE
BadRequest X-No-CORS-Reason when sending transactional template mail, substitutes are causing failure

### ISSUE THREAD

**Issue by DavidShukvani** [sendgrid/sendgrid-csharp#727]
#### Issue Summary

I am trying to send a transactional template mail to recipient, but get **bad request** error.
When I am removing the substitutes it's working, otherwise no

#### Steps to Reproduce

BadRequest
Connection: keep-alive
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
Date: Mon, 20 Aug 2018 09:35:06 GMT
Server: nginx

My code:
```
var client = new SendGridClient(myApiKey);
var msg = new SendGridMessage();
msg.SetFrom(new EmailAddress("my sender mail", "name"));
msg.AddTo(new EmailAddress("address to", "name"));
msg.SetTemplateId("template id");

msg.AddSubstitution("-someText-", "substitute");
msg.AddSubstitution("-AnotherText-", "substitute2");

var response = await client.SendEmailAsync(msg);
Console.WriteLine(response.StatusCode);
Console.WriteLine(response.Headers.ToString());
Console.WriteLine("\n\nPress any key to exit.");
Console.ReadLine();
```

This is HTML:

```
<html><head>
	<title></title>
</head>
<body style="margin: 0px;">
	-someText-
	<%body%>
	<br />
	-AnotherText-
</body>
</html>
```

I can supply more specific data if needed to resolve the issue.

Thanks in advance!

#### Technical details:

* I use 9.9.0 version, retrieved from NuGet.
* .NET version: 4.6.1
* Platform is ASP.NET MVC

**Comment by thinkingserious** [comment]
Hello @DavidShukvani,

Please see [this issue](https://github.com/sendgrid/sendgrid-csharp/issues/716) for a solution. The `X-No-CORS-Reason` is an expected header.

With Best Regards,

Elmer
