### ISSUE TITLE
CC email issue while sending in Bulk

### ISSUE THREAD

**Issue by avdhoota** [sendgrid/sendgrid-csharp#731]
Hi team,

I am using sendgrid to send emails in Bulk. 
For ex. I am sending an email to 100 users with substitutions in a personalization object. So I am adding 100 personalization object to sendgrid mail object. So with each personalization object, I'm adding CC email id. 
Now users who are in To, getting the email properly, but the user who is CCed gets only one email. Here my requirement is like if I am sending 100 emails to different users, I should get 100 emails too if my email id is in CC.

Kindly let me know the solution for the same. 

#### Technical details:

* sendgrid-csharp Version: master (9.8.0.0)
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by DrMeloMoney** [comment]
Hi there,

In order to get the 100 CCs for the 100 emails that you're sending, you'll want to add the CC in the Personalizations for each email. If you add the CC'd email globally, outside the personalization block, there will only be one email sent. Here is our documentation that might help. [Link here](https://sendgrid.com/docs/for-developers/sending-email/personalizations/) Let me know if you have any questions. 

Thanks,
Zach

**Comment by avdhoota** [comment]
Hi Zach,

Thanks a lot for your reply. As you said I am adding CC email to each personalization object but the email id will be same for each object. can that be a problem?

here is my code,

            foreach (var addressPlusReplacements in BulkMessage.BodyReplacements)
            {
                if (IsValidEmail(addressPlusReplacements.Key.Address))
                {
                    SendGrid.Helpers.Mail.Personalization personalization = new SendGrid.Helpers.Mail.Personalization();
                    foreach (var x in addressPlusReplacements.Value.Item2.Replacements)
                        personalization.AddSubstitution(x.StringToReplace, x.ReplaceWith);
                    personalization.AddTo(emailAddressForSendGrid(addressPlusReplacements.Key));
					personalization.AddCc(new SendGrid.Helpers.Mail.Email("XXX@gmail.com"));
					sendGridMessage.AddPersonalization(personalization);
                    if (addressPlusReplacements.Value.Item1.HasValue)
                        userIDs.Add(addressPlusReplacements.Value.Item1.Value);
                }
            }

Please let me know if I am missing anything.

Thanks,
Avdhoota

**Comment by avdhoota** [comment]
I have tried this too,

			foreach (var personalization in sendGridMessage.Personalization)
			{
				personalization.AddCc(new SendGrid.Helpers.Mail.Email("xxx@gmail.com"));
			}

Still, I'm getting single email only.

**Comment by DrMeloMoney** [comment]
Hi there,

Thanks for sending that over. If you're CC'ing to the same email address, many ESPs like Gmail will dedup emails that have the same message_id. So when you send these emails in one batch, they will all have the same message_id, which will cause the ESP to dedup the emails. Let me know if you have any additional questions. 


Thanks,
Zach
