### ISSUE TITLE
SendGrid C# API template substitution issue

### ISSUE THREAD

**Issue by Seekeer** [sendgrid/sendgrid-csharp#734]
I got transaction template with following subject: `Request at {{receiveDate}}`. But I couldnt send substitution to it.

I am trying following code:

             var msg = new SendGridMessage { };
            msg.From = new EmailAddress(emailFrom.Address.ToLower(), emailFrom.DisplayName);
            msg.AddTo(new EmailAddress("testtest@gmail.com"));
            msg.AddSubstitution("{{receiveDate}}","date");
            msg.TemplateId = ID;
            var result = client.SendEmailAsync(msg).Result;

but got error: `result.StatusCode == BadRequest'. How could I fix that? 
When I comment line with substitution - everything works fine.

**Comment by Leeemons** [comment]
@Seekeer look at issue   #716

**Comment by Seekeer** [comment]
@Leeemons as far as I understand its about dynamic templates. But I want to use templates created on server.

**Comment by thinkingserious** [comment]
Hello @Seekeer,

Please upgrade to version 9.10.0 of this SDK and see [this example](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates).

Thanks!

With Best Regards,

Elmer

**Comment by GiorgioG** [comment]
None of these examples work.  This library is a mess.

**Comment by thinkingserious** [comment]
Hello @GiorgioG,

Do you mind sharing your code so that I may try to reproduce your issue? Thanks!

With Best Regards,

Elmer

**Comment by Rody66** [comment]
It works for me:
```csharp
msg.SetTemplateData(new { receiveDate = date });
```
I think it's more gracefully than method from sample.

**Comment by bortnik-unifyone** [comment]
> It works for me:
> 
> ```cs
> msg.SetTemplateData(new { receiveDate = date });
> ```
> 
> I think it's more gracefully than method from sample.

Use the SetTemplateData method which works fine.
