### ISSUE TITLE
CreateSingleTemplateEmailToMultipleRecipients in MailHelper not available

### ISSUE THREAD

**Issue by joeshepherdmba** [sendgrid/sendgrid-csharp#737]
#### Issue Summary

I am trying to create a single email to multiple recipients using a transaction template. The method for doing this in the MailHelper class does not show up in my code base. None of the Create Template methods show up. 

#### Steps to Reproduce

1. Get a reference to the MailHelper class
2. Create a new msg object and call MailHelper. => only the non-template methods are available

In the end I am trying to get at the Dynamic Template Data Object that is part of a templated message. 

#### Technical details:

* sendgrid-csharp Version: master (9.9.0) (latest commit: dc345bc)
* Platform .net core web api
* .NET Core Version: 2.1.0
<img width="528" alt="mailhelper_scr" src="https://user-images.githubusercontent.com/12962084/45255873-9481eb80-b353-11e8-9e31-1f3baef9b2a7.png">

**Comment by Niladri24dutta** [comment]
@joeshepherdmba most probably you are looking for `CreateSingleTemplateEmailToMultipleRecipients` method of the `MailHelper` class which accepts templateid and dynamic data for dynamic templates . But this method was added as part of version 9.10.0 which is the current version. So you need to upgrade your SDK version to 9.10.0.

@thinkingserious  There seems to be a small typo in the changelog for the current release. The release date is mentioned as `2017-09-12`

**Comment by thinkingserious** [comment]
Good catch @Niladri24dutta and thanks for helping out!

Yes, a PR would be nice :)

**Comment by Niladri24dutta** [comment]
ok I will submit a PR for this

**Comment by Niladri24dutta** [comment]
@thinkingserious  here is the PR #741
