### ISSUE TITLE
'SendGridMessage' does not contain a definition for 'SetTemplateData'

### ISSUE THREAD

**Issue by AndrewTziAnChan** [sendgrid/sendgrid-csharp#740]
When attempting to my compile project, I get the following error output.

'SendGridMessage' does not contain a definition for 'SetTemplateData' and no extension method 'SetTemplateData' accepting a first argument of type 'SendGridMessage' could be found (are you missing a using directive or an assembly reference?)

I used the sample for the new transactional templates using a mail helper class in the use case document:

https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#with-mail-helper-class

I notice that at the time of writing, the use case document was updated just 15 hours ago and the associated changes for transactional templates were merged a week earlier. I assume the latest changes are not yet served as through nuget yet.

**Comment by HindoliyaYogesh** [comment]
Getting the same issue.
If the changes have not yet been served through NuGet yet, is there a timeline on the same?

Cheers,

**Comment by thinkingserious** [comment]
Hello @AndrewTziAnChan, @HindoliyaYogesh

Please try version 9.10.0.

Thanks!

With Best Regards,

Elmer

**Comment by AndrewTziAnChan** [comment]
Issue has been addressed. Thank you.
