### ISSUE TITLE
Mismatching dependencies between csproj and nuspec 

### ISSUE THREAD

**Issue by bmeredith** [sendgrid/sendgrid-csharp#742]
I was excited to see #601 was merged into v9.10.0. Although it looks like the nuspec that is being used has an old set of frameworks and dependencies, which brings it back to the same point as previous in #601 + different target frameworks being used between the nuspec and csproj.

Based off of the current csproj:
* net40 target framework has returned
* net452 target framework is missing
* System.Net.Http v4.3.3 is still required

Current view from Nuget:
![image](https://user-images.githubusercontent.com/1832575/45635317-4a42ed80-ba6a-11e8-9a68-bd88ff82a148.png)

**Comment by thinkingserious** [comment]
Thanks for catching that @bmeredith!

Do you mind creating a PR against the nuspec file so I can get this right once and for all?

If not, please give me a moment and I'll make a PR and check with you for a review. Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @bmeredith,

We are going to close this PR in favor of #892, but we wanted to say thanks for taking the time to create a PR. Please fill out [this link](https://dx.sendgrid.com/swag) to receive some swag. Note that we are very backlogged on swag fulfillment, so I don't have a timeline on when we can send it you.

With best regards,

Elmer
