### ISSUE TITLE
Email subject with non-letter-or-digit characters

### ISSUE THREAD

**Issue by AndrewTziAnChan** [sendgrid/sendgrid-csharp#747]
Using transactional templates, when I try to set the subject to have something with a non-letter or non-digit character, the character seems to be transformed into some sort of markup.

If the subject is "Here's the subject", the e-mail will be sent to the recipient as "Here&apos;s the subject". How are e-mail subjects like these supposed to be formatted?

**Comment by thinkingserious** [comment]
Hello @AndrewTziAnChan,

Please try using triple {'s in your template. For example: {{{ Here's the subject }}}.

Thanks!

With Best Regards,

Elmer

**Comment by AndrewTziAnChan** [comment]
Great. That work.
