### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#752]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by Gimly** [comment]
I've started working on this, in the PR #753. It's probably not complete, but it adds a deploy phase that should be able to deploy correctly the package to NuGet. Tell me if that's sufficent or if you need more.
