### ISSUE TITLE
Run our *.md documents in this repo through the Grammer.ly service and update

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#756]
#### Issue Summary

We would like to get our English polished up throughout the repo.

#### Aceptance Criteria

* Every .md file in this repo has been run through the Grammer.ly service and updated accordingly

**Comment by danimart1991** [comment]
I take this task if you want. 😉

**Comment by thinkingserious** [comment]
Thank you @danimart1991, it's all yours!
