### ISSUE TITLE
Update documenation for retrieving a list of all templates (dynamic & legacy)

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#759]
#### Issue Summary

Please update the `USAGE.md` and corresponding `\example` with the call to list all templates. 

This is the API call required: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

#### Acceptance Criteria

* The Usage.md file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic
* The corresponding `/example` file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

**Comment by thinkingserious** [comment]
Specifically these locations:
https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md#get-templates
https://github.com/sendgrid/sendgrid-csharp/tree/master/examples

Thanks!

**Comment by tony-ho** [comment]
@thinkingserious I'll take this one.
