### ISSUE TITLE
Create a Dockerized event webhook consumer

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#765]
#### Issue Summary

SendGrid has an [Event Webhook](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html) which posts events related to your email activity to a URL of your choice. We want to have an easily deployable solution that allows for customers to easiy get up and running processing (parse and save) their event webhooks.

#### Acceptance Criteria

* A folder which contains a Dockerized solution
* Example documentation on how to deploy locally and start processing events
* Example documentation on how to deploy on at least one cloud service and start processing events
* An example complete payload with a test to verify the data is parsed properly

**Comment by KoditkarVedant** [comment]
Hello @thinkingserious,

If this is still up for grab, I would like to help.

Thanks,
Vedant

**Comment by KoditkarVedant** [comment]
@thinkingserious I have started working on this. Can you please update the status?
Isn't #572 is duplicate and should be close?
