### ISSUE TITLE
Create a Dockerized email inbound parse webhook consumer

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#766]
#### Issue Summary

SendGrid has an [Email Inbound Parse Webhook](https://sendgrid.com/docs/API_Reference/Parse_Webhook/inbound_email.html) which posts data from a specified incoming email address to a URL of your choice. We want to have an easily deployable solution that allows for customers to easiy get up and running processing (parse and complete some action) their inbound parse webhooks.

#### Acceptance Criteria

* A folder which contains a Dockerized solution
* Example documentation on how to deploy locally and start processing incoming emails
* Example documentation on how to deploy on at least one cloud service and start processing incoming emails
* An example complete payload with a test to verify the data is parsed properly

**Comment by thinkingserious** [comment]
For a good reference, please see [this](https://github.com/Jericho/StrongGrid/tree/master#parser).

**Comment by KoditkarVedant** [comment]
Hello @thinkingserious,

I have completed the implementation. This is the first big requirement in OSS I have worked on.
You may start reviewing it. I have pushed all my code [here](https://github.com/KoditkarVedant/sendgrid-inbound).

Please let me know if I have missed anything.

Thanks,
Vedant

**Comment by KoditkarVedant** [comment]
Hello @thinkingserious,

How can I add this contribution under the `hacktoberfest`? 

Thanks,
Vedant

**Comment by Jericho** [comment]
The code in your `InboundWebhookParser.cs` appears to be copy/paste from the StrongGrid library (I'm the author). Not cool to take someone else's work and present it as your own.

**Comment by KoditkarVedant** [comment]
@Jericho I'm not claiming this code was completely done by me. As mentioned in the above comment I refer that code in my implementation and I just made the changes whenever I felt necessary like added `RawEmail` property in InboudEmail. Is there anything I could do?

**Comment by Jericho** [comment]
The best would be to reference the StrongGrid nuget package rather than copy/paste the code.

**Comment by KoditkarVedant** [comment]
I would have but that may add significant dependency which I think would be too much for the current requirement. As this only related to the inbound email parser and will might not use any other part of library.

**Comment by KoditkarVedant** [comment]
@Jericho as mentioned your implementation doesn't have `RawEmail` in your Inbound email parser which I need for my implementation.

**Comment by Jericho** [comment]
If StrongGrid is missing a feature that you need, you should open [an issue[](https://github.com/Jericho/StrongGrid/issues) and describe what you need.

**Comment by thinkingserious** [comment]
Hello @KoditkarVedant,

Congratulations on your first large contribution to OSS! We greatly appreciate it and hope that you will continue to [celebrate Hacktoberfest](https://dx.sendgrid.com/hacktoberfest) with us :)

I will modify your PR to include the proper attribution as dictated by the [MIT license](https://opensource.org/licenses/MIT).

To add this work to Hacktoberfest, simply make a PR against this repo.

I would also encourage you to open an issue about the `RawEmail` functionality in the [StrongGrid SDK](url) and perhaps making a PR there as well.

Hi @Jericho,

Thanks for taking the time to review this PR and alert us to the attribution issue! 

As discussed [here](https://github.com/sendgrid/sendgrid-csharp/issues/530), I will be posting more issues (I finally will have the time to do so) to help us achieve parity with the amazing [StrongGrid library](https://github.com/Jericho/StrongGrid). For those that don't wish to wait, I think the [StrongGrid library](https://github.com/Jericho/StrongGrid) is an excellent alternative. Jericho is super responsive and constantly improving his SDK.

I apologize for not doing a good job on making it clear how attribution should be applied and will do better moving forward.

With Best Regards,

Elmer

**Comment by KoditkarVedant** [comment]
Hello @thinkingserious,

> To add this work to Hacktoberfest, simply make a PR against this repo.
Sorry to bother you again, I did not understand this. What the PR is going to contain or is it just Blank PR?

Thanks,
Vedant

**Comment by aroach** [comment]
@KoditkarVedant Probably what you'll want to do is create a fork of the SG csharp repo.  After that, you'd clone it to your machine, create a branch, and copy the work that you've done into the `examples` directory?  Maybe should have @thinkingserious chime in here on the best place to put it.  

Once your code is in the fork, you'd commit those changes in your branch, push to GitHub, and then submit the PR.
