### ISSUE TITLE
Library won't send on my production server

### ISSUE THREAD

**Issue by 1886** [sendgrid/sendgrid-csharp#773]
#### Issue Summary

I can send emails locally and when I deploy to Azure however when I deploy to my production windows box (not hosted on azure) they wont send.

As a test I tried to print client.Version on a label and I get this error

[MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.]
   SendGrid.SendGridClient.InitiateClient(String apiKey, String host, Dictionary`2 requestHeaders, String version, String urlPath) +0
   SendGrid.SendGridClient..ctor(HttpClient httpClient, SendGridClientOptions options) +196
   SendGrid.SendGridClient..ctor(String apiKey, String host, Dictionary`2 requestHeaders, String version, String urlPath) +42

The documentation seems to suggest I just need .net framework 4.5.2 but after searching the '[MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.]' part of the error people suggest 4.6 is needed. Is this the case? If so I will have to upgrade my server and don't want to do it speculatively.

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number]) 9.10.0
* .NET Version: 4.5.2

**Comment by 1886** [comment]
So I went ahead and upgraded to 4.6, seems it is a requirement? It now works as expected.

**Comment by thinkingserious** [comment]
Hello @1886,

The library should work on .NET 4.5.2 and higher. I'll leave this open for further investigation.

With Best Regards,

Elmer
