### ISSUE TITLE
Auto-generate the CHANGELOG.md file upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#776]
#### Issue Summary

For every release, we currently hand craft a CHANGELOG.md update, now we would like to automate this process. Please see the existing CHANGELOG.md for formatting structure.

#### Acceptance Criteria

* A script, which when run, creates a CHANGELOG.md update based on any merged PRs since the last release.

**Comment by Gimly** [comment]
The idea would be that this script is run during which process? Would it get the last PR information from Git or through GitHub's APIs?

**Comment by smikis** [comment]
Couple of questions:
1. Does it matter in what language script is written? Can it be .NET Console application or you want PowerShell script or something like that?
2. Is there any way to discern from PR if it's something added, updated or fixed? I did not found clear pattern between them, maybe I'm just missing something? How are they categorized currently?

**Comment by childish-sambino** [comment]
Closing as we're now using internal tooling for this.
