### ISSUE TITLE
Unable to Nuget install SendGrid 9.10.0

### ISSUE THREAD

**Issue by tguillet** [sendgrid/sendgrid-csharp#777]
#### Issue Summary

I'm trying to install SendGrid into my .net MVC4 application using NuGet and it errors out saying it cannot install the package

#### Steps to Reproduce

1. Open Nuget
2. Type 'Install-Package Sendgrid -Version 9.10.0'
3. I get this error message  
"@ Installing Sendgrid.9.10.0 in MartialMember.WebUI finished (5.871 sec)
[Notification][Install] Install failed (project: MartialMember.WebUI, package: Sendgrid v9.10.0)
Could not install package 'Sendgrid 9.10.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
"

**Comment by thinkingserious** [comment]
Hello @tguillet,

Is your target framework less than v4.5.2?

With Best Regards,

Elmer

**Comment by reg568** [comment]
When I am trying to install framework more than v4.5 it tells already you have version v4.5.2 but tells the error - Could not install package 'Sendgrid 9.10.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by childish-sambino** [comment]
Support for v4.0 was added in the [9.17.0](https://github.com/sendgrid/sendgrid-csharp/releases/tag/9.17.0) release which would also allow for v4.5 support. Recommend upgrading to the latest release of this library.
