### ISSUE TITLE
Email is sent without attachemnt

### ISSUE THREAD

**Issue by DigitalPal** [sendgrid/sendgrid-csharp#788]
Hi,
I was trying to send email with image attachment. I was able to send the email but it did not show any attachment.

Here is code 
`var client = new SendGridClient("api key"); // https://app.sendgrid.com

                var msg = new SendGridMessage()
                {
                    From = new EmailAddress("contact@mydomain.co.in", "Poki"),
                    Subject = "Image subject",
                    PlainTextContent = "Image body",
                };

                var attachments = new List<SendGrid.Helpers.Mail.Attachment>()
                {
                    new SendGrid.Helpers.Mail.Attachment()
                    {
                        Content = Convert.ToBase64String(System.IO.File.ReadAllBytes(AppDomain.CurrentDomain.BaseDirectory + "whatever2.png")),
                        Type = "image/png",
                        Filename = "banner.png",
                        Disposition = "inline",
                        ContentId = "Banner"
                    }
                };
                msg.AddAttachments(attachments);

                msg.AddTo(new EmailAddress("contact@mydomain.co.in", "Test Email"));

                var response = await client.SendEmailAsync(msg);`
I do receive the response as "Accepted" and mail appears in inbox after some time. But it does not have attachment to it.

Any help appreciated.

**Comment by DigitalPal** [comment]
Anyone ?

**Comment by thinkingserious** [comment]
Hello @DigitalPal,

[Here](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#attachments) is an example of sending an email with an attachment. Please take a look and let me know how it goes.

With Best Regards,

Elmer
