### ISSUE TITLE
Auto-generate the release notes upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#795]
#### Issue Summary

For every release, we hand craft the release notes on GitHub, now we would like to automate this process. Please see the existing [release notes](https://github.com/sendgrid/sendgrid-csharp/releases) for an example. The contents of the release notes are generated from the CHANGELOG.md file. [Here](https://developer.github.com/v3/repos/releases/#create-a-release) is the documentation for updating the release notes via the GitHub API. 

#### Acceptance Criteria
 

* A script, which when run, creates a release note update based on the last deployed release

**Comment by DreamN** [comment]
Hi, I would like to take this one

**Comment by childish-sambino** [comment]
Closing as we're now using internal tooling for this.
