### ISSUE TITLE
Modification in Prerequisites for installation

### ISSUE THREAD

**Issue by Rishabh04-02** [sendgrid/sendgrid-csharp#813]
#### Issue Summary

On the website its mentioned that **Send up to 40,000 emails for 30 days, then send 100 emails/day free forever** but it has not been mentioned in the README.

**Comment by caseychien** [comment]
I can take this one!

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-csharp/pull/814
