### ISSUE TITLE
Email is sent twice sometimes when the dynamic data object is huge 

### ISSUE THREAD

**Issue by SailleshPawar** [sendgrid/sendgrid-csharp#822]
#### Issue Summary

I am using dynamic template to show the list of object in a table format in order to implement this i am using TemplateData to pass my object. Our users are receiving duplicate emails when there are more than 40000 objects in a dictionary collection.

#### Steps to Reproduce

1. Create a dynamic  transactional template on send grid with 
        like this
           <table>             
          {{#each alerts.AlertDetails}}            
              <tr>
                <td width="60%" style="padding:0px; font-size:14px;padding-top:10px">
                  <b>{{FullLocationNameWithCode}}</b>
                </td>
                
              </tr>
                <tr>
                <td width="60%" style="padding:0px; font-size:14px">
                 {{ToolImpactedHeading}}
                </td>
               
              </tr>
              <tr>
                <td width="60%" style="padding:0px; font-size:14px">
                 <b>{{ToolTypeHeading}}</b>
                </td>
                <td style="padding:0px; font-size:14px">
                 {{ToolTypeName}}
                </td>
              </tr>        
              <tr>
                <td width="60%" style="padding:0px; font-size:14px">
                 <b>{{SerialNumberHeading}}</b>
                </td>
                <td style="padding:0px; font-size:14px">
               {{SerialNumber}}
                </td>
            
              </tr> 
              <tr>
                <td width="60%" style="padding:0px; font-size:14px">
                 <b>{{ComponentHeading}}</b>
                </td>
                <td style="padding:0px; font-size:14px">
               {{ComponentName}}
                </td>
            
              </tr> 
              {{/each}}
              
            </table>

2. Code

 public async Task<bool> SendEmail(Template mail)
        {
            try
            {
                var client = new SendGridClient(ApiKey);
                var msg = new SendGridMessage();
                DisableTracking(msg);
                msg.From = (new EmailAddress(mail.From, mail.FromName));
                msg.Subject = mail.Subject;
                msg.SetTemplateId(mail.TemplateId);
                Dictionary<string, SubscribedEmailVinTemplate> alertDetails = new Dictionary<string, SubscribedEmailVinTemplate>();
                alertDetails.Add("alerts", mail);
                Personalization personalization = new Personalization();
                personalization.TemplateData = alertDetails;
                personalization.Tos = new List<EmailAddress>() { new EmailAddress(mail.To, mail.FirstName) };
                msg.Personalizations.Add(personalization);
                var response = await client.SendEmailAsync(msg);
                return response.StatusCode == System.Net.HttpStatusCode.Unauthorized ? false : true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

3. Further steps, etc.

This happens sometimes and only for users which has huge objects.

#### Technical details:

* sendgrid-c# 9.10.0.0   : master (latest commit: [commit number])

**Comment by raman0619** [comment]
Similar issue is faced by us.

Email is sent twice in one of the scheduled job.Every time  this particular scheduler runs 90% users receive duplicate emails.

Other scheduled job delivers emails only once.

The common sendgrid code is being used to sent emails for all the schedule jobs.

 public async Task Execute(SendGridInputDto input)
        {
            try
            {
            SendGridMessage msg;

            IConfigurationRoot configuration = builder.Build();
            var apiKey = configuration["App:SendGridAPIKey"];
            var fromEmail = configuration["App:FromEmail"];
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress(fromEmail, "DosedDaily");
            var subject = input.emailSubject;
            var to = new EmailAddress(input.toEmail);
            var plainTextContent = input.plainTextContent;
            var htmlContent = input.htmlContent;
            msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);

                if (!(response.StatusCode == HttpStatusCode.Accepted))
                    Logger.Info("SendGrid Status Code: " + response.StatusCode);
            }
            catch (System.Exception ex)
            {

              
            }
        }

**Comment by thinkingserious** [comment]
Hello @SailleshPawar @raman0619,

To further assist, it would be useful to understand how the code is being called. I suspect there is some issue with the calling logic. It's also important that the input to the calling function be verified to not contain duplicate content.

With Best Regards,

Elmer

**Comment by SailleshPawar** [comment]
Thanks @thinkingserious  for looking into this issue..
This is my calling code

 public abstract class AlertType
    {
        public abstract void SendEmail(List<Alert> Alerdetails, int ClientId, User Userdetails);
    }

    public class VinAlert : AlertType
    {
        public readonly IAlertEmail _emailService;
        public readonly ISubscriptionConfiguration _configurations;
        public VinAlert(IAlertEmail emailService, ISubscriptionConfiguration configurations)
        {
            _emailService = emailService;
            _configurations = configurations;
        }
        public override void SendEmail(List<Alert> Alertdetails, int ClientId, User Userdetails)
        {
            var firstAlertDetails = Alertdetails.FirstOrDefault();

             AlertTemplate vinTemplate = new SubscribedEmailVinTemplate()
            {
                FirstName = Userdetails.FirstName,
                LastName = Userdetails.LastName,
                AlertsDetails = Alertdetails,
                Vin = firstAlertDetails.Vin,
                From = _configurations.From,
                Subject =    string.Format("{0} {1}", firstAlertDetails.AlertDescription, _configurations.Subject),
                TemplateId = _configurations.TemplateIdVin,
                 UnSubscribedURL =  _configurations.UnSubscribedURL + firstAlertDetails.UserAlertsId.ToString()  
               

             };
            vinTemplate.To = Alertdetails.FirstOrDefault().Email;
            _emailService.SendVinAlertNotificationEmail((SubscribedEmailVinTemplate)vinTemplate);
        }
    }

    public class OtherAlert : AlertType
    {
        public readonly IAlertEmail _emailService;

        public readonly ISubscriptionConfiguration _configurations;
        public OtherAlert(IAlertEmail emailService, ISubscriptionConfiguration configurations)
        {
            _emailService = emailService;
            _configurations = configurations;
        }

        public override void SendEmail(List<Alert> Alertdetails, int ClientId, User Userdetails)
        {
            var firstAlertDetails = Alertdetails.FirstOrDefault();
            BMIS2.Entity.EmailTemplate.MailTemplate OtherTemplate = new SubscribedEmailOtherTemplate()
            {
                FirstName = Userdetails.FirstName,
                LastName = Userdetails.LastName,
                AlertDetails = Alertdetails,
                Heading = firstAlertDetails.AlertDescription,
                To = firstAlertDetails.Email,
                From = _configurations.From,
                Subject =  string.Format("{0} {1}", firstAlertDetails.AlertDescription, _configurations.Subject),
                TemplateId = _configurations.TemplateId,
                FromName = _configurations.FromName,
                UnSubscribedURL = _configurations.UnSubscribedURL + firstAlertDetails.UserAlertsId.ToString()

            };
            _emailService.SendAlertNotificationEmail((SubscribedEmailOtherTemplate)OtherTemplate);
        }

    }





These API calls the below methods as shown below. The major concern is this happening only for users which has large object count. Other user are getting only 1 email.

 public class SubscribedAlertEmailService : IAlertEmail
    {
        private static readonly string ApiKey = ConfigurationManager.AppSettings["SendGridKey"];
        public async Task<bool> SendAlertNotificationEmail(SubscribedEmailOtherTemplate mail)
        {
            try
            {

                var client = new SendGridClient(ApiKey);
                var msg = new SendGridMessage();
                DisableTracking(msg);
                msg.From=(new EmailAddress(mail.From, mail.FromName));
                msg.Subject = mail.Subject;
                msg.SetTemplateId(mail.TemplateId);                
                Dictionary<string, SubscribedEmailOtherTemplate> alertDetails = new Dictionary<string, SubscribedEmailOtherTemplate>();              
                alertDetails.Add("alerts", mail);
                Personalization personalization = new Personalization();
                personalization.TemplateData = alertDetails;
                personalization.Tos = new List<EmailAddress>() { new EmailAddress(mail.To, mail.FirstName) };
                msg.Personalizations.Add(personalization);
                var response = await client.SendEmailAsync(msg);
                return response.StatusCode == System.Net.HttpStatusCode.Unauthorized ? false : true;
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }


        public static void DisableTracking(SendGridMessage mail)
        {

            mail.TrackingSettings = new TrackingSettings
            {
                ClickTracking = new ClickTracking { Enable = false, EnableText = false },
                Ganalytics = new Ganalytics { Enable = false, UtmCampaign = "", UtmContent = "", UtmMedium = "", UtmSource = "", UtmTerm = "" },
                OpenTracking = new OpenTracking { Enable = false, SubstitutionTag = "" },
                SubscriptionTracking = new SubscriptionTracking { Enable = false, Html = "", SubstitutionTag = "", Text = "" },
            };

        }
        public async Task<bool> SendVinAlertNotificationEmail(SubscribedEmailVinTemplate mail)
        {
            try
            {
                var client = new SendGridClient(ApiKey);
                var msg = new SendGridMessage();
                DisableTracking(msg);
                msg.From = (new EmailAddress(mail.From, mail.FromName));
                msg.Subject = mail.Subject;
                msg.SetTemplateId(mail.TemplateId);
                Dictionary<string, SubscribedEmailVinTemplate> alertDetails = new Dictionary<string, SubscribedEmailVinTemplate>();
                alertDetails.Add("alerts", mail);
                Personalization personalization = new Personalization();
                personalization.TemplateData = alertDetails;
                personalization.Tos = new List<EmailAddress>() { new EmailAddress(mail.To, mail.FirstName) };
                msg.Personalizations.Add(personalization);
                var response = await client.SendEmailAsync(msg);
                return response.StatusCode == System.Net.HttpStatusCode.Unauthorized ? false : true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }

**Comment by thinkingserious** [comment]
@SailleshPawar,

To verify. You are sending out a batch job that whenever you have 40k+ emails there are some duplicates?

Some further questions:

1. How are you determining the duplicates?
2. Are you certain that your calling code does not have duplicate emails or calls the same email twice?

**Comment by SailleshPawar** [comment]
@thinkingserious  I just send a email to single person at a time, the email body contains a list of information. That list can go upto 40000.  
Coming to your questions about duplicates content?
It is a table structure which will have some duplicate values not all values will be duplicate.
Snapshot  of email. 

![image](https://user-images.githubusercontent.com/16855395/47803258-17be2d00-dd58-11e8-937f-5005d8476f50.png)

**Comment by SailleshPawar** [comment]
After more analysis found that it was issue of Azure function lock timeout. 
@thinkingserious  thanks for your valuable time for actively looking into this issue and guiding me.
