### ISSUE TITLE
C#, How to use SendGrid to send an email and attach a html page as attachment

### ISSUE THREAD

**Issue by CalvinFengDatacom** [sendgrid/sendgrid-csharp#831]
#### Issue Summary

I just wonder how to use SendGrid C# SDK for sending an email and attach a HTML page as the attachment.

Do I need to create the HTML page and save it first before I send it or can I just save it in the memory? I prefer the second option just like my current example below, here I'm attaching a text file without save it to the source code.

```
                var msg = MailHelper.CreateSingleEmail(from, to, subject, null, content);
                // Add attachment as txt/plain
                byte[] byteData = Encoding.ASCII.GetBytes(transcript);
                msg.Attachments = new List<SendGrid.Helpers.Mail.Attachment>
                {
                    new SendGrid.Helpers.Mail.Attachment
                    {
                        Content = Convert.ToBase64String(byteData),
                        Filename = "Transcript.txt",
                        Type = "txt/plain",
                        Disposition = "attachment"
                    }
                };
```

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (ASP.NET)
* .NET Version: 4.5.2

**Comment by CalvinFengDatacom** [comment]
@thinkingserious Thanks Elmer, I found the solution as well. Thanks for sharing.

**Comment by yshih** [comment]
Hello @CalvinFengDatacom  

Thanks so much for your sample codes. This one works great. I been Googling for any examples that may works until your sample. Thanks so much!
          
               var msg = MailHelper.CreateSingleEmail(from, to, subject, null, content);
                // Add attachment as txt/plain

                byte[] byteData = Encoding.ASCII.GetBytes(File.ReadAllText(filePath));
                msg.Attachments = new List<SendGrid.Helpers.Mail.Attachment>
                {
                    new SendGrid.Helpers.Mail.Attachment
                    {
                        Content = Convert.ToBase64String(byteData),
                        Filename = "Transcript.txt",
                        Type = "txt/plain",
                        Disposition = "attachment"
                    }
                };

**Comment by kevinwedwards** [comment]
I utilized this also.  Thank you!

**Comment by josefoira** [comment]
why is that when I send an email with password. I can't open it with the password I set
