### ISSUE TITLE
Not able to install SendGrid NuGet Package

### ISSUE THREAD

**Issue by xyz92** [sendgrid/sendgrid-csharp#834]
On installing SendGrid NuGet Package Version 9.10.0, I see the following error:

![image](https://user-images.githubusercontent.com/6519992/48587633-bade7d00-e8e8-11e8-9c3f-52ef3761bb86.png)

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1108?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(NU1108)%26rd%3Dtrue

Can someone please let me know how to fix this? Thanks!

**Comment by thinkingserious** [comment]
Hello @xyz92,

What is the name of your project? This happens when you project is the same name as the Nuget package.

With Best Regards,

Elmer

**Comment by xyz92** [comment]
Cool thank you!
