### ISSUE TITLE
Newtonsoft.JSON version support

### ISSUE THREAD

**Issue by tasdpp** [sendgrid/sendgrid-csharp#835]
Why is Newtonsoft.Json version 11 not supported? Aren't we paying you money to use Sendgrid and this is as up to date as this can be? I have an app that has another dependency on Newtonsoft.Json >=10 and your solution makes it so I can use the other. Going to have to decide and probably look to another solution for email that keeps things up to date.

**Comment by thinkingserious** [comment]
Hello @tasdpp,

Newtonsoft.Json version 11 is not yet supported pending the release of [this PR](https://github.com/sendgrid/sendgrid-csharp/pull/748). Please comment and follow that thread as the more activity the thread gets the higher it rises on our backlog.

With Best Regards,

Elmer
