### ISSUE TITLE
Does reputations api support passing in multiple usernames?

### ISSUE THREAD

**Issue by kirk-quinbar** [sendgrid/sendgrid-csharp#837]
I am using the api subusers/reputations and the c# client v9.10.0 to pull back reputations, so we can alert on them if they go over a threshold. my question is whether it supports passing in multiple usernames? the api documentation calls the query parameter "usernames" which seems to indicate it does, but i cannot get it to recognize more than 1 no matter how i formatted the value. i have tried comma delimited, and also a json array. I cannot find an example in the client github code to call it with multiple usernames, so is it capable of multiple usernames or is that parameter just poorly spelled?

**Comment by thinkingserious** [comment]
Hello @kirk-quinbar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by kirk-quinbar** [comment]
I did an their response was that i needed to pass the querystring parameters like this if i want more than 1: /subusers/reputations?usernames=user1&usernames=user2

With the C# client, although I can get this work, it was weird coding. 

This works but seems weird compared to other examples in the sendgrid client github code. It does return two reputations.
var client = new SendGridClient(ApiKey);
var response = await client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "subusers/reputations?usernames=zywavedevibr&usernames=zywaveibr");

I then tried code similar to how the examples are setup and this seems to only include the last one. I have a feeling the client is deduplicating the json array or something? Is there a better way to do that or do I have to use my first code above?
string queryParams = $"{{\'usernames\': \'zywaveibr\',\'usernames\': \'zywavedevibr\'}}";
var client = new SendGridClient(ApiKey);
var response = await client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "subusers/reputations", queryParams: queryParams);

**Comment by brettpostin** [comment]
Just hit this problem also. The &usernames=foo&usernames=bar syntax works but it is weird given the parameter name.

Also it eats up URL characters if you have a particularly large number of subusers you want to bring back. I have to request them in batches. 

The docs state the parameter is optional. Could the endpoint not return all subusers if no parameter is specified?

**Comment by childish-sambino** [comment]
@brettpostin Best to contact support as this issue is not specific to this library: https://support.sendgrid.com/
