### ISSUE TITLE
Substituting Raw HTML into Template not working

### ISSUE THREAD

**Issue by euangordon** [sendgrid/sendgrid-csharp#841]
Hi,

Using C# with Nuget SendGrid v9.10.0

I have substutions working fine, but I would like to also substitute raw HTML into one area of a template. When I use SG website with test data it is working fine, but in real life I can see the HTML tags.

Referring to the document https://sendgrid.com/docs/ui/sending-email/using-handlebars/#substitution I can see that I need to use tripple {{{ }}} brackets, but it makes no difference.

Sample Code:
```
{{{html}}}
Kind Regards,
Euan
```

Test Data
`{ "html":"<p>You have been registered by Euan,</p> <p>Your login is euan@mailinator.com and your temporary password is 234567</p> <p> You will be requested to change your password on first login.<br/> </p> Please click here to login <a href=\"http://www.google.com\">here</a>", "subject":"Login Details" }`

In SendGrid's Preview, this appears like:
![image](https://user-images.githubusercontent.com/32622054/49521754-078cf680-f89e-11e8-9a13-507e0b7a29f4.png)

In a mail client (mailinator) it appears like:
![image](https://user-images.githubusercontent.com/32622054/49521779-14114f00-f89e-11e8-8f82-e7e828149dcb.png)

**Comment by kylearoberts** [comment]
@euangordon 

Sorry to hear you are having issues getting HTML to substitute. Can you share your full code so we can test on our end? This will help us to either replicate the issue and/or see what is causing the issue.

**Comment by euangordon** [comment]
`                    var callbackUrl = ConfigurationManager.AppSettings["LoginURL"];

                    var html = "<p>You registered on the Compass System, Your login is " + user.Email + "</p> Please click <a href=\"" + callbackUrl + "\">here</a> to login";

                    var emailData = new EmailData
                    {
                        html = html,
                        subject = "Compass - Admin Login Details"
                    };

                    await SendTemplateEmail(user.Email, "SG_CompassBlank", emailData);
                    return RedirectToAction("Login", "Account");`



`        public static Task SendTemplateEmail(string strRecipientEmail, string templateName, EmailData emailData)
        {
            var templateID = ConfigurationManager.AppSettings[templateName].ToString();
            return Task.FromResult(SendSendGridEmail(strRecipientEmail, "", "", EmailSenderEmail, EmailSenderName, templateID, emailData));
        }`
`        public static async Task SendSendGridEmail(string strRecipientEmail, string strSubject, string strMessage, string emailsenderemail, string emailsendername, string templateid, EmailData emailData)
        {
            var client = new SendGridClient(EmailApiKey);

            var myMessage = new SendGridMessage();
                myMessage.AddTo(strRecipientEmail);
                myMessage.From = new EmailAddress(emailsenderemail, emailsendername);
                myMessage.SetTemplateData(emailData);
                myMessage.TemplateId = templateid;

            var response = await client.SendEmailAsync(myMessage);
        }`

**Comment by kylearoberts** [comment]
@euangordon 

Happy to hear things are working now. It is possible that there was some delay in updating the template. I also wanted to note that you should not need to include an Text or HTML potion in your sending as this could cause issues:

```
var emailData = new EmailData
{
    html = html,
    subject = "Compass - Admin Login Details"
};
```

If you have any further issues please let us know.
