### ISSUE TITLE
Issues with AddAttachmentAsync

### ISSUE THREAD

**Issue by kirk-quinbar** [sendgrid/sendgrid-csharp#842]
#### Issue Summary

I have discovered a couple of issues with AddAttachmentAsync method and wanted to get your thoughts.

1. The method assumes a buffered stream because the code is trying to use the .Length property in order to set the size of the byte array that it uses to call AddAttachment. There are a number of cases where you may not have a buffered stream and in general buffering streams is bad for memory usage on a server. For instance we have websites that get files from our service layer. we transfer the file via a stream that isnt buffered (NetworkStream in the case of WCF). This type of stream also has CanSeek = false. this would prevent the .Length property from working and it throws an exception. We have designed our entire service layer and websites to use non-buffered streams for file transfers and have spent a lot of time working on ways to keep memory usage down on our servers especially due to files, so we are trying to avoid changing that. I'm thinking there could a different way to get the length? pass it in or maybe my second point will help.

2. reading a stream into a byte array is horrible for memory usage. If that byte array ends up larger than 85k, it will end up on the large object heap and never get released. we spent a lot of time figuring out this little tidbit as we used to transfer all of our files using byte arrays, but switched to non-buffered streams years ago. It is probably better to convert the stream to a base64 string in increments. That way you dont have both a large byte array and a large string. large strings typically clean themselves up although in a longer timeframe than smaller ones. I came across an interesting article that i used to create this method we've been using for a while. It seems to work pretty good although im sure there's always room for improvement. something maybe to add to your method?

`
private string GetBase64FromStream(Stream inputStream)
        {
            //unfortunately SendGrid API doesnt support streaming so we have to convert the stream to a base64 string.
            //this method will do that incrementally so we dont have both a large byte array and a large string
            //https://stackoverflow.com/questions/32702965/convert-a-very-large-binary-file-into-a-base64string-incrementally

            int base64BlockSize = 76800;  //75k (note that block size needs to be multiples of 3
            byte[] base64Block = new byte[base64BlockSize];
            var output = new StringBuilder();
            int bytesRead = 0;

            do
            {
                // read one block from the input stream
                bytesRead = inputStream.Read(base64Block, 0, base64Block.Length);

                // encode the base64 string
                string base64String = Convert.ToBase64String(base64Block, 0, bytesRead);
                output.Append(base64String);
            } while (bytesRead == base64Block.Length);

            return output.ToString();
        }
`

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

I expect that if i pass a non-buffered stream into the AddAttachmentAsync method, that it won't error out

#### Technical details:

* sendgrid-csharp Version: 9.10.0
* Platform (dll)
* .NET Version: 4.7.2

**Comment by kirk-quinbar** [comment]
I realized i had some bad code in the example for #2, so here is the fixed code. If you are passing in a NetworkStream the original code would never get read past the first read. This works as expected.

` private string GetBase64FromStream(Stream inputStream)
        {
            int base64BlockSize = 76800;  //75k (note that block size needs to be multiples of 3
            byte[] base64Block = new byte[base64BlockSize];
            var output = new StringBuilder();
            int bytesRead = 0;

            do
            {
                // read one block from the input stream
                bytesRead = inputStream.Read(base64Block, 0, base64Block.Length);

                if (bytesRead > 0)
                {
                    // encode the base64 string
                    string base64String = Convert.ToBase64String(base64Block, 0, bytesRead);
                    output.Append(base64String);
                }
            } while (bytesRead > 0);

            return output.ToString();
        }`

**Comment by thinkingserious** [comment]
Hello @kirk-quinbar,

Thank you for providing this detailed feedback! I've added it to our backlog for further review, but perhaps someone in our C# community may take it up and submit a PR. 

With Best Regards,

Elmer

**Comment by aevitas** [comment]
@kirk-quinbar Is this still a relevant issue for you? It would seem to me that the `byte[]` allocation in `AddAttachmentAsync` is the culprit here - which could be fixed relatively easily by pooling buffers and renting them out rather than allocating them on every call.

In doing so, only the buffer pool would end up on the LOH, rather than the individual attachments. Would that be a solution to your problem?

**Comment by kquinbar** [comment]
yes it continues to be of some concern to us. so is your suggestion a pull request and maybe provide an example of what you are talking about doing?

**Comment by aevitas** [comment]
@kquinbar I'd be happy to submit a pull request for this if @thinkingserious thinks it's a good change as well. Basically, I'd introduce an `ArrayPool<byte>` to `SendGridMessage` which can either be passed in, providing large size buffers for use cases such as yours, or use a shared pool for all other use cases:

```csharp
public SendGridMessage()
    : this(ArrayPool<byte>.Shared)
{
}

public SendGridMessage(ArrayPool<byte> bufferPool)
{
    this.bufferPool = bufferPool ?? throw new ArgumentNullException(nameof(bufferPool));
}
```

Instead of allocating a new `byte[]` every time an attachment is added, `AddAttachmentAsync` would rent a buffer from the pool, read the contents into that buffer, process it, and return the buffer to the pool. This means that instead of allocating numerous large `byte[]`'s on the LOH, you'd only allocate one (possibly very large) array, and rent out chunks of it. 

The implementation of `AddAttachmentAsync` would look something along the lines of:

```csharp
public async Task AddAttachmentAsync(string filename, Stream contentStream, string type = null, string disposition = null, string content_id = null, CancellationToken cancellationToken = default(CancellationToken))
{
    // Stream doesn't want us to read it, can't do anything else here
    if (contentStream == null || !contentStream.CanRead)
    {
        return;
    }

    var contentLength = Convert.ToInt32(contentStream.Length);
    var streamBytes = this.bufferPool.Rent(contentLength);
    try
    {
        await contentStream.ReadAsync(streamBytes, 0, contentLength, cancellationToken);

        var base64Content = Convert.ToBase64String(streamBytes);

        this.AddAttachment(filename, base64Content, type, disposition, content_id);
    }
    finally
    {
        this.bufferPool.Return(streamBytes);
    }
}
```

Of course the very large `base64Content` string would still be LOH allocated, but as strings get special treatment, that should be far less of an issue.

Let me know what you guys think, I'd be happy to implement these changes and submit a PR.

**Comment by jnyrup** [comment]
@aevitas One of the problems are, that non-buffered `Stream`s does not have the `Length` available.
E.g. [NetworkStream.Length](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.length) will throw a `NotSupportedException`.

I don't have a concrete implementation at hand, but maybe something like:
```c#
int chunkSize = 2048; 
var buffer = ;// stackalloc readonly span would probably be preferable, otherwise ArrayPool<byte>.Shared
var sb = new StringBuilder();

int readBytes = 0;
while ((readBytes = contentLength.ReadAsync(buffer, chunkSize)) == chunkSize)
{
    var base64Coded = Convert.ToBase64String(buffer);
    sb.Append(base64Coded);
}

if (readBytes > 0)
{
    // handle the remaining bytes
}

var base64Content = sb.ToString();
this.AddAttachment(filename, base64Content, type, disposition, content_id);
```

My best advice would be to try different implementations and use [BenchmarkDotNet](https://benchmarkdotnet.org/index.html) to benchmark which is the fastest and least allocating.

**Comment by aevitas** [comment]
I hadn't figured that part out yet, but the draft I have for it is similar to yours:

```csharp
public async Task AddAttachmentAsync(string filename, Stream contentStream, string type = null, string disposition = null, string content_id = null, CancellationToken cancellationToken = default)
{
    // Stream doesn't want us to read it, can't do anything else here
    if (contentStream == null || !contentStream.CanRead)
    {
        return;
    }

    // If the stream is seekable, just grab the length and read it.
    if (contentStream.CanSeek)
    {
        await this.AddAttachmentFromSeekableStreamAsync(filename, contentStream, type, disposition, content_id, cancellationToken);
        return;
    }

    // Otherwise, we'll have to read the stream until there is nothing more to be read.
    // Every chunk we read will be converted to base64, and appended to the StringBuilder.
    var buffer = this.bufferPool.Rent(4 * 1024); // at least 4 KiB, often this will be larger.
    var offset = 0;
    var sb = new StringBuilder();

    try
    {
        while (true)
        {
            try
            {
                var numRead = await contentStream.ReadAsync(buffer, offset, buffer.Length, cancellationToken);

                if (numRead == 0)
                {
                    break;
                }

                var content = Convert.ToBase64String(buffer, 0, numRead);

                sb.Append(content);

                offset += numRead;
            }
            catch (EndOfStreamException)
            {
                break;
            }
        }
    }
    finally
    {
        this.bufferPool.Return(buffer);
    }

    this.AddAttachment(filename, sb.ToString(), type, disposition, content_id);
}

private async Task AddAttachmentFromSeekableStreamAsync(string fileName, Stream contentStream, string type = null, string disposition = null, string content_id = null, CancellationToken cancellationToken = default)
{
    var contentLength = Convert.ToInt32(contentStream.Length);
    var streamBytes = this.bufferPool.Rent(contentLength);
    try
    {
        await contentStream.ReadAsync(streamBytes, 0, contentLength, cancellationToken);

        var base64Content = Convert.ToBase64String(streamBytes);

        this.AddAttachment(fileName, base64Content, type, disposition, content_id);
    }
    finally
    {
        this.bufferPool.Return(streamBytes);
    }
}
```
Using stack allocated spans would definitely lead to fewer allocations, but IIRC, you can't `await` in an unsafe context. 

Either way, this keeps the behaviour for seekable streams (i.e. the ones where `Length` is available) exactly the same as before, and only applies special treatment to stuff like `NetworkStream` where it's needed.

The above code is definitely still a work in progress and I haven't yet tested or benchmarked it, but I figured I'd throw it in here to get some thoughts on the approach.
