### ISSUE TITLE
v9.10.0 does not work with Newtonsoft.Json.10.0.2

### ISSUE THREAD

**Issue by tylerolechnowicz** [sendgrid/sendgrid-csharp#843]
#### Issue Summary

v9.10.0 does not work with Newtonsoft.Json.10.0.2. Installing Newtonsoft.Json.10.0.2 compiles and builds fine, but throws an exception at Runtime.

FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

SendGrid v9.10.0 appears to be looking for Newtonsoft.Json v9, even though it is stated that SendGrid v9.10.0 is compatible with Newtonsoft.Json v9.0.1 and above.

![image](https://user-images.githubusercontent.com/32344917/50452214-bbfec300-0906-11e9-83e7-ed53c8c341b9.png)

#### Technical details:

* sendgrid-csharp Version: 9.10.0
* Platform: .NET
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @tylerolechnowicz,

We have an open PR for this. Please [follow this PR](https://github.com/sendgrid/sendgrid-csharp/pull/780) for progress. 

At first glance, my concern with that PR is that is seems to require version 11. Not sure if we need to keep supporting 9 and 10 also.

With Best Regards,

Elmer

**Comment by tylerolechnowicz** [comment]
@thinkingserious excellent. Glad to hear it. I think supporting 9 and 10 as well would be the best approach because other assemblies might rely on those. For example, I use SendGrid and Auth0 in my application. Auth0 requires 10 (not sure if it can work with 11) and SendGrid requires 9. 

Supporting both would be mean that I could just have a binding redirect in my .config file and not have to set up different folders with different versions of Newtonsoft.Json.

Regards,

Tyler Olechnowicz
