### ISSUE TITLE
Should SendGridClient accept an IHttpClient in the constructor instead of creating it's own?

### ISSUE THREAD

**Issue by PureKrome** [sendgrid/sendgrid-csharp#847]
#### Issue Summary

As part of learning if `SendGridClient` is thread safe, I noticed that there is not `ctor` that accepts an `IHttpClient` and that the `ctor` actually creates the `HttpClient`.

I was wondering if it's worth leveraging the new `HttpClientFactory` stuff available from .NET Core 2.1+ (which can also handle Polly retries, etc) plus some other magic-under-the-hood.

**Comment by thinkingserious** [comment]
Hi @PureKrome,

I'm going to reference this issue here: https://github.com/sendgrid/sendgrid-csharp/issues/521

Short answer is that we have not gotten to this issue in our backlog just yet. We are definitely open to PRs if your up for it. 

With Best Regards,

Elmer

**Comment by kanup** [comment]
There is a constructor that takes HttpClient. I think you can just use that to inject it with something like:

services.AddHttpClient<ISendGridClient, SendGridClient>();
