### ISSUE TITLE
Inline Images are not embedding correctly.

### ISSUE THREAD

**Issue by Vapok** [sendgrid/sendgrid-csharp#848]
#### Issue Summary

***NOTE: This issue is actually an issue with the SendGrid v3 API, and not the sendgrid-csharp project. The resulting JSON that sendgrid-csharp generates, meets the spec that is defined at [https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send](https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send)***

When using the following code, as an example:
```
			foreach (FileResource fileResource in message.Attachments)
				email.AddAttachment(fileResource.Name, Convert.ToBase64String(fileResource.ByteContent), null,
					fileResource.IsEmbedded ? SendGridApi.Parameters.AttachmentInline : SendGridApi.Parameters.AttachementNotInline, fileResource.GetContentId());
```

email is the `SendGridMessage` object, and I'm using the AddAttachment() method to add an image.
SendGridApi.Parameters.AttachmentInline = "inline"
SendGridApi.Parameters.AttachementNotInline = "attachment"

When, I use "inline" in this method, the resulting message is created and sent, but the image src is not correctly implemented through the SendGrid v3 API.

The image tag in the sent email shows:
```
<td>
  <img src=3D"182898383" alt=3D"logo" width=3D"215" height=3D="54" />
</td>
```

And the related embedded image is recorded as:
--4588a74ee9d04ae8752fdc4392e1e1c8da97ca62e794684ae59ba96058c3
Content-Disposition: inline; filename="logo.png"
Content-ID: <182898383>
Content-Transfer-Encoding: base64
Content-Type: image/png; name="logo.png"
--4588a74ee9d04ae8752fdc4392e1e1c8da97ca62e794684ae59ba96058c3--

The image src replacement in the v3 API does not contain the required "cid:".  It should look like:

```
  <img src=3D"cid:182898383" alt=3D"logo" width=3D"215" height=3D="54" />
```

This is causing Embedded Images not to work.

#### Steps to Reproduce

1. Create an email message using the SendGridMessage object with the v3 API.
2. Add an attachment with the inline attribute and send a message to yourself.
3. View message in email client and note that the image does not link.
3. Look at the sent message source and evaluate the HTML looking at the <img> tag. Note that "cid:" is not specified.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: v9.10.0 (latest commit: 1232f3b)
* Platform (Sitecore 9.0.2, .NET 4.6.2)
* .NET Version: 4.6.2

**Comment by thinkingserious** [comment]
Hello @Vapok,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
