### ISSUE TITLE
403 on SendMailAsync

### ISSUE THREAD

**Issue by HindoliyaYogesh** [sendgrid/sendgrid-csharp#849]
Hello,

I am using SendGrid Free account at the moment for development. Following is the implementation I have to send out mails using Transactional templates. This implementation was working fine, returning ACCEPTED as response code. A few days back the same code started returning FORBIDDEN response code.
I tried generating a new API Key and using it for emails, no luck there.
Please advise.

```
//Instantiate a client
var client = new SendGridClient(emailInput.APIKey);
var msg = new SendGridMessage();

if (!string.IsNullOrEmpty(emailInput.FromEmail))
{
	msg.SetFrom(new EmailAddress(emailInput.FromEmail));
}

if (emailInput.ToRecipients.Any())
{
	foreach (NotificationAudienceDTO recipient in emailInput.ToRecipients)
	{
		msg.AddTo(new EmailAddress(recipient.AudienceEmailAddress, recipient.AudienceAlias));
	}
}

msg.SetTemplateId(emailInput.TemplateKey);
if (emailInput.Fields.Any())
{                 
	dynamic templateData = new System.Dynamic.ExpandoObject();
	var dataDictionary = (IDictionary<string, object>)templateData;
	foreach (FieldMapper field in emailInput.Fields)
	{
		dataDictionary.Add(field.FieldId, field.FieldValue);
	}
	msg.SetTemplateData(templateData);
}

//send email async
var response = await client.SendEmailAsync(msg);
```

Any help would be appreciated.

Cheers,
Yogesh

**Comment by Vapok** [comment]
Do other API calls work? I would make sure that you haven't run out of messages for the free account. I believe after 30 days, it drops down to 100 or something like that.

**Comment by thinkingserious** [comment]
Hello @HindoliyaYogesh,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by HindoliyaYogesh** [comment]
Hello @thinkingserious 

Following is the response received from sendgrid support!
Regardless, I have logged another ticket quoting your response on this issue.

![image](https://user-images.githubusercontent.com/40543539/51467067-50c4d700-1d74-11e9-9118-cb6cda1424d8.png)

Thanks,
Yogesh

**Comment by shuaibgloballogic** [comment]
Hi Yogesh,

I am also facing same issue. Did you find the solution of this problem? When i use key given by company key(though it is free account) , it works fine but same time i get 403 using my personal free account key.  I am trying to send mails through my C# code which run using Visual Studio credentials.

**Comment by HindoliyaYogesh** [comment]
@shuaibgloballogic 
When you say Visual Studio Credentials, are you talking about your AD creds? SendGrid API from C# works using API key generated using the portal. The API key is a secret that you can store in your config files and when instantiating the object for SendGrid, pass it to the constructor.
var client = new SendGridClient(_**<pass your key here>**_);
Check the following:

1. You are using a valid API key to send emails.
2. Your Email Limit is not breached.
3. The sender domain is whitelisted and if you are not whitelisting domains, then the sender email address has a totally invalid domain (something like _@mailer-yourdomain.com_)

To generate an API key, login to sendgrid, go to settings > API Keys and create new API Key. Copy the key, because it will not be visible anytime after this instance.

To White label, you will need help of your domain administrator.

1. Login to SendGrid
2. Go to Settings > Sender Authentication
3. And follow this tutorial : [Sender Authentcation](https://sendgrid.com/docs/ui/account-and-settings/how-to-set-up-domain-authentication/)

**Comment by childish-sambino** [comment]
Also recommend logging/printing to full error response body which contains additional error details. Example here: https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error-messages
