### ISSUE TITLE
SendEmailAsync no response from c# project

### ISSUE THREAD

**Issue by FourieDeWet** [sendgrid/sendgrid-csharp#853]
#### Issue Summary

I have a C# WinForms project using SendGrid 9.10.0. I send email using the SendEmailAsync but the call never returns a result even though the email is sent. 
I have Googled for resolutions but could not find a anything, I also contacted SendGrid API Support and they informed me to post here because their knowledge to code review/scripts is limited. I see the same issue logged here #https://github.com/sendgrid/sendgrid-csharp/issues/410 but I need to keep this call asynchronous and have some type of response.

### C# Winforms Code
```
private void sendBtn_Click( object sender, EventArgs e )
        {
            var response = Execute().Result;
        }

public async Task<Response> Execute()
        {
            var client = new SendGridClient( _sendGridApiKey );
            var mailMessage = new SendGrid.Helpers.Mail.SendGridMessage()
            {
                From = new EmailAddress( _fromMailAddress ),
                Subject = _subject,
                PlainTextContent = _plainTextContent,
                HtmlContent = _htmlContent
            };

            mailMessage.AddTo( _toMailAddress );
            var response = await client.SendEmailAsync( mailMessage );

            return response; // Code never reach this
        }
```

#### Steps to Reproduce

1. Setup a C# WinForms project
2. Install SendGrid via Package Manager Console (Install-Package SendGrid)
3. Add the necessary form controls with the backend code as specified above in the Issue Summary
4. Run the project filling in all the details and execute
5. The call is made and the email is sent but I never get a response from await client.SendEmailAsync( mailMessage );

#### Technical details:

* sendgrid-csharp Version: 3.0.0
* sendgrid Version: 9.10.0
* Platform (C# Winforms)
* .NET Version: 4.6.1
* Visual Studio 2017

**Comment by FourieDeWet** [comment]
@thinkingserious, 
Thank you for getting back with a proposed solution.
I can confirm that adding `.ConfigureAwait(false)` indeed solved my problem.

Thanks again

**Comment by nhanit2012** [comment]
> 
> 
> @FourieDeWet,
> 
> Thank you for the detailed note.
> 
> I would try the [solution proposed here first](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#ui-requests-are-failing--deadlocks). Please give it a try and let me know how it goes.
> 
> With Best Regards,
> 
> Elmer
Hi there,
When i try to use .ConfigureAwait(false) then all account of gmail will be send to spam folder. So, can we have any solution for this case?
Thank
