### ISSUE TITLE
SetTemplateData not working in .NET ( azure functions)

### ISSUE THREAD

**Issue by thilankascentic** [sendgrid/sendgrid-csharp#858]
Im trying to bind some values to transcriptional template, but those values not binding.

```
 var jsosn = JsonConvert.DeserializeObject<object>(ddata);
                    string sendGrid_API = "key";
                    var client = new SendGridClient(sendGrid_API);
                    var from = new EmailAddress("from@gmail.com", "Example User");
                    var to = new EmailAddress("to@mymail.lk", "Example User 2");
                    var dynamicTemplateData = new Person
                    {
                        name="new Name"                       
                    };
                    var msg = MailHelper.CreateSingleTemplateEmail(from, to, "d-xxxxx",jsosn);
                    msg.SetTemplateData(dynamicTemplateData);
                    var response = await client.SendEmailAsync(msg);
```

email sending perfectly but values not binding, anyone got a solution for this ?

**Comment by thinkingserious** [comment]
Hello @thilankascentic,

Can you please try refactoring your code based on [this example](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates)?

With Best Regards,

Elmer

**Comment by davidbilling** [comment]
@thinkingserious  I try to use your example, but the methon SetTemplateData does not even exist!?!

**Comment by Geertvdc** [comment]
> @thinkingserious I try to use your example, but the methon SetTemplateData does not even exist!?!

I ran in to the same problem as @davidbilling today and you'll need to add the "sendgrid" nuget package as well to get the SetTemplateData method ;) with only the "Microsoft.Azure.WebJobs.Extensions.SendGrid" Pacakage it doesn't have this method.

will probably be to late for @davidbilling but might help others also stumbling upon this.

**Comment by toastmastern** [comment]
Microsoft.Azure.WebJobs.Extensions.SendGrid uses SendGrid 9.9.0, dynamic templates seems to be introduced in 9.10.0 (released 2018), https://github.com/sendgrid/sendgrid-csharp/blob/master/CHANGELOG.md

I skipped the function binding and used the new package but would be nice to be able to do this out of the box

**Comment by thinkingserious** [comment]
Thanks for helping out @Geertvdc!

@thilankascentic, @davidbilling,

Please re-open this issue if you are still experiencing issues.

**Comment by DjolePetrovic** [comment]
Did you get this working with the IAsyncCollector? Or are you creating every time a new SendGridClient?

**Comment by Dreathorian** [comment]
> 
> 
> Hello @thilankascentic,
> 
> Can you please try refactoring your code based on [this example](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates)?
> 
> With Best Regards,
> 
> Elmer

woooow, after hours of trial and error I finally found the proper code example for the most simple tasks. slowclap guys, slowclap.
