### ISSUE TITLE
Get data from marketing campaigns from your api

### ISSUE THREAD

**Issue by Pieter-1337** [sendgrid/sendgrid-csharp#861]
Hi, I am using Sendgrid for a client of us whom also started using marketing campaigns recently. Now they are asking if it is possible to get the statistics concerning the marketing campaigns they are sending in a seperate rapport.  So is it possible for your api to return data concerning Marketing campaigns if I would make a let's say a daily request of all marketing campaigns of a certain SendGrid account?

**Comment by thinkingserious** [comment]
Hello @Pieter-1337,

Here is the information on [marketing campaign stats.](https://sendgrid.com/docs/API_Reference/api_v3.html)

I hope that helps!

With Best Regards,

Elmer

**Comment by Pieter-1337** [comment]
Hi Elmer,

Thanks for the reponse, according to that documentation it would not be possible to retrieve data like unique opens, clicks in the mail, and other marketing related statistics concerning single mail campaigns? Am I right to assume this or have I missed something in the documentation? My client would very get all possible information (so what the end receiver does with the mail) concerning here marketing campains (all campaigns together or seperated). Please inform me if this is possible with SendGrid.

With Best regards 

Pieter

**Comment by thinkingserious** [comment]
Hello @Pieter-1337,

You are correct. However, there is a workaround. If you use categories in Marketing Campaigns, you could then use the `/categories/stats` endpoint.

With Best Regards,

Elmer

**Comment by Pieter-1337** [comment]
Hi, @thinkingserious ,

Thanks for the work-around that's already a lot of information I can use now.
One more question though, with the` categories/stats` endpoint I would be receiving a lot of information about Clicks, opens, bounced etc but all would return integers as in the number of actions. Is there a possibility to get the actual values of the email-addresses (array or list perhaps) whom clicked,opened bounced etc. Or does the API not offer that kind of Data?

With Best Regards

Pieter

**Comment by thinkingserious** [comment]
No, the API does not offer that level of granularity currently.
