### ISSUE TITLE
Send Grid Transnational Template example 

### ISSUE THREAD

**Issue by simba22042** [sendgrid/sendgrid-csharp#863]
Is there a working example of using the C# Send Grid Client SDK with transnational template. My issue is my dynamic data is not getting populated when using a transnational template .  

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @simba22042,

Have you taken a look [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates)?

Please let me know if that helps.

With Best Regards,

Elmer
