### ISSUE TITLE
Quickstart C# code sends mail, but hangs on last instruction in MVC

### ISSUE THREAD

**Issue by jrichview** [sendgrid/sendgrid-csharp#869]
#### Issue Summary

Using the sample code provided for quickstart I created a simple ASP.NET  MVC app. During form post I call the Execute() method and it never returns from the final instruction of the method, thus hanging the application. The email DOES get sent, though.

#### Steps to Reproduce

1) Create a simple MVC app (regular dotnet, not Core), add the Sendgrid library via Nuget
2) create very, very basic Contact Us html form and post method.
3) Call the quick start C# sample code Execute() method as documented, hangs the application.
4) Step through the Execute method in the debugger to determine what line it hangs on

I am using library version 9.10.0 (latest stable in Nuget)

DotNet framework version is 4.6.1

Only other thing code is doing is reading some of the values from the web.config file the usual way.  This does not impact the behavior as you can tell by hard-coding the values.

**Comment by jrichview** [comment]
Tested with framework 4.7.2 and same problem. Created new project from scratch.

**Comment by thinkingserious** [comment]
Hello @jrichview,

For ASP.NET projects, please have a look at [this example project](https://github.com/sendgrid/sendgrid-csharp/blob/master/ExampleNet45ASPNetProject/SendGrid.ASPWebFormsSamples/Services/SendGridService.cs).

Please let me know if that helps!

With Best Regards,

Elmer

**Comment by jrichview** [comment]
Elmer, 
Thank you for sending that link. However, that is an example of an ASP.NET WebForms project, not an MVC project.  Also, I'm not having any difficulty understanding how to call the code. I've been a professional software developer since the late 1980s.  I clearly understand how to include the library and call it. I've used the C# sample code in the past (I believe it was V2 interface).

What I am saying is that there's a bug in the library that is hosted in Nuget. When you execute the send, the await never returns:

`await _client.SendEmailAsync(sendgridMessage);
`

**Comment by thinkingserious** [comment]
Thank you for the elaboration @jrichview.

Just one more clarification, are you calling the `Execute()` method like this `Execute().Wait();`?

In any case, I'm adding this to our backlog for further investigation as well.

**Comment by jrichview** [comment]
I've uploaded a full demo here: https://github.com/jrichview/SendgridV3BugMVCDemo/

This project was created from scratch in Visual Studio 2017 using MVC and bare bones code. I am attaching Steps to reproduce this issue if you'd like or you can just download the project from the above link and plug in your own Sendgrid key and TO email to run it for yourself and see the problem.

[Steps To Reproduce Sendgrid Problem.txt](https://github.com/sendgrid/sendgrid-csharp/files/2989792/Steps.To.Reproduce.Sendgrid.Problem.txt)

**Comment by jnyrup** [comment]
@jrichview The problem might be, that your code blocks the async part
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by jrichview** [comment]
Well, to begin with I'm calling the code precisely the way the C# sample specifies it should be called. Did you look at the example controller code in the project above?

**Comment by thinkingserious** [comment]
Thanks for helping out @jrichview, we appreciate it!

@jrichview, thanks for the great job on explaining the issue. This is currently on our backlog for further review. It looks like you've provided us with all we need to replicate the issue.

**Comment by thinkingserious** [comment]
@jrichview,

On [this line](https://github.com/jrichview/SendgridV3BugMVCDemo/blob/master/SendgridMVCDemo/Controllers/HomeController.cs#L39), can you try `client.SendEmailAsync(emailMessage).Result`? and see if you get a response?

**Comment by LCichanowiczPMG** [comment]
@thinkingserious, I just experienced the same problem as the OP (@jrichview), with a clean, simple setup.  I changed [that line ](https://github.com/jrichview/SendgridV3BugMVCDemo/blob/master/SendgridMVCDemo/Controllers/HomeController.cs#L39) of code, as you described, and now it works, but is now sync, instead of async.

**Comment by lcichanowicz** [comment]
@thinkingserious, I just experienced the same problem as the OP (@jrichview), with a clean, simple setup.  I changed [that line ](https://github.com/jrichview/SendgridV3BugMVCDemo/blob/master/SendgridMVCDemo/Controllers/HomeController.cs#L39) of code, as you described, and now it works, but is now sync, instead of async.

**Comment by lcichanowicz** [comment]
@thinkingserious, I just experienced the same problem as the OP (@jrichview), with a clean, simple setup.  I changed [that line ](https://github.com/jrichview/SendgridV3BugMVCDemo/blob/master/SendgridMVCDemo/Controllers/HomeController.cs#L39) of code, as you described, and now it works, but is now sync, instead of async.

**Comment by thinkingserious** [comment]
Thanks for the additional input @lcichanowicz!

**Comment by jrichview** [comment]
Sorry guys, I ended up rewriting it to use std DotNet SMTP rather than the SendGrid library.  If you still need me to I can download the sample code that I linked above and try the mod.

**Comment by thinkingserious** [comment]
No worries @jrichview, I'm appreciative that you circled back with us. If you do have a minute, your additional feedback would be useful towards improving the experience for future users :)
