### ISSUE TITLE
System.Core Warning

### ISSUE THREAD

**Issue by Tenrosei** [sendgrid/sendgrid-csharp#87]
The SendGrid.SmtpApi.dll uses System.Core Version 2.0.5.0 with a PublicKeyToken=7cec85d7bea7798e This causes conflicts when you add the csharp package to a project with System.Core Version 4.0.0.0 with a PublicKeyToken=B77A5C561934E089 . the different public key tokens are stopping us from using assembly binding redirects. and stops us from being able to upgrade our solution to the new versions of system.core without having to suppress a build warning.

could we get the SendGrid.SmtpApi.dll upgraded to use the new core?
(note microsoft seems to have changed System.Core's public key when they went from 2.0.5.0 to 3.5.0.0 but 3.5.0.0 uses the same public key as 4.0.0.0)

**Comment by brandonmwest** [comment]
Moving this to smtpapi-csharp https://github.com/sendgrid/smtpapi-csharp/issues/9 thanks for the report!
