### ISSUE TITLE
Needed to reboot azure webapp to let SendMail API working

### ISSUE THREAD

**Issue by easytruckingET** [sendgrid/sendgrid-csharp#872]
Hi, 

we are experiencing a problem related to the sendgrid API that automatically sends e-mail templates from a C#.NET code. As follows you find a functional description of the issue:

1) When a new user registers to our web platform, the sendgrid API is automatically called by a procedure written in C#

2) At this point the system should send an e-mail automatically to the user that has registered but nothing happens. In the activity list of the sendgrid dashboard, there is no trace of the mail sent by the system.

3) We reboot our Azure application and wait some minutes

4) We manually push a button located in our dashboard that calls the same API of the automatic procedure explained in the point 1. This button attempts again the mail sending to the same e-mail address that has completed the registration to our platform. After some minutes from rebooting and after having pushed the button, the mail is correctly sent to the user and it appears also in the Activity list (well note if we try to push this button before rebooting nothing happens)

As follows you find the text of the C# code that calls the API:

````
public static async Task<dynamic> SendMail(string apiKey, string templateId, string mailFrom, string mailFromAlias, string mailTo, string mailToAlias, string subject, string body, IEnumerable<KeyValuePair<string, string>> dataToBind, IEnumerable<AttachmentInfo> attachments, bool html)
        {
            dynamic sg = new SendGridAPIClient(apiKey);
            Email from = new Email(mailFrom, mailFromAlias);
            Email to = new Email(mailTo, mailToAlias);
            Content content = new Content(html ? "text/html" : "text/plain", body);
            global::SendGrid.Helpers.Mail.Mail mail = new global::SendGrid.Helpers.Mail.Mail(from, subject, to, content) { TemplateId = templateId };

            foreach (var p in dataToBind)
                mail.Personalization[0].AddSubstitution("-" + p.Key + "-", p.Value);

            if (attachments != null)
                foreach (var attach in attachments)
                    mail.AddAttachment(new Attachment
                    {
                        Filename = attach.FileName,
                        Content = attach.Content,
                        Type = attach.Type
                    });

            dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());

            try
            {
                string resultSendGrid = Newtonsoft.Json.JsonConvert.SerializeObject(response);
                var logPath = ConfigurationManager.AppSettings["LogPath"];
                if (logPath.StartsWith("~"))
                    logPath = System.Web.Hosting.HostingEnvironment.MapPath(logPath);

                System.IO.File.AppendAllText(Path.Combine(logPath,"LogSendgrid.txt"), resultSendGrid);  

            }
            catch (Exception e)
            {
                var errore = e.Message;
            }
            return response;
        }
````

Is there anybody that has already experienced this issue before that can propose us a possible solution? 

We wait your feedbacks, feel free to ask me for any other clarifications

Thanks in advance

**Comment by thinkingserious** [comment]
Hello @easytruckingET,

In the case where the email is not sent, do you receive any errors? My guess would be that the issue is related to your API Key not getting set properly the first time.

With Best Regards,

Elmer

**Comment by easytruckingET** [comment]
Hello @thinkingserious ,

no errors at all! In our log file there is always the 202 code that means Accepted. As follows you find an example taken from the log file:

`{
"StatusCode": 202,
"Body": {
"Headers": [{
"Key": "Content-Length",
"Value": ["0"]
}, {
"Key": "Content-Type",
"Value": ["text/plain; charset=utf-8"]
}
]
},
"Headers": [{
"Key": "Connection",
"Value": ["keep-alive"]
}, {
"Key": "X-Message-Id",
"Value": ["p--rdhrcT9-Nj6eF5mL6hQ"]
}, {
"Key": "Access-Control-Allow-Origin",
"Value": ["https://sendgrid.api-docs.io"]
}, {
"Key": "Access-Control-Allow-Methods",
"Value": ["POST"]
}, {
"Key": "Access-Control-Allow-Headers",
"Value": ["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"]
}, {
"Key": "Access-Control-Max-Age",
"Value": ["600"]
}, {
"Key": "X-No-CORS-Reason",
"Value": ["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]
}, {
"Key": "Date",
"Value": ["Thu, 21 Mar 2019 15:55:33 GMT"]
}, {
"Key": "Server",
"Value": ["nginx"]
}
]
}`

We use libraries adviced by Sendgrid (Sendgrid.CSharp.HTTP.Client) taken from nuget:

![image](https://user-images.githubusercontent.com/49001415/55169373-fb8eb280-5174-11e9-8304-0a306602d61f.png)

Can you please be more clear regarding the setting of the API Key at the first time?

Thanks in advance

**Comment by thinkingserious** [comment]
Hello @easytruckingET,

I think have misunderstood you. Could you please verify my assumptions:

1. You have live code running on Azure and when an email should be triggered, nothing happens. 
2. Or, during item 1, do you get the 202, but don't see the email activity?

If item 1 is correct, can you try logging the request body after you make the call?

What I meant by setting the API Key at the first time, is that if your API Key was not set properly in the environment, the call will fail and you should receive an error. I was guessing that by rebooting the machine, that allowed the API Key to get set properly. 

With Best Regards,

Elmer

**Comment by easytruckingET** [comment]
Hello @thinkingserious,

1. Yes, it's right what you're saying regarding the activation mail sent to the user. The situation with other mails triggered by the system in other steps of our workflow (e.g. the order confirmation) when the user has already activated the account is different and mails are correctly sent.
2. Yes, during item 1, we get the 202 but there isn't mail activity.

I let you know regarding the logging of the request body after the call.

Best regards
Antonio

**Comment by thinkingserious** [comment]
Hello @easytruckingET,

Based on your description, my guess is that the logic to send the email in the activation work flow is not triggering the email. Please let me know what your logging reveals.

With Best Regards,

Elmer
