### ISSUE TITLE
Empty list call to AddCcs results in Bad Request from API.

### ISSUE THREAD

**Issue by kowalej** [sendgrid/sendgrid-csharp#873]
#### Issue Summary

When sending an email after calling SendGridMessage.AddCCs and supplying a null or empty CC list - I receive a [400] Bad Request response from the API and my email is not sent.

No error is thrown when calling AddCCs with a null or empty list, and the problem only arises after calling the API. It took my a very long time to narrow this down as the single reason I was getting bad responses.

Obviously my solution was to not call AddCCs if there are no CCs provided to my function that generates the SendGridMessage, however I really don't think calling the method with a null or empty list should destroy the message integrity from an API validation standpoint.

#### Steps to Reproduce

I'm setting up the email using the template helper:
var emailInfo = MailHelper.CreateSingleTemplateEmailToMultipleRecipients(...);

Then adding some CC addresses like this:
emailInfo.AddCcs(ccList);

And sending using the SendGridClient:
SendGridClient client = client = new SendGridClient(_apiKey);
response = await client.SendEmailAsync(emailInfo); ...

#### Technical details:

* sendgrid-csharp Version: 9.10.0 (Nuget)
* Platform (ASP.NET WebAPI)
* .NET Version: 4.7.2

**Comment by thinkingserious** [comment]
Hello @kowalej,

I agree with you, we should be handling this much more gracefully. My apologies for the poor experience :( 

I've added this to our backlog.

With Best Regards,

Elmer

**Comment by manutdkid77** [comment]
@thinkingserious Can I work on this issue?

**Comment by hariharan618** [comment]
#927

**Comment by hariharan618** [comment]
#927 I have fixed this today and submitted a PR

**Comment by indy-singh** [comment]
I believe I fixed this in https://github.com/sendgrid/sendgrid-csharp/pull/981 cc @childish-sambino
