### ISSUE TITLE
SendGrid - Unable to send email with Substitution in Asp.Net MVC

### ISSUE THREAD

**Issue by MuhammadTanveerAshraf** [sendgrid/sendgrid-csharp#874]
#### Issue Summary

I am using SendGrid Free version Transactional Templates. I am trying to send email with substitutions using Mail object. When I remove substitutions from Personalization, it sends email successfully to the recipient. But with substitutions, it fails with 400 - BAD REQUEST.
Moreover i reconfirm from the template my dynamic parameters are the same as i am using in SendGrid Mail object i.e.
[Email]
[UserName]
[Password]

#### Steps to Reproduce

1. Add Substitutions as new Dictionary<string, string>
   new Dictionary<string, string>
                {
                    { "[Email]", "my email"},
                    { "[UserName]", "user name"},
                    { "[Password]", "password" }
                }
2. send email using Mail object

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: 8.0.5
* Platform: ASP.NET MVC
* .NET Version: 4.6.2

@thinkingserious

**Comment by MuhammadTanveerAshraf** [comment]
@thinkingserious

**Comment by thinkingserious** [comment]
Hello @MuhammadTanveerAshraf,

Could you please try utilizing the examples [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates)? You will need to upgrade to [v9.10.0](https://github.com/sendgrid/sendgrid-csharp/releases/tag/v9.10.0).

With Best Regards,

Elmer

**Comment by MuhammadTanveerAshraf** [comment]
Thanks @thinkingserious for your response. 
I've tried using substitutions with Legacy Templates and its working :)
