### ISSUE TITLE
HttpClient timeout

### ISSUE THREAD

**Issue by liweipro** [sendgrid/sendgrid-csharp#88]
Hi, When I use SendGrid 5.0.0.0 library to send large size file, I get Task cancelled exception. Then I change the source code to increase the default HttpClient timeout, the email sent out successfully. So the problem must be the timeout. 
Could you please add a overload Deliver method to accept a timeout value ? That would be very useful. 
Thanks.

**Comment by brandonmwest** [comment]
I'm adding a new Web interface constructor that allows this to be specified. That way we can avoid changing the ITransport interface. Hope that will work for you.

**Comment by brandonmwest** [comment]
Fixed in 5.1.0

**Comment by IS-LiweiXu** [comment]
Thank you very much. This really helps us.
