### ISSUE TITLE
HtmlContent: special characters are being replaced

### ISSUE THREAD

**Issue by vogeljo** [sendgrid/sendgrid-csharp#884]
#### Issue Summary

When trying to send an email containing an [Adaptive Card](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card), it is necessary to wrap the card data into a `<script type="application/adaptivecard+json">`. When i send an email containing an adaptive card, SendGrid replaces the `+` sign by `&#43;`. This destroys the complete adaptive card scenario, since Outlook does not recognize this tag as an adaptive card anymore.
This occures when sending an HTML file as email using SendGrid, no templates used.

I would not expect SendGrid to do any escaping/transcoding of any sort with my HTML mail, since this should be **MY** task as i am sending an HTML **ENCODED** message, hence i am responsible for its content. What is the reason for SendGrid doing this to my markup?

Is there any option to disable this "feature"?

#### Steps to Reproduce

1. Create a SendGridMessage and set HtmlContent to valid HTML code containing a `script` with `type="application/adaptivecard+json"`
2. Send this SendGridMessage 
3. Open the message in Outlook to see a blank page, instead of displaying the adaptive card. View the mail source in Outlook to confirm `application/adaptivecard+json` has been replaced by `application/adaptivecard&#43;json`.

#### Technical details:

* sendgrid-csharp Version: 9.11.0
* Platform: .NET Core 2.2 (netcoreapp2.2)

**Comment by thinkingserious** [comment]
Hello @vogeljo,

In order to further assist, could you pease provide a [sample request body](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#request-body) so I may try to reproduce? You can also send it to dx@sendgrid.com if you prefer. 

Thanks!

With Best Regards,

Elmer

**Comment by vogeljo** [comment]
Hi @thinkingserious,

here is an example request body:

```json
{
    "from": {
        "email": "test@example.org"
    },
    "subject": "Actionable Message Test",
    "content": [
        {
            "type": "text/html",
            "value": "\u003chtml\u003e\u003chead\u003e\u003cscript type=\u0022application/adap\u0026tivecard+json\u0022\u003e{ [Adaptive Card Metadata here] }\u003c/script\u003e\u003c/head\u003e\u003c/html\u003e"
        }
    ]
}
```

**Comment by thinkingserious** [comment]
This code appears to work:

```javascript
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'ethomas@twilio.com',
  from: 'dx@sendgrid.com',
  subject: 'Hello world',
  text: 'Hello plain world!',
  html: '<html><head><script type="application/adaptivecard+json">MetaData</script></head></html>'
};

sgMail
  .send(msg)
  .then(() => {
    //Celebrate
    console.log('Email Sent!');
  })
  .catch(error => {

    //Log friendly error
    console.error(error.toString());

    //Extract error msg
    const {message, code, response} = error;

    //Extract response msg
    const {headers, body} = response;
  });
```

Could you please give it a try?

**Comment by vogeljo** [comment]
Hi @thinkingserious,

i don't know how this node script is related to the C# client, but i tried it anyways. The result was exactly the same, meaning this is a server-side issue.
Is there any way i can work around this? Or can you tell me who i should speak to about this issue?

Thanks.

**Comment by thinkingserious** [comment]
My apologies for getting my programming languages mixed up, I suppose I must have just answered a question on our Node.js library (facepalm)

For me, the Node.js code above did not do the special character replacements. Are you saying that the characters were still replaces when you tried to run that code in Node?

**Comment by vogeljo** [comment]
Yes, exactly.

**Comment by thinkingserious** [comment]
Hi @vogeljo,

Did it replace them in the same way as you describe above? When I looked in Gmail (view original), I saw that the characters were as I described them in my example.

Perhaps you can also try using [curl](https://sendgrid.com/docs/for-developers/sending-email/curl-examples) for debugging purposes.

Please let me know how it goes. If it's a server side issue, then I suggest you reach out to our [support team](https://support.sendgrid.com). 

With Best Regards,

Elmer

**Comment by vogeljo** [comment]
Hi @thinkingserious ,
you are right. I did not try using another mail hoster or client yet because Outlook is the only Client actually supporting Adaptive Cards and my company is using Office365 Exchange. We are now convinced that the problem lies inside our Exchange configuration.

For anyone else having the same issue: The faulty part is **NOT SendGrid**, it's _probably_ hidden somewhere in your Exchange configuration

Thanks for your kind support! :)

**Comment by thinkingserious** [comment]
Thanks for following up @vogeljo!
