### ISSUE TITLE
Trying to get stats using SendGrid.SendGridClient.Method.Get, error 'given key was not present in the dictionary'

### ISSUE THREAD

**Issue by BigClear** [sendgrid/sendgrid-csharp#886]
#### Issue Summary

I am getting an exception error 'the given key was not present in the dictionary' when I try to do a GET request for categories/stats 

I am able to send emails so my SendGrid.SendGridClient and API key work for that, just not when I try to retrieve category stats using the SendGridClient.Method.Get … I've tried it with and without Headers when I create the SendGridClient.

Here is the error stack trace I get 
 at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SendGrid.SendGridClient.ParseJson(String json) in C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\SendGridClient.cs:line 396
   at SendGrid.SendGridClient.BuildUrl(String urlPath, String queryParams) in C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\SendGridClient.cs:line 275
   at SendGrid.SendGridClient.<RequestAsync>d__22.MoveNext() in C:\Users\elmer\Documents\GitHub\sendgrid-csharp\src\SendGrid\SendGridClient.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LLP.LogicLayer.Common.VB$StateMachine_220_TrySendGridStats.MoveNext() in C:\Users\artdu\source\repos\LLP_Azure\LLP_Azure\LogicLayer\Common.vb:line 1726

here is my code with the headers - I've also tried it without the myHeaders which is how I create the SendGridClient for sending emails which works.  

Public Shared Async Sub TrySendGridStats(ByVal CallingProc As String, ByVal myAssocName As String, ByVal myConn As String)
 
            Dim myResult As String
            Dim myAPIKey As String
            myAPIKey = ConfigurationManager.AppSettings("SGapiKey")
            Dim myHeaders As New Dictionary(Of String, String)
            myHeaders.Add("X-Mock", "200")
            Dim myClient As SendGrid.SendGridClient
            myClient = New SendGrid.SendGridClient(myAPIKey,, myHeaders)
            Try
                Dim response As SendGrid.Response = Await myClient.RequestAsync(SendGrid.SendGridClient.Method.GET,, "'aggregated_by':'day','categories':'MyLakeAssociation','end_date':'2019-05-18','start_date':'2019-05-17'", "categories/stats")
                If response.StatusCode.ToString <> "Accepted" Then
                    myResult = "Failed: " + response.StatusCode.ToString
                    LogicLayer.Common.WriteError(myConn, "SendGrid Stats error in " + CallingProc, myAssocName, myResult)
                End If
            Catch ex As Exception
                myResult = "Failed: " + ex.ToString
                LogicLayer.Common.WriteError(myConn, "SendGrid Stats error in " + CallingProc, myAssocName, myResult)
            End Try
        End Sub

#### Steps to Reproduce

I call the above procedure to get my stats

Don't expect it to be a bug, rather I'm not doing something correctly in my code - any help fixing my code would be appreciated!  thanks

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by BigClear** [comment]
ok I found, and fixed, the problem.  The queryParams string was  missing the { } … so instead of "'aggregated_by':'day','categories':'MyLakeAssociation','end_date':'2019-05-18','start_date':'2019-05-17'" it needed to be "{'aggregated_by':'day','categories':'MyLakeAssociation','end_date':'2019-05-18','start_date':'2019-05-17'}" … error message was misleading - makes you think there is something wrong with the API key.

**Comment by thinkingserious** [comment]
Thanks for taking the time to provide an update!
