### ISSUE TITLE
Sign an email with personal certificate

### ISSUE THREAD

**Issue by stiliqn-angelov** [sendgrid/sendgrid-csharp#887]
We are considering using SendGrid in our .NET framework application, but I am having a hard time finding out if it is possible configure emails to be signed. 
I would appreciate an alternative option if this is not possible. Thanks in advance!

**Comment by thinkingserious** [comment]
Hello @stiliqn-angelov,

This is not possible using our APIs directly. You would [configure your email client](https://sendgrid.com/blog/end-end-email-encryption-smime/) with your certificate while using your [SendGrid SMTP credentials](https://sendgrid.com/docs/for-developers/sending-email/integrating-with-the-smtp-api/).

I hope that helps!

With Best Regards,

Elmer
