### ISSUE TITLE
Question - How long does it take to send an email?

### ISSUE THREAD

**Issue by warrenkc** [sendgrid/sendgrid-csharp#891]
#### Issue Summary

I am trying to reduce the amount of time it takes to send an email using SendGrid.
I tested the amount of time using the SendEmailAsync api call. Time: 774 Milliseconds https://github.com/sendgrid/sendgrid-csharp#hello-email
I tested the amount of time using the SendGrid with SmtpClient. 1837 Milliseconds

Is there any way to get the time down for sending a single email? If I upload a file to AWS S3 it much faster than sending an email. I appreciate your help.

SmtpClient Code
` private static void SendSmtpEmail()
        {
            var from = "user@example.com";
            var subject = "Sending with Twilio SendGrid is Fun";
            var to = "123@sink.sendgrid.net";
            var body = "and easy to do anywhere, even with C#";            

            MailMessage mail = new MailMessage(from, to, subject, body);

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.sendgrid.net";
            smtp.Port = 587;
            smtp.Credentials = new NetworkCredential(
            "apikey", "xxxxxxxxxxxxxxxxxxxxxxxxxxxx");
            smtp.EnableSsl = true;            
            smtp.Send(mail);
        }`

#### Steps to Reproduce

1. Created Console app for demo.
2. Used System.Diagnostics.Stopwatch to time the operation.
3. Compared various methods.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: 9.x
* Platform .Net Console App
* .NET Version: 4.6.1

**Comment by thinkingserious** [comment]
Hello @warrenkc,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
