### ISSUE TITLE
Passing data into {{#each }} returns unexpected results.

### ISSUE THREAD

**Issue by Ihavenowand** [sendgrid/sendgrid-csharp#894]
I pass the following JSON into SendGrid (expecting one iteration of the product card using the HTML below.  Instead, I get four.  Any ideas why?

```
      var dynamicTemplateData = new TemplateData
            {
                order_id = 123456,
                total = "12.10",
                subtotal = "10.10",
                tax = "2.00",
                items = new Items
                {
                    text = "test item",
                    sku = "AA1234",
                    price = "12.50",
                    qty = 5
                }
}
```

![sendGridProblem](https://user-images.githubusercontent.com/26672549/59851780-62cb9580-9365-11e9-99c1-d0fa68799f24.png)
```
{{#each items}}

<table class="wrapper" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td class="px-sm-16" align="center" bgcolor="#EEEEEE">
      <table class="container" cellpadding="0" cellspacing="0" role="presentation" width="600">
        <tr>
          <td class="px-sm-8" align="left" bgcolor="#FFFFFF" style="padding: 0 24px;">
            <table cellpadding="0" cellspacing="0" role="presentation" width="100%">
              <tr>
                <td class="col col-sm-1 pb-sm-8" width="100" style="padding: 0 8px;">
                  <img src="https://dummyimage.com/200x260/0CBACF/FFFFFF" alt="Product title" width="100">
                </td>
                <td class="col col-sm-3 webfont" width="284" style="padding: 0 8px; vertical-align: middle;">
                  <p style="color: #999999; margin: 0;">{{this.text}}</p>
                  <p style="color: #999999; margin: 0;">SKU: {{this.sku}}</p>
                </td>
                <td class="col col-sm-1 col-sm-push-1 webfont" width="48" style="color: #999999; padding: 0 8px; vertical-align: middle;">QTY: {{this.qty}}</td>
                <td class="col col-sm-1 col-sm-push-1 webfont" align="right" width="56" style="color: #999999; padding: 0 8px; vertical-align: middle;">£{{this.price}}</td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<table class="wrapper" cellpadding="0" cellspacing="0" role="presentation" width="100%">
  <tr>
    <td class="px-sm-16" align="center" bgcolor="#EEEEEE">
      <table class="container" cellpadding="0" cellspacing="0" role="presentation" width="600">
        <tr>
          <td class="divider py-sm-16 px-sm-16" bgcolor="#FFFFFF" style="padding: 24px 32px;">
            <div style="background: #EEEEEE; height: 1px; line-height: 1px;">&zwnj;</div>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

{{/each}}

```

**Comment by aevitas** [comment]
How is `Items` implemented?

**Comment by Ihavenowand** [comment]
private class TemplateData
        {
            public string order_id { get; set; }
            public string total { get; set; }
            public string subtotal { get; set; }
            public string tax { get; set; }
            public Items items { get; set; }
            public ShippingAddress shipping_address { get; set; }
            public BillingAddress billing_address { get; set; }
        }

        private class Items
        {
            public string text { get; set; }
            public string sku { get; set; }
            public string price { get; set; }
            public int qty { get; set; }
        }

        private class ShippingAddress
        {
            public string first_name { get; set; }
            public string last_name { get; set; }
            public string street { get; set; }
            public string city { get; set; }
            public string region { get; set; }
            public string postcode { get; set; }
        }
        private class BillingAddress
        {
            public string first_name { get; set; }
            public string last_name { get; set; }
            public string street { get; set; }
            public string city { get; set; }
            public string region { get; set; }
            public string postcode { get; set; }
        }

**Comment by aevitas** [comment]
I'm fairly sure handlebars expects the object that is being `#each`'d to be enumerable, e.g. an array in JSON, or simply an `IEnumerable<T>` in C#.

Ergo, your `TemplateData` type should look something along the lines of:

```csharp
        private class TemplateData
        {
            public string order_id { get; set; }
            public string total { get; set; }
            public string subtotal { get; set; }
            public string tax { get; set; }
            public List<Items> items { get; set; }
            public ShippingAddress shipping_address { get; set; }
            public BillingAddress billing_address { get; set; }
        }
```

Also, I'm fairly confident the `this.` accessor shouldn't be in your HTML. If I'm not mistaken, `this.` points to an instance member, while you're looking to access the current item in the iteration. 

Your HTML should look something along the lines of:

```
{{#each items}}
[...]
                  <p style="color: #999999; margin: 0;">{{text}}</p>
[...]
{{/each}}
```

As an aside, if you're looking to maintain `PascalCase` naming conventions in your C# code while still making the thing compatible with the SendGrid API, you can use the `[JsonProperty]` attribute to rename your properties when they are serialized:

```csharp
private class TemplateData
{
    [JsonProperty("order_id")]
    public string OrderId { get; set; }

    [JsonProperty("total")]
    public string Total { get; set; }

    [JsonProperty("subtotal")]
    public string Subtotal { get; set; }

    [JsonProperty("tax")]
    public string Tax { get; set; }

    [JsonProperty("items")]
    public IEnumerable<Item> Items { get; set; }

    [JsonProperty("shipping_address")]
    public ShippingAddress ShippingAddress { get; set; }

    [JsonProperty("billing_address")]
    public BillingAddress BillingAddress { get; set; }
}

I reckon if you set that as the template using `message.SetTemplate(template);` and send it off, you should see the correct amount of orders and their respective data.

**Comment by Ihavenowand** [comment]
Thanks for your response aevitas.

I have implemented a list as per your advice, how would I call that within dynamicTemplateData?

`            // Set data for email template
            var dynamicTemplateData = new TemplateData
            {
                order_id = "123456",
                total = "12.10",
                subtotal = "10.10",
                tax = "2.00",
                // list to go here
            };`

**Comment by aevitas** [comment]
@Ihavenowand In the same way as you do the other assignments, e.g.:

```csharp
var dynamicTemplateData = new TemplateData
{
    // Other members omitted for brevity
    items = items
}
```

If you then pass that as the template data for your message, things should work out.

**Comment by thinkingserious** [comment]
Thank you for helping out @aevitas!

It looks like this issue is resolved, please reopen if necessary @Ihavenowand. Thanks!
