### ISSUE TITLE
Readme Quick Start section is using outdated syntax

### ISSUE THREAD

**Issue by aevitas** [sendgrid/sendgrid-csharp#895]
#### Issue Summary

The quick start example provided calls `.Wait()` on an `async` method to invoke the SendGrid API asynchronously. This is fine in this specific example, but [as of C# 7.1](https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/), the `Main` method in a console application can have the `static async Task Main()` signature:
```
    internal class Example
    {
        private static async Task Main()
        {
            var apiKey = Environment.GetEnvironmentVariable("NAME_OF_THE_ENVIRONMENT_VARIABLE_FOR_YOUR_SENDGRID_KEY");
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("test@example.com", "Example User");
            var subject = "Sending with Twilio SendGrid is Fun";
            var to = new EmailAddress("test@example.com", "Example User");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }
    }
```

Which is not only more succinct, but also promotes more idiomatic C#, as calling `Wait()` from synchronous methods can potentially cause heaps of trouble (like deadlocks, and nobody likes deadlocks).

Granted, nothing major, but I reckon we should promote good coding practice from the get go, and the readme is likely the first point of contact with programmers. 

In Visual Studio 2019 (and 2017 as well, iirc), the default language version is set to "C# latest minor version (latest)", which at the time of writing is C# 7.3, ergo this syntax should be supported by default for anyone looking to use the library.

**Comment by thinkingserious** [comment]
Thank you for reporting this @aevitas! I appreciate the detailed explanation and this has been added to our backlog and the issue tagged appropriately for community contribution.

With best regards,

Elmer
