### ISSUE TITLE
HttpClient should be a static instance, and threadpool expired periodically

### ISSUE THREAD

**Issue by mikeball** [sendgrid/sendgrid-csharp#897]
Currently HttpClient as used in https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGridClient.cs#L32 creates multiple instances of HttpClient which is improper use of the class.

It which needlessly recreates/duplicates the underlying tcp connection pools for each instance of SendGridClient created. More troublesome, it leaves the underlying pools of tcp connections in a wait status for several minutes after each instance of SendGridClient is disposed, using up limited network ports which can often cause issues on cloud platforms such as azure which are easily exhausted.

HttpClient instances should be static, and the underlying threadpool connections should be expired periodically to account for DNS changes for the remote host.

See https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.8

**Comment by aevitas** [comment]
See #839 @akunzai implemented this over half a year ago and it's awaiting response from one of the repository owners.
