### ISSUE TITLE
Chinese Character in AddSubstitution

### ISSUE THREAD

**Issue by chojowliu** [sendgrid/sendgrid-csharp#90]
Chinese characters work fine in .Subject .Html .Text, but when I tried to use AddSubsitution with Chinese characters, I kept getting wrong encoding in the result. Any idea?

**Comment by bobmclaren** [comment]
I experienced this same issue with AddSubstitution when using unicode with Latin characters. (Ã)

**Comment by brandonmwest** [comment]
This is being addressed in smtpapi-csharp and should be fixed soon. The workaround right now is to encode unicode in substitutions values to ASCII escape sequences.

**Comment by brandonmwest** [comment]
Fixed in 5.1.0
