### ISSUE TITLE
MailHelper.StringToEmailAddress() returns bad data when the display name contains an @ symbol

### ISSUE THREAD

**Issue by Fieora** [sendgrid/sendgrid-csharp#902]
#### Issue Summary

When using the MailHelper.StringToEmailAddress function, if the display name contains a @ symbol (ex. username@example.com <username@example.com>) instead of working correctly or failing, the regular expression sets the NameGroup to an empty string, and the Email group to a now deformed email string (ex. username@example.com <username@example.com) (missing the closing angle bracket)

#### Steps to Reproduce

1. Call MailHelper.StringToEmailAddress() with an '@' symbol in the display name area.

I am creating a pull request to resolve this issue.

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hi @Fieora,

Thanks for reporting and creating a PR! We've added this to our backlog for a code review. 

With best regards,

Elmer
