### ISSUE TITLE
Method not found: System.Net.Http.HttpContent SendGrid.Response.get_Body()

### ISSUE THREAD

**Issue by niranjankrsingh** [sendgrid/sendgrid-csharp#908]
#### Issue Summary

I have integrated Sendgrid in .net Web API. In local development environment it worked fine but when I deployed it on production server, it throws error as follows:

Method not found: 'System.Net.Http.HttpContent SendGrid.Response.get_Body()'.

I have use sendgrid  9.11.0.0. 
#### Technical details:

* sendgrid-csharp Version: 9.11.0.0
* Platform (Asp.net Web API)
* .NET Version: 4.6.1

**Comment by niranjankrsingh** [comment]
I observed it deployment issue. Removed reference of system.net.http from program files directory and added it from nuget package. It added below entry in web.config and issue got resolved.


<dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>

**Comment by christophborndigital** [comment]
In our case the SendGrid package was used in a class library, but the web project referencing it had an older version of System.Net.Http installed. Consolidating the versions of System.Net.Http allowed us to get the response body to see the error message.
