### ISSUE TITLE
Once domain is authenticated, SendGrid email doesn't display the "From" name in Gmail inbox

### ISSUE THREAD

**Issue by mirikerstein** [sendgrid/sendgrid-csharp#909]
Using .NET Core, and the SendGrid and SendGrid.Helpers.Mail nuget packages.
Using standard code to send a simple email. Code is:
`
private async void SendEmail(string fileString, string fileName, string body){

            try

            {

                var msg = new SendGridMessage();

                msg.SetFrom(new EmailAddress("no-reply@mydomain.com", "John Smith"));

                var recipients = new List<EmailAddress>

                {

                    new EmailAddress("janedoe@gmail.com", "Jane Doe")

            };

                msg.AddTos(recipients);

                msg.SetSubject("Email sent via SendGrid");

                msg.AddContent(MimeType.Text, body);

                msg.AddAttachment(fileName, fileString);

                var client = new SendGridClient(apiKey);

                var response = await client.SendEmailAsync(msg);

            }

            catch

            {

            }

        }

    }`

This sends the email just fine. Before I authenticated mydomain.com, the email would appear in Jane Doe's inbox perfectly, albeit with the 'sent via sendgrid' bit. Now, after authenticating the domain, the email appears in Jane Doe's inbox. But, instead of having the name "John Smith" appear as the "sender name", it merely displays no-reply@mydomain.com as the sender name in the Gmail inbox. Examining the email details shows that John Smith <no-reply@mydomain.com> is indeed the sender, but when you see the email in your inbox, you don't see that display name.

Any suggestions?

Thank you!

**Comment by thinkingserious** [comment]
Hello @mirikerstein,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
