### ISSUE TITLE
Please add the .XML and .CHM documentation files

### ISSUE THREAD

**Issue by DavidThi808** [sendgrid/sendgrid-csharp#91]
Please add the standard .xml (for intellisense) and .chm (the API documentation) files to this distribution. Without these using the API is basically a guessing game.

thanks - dave

**Comment by brandonmwest** [comment]
Hi Dave, thanks for the feedback. I'm adding the .xml file but I don't know how to get the .chml file. Can you point me in the right direction? Thanks!

**Comment by DavidThi808** [comment]
We use DocumentX<http://www.innovasys.com/product/dx/overview> to generate it. If your public methods are properly documented it’s all automatic once you set it up.

Thanks – dave

**Comment by brandonmwest** [comment]
Hi David, at this time I don't have the resources to instrument the project to generate .chm files. Hopefully the .xml file will help. Thanks for your feedback.
