### ISSUE TITLE
Problem making a request to SendGrid API

### ISSUE THREAD

**Issue by EdoRguez** [sendgrid/sendgrid-csharp#912]
#### Issue Summary

I'm trying to make a GET request to the API in C# using the NuGet Package. The problem is when I try to make a GET request to "categories/stats" it throws an error message saying _"start_date is required and should be a YYYY-MM-DD formatted date"_ even though I'm writting _"start_date"_ to the query parameter like the documentation says. Here is my code.

```
string queryParams = @"{
                              'aggregated_by': 'day', 
                              'categories': '2586', 
                              'end_date': '2019-07-01',
                              'limit': 1,
                              'offset': 1, 
                              'start_date': '2019-03-01' 
                       }";

var response = await client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "categories/stats", requestBody: queryParams)
```

#### Technical details:

* sendgrid-csharp Version: master #839
* Platform ASP.NET Core MVC
* .NET Core Version: 1.0

**Comment by EdoRguez** [comment]
Btw, I solved the issue without using the NuGet Package.
```
var client = new RestClient("https://api.sendgrid.com/v3/categories/stats?aggregated_by=day&limit=10&categories=MyCategory&start_date=2019-06-06");
var request = new RestRequest(Method.GET);
request.AddHeader("authorization", "Bearer <<MY TOKEN>>");
request.AddParameter("undefined", "{}", ParameterType.RequestBody);
IRestResponse response = client.Execute(request);
```

But I'm still confused about why the first solution didn't work in this case if I've previously used the same way to make a GET request to other urlPath.

**Comment by thinkingserious** [comment]
Hello @EdoRguez,

Thanks for reporting this and for providing a work around. We've added this issue to our backlog for further review.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
This is probably the issue in your code:
```
requestBody: queryParams
```
Working example here: https://github.com/sendgrid/sendgrid-csharp/blob/master/examples/categories/categories.cs#L37
