### ISSUE TITLE
CreateSingleTemplateEmail with dynamic HTML

### ISSUE THREAD

**Issue by raymondlittle100** [sendgrid/sendgrid-csharp#915]
#### Issue Summary

I'm trying to send an email via SendGrid using the nuget package with MailHelper.CreateSingleTemplateEmail. I have this working with static content but in my case I'm trying to inject HTML not content. When doing this it renders the code not the HTML representation. Is this expected? Is there another way to do this?

![image](https://user-images.githubusercontent.com/23637375/62627521-70db7280-b921-11e9-998d-2f21f484bc1b.png)

#### Technical details:

* sendgrid 9.11.0
* Platform ASP.NET
* .NET Version: 4.7.2

**Comment by thinkingserious** [comment]
Hello @raymondlittle100,

Could you please post some sample code so that we may try to reproduce?

Thanks!

With best regards,

Elmer

**Comment by raymondlittle100** [comment]
Hi,

Here is the code I'm using

var client = new SendGridClient(apiKey);
            var from = new EmailAddress(fromEmail, fromName);
            var subject = "Sending with SendGrid is Fun";
            var to = new EmailAddress(toEmail, "Example User");

            var dynamicTemplateData = new Dictionary<string, string>
            {
                {"first_name", "&lt;p&gt;this is some html&lt;/p&gt;"},
                {"last_name", "<div>l23456</div>"},
                {"Sender_Name", "<div>Sender_Name</div>"},
            };

            //var plainTextContent = "and easy to do anywhere, even with C#";
            //var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";

            //MailSettings ms = new MailSettings();
            //MailHelper.CreateSingleEmail(()

            var msg = MailHelper.CreateSingleTemplateEmail(from, to, "d-90506e62859942939bd3cbe383aa214c", dynamicTemplateData);
            //var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);

Cheers,

Ray

**Comment by thinkingserious** [comment]
Hello @raymondlittle100,

I am unable to reproduce the issue testing with version 9.13.2 of this library with the following template and corresponding code. Can you please take a look and let me know if there are still issues?

```html
<html>
<head>
    <title></title>
</head>
<body>
Hello {{{ name }}},
<br /><br/>
I'm glad you are trying out the template feature!
<br /><br/>
I hope you are having a great day in {{{ city }}} :)
<br /><br/>
</body>
</html>
```

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Example
{
    internal class Example
    {
        private static void Main()
        {
            Execute().Wait();
        }

        static async Task Execute()
        {
            var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("example+from@example.com", "Example From");
            var to = new EmailAddress("example+to@twilio.com", "Example To");
            var dynamicTemplateData = new Dictionary<string, string>
            {
                {"name", "<strong>John</strong>"},
                {"city", "<div>Denver</div>"}
            };
            var msg = MailHelper.CreateSingleTemplateEmail(from, to, "d-bxddb3551x76483598ece251aa7fae6x", dynamicTemplateData);
            var response = await client.SendEmailAsync(msg);
            Console.WriteLine(response.StatusCode);
            Console.WriteLine(response.Headers.ToString());
            Console.WriteLine("\n\nPress any key to exit.");
            Console.ReadLine();
        }
    }
}
```

Thanks for helping out @kurt70!
