### ISSUE TITLE
Unable to received mail in Inbox

### ISSUE THREAD

**Issue by Rashree138** [sendgrid/sendgrid-csharp#926]
#### Unable to received mail in Inbox

Hi team, 
I am using SendGrid to send mail from C# code, mail is send successfully but unable to get in Inbox.
I am using below sample code :

var apiKey = "PASS APIKEY ";
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("test@example.com", "Example User");
            var subject = "Sending with Twilio SendGrid is Fun";
            var to = new EmailAddress("test@example.com", "Example User");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);

I am following : https://sendgrid.com/docs/for-developers/sending-email/v2-csharp-code-example/

I have created SendGrid account in Azure. Am I missing any setting anywhere?

**Comment by hariharan618** [comment]
Have you checked the response code? Try printing `    Console.WriteLine(response.StatusCode);` If you response code is `200` check for inbox filters or your spam folder. If the response is not 200, then report back

**Comment by Rashree138** [comment]
Response is 200 and I have checked in spam also but it is not there......

Please guide us in settings as well.....

**Comment by thinkingserious** [comment]
Hello @Rashree138,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
