### ISSUE TITLE
Sending an email fails with 415: Content-Type should be application/json

### ISSUE THREAD

**Issue by avonheimburg** [sendgrid/sendgrid-csharp#929]
Sending an EMail via SendEmailAsync() currently fails with a message from the SendGrid servers:

Status Code: 415
Response Text: {"errors":[{"message":"Content-Type should be application/json.","field":null,"help":null}]}

dotnet 3.0-preview8
SendGrid 9.12

**Comment by thinkingserious** [comment]
Hello @avonheimburg,

Could you please provide some sample code so that we may try and reproduce the error? Thank you!

With best regards,

Elmer
