### ISSUE TITLE
Send multiple emails using async fail after sending 100 or so emails

### ISSUE THREAD

**Issue by neogeoit** [sendgrid/sendgrid-csharp#930]
Looping through a batch of email addressese list using:

            List<string> emailadd = new List<string>();
            List<Task> responses = new List<Task>();
            foreach (var email in emailadd)
            {
                responses.Add(SendAsync(email, fromemail, fromname, subject, htmlcontent, plaintextcontent, api));                               
            }

            await Task.WhenAll(responses);

The sending method:

public async Task SendAsync(string toemail, string fromemail, string fromname, string subject, string htmlcontent, string plaintextcontent, string apikey)
        {
            Response response = null;
            SendGridClient client = null;
            try
            {
                var to = new EmailAddress(string.Copy(toemail));
                var content = string.Copy(htmlcontent);
                var ptcontent = string.Copy(plaintextcontent);
                var from = new EmailAddress(string.Copy(fromemail), string.Copy(fromname));
                var mysubject = string.Copy(subject);
                client = new SendGridClient(string.Copy(apikey));
                var version = client.Version;
                var msg = MailHelper.CreateSingleEmail(from, to, mysubject, ptcontent, content);
                response = await client.SendEmailAsync(msg);
                Debug.WriteLine("sending: " + toemail);
                Debug.WriteLine(response.StatusCode);
                Debug.WriteLine(response.Body);                
            }
            catch (Exception ex)
            {
                throw;
            }            
        }

Occasionally I am able to send 100 or so emails, using a batch of 10 (so around 10 batches). But after around 10 batches the call started to return status code of "Forbidden" or "Unauthorized". Once stuck, I could not even send using sample code like below, returning "UnAuthorized"

        static async Task Execute()
        {
            var apiKey = GetAPI();
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("hello@xyz.com", "xyz");
            var subject = "Sending with SendGrid is Fun 20190522";
            var to = new EmailAddress("myemail@gmail.com", "me");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = "<strong>and easy to do anywhere, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }

I have contacted SendGrid support and I was suggested to get help here.
#### Technical details:

* sendgrid-csharp Version: 9.12.0.0, file version: v4.0.30319
* Platform (Winforms)
* .NET Version: 4.5.2

**Comment by neogeoit** [comment]
Turns out my sendinglimit did not get upgraded after I paid my subscription. Support helped reset the limit and resolved.

**Comment by thinkingserious** [comment]
Thanks for following up @neogeoit!
