### ISSUE TITLE
Email go to junk box

### ISSUE THREAD

**Issue by alexchx** [sendgrid/sendgrid-csharp#933]
#### Issue Summary

I sent an email with the code below, but the received email is moved to the junk box, I tried several email service providers but the result is the same, any idea to fix it? Thank you.

```c#
var apiKey = ConfigurationManager.AppSettings["SENDGRID_API_KEY"];
var client = new SendGridClient(apiKey);
var from = new EmailAddress("[email address 1]", "Alex Biz");
var subject = "Meeting summary today";
var to = new EmailAddress("[email address 1]", "Alex Chen");
var htmlContent = "Hi, all<p/>As per the meeting earlier today, let's all try our best to get prepared for the annual event and won more!<p/>Regards,<br/>Alex Chen";
var msg = MailHelper.CreateSingleEmail(from, to, subject, null, htmlContent);
var response = await client.SendEmailAsync(msg);
```

#### Steps to Reproduce

See above

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* ASP.NET
* .NET Version: 4.6.1

**Comment by thinkingserious** [comment]
Hello @alexchx,

I suggest that you review [this blog post](https://sendgrid.com/blog/10-tips-to-keep-email-out-of-the-spam-folder/) for some advice on how to keep your emails out of the SPAM folder.

Thanks for reaching out!

With best regards,

Elmer

**Comment by alexchx** [comment]
@thinkingserious Thanks for your advice!
