### ISSUE TITLE
Missing authorization header with v9.12.0 - downgrading solves the problem.

### ISSUE THREAD

**Issue by barissaydag** [sendgrid/sendgrid-csharp#934]
c# with asp.net core, on windows 10, sendgrid nuget package v.9.12.0 against v3 API

SendGrid doesn't add authorization header, even when overriden with AddAuthorization. Downgrading to v9.11.0 solves the problem.

**Comment by thinkingserious** [comment]
Hello @barissaydag,

Thanks for reporting this issue!

Could you please post some sample code so that we may try to reproduce? What's the error message you receive when using v9.12.0?

With best regards,

Elmer

**Comment by barissaydag** [comment]
For example:

API_KEY is initialized properly. Change nuget packages to 9.11 and everything works.

```
			SendGrid.SendGridClient SGC = new SendGrid.SendGridClient(API_KEY);
			var a = SGC.AddAuthorization(new KeyValuePair<string, string>("Authorization", $"Bearer {API_KEY}"));

			foreach (string Cur in TEMPLATES_NEWSLETTER) //this is just a string collection, contains template ids, like d-1231...
			{
				HttpRequestMessage Req = new HttpRequestMessage(HttpMethod.Get, $"https://api.sendgrid.com/v3/templates/{Cur}");
				SendGrid.Response Res = SGC.MakeRequest(Req).Result;
				Dictionary<string, dynamic> Body = Res.DeserializeResponseBodyAsync(Res.Body).Result;
				TemplateIdToName.Add(Cur, Body["name"]);
			}
```

**Comment by thinkingserious** [comment]
Hello @barissaydag,

I'm having trouble re-producing this issue. Are you still experiencing this issue in the latest version of this helper library?

With best regards,

Elmer

**Comment by barissaydag** [comment]
Hi Elmer, 

I just reproed again on .NET CORE 3.1 with SendGrid 9.14. Downgrading to 9.10 immediately solves the problem with no other code / password etc. change.

Here is the request I make:

```
{Method: GET, RequestUri: 'https://api.sendgrid.com/v3/templates/d-e70bbf59c17c419b90353ccd8e1a1ae4', Version: 1.1, Content: <null>, Headers:
{
}}
```

Here is the response I receive: 
```
{[errors, {[
  {
    "field": null,
    "message": "authorization required"
  }
]}]}
```

**Comment by thinkingserious** [comment]
Thank you @barissaydag!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by childish-sambino** [comment]
`MakeRequest` doesn't add auth to the request. It's called by `RequestAsync` which builds out the request with auth, headers, and address information. I don't know historically why it used to work, but probably some refactoring that broke this. Simplest thing is to update to using `RequestAsync`. In your case:

```c#
var SGC = new SendGrid.SendGridClient(API_KEY);

foreach (string Cur in TEMPLATES_NEWSLETTER) //this is just a string collection, contains template ids, like d-1231...
{
    var Req = new HttpRequestMessage(method: SendGridClient.Method.Get, urlPath: $"/v3/templates/{Cur}");
    var Res = SGC.RequestAsync(Req).Result;
    Dictionary<string, dynamic> Body = Res.DeserializeResponseBodyAsync(Res.Body).Result;
    TemplateIdToName.Add(Cur, Body["name"]);
}
```
