### ISSUE TITLE
Weblink via API

### ISSUE THREAD

**Issue by raymondlittle100** [sendgrid/sendgrid-csharp#935]
#### Issue Summary

I'm looking to send an email via the API and plan on using SendGrid in Azure. My client has asked about including a weblink. I found the link below but it was from a couple of years ago. Is it still the case this is only supported in marketing emais? 

https://github.com/sendgrid/sendgrid-csharp/issues/549

#### Technical details:

Platform (ASP.NET)
.NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @raymondlittle100,

Could you please describe what the desired outcome should be? Perhaps there is a workaround to achieve the result you require.

With best regards,

Elmer

**Comment by raymondlittle100** [comment]
Its not strictly development more a question about general functionality for SendGrid so I'm not sure if this is the right place to ask. Basically I'm planning on using SendGrid to issue emails for a client using C#. They were asking if there is functionality for the email to include a web version of the email. 

I looked around and there was some information saying SendGrid used to include this functionality but it was discontinued. The new position was anyone using the API had to implement and host the web version of the email and this was no longer done in SendGrid. The last information I could find was from a few years ago so I wondered if anyone else knew if there was a way to do this using SendGrid?

Thanks for the response

**Comment by thinkingserious** [comment]
Hello @raymondlittle100,

Thanks for clarifying. 

You would need to host the web version of the email on your own server.

With best regards,

Elmer
