### ISSUE TITLE
Serialization issue if non-defaults used

### ISSUE THREAD

**Issue by duncanchung** [sendgrid/sendgrid-csharp#937]
#### Issue Summary

Json serialization of the `SendGridMessage` is not guaranteed 100% accurate if non-defaults are set.

#### Steps to Reproduce

```
    JsonConvert.DefaultSettings = () => new JsonSerializerSettings()
    {
        ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver()
    };

    var message = new SendGridMessage();

    message.AddGlobalHeader("List-Unsubscribe", "Look at the first character");

    var json = message.Serialize();

    Console.WriteLine(json);
```

Output is:

```
{"headers":{"list-Unsubscribe":"Look at the first character"}}
```

I would expect:

```
{"headers":{"List-Unsubscribe":"Look at the first character"}}
```

Note the `l` vs `L` in `"List-Unsubscribe"`.

#### Technical details:

* `Sendgrid 9.12.0` nuget package
* .NET Core 2.2

**Comment by duncanchung** [comment]
Root cause is in the ContractResolver:

https://github.com/JamesNK/Newtonsoft.Json/blob/6b9f467e817854532ea31e6c08abe47c53ac8b5c/Src/Newtonsoft.Json/Serialization/CamelCasePropertyNamesContractResolver.cs#L49

and how it treats dictionaries.

**Comment by aevitas** [comment]
Nice find! Wouldn't this be an issue in Newtonsoft.Json according to your findings?

**Comment by duncanchung** [comment]
This line serializes the `SendGridMessage` class:

https://github.com/sendgrid/sendgrid-csharp/blob/02200e5e3171c49a0ed8cf2801346039be5f233c/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L1616

Internally, the method used in the `JsonConvert.Serialize` method (as in the `SendGridMessage` class) uses the `CreateDefault` on the JsonSerializer.

https://github.com/JamesNK/Newtonsoft.Json/blob/8e4261a350dbd11f59500ed8901d30d498b34c04/Src/Newtonsoft.Json/JsonConvert.cs#L651

applying the passed in settings _on top of_ the defaults.

To make the Sendgrid helper class serialize untainted from app configuration, the JsonSerializer exposes a `Create` method.

Sample pull request to fix this issue coming.

**Comment by duncanchung** [comment]
The fix above just copies the serialization code from Newtonsoft.Json (replacing `CreateDefault` with `Create`).

Given how widespread that package is, I wouldn't think they'd be changing their default behaviour of the `JsonConvert.SerializeObject` method any time soon.

**Comment by thinkingserious** [comment]
Thank you @duncanchung! We've added this to our backlog for a code review.
