### ISSUE TITLE
Bad Request using Deliver

### ISSUE THREAD

**Issue by StephaneBischoff** [sendgrid/sendgrid-csharp#94]
Receiving an unhandled exception with message Bad Request when using Deliver.
Should provide a better message in exception such as "Subject is missing and is required" and "Text is missing and is required."

Finally resolved my issue with this answer: http://stackoverflow.com/questions/21892185/bad-request-error-using-sendgrid-smtp-email-submission

**Comment by brandonmwest** [comment]
Thanks for the feedback! Will work on adding some simple validation.

**Comment by MarcelloCarreira** [comment]
I also had some similar problems. I know the sdk have now better error handling, but I still think this could be simplified for the final user. I forked this rep and added an example file, SendGridSendAsync.cs, that catches the exceptions, merge them, and then give a simple string to the user, so it´s easier to know what happened, as the api itself returns errors like missing body or subject. I but I would love to see it in the official version, so other people can use it it they need.

**Comment by bloomk** [comment]
3 months and still no validation? I left the "text" null and got this weird error... At LEAST give us access to the "errors" that the api returns that the inner exception mentions..

**Comment by thinkingserious** [comment]
Hello Everyone,

Thanks for your support and patience!

We have completely revamped our /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html and this library will be replaced with this one: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta in a few weeks.

We heard you loud and clear, as a result this new version our /mail/send API has much better error descriptions and we do validation up front. You can also use our sandbox mode to test your payload before sending an actual email.

With Best Regards,

Elmer
