### ISSUE TITLE
Attempting to Install SendGrid using NuGet Package Manager Stops with Error

### ISSUE THREAD

**Issue by TomClearCase** [sendgrid/sendgrid-csharp#940]
#### Issue Summary

I am attempting to install SendGrid using the NuGet Package Manager in Microsoft Visual Studio 2012.  

#### Steps to Reproduce

1. Launch Visual Studio.  
2. Open the Solution.  
3. Go to the Package Manager Console window in Visual Studio and run the command:  

PM> Install-Package SendGrid

4.  After running the command above the following messages are output:  

Attempting to resolve dependency 'Newtonsoft.Json (≥ 9.0.1)'.
Install-Package : 'Sendgrid' already has a dependency defined for 'Newtonsoft.Json'.
At line:1 char:1
+ Install-Package SendGrid
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
NuGet did not tell me which SendGrid C# version it was attempting to install.  

* Platform (ASP.NET WebForms)
* .NET Version: 4.5.2

**Comment by TomClearCase** [comment]
Hi Everyone at Twilio **SendGrid**, 

Yang Shen has a great explanation for the **SendGrid** installation issue.  He responded on the ASP.NET forums thread I started.  Please see:  

[https://forums.asp.net/p/2160444/6280687.aspx?p=True&t=637061128611464092](url)

I am **Tom.NET** in this thread. In case the link above does not work go to [http://forums.asp.net/](url) 

Go to **Community --> Component Discussions --> “Attempting to Install SendGrid in an ASP.NET Web Forms . . .**

**Comment by thinkingserious** [comment]
Nice, thanks for sharing the fix @TomClearCase!
