### ISSUE TITLE
Bad Request When using AddBccs

### ISSUE THREAD

**Issue by chobo2** [sendgrid/sendgrid-csharp#945]
#### Issue Summary

When I use addBccs and send it into a transaction template I get a Bad Request.

#### Steps to Reproduce
```
            var msg = new SendGridMessage();
            msg.SetFrom(from);
            var emails = sendTo.Select(x => new EmailAddress(x.Email, "test")).ToList();
           msg.AddBccs(emails);

     msg.SetTemplateId("d-515151515");

       var response = await sendGridClient.SendEmailAsync(msg);
```

#### Technical details:

Version: 9.12.0
.Net Core 2.2

**Comment by thinkingserious** [comment]
Hello @chobo2,

Thanks for submitting your issue!

Could you please retrieve the [underlying error message](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error-messages)?

Also, if you could provide [the request body](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#viewing-the-request-body), that would help troubleshoot.

With best regards,

Elmer

**Comment by chobo2** [comment]
> Hello @chobo2,
> 
> Thanks for submitting your issue!
> 
> Could you please retrieve the [underlying error message](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#error-messages)?
> 
> Also, if you could provide [the request body](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#viewing-the-request-body), that would help troubleshoot.
> 
> With best regards,
> 
> Elmer

Ah was wondering how to get the error messages as I thought there must be something more than "BadRequest"

from response.body - 

`{"errors":[{"message":"The to array is required for all personalization objects, and must have at least one email object with a valid email address.","field":"personalizations.0.to","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]}`


this is what is in the msg.Serialize()

```
{
  "from": { "email": "noreply@example.com" },
  "personalizations": [
    {
      "bcc": [
        { "email": "email1@example.org" },
        { "email": "test@gmail.com" }
      ],
      "dynamic_template_data": {
        "data": [
          {
            "name": "Test Name"
          }
        ]
      }
    }
  ],
  "template_id": "d-3f2417a3adsfadf151a6c74333cef8803"
}

```

**Comment by chobo2** [comment]
@thinkingserious - any update on this?

**Comment by adesokanayo** [comment]
@chobo2 , from the reponse.Body  , it's requesting that you add " To " in your personalization.

**Comment by chobo2** [comment]
@adesokanayo 

I am not sure what you mean, are you saying I have to specify a "To" eventhough I want to send everything as a Bcc?

**Comment by thinkingserious** [comment]
Hello @chobo2,

Yes, @adesokanayo (thanks for helping out!) is correct. Our API requires that you specify a "To". I suggest using a generic catch-all email address for that.

With best regards,

Elmer
