### ISSUE TITLE
Does the Method EmailAddress() in Version 9.x have an Equivalent Method in Version 7.0.6 ?

### ISSUE THREAD

**Issue by TomClearCase** [sendgrid/sendgrid-csharp#949]
To which C# class in which .NET namespace does the method **EmailAddress()** belong?  

Does the method **EmailAddress()** exist in SendGrid version 7.0.6 ?  If yes, to which C# class in which .NET namespace does the method **EmailAddress()** belong?  If no, what would the equivalent method be in version 7.0.6 ?

**Comment by thinkingserious** [comment]
Hello @TomClearCase,

No, `EmailAddress()` does not exist in Twilio SendGrid version 7.0.6. The equivilent method would be [`Email()`](https://github.com/sendgrid/sendgrid-csharp/blob/7d04be36d6a73ed69dd6ccbc0fb6590d3be94587/SendGrid/SendGrid/Helpers/Mail/Mail.cs#L1066).

With best regards,

Elmer

**Comment by TomClearCase** [comment]
Hi @thinkingserious , 

Thank you for the reply.  

In version 9.x the method **SendGridClient(**apiKey**)** is used.  This method doesn't exist in version 7.0.6.  Consequently, would I use the **SendGridAPIClient(**apiKey, "https://api.sendgrid.com", "v3"**)** instead?

**Comment by TomClearCase** [comment]
In Version 7.0.6 use the following: 

var oClient = new SendGridAPIClient(apiKey, "https://api.sendgrid.com", "v3");
