### ISSUE TITLE
RuntimeBinderException with Error Message "Cannot invoke a non-delegate type"

### ISSUE THREAD

**Issue by TomClearCase** [sendgrid/sendgrid-csharp#950]
Because I am using **Visual Studio 2012**, the most recent version of **SendGrid** I can use is **7.0.6**.  

I am trying to send my first email using the code below.  

A "**RuntimeBinderException**" happens on the line **client.client(oMail);**  The error message says, "**Cannot invoke a non-delegate type**."  

Why is an e-mail message not sent out?  Is **oContent** for the e-mail body?  

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// using SendGrid's C# Library
// https://github.com/sendgrid/sendgrid-csharp
using SendGrid;
using SendGrid.Helpers.Mail;

using SendGrid.CSharp.HTTP.Client;
using System.Net.Http;
using System.Net.Http.Formatting;
using SendFirstEmail;

namespace SendFirstEmail
{
    class Program
    {
        static void Main()
        {
            Execute();
        }

        static void Execute()
        {
            var apiKey = Environment.GetEnvironmentVariable("SendGridAPIKey");

            SendGridAPIClient oClient = new SendGridAPIClient(apiKey, "https://api.sendgrid.com", "v3");

            SendGrid.Helpers.Mail.Email oEmailTo = new Email("tradojicic@AcmeCorp.com", "Tom Radojicic");
            SendGrid.Helpers.Mail.Email oEmailFrom = new Email("ProdHelp@AcmeCorp.com", "ProdHelp");

            Content oContent = new Content("sType", "sValue");

            SendGrid.Helpers.Mail.Mail oMail = new SendGrid.Helpers.Mail.Mail(oEmailFrom, "Two-Factor Authentication Code from Harvest Investments", oEmailTo, oContent);
            
            client.client(oMail);

            return;
        }
    }
}

**Comment by TomClearCase** [comment]
The line of code 

client.client.(oMail);  

was replaced by the line of code 

dynamic response = oClient.client.mail.send.post(requestBody: oMail.Get());

Now the StatusCode on the response object above is "Unauthorized".  That is progress.

**Comment by thinkingserious** [comment]
Hello @TomClearCase,

An "Unauthorized" response is usually related to API key permissions. If you reach out to our [support team](https://support.sendgrid.com), they can help you debug API key access. 

An easy check may be to create a new API Key and try again and/or try using your existing API Key with our [interactive documentation](https://sendgrid.com/docs/API_Reference/api_v3.html).

With best regards,

Elmer

**Comment by TomClearCase** [comment]
Thank you @thinkingserious.  This issue can be closed.  I was able to successfully send out an e-mail using **SendGrid** Version **7.0.6**.
