### ISSUE TITLE
The Environment Variable API Key Value is Masked, So How Can One Get This Value to Enter in Windows 10? 

### ISSUE THREAD

**Issue by TomClearCase** [sendgrid/sendgrid-csharp#951]
I am following along doing the steps on the "Integrate using our Web API" web page ( https://app.sendgrid.com/guide/integrate/langs/csharp ).  

On Step 2, I enter the key name **SendGridAPIKey** and then click the blue "Create Key" button.  

On the API Keys Page ( https://app.sendgrid.com/settings/api_keys ) the actual API key value is not displayed for security purposes.  How then can the environment variable value be set in Windows 10?  Both the variable name and the value need to be entered, but the value is masked on the API Keys Page.

**Comment by rhsobr** [comment]
When you create an API Key, you're able to see it once. So you must copy and keep safe it on your side.

Every API Key starts with `SG.`.

**Comment by TomClearCase** [comment]
Hi rhsobr, 

OK.  Thank you for replying.

**Comment by thinkingserious** [comment]
Thanks for helping out @rhsobr!

It looks like your question has been resolved, so I'm going to close this one out. Please feel free to re-open if there are additional difficulties.

With best regards,

Elmer
