### ISSUE TITLE
How to use basic authorization for v3 API in C#?

### ISSUE THREAD

**Issue by MartyZhou** [sendgrid/sendgrid-csharp#954]
#### Issue Summary

How to use basic authorization for v3 API in C#?

#### Steps to Reproduce

I tried to use the following code and it returns access denied.

sendGridOptions.RequestHeaders.Add("Authorization", $"Basic {urlEncodedUserName}{urlEncodedPassword}");

var sendgridClient = new SendGridClient(sendGridOptions);

**Comment by thinkingserious** [comment]
Hello @MartyZhou,

Thanks for reaching out to us!

This is an unsupported means of authenticating, I suggest you obtain an [API Key](https://github.com/sendgrid/sendgrid-csharp#obtain-an-api-key) with only the permissions needed for your app.

With best regards,

Elmer

**Comment by Jericho** [comment]
@thinkingserious There's a section in the [documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/authentication.html) that explains how to use basic authentication which leads me to believe that it's supported. To be fair, the documentation says that basic authentication is not __recommended__ but if it truly is unsupported, the documentation should be updated.

**Comment by Jericho** [comment]
@thinkingserious Maybe you meant to say that it's not supported by the C# client (despite the fact that the API actually supports it)?

@MartyZhou If you need basic authentication, I suggest you consider StrongGrid which is an alternative to SendGrid's C# client. StrongGrid supports both basic and api key authentication (disclaimer: I'm the author of this library). StrongGrid is available on [nuget](https://www.nuget.org/packages/StrongGrid/) and [Github](https://github.com/Jericho/StrongGrid).
