### ISSUE TITLE
Request for "email_activity" returns with "Forbidden"

### ISSUE THREAD

**Issue by ducpp7406** [sendgrid/sendgrid-csharp#959]
#### Issue Summary

I try to use the following code lines to retrieve email activities.

```csharp
var client = new SendGridClient(apiKeyFullAccess);
            string queryParams = @"{
              'limit': 10, 
              }";
            var response = await client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "email_activity", queryParams: queryParams);
            Console.WriteLine(response.StatusCode);
            Console.WriteLine(response.Body.ReadAsStringAsync().Result);
            Console.WriteLine(response.Headers.ToString());
```

And get following result 
Forbidden
{"errors":[{"field":null,"message":"access forbidden"}]}
Server: nginx
Date: Sat, 14 Dec 2019 16:21:14 GMT
Connection: keep-alive
Access-Control-Allow-Methods: HEAD, OPTIONS, GET
Access-Control-Max-Age: 21600
Access-Control-Expose-Headers: Link, Location
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: AUTHORIZATION, Content-Type, On-behalf-of, x-sg-elas-acl, X-Recaptcha, X-Request-Source
Content-Security-Policy: default-src https://api.sendgrid.com; frame-src 'none'; object-src 'none'
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000
X-Ratelimit-Remaining: 73
X-Ratelimit-Limit: 100
X-Ratelimit-Reset: 1576342800

SendGrid returns a response with response.StatusCode = Forbidden instead of a list of email activities.

**Comment by thinkingserious** [comment]
Hello @ducpp7406,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
