### ISSUE TITLE
Error Handling code in DeliverAsync confused.

### ISSUE THREAD

**Issue by Jospeh** [sendgrid/sendgrid-csharp#96]
Code at line https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/SendGridMail/Transport/Web.cs#L172

The code checks the status code of the response and throws Exception. If we really want to throw an exception, "Exception" is probably still not what we want. However, the last 2 lines then perform the same test against the status code for OK, and this time try to FindErrorsInResponse(content);

Comments are mine:

		private static async Task CheckForErrorsAsync(HttpResponseMessage response)
		{
			//throw "Exception" for any status code that is not OK
			if (response.StatusCode != HttpStatusCode.OK)
			{
				throw new Exception(response.ReasonPhrase);
			}

			var content = await response.Content.ReadAsStreamAsync();

		    var errors = GetErrorsInResponse(content);

            // API error
            if (errors.Any())
                throw new InvalidApiRequestException(response.StatusCode, errors, response.ReasonPhrase);

            // THEN AGAIN check if status code is not OK - but this time lets try and find errors
            if (response.StatusCode != HttpStatusCode.OK)
                FindErrorsInResponse(content);//this will never happen
		}

I propose that we should remove this code:

		if (response.StatusCode != HttpStatusCode.OK)
			{
				throw new Exception(response.ReasonPhrase);
			}

As the method FindErrorsInResponse is at least making a proper attempt at raising the appropriate exception.

**Comment by bcrosnier** [comment]
I have encountered this today. When calling `DeliverAsync()` with eg. a wrong username and password, the SendGrid API will, as written, throw a simple `Exception` with the simple message associated with 400 (`Bad Request`).
I could not actually know it was because of a bad username or password until I had access to the HTTP request and saw the `Bad username / password` sent in XML.

**Comment by brandonmwest** [comment]
Thanks, fixing this in the next release.

**Comment by brandonmwest** [comment]
Fixed in 5.1.0
