### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by TomGullen** [sendgrid/sendgrid-csharp#960]
#### Issue Summary:

In the `SendGridClient` the `HTTPClient` private variable `client` is never disposed.  After a lot of investigation, it appears like this could be the cause of memory leaks on our website and possible port leaks.  If this is the cause, it's been very problematic and expensive for us.

#### Solution:

We've changed the header of the `SendGridClient` to:

`public class SendGridClient : ISendGridClient, IDisposable`

We've then added in the code:

```
private bool _disposed = false;

protected virtual void Dispose(bool disposing)
{
	if (_disposed)	return;

	if (disposing)
	{
		if (client != null)
		{
			client.Dispose();
		}
	}
	_disposed = true;
}

public void Dispose()
{
	Dispose(true);
	GC.SuppressFinalize(this);
}

~SendGridClient()
{
	Dispose(false);
}
```

We now use the `SendGridClient` as follows:

```
using (var sg = new SendGridClient(Settings.Email.SendgridAPIKey))
{
	// Do something
}
```

I'd strongly suggest updating the `SendGridClient` to dispose of the client properly as in some environments this can cause real problems.

### Edit

Looks like emails wont send with HTTPClient disposed, so alternative solution we've gone for is stripping out the `client` property and adding a helper method to get a global reusable HTTPclient:
```

    internal static class Helper
    {
        private static HttpClient Client { get; set; }
        internal static HttpClient GetClient()
        {
            if (Client == null)
            {
                Client = new HttpClient(new RetryDelegatingHandler(new SendGridClientOptions().ReliabilitySettings));
            }
            return Client;
        }
    }
```

**Comment by TomGullen** [comment]
Turns out was wrong, instead of creating new SG client, should have one global one.

**Comment by aevitas** [comment]
You should treat the `HttpClient` used by `SendGridClient` as a singleton, and not re-create it every single time you need to send an e-mail. One way of doing that is by declaring a single instance of `SendGridClient` and re-using that across your code, and alternative approach (if you're using ASP.NET Core and its dependency injection) could be:

```
services.AddSingleton(new HttpClient());
services.AddScoped<ISendGridClient, SendGridClient>();
```

When injected, `SendGridClient` accepts an injected `HttpClient` whose lifetime is managed by the DI container. Either approach should resolve the problems you're seeing.

For more info on why HttpClient should be a singleton, see https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
