### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0

### ISSUE THREAD

**Issue by krillehbg** [sendgrid/sendgrid-csharp#961]
#### Issue Summary
When i added the nuget package to my project running with .NET Framework v4.7.1
i get this error shown

"Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

I have Newtonsoft.Json latest version (v12.0.3) already added installed to other projects within my solution.

No idea how to solve this issue

**Comment by thinkingserious** [comment]
Hello @krillehbg,

Please add your voice to this issue: https://github.com/sendgrid/sendgrid-csharp/issues/744

Meanwhile, perhaps this workaround will work for you: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection#enabling-automatic-binding-redirects-manually

With best regards,

Elmer
