### ISSUE TITLE
Visual Studio - 2017 : Could not load file or assembly 'SendGrid, Version=9.12.0.0,

### ISSUE THREAD

**Issue by raghunandanhj** [sendgrid/sendgrid-csharp#962]
#### Issue Summary

Created a new project in VSTS 2017 and added the latest  SendGrid NuGet package. 
Upon using the C# sample code from SendGrid the code breaks with the below information.

-		$exception	{"Could not load file or assembly 'SendGrid, Version=9.12.0.0, Culture=neutral, PublicKeyToken=4f047e93159395ca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"SendGrid, Version=9.12.0.0, Culture=neutral, PublicKeyToken=4f047e93159395ca"}	System.IO.FileLoadException

**Comment by nishantpant** [comment]
I have the exact same issue too. Got the example code from sendgrid, installed nuget and it blew up with the same error.

**Comment by BrianMikinski** [comment]
I'm seeing the same thing with 9.12.0 on 4.8 framework. I have to downgrade to 9.11 to compile my project.

**Comment by nishantpant** [comment]
Brian, compiling is not a problem for me but when I  run my project, I keep getting a runtime error that the assembly was not found.

**Comment by thinkingserious** [comment]
Hello @raghunandanhj, @nishantpant, @BrianMikinski,

Are you still experiencing this issue in version 9.13.0? 

Thanks!

With best regards,

Elmer
