### ISSUE TITLE
Set TLS 1.2 as default

### ISSUE THREAD

**Issue by georgeemr** [sendgrid/sendgrid-csharp#964]
When we disabled TLS 1.0 on our servers, the API starts to fail.
How can we set API to connect with TLS 1.2?

**Comment by georgeemr** [comment]
I mention this on #505, currently last comment.

**Comment by vonHaupt** [comment]
I ran into the same issue and finally figured it out. Add the following line before making calls to the API,

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

**Comment by childish-sambino** [comment]
@georgeemr Does the previous comment help to resolve this issue?

**Comment by georgeemr** [comment]
Sure, this resolve the issue. Thanks
