### ISSUE TITLE
BCC not working

### ISSUE THREAD

**Issue by craig-acutest** [sendgrid/sendgrid-csharp#97]
Here is code I'm using to add a Blind carbon copy:

mail.AddBcc(staff.Email);

Where staff is an object with attributes about the staff member, one of which is email, this being a string containing the staff members email address.

We have recently moved our websites to Microsoft Azure, and investigated this as being the best solution to send emails.

We rely on sending BCC as this allows many people to get the email our customers get, so that internal company audits can be performed, it is important that the customer not see who is dealing with or who has receive the email.

Please can you show me why this isn't working? or if this is a bug i have found, can it be fixed?

Thanks,

Craig.

Full code of function below:

                public void emailQuote(string REFID, int ID)
                        {
            try
            {
                var refno = REFID.ToString().Split('-');

                var refid = refno[2];
                var custid = refno[1];
                var quoteid = refno[0];

                var quote = returnQuote(refid, Convert.ToInt32(custid));

                var customer = returnCustomer(quote.CustomerID);

                var ASMName = "";

                var mail = new SendGridMessage();
                string EmailTo = "";

                EmailTo = customer.Email;               

                string directEmailSubject = "Acutest Direct - New Quotation";

                mail.From = new MailAddress(Process.Constants.AcutestDirectEmail);

                if (quote.ASMID == 0)
                {
                    mail.AddBcc(Process.Constants.AcutestDirectEmail);
                }
                else
                {
                    var staff = AcutestLoginReader.StaffAPI.GetStaffByID(quote.ASMID);

                    if(staff != null){
                        ASMName = staff.FirstName + " " + staff.Surname;
                        mail.AddBcc(staff.Email);
                    }
                                        
                    mail.AddBcc(Process.Constants.AcutestDirectEmail);
                    mail.AddBcc(Process.Constants.AcutestAdmin);
                }
                mail.AddBcc(Process.Constants.AcutestWebTeam);
                mail.AddTo(EmailTo);
                mail.Subject = directEmailSubject;

                mail.AddAttachment(new MemoryStream(Utilities.Generator.CreatePDF(REFID, Process.Constants.WebsiteAddress, Process.Constants.WebsiteAddress + "/footerPDF.aspx")), "Quotation_" + refid + ".pdf");

                string emailBody = "<span>AcutestDirect is a Trading Division of Acute Sales Ltd<br/>" +
                                    "Century Road<br/>" +
                                    "High Carr Business Park<br/>" +
                                    "Newcastle-under-Lyme<br/>" +
                                    "Staffordshire<br/>" +
                                    "ST5 7UG<br/></span><br/><br/>";

                emailBody += "<span>The information contained in this electronic mail message is confidential. It is intended solely for the use of the individual " +
                "or entity to whom it is addressed and others authorised to receive it. If the reader of this message is not the intended recipient, " +
                "you are hereby notified that any use, copying, dissemination or disclosure of this information is strictly prohibited.</span><br/><br/>";

                mail.Html = "Hello " + customer.FirstName + " " + customer.Surname + ",<br/><br/>Please find attached your quotation.<br/><br/>" +
                    "Kind Regards,<br/><br/>" + ASMName + "<br/>Area Sales Manager" + "<br/><br/>" + emailBody;

                var credentials = new NetworkCredential(Constants.SendGridUsr, Constants.SendGridPwd);

                var transportWeb = new Web(credentials);

                transportWeb.Deliver(mail);
            }
            catch (Exception err)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(err);
                emailError("emailDeclineQuote", "Email:" + Process.Constants.AcutestDirectEmail + " Error:" + err.ToString());
            }
        }

**Comment by 0xdeafcafe** [comment]
This is a known issue (#68). It's caused by the fact that this version of the library uses WebAPI (not smtp), and sadly, at the moment, the WebAPI doesn't support BCC.

You can still use the c# smtp library though - available at https://github.com/sendgrid/smtpapi-csharp.

**Comment by brandonmwest** [comment]
@0xdeafcafe BCC was put back in in 5.0.0 and the web api supports it now https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/SendGridMail/SendGrid.cs#L188-L197

Not sure what's going on here

**Comment by 0xdeafcafe** [comment]
@brandonmwest oops! removed my comment.

@craig-acutest could you set up fiddler and inspect the request going out?

**Comment by craig-acutest** [comment]
0xdeafcafe I will do now...

Is there anything in particular I'm looking for?

thanks?

**Comment by 0xdeafcafe** [comment]
You'll have to add the fiddler https cert to your system, and allow it to sniff HTTPS packets. The instructions on doing so are listed in that output.

When you've done that, you'll be able to see the POST payload, and the headers of the request.

**Comment by craig-acutest** [comment]
Here is decrypted output:

--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=api_user

azure_175b6e13f8192248c2a0d1e6c63c39f5@azure.com
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=api_key

knhkzxng
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=from

sales@acutesales.co.uk
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=subject

Acutest Direct - New Quotation
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=html

Hello Craig Williams,<br/><br/>Please find attached your quotation.<br/><br/>To view datasheets regarding products quoted for please use the links below:<br/><br/>PROMO MACROTOUCH Multifunction Tester - Introductory Price<br/><hr/><a href='https://s3-eu-west-1.amazonaws.com/productdatasheetsv2/Data Sheet_5552.pdf' >Data Sheet_5552.pdf</a><br/><br/><a href='https://s3-eu-west-1.amazonaws.com/productdatasheetsv2/Brochure_5552.pdf' >Brochure_5552.pdf</a><br/><br/><a href='https://s3-eu-west-1.amazonaws.com/productdatasheetsv2/Catalogue_5552.pdf' >Catalogue_5552.pdf</a><br/><br/><a href='https://s3-eu-west-1.amazonaws.com/productdatasheetsv2/Professional Electrician Published Article_5552.pdf' >Professional Electrician Published Article_5552.pdf</a><br/><br/>Kind Regards,<br/><br/>Richard Guthrie<br/>Area Sales Manager<br/><br/><span>AcutestDirect is a Trading Division of Acute Sales Ltd<br/>Century Road<br/>High Carr Business Park<br/>Newcastle-under-Lyme<br/>Staffordshire<br/>ST5 7UG<br/></span><br/><br/><span>The information contained in this electronic mail message is confidential. It is intended solely for the use of the individual or entity to whom it is addressed and others authorised to receive it. If the reader of this message is not the intended recipient, you are hereby notified that any use, copying, dissemination or disclosure of this information is strictly prohibited.</span><br/><br/>
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name="to[]"

generalcaw@gmail.com
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name="bcc[]"

richard.guthrie@acutesales.co.uk
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name="bcc[]"

sales@acutesales.co.uk
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name="bcc[]"

craig.williams@acutesales.co.uk
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name="bcc[]"

web@acutesales.co.uk
--5d906b49-b109-4796-b3d8-956d0818e9da
Content-Disposition: form-data; name="files[Quotation_08011526RG.pdf]"; filename=Quotation_08011526RG.pdf
Content-Type: application/octet-stream

%PDF-1.4
%    
1 0 obj
<<
/Pages 2 0 R
/Outlines 3 0 R
/PageLayout /OneColumn
/Type /Catalog
/OutputIntents [<<
/OutputCondition ()
/OutputConditionIdentifier (Custom)
/RegistryName ()
/Info (sRGB IEC61966-2.1)
/Type /OutputIntent
/DestOutputProfile 4 0 R
/S /GTS_PDFA1
>>
]
/ViewerPreferences 5 0 R
/PageMode /UseNone
>>

endobj
2 0 obj
<<
/Count 1
/Kids [6 0 R]
/Type /Pages
>>

endobj
6 0 obj
<<
/Resources <<
/ProcSet [/PDF /Text /ImageC]
/XObject <<
/EvoPdf_ggkohaidjdjjkhanolabafcplngdmagl 7 0 R
/EvoPdf_flpcjlplcpdmkichoihckefffiifajac 8 0 R
/EvoPdf_laddmnbpokikkpfkpibbophkmjpjdnnc 9 0 R
>>

>>

/Parent 2 0 R
/MediaBox [0.00000 0.00000 595.00000 842.00000]
/Annots [10 0 R]
/Type /Page
/Contents [11 0 R 12 0 R]
>>

endobj
11 0 obj
<<
/Filter /FlateDecode
/Length 136
>>
stream
x^M ; 0D{K Þ lB=T ǉH   a#o    N
  |m 3H[ k 
D        " H 7   ~
  U .`+JTK V    N~ >nއ r  (ϔ R SX  c 8;s e0
endstream

endobj
12 0 obj
<<
/Filter /FlateDecode
/Length 151
>>
stream
x^  ; 0D{K Þ

**Comment by 0xdeafcafe** [comment]
That's very strange. It looks like the post body is fine. Next thing I can suggest is going to https://sendgrid.com/logs/index and seeing if the to and bcc emails are being shown there.

nb: you might want to modify that comment as it has links to pdf documents that might be private.

**Comment by craig-acutest** [comment]
Hi @0xdeafcafe, Thanks for your help so far, it looks like my bcc emails are bouncing:

email: craig.williams@acutesales.co.uk

type: bounce

reason: 554 5.7.1 Command rejected

smtp-id: <14acb2d0f10.34bf.3abd6a@ismtpd-033>

processed string: January 8, 2015 - 08:12:23 PM

is this something for sendgrid support, or could the command being sent through from the API be incorrect somewhere?

Thanks.

**Comment by 0xdeafcafe** [comment]
If you open a ticket here https://support.sendgrid.com/hc/en-us/requests/new detailing the bounce, the SendGrid support team will look into it. Anything else you could suggest @brandonmwest?

**Comment by craig-acutest** [comment]
Thank you so much @0xdeafcafe you've been a great help.
I will raise a ticket and keep you informed.

**Comment by craig-acutest** [comment]
Hi guys,

It looks like there is a spam filter that the IT Support People here didn't know existed, and has been blocking Emails sent from sendgrid.

Its what i'm up against everyday with my job here, spending hours and being told its not our fault only to prove its there fault. In my opinion, they should have an audit log on all systems and changes to those systems. Similar to how GIT handles my code changes, and what i put in place on the admin side of my websites to track who changes what.

Thank you guys a lot especially @0xdeafcafe.

**Comment by brandonmwest** [comment]
@craig-acutest Glad you got it sorted out! Thanks @0xdeafcafe

**Comment by 0xdeafcafe** [comment]
Anytime @craig-acutest! Glad you got it sorted 💃
