### ISSUE TITLE
Strong name signature could not be verified

### ISSUE THREAD

**Issue by attilabicsko** [sendgrid/sendgrid-csharp#972]
I'm getting an error with the latest nuget version in an ASP.Net Web API application: 

Could not load file or assembly 'SendGrid, Version=9.12.5.0, Culture=neutral, PublicKeyToken=4f047e93159395ca' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]

#### Technical details:

* sendgrid-csharp Version: nuget 9.12.5
* Platform ASP.Net Web API
* .NET Version: 4.7

**Comment by M74M4D** [comment]
same for me with (9.12.5 vesion) !
but when downgrade to 9.12.1 allright.

**Comment by MrCsabaToth** [comment]
Same here.
```
c:\Users\Csaba\.nuget\packages\sendgrid\9.12.5\lib\net452>sn -v SendGrid.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.

c:\Users\Csaba\.nuget\packages\sendgrid\9.9.0\lib\net452>sn -v SendGrid.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'SendGrid.dll' is valid
```

**Comment by JulianGuppy** [comment]
Yes this release is broken I am getting the same error, and its affecting my Ci/CD build, can we have a fix asap please

**Comment by nemethyd** [comment]
The same issue, should we downgrade?

**Comment by TomGullen** [comment]
Downgraded to previous stable and works fine.

**Comment by attilabicsko** [comment]
My concern is that the previous release (9.12.1) still has a dependency on System.Net.Http NuGet package which causes conflicts in my solution, that was the main reason I was very happy about the 9.12.5 release and wanted to upgrade. So would much appreciate a fix for that latest release.

**Comment by thinkingserious** [comment]
Hello everyone,

I apologize for the hiccup. We are moving this library into a 2 week release cycle to better serve you and this was the first release we automated and released through the command line. 

I will be investigating why the strong signing is failing today. At first glance, it looks like [we have the correct settings in our .csproj file](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGrid.csproj#L10). If anyone has any insights as to what went wrong, I would greatly appreciate it.

With best regards,

Elmer

**Comment by jnyrup** [comment]
@thinkingserious I'm pretty confident that the culprit is
https://github.com/sendgrid/sendgrid-csharp/blob/a4d104fc665e7592d467b776a5377a8574669a98/src/SendGrid/SendGrid.csproj#L11

We're you building SendGrid on a Windows machine before?

I tried checking out master and building on a linux machine

#### With no changes:
```
sn -v SendGrid.dll
> Assembly SendGrid.dll is delay-signed but not strongnamed
```

#### After removing `<PublicSign>`
```
sn -v SendGrid.dll
> Assembly SendGrid.dll is strongnamed.
```

**Comment by thinkingserious** [comment]
Thanks @jnyrup!

Yes, I was building on a Windows machine manually before.

I will try your suggestion now :)

**Comment by thinkingserious** [comment]
It looks like assembly signing is not supported in our current travis environment https://travis-ci.org/sendgrid/sendgrid-csharp/builds/641599971#L2779

... continuing to investigate

**Comment by jnyrup** [comment]
Here's my setup:
ubuntu 18.04 (Linux Mint 19.2)
mono 6.8.0.96
msbuild 16.5.0.6501
dotnet 3.0.102

Comparing to your travis setup, you might want to try upgrading the `dist` from `trusty` (14.04) to `bionic` (18.04).

According to https://github.com/dotnet/roslyn/issues/8210 cross-platform strong naming has been available for some time.

**Comment by thinkingserious** [comment]
Nice! Thanks for the additional detail, trying `bionic` now.

**Comment by thinkingserious** [comment]
Received the same error: https://travis-ci.org/sendgrid/sendgrid-csharp/builds/641765790#L2491

... continuing to investigate

**Comment by thinkingserious** [comment]
Version 9.12.6 released:
- https://github.com/sendgrid/sendgrid-csharp/releases/tag/9.12.6
- https://www.nuget.org/packages/Sendgrid/9.12.6
