### ISSUE TITLE
Anchor tags not working

### ISSUE THREAD

**Issue by atmeginnis** [sendgrid/sendgrid-csharp#973]
When I save this message the link gets converted - what I actually have is:

< a href=site > site description < /a >

I added spaces here to see what I have - the actual code does not have spaces.

I have created a small routine to send emails.  However the anchor tags <a> are not working.  Here is a snapshot of my code:

tBody += "<a href='www.myjourneypayroll.com'>www.myJourneyPayroll.com</a>";

I then issue your command in the guide:

var htmlContent = tBody;			
var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
var response =  await client.SendEmailAsync(msg);

I get the email, however my link is not valid.  If I inspect the element I see:

<a rel="nofollow">www.myJourneyPayroll.com</a>

I am not sure where the NOFOLLOW text is coming from
#### Technical details:

* Not sure what version of sendgrid I have - downloaded in December, 2019
* ASP.NET CORE
* .NET Core 2.1

**Comment by thinkingserious** [comment]
Hello @atmeginnis,

I am unable to reproduce this issue with the following code:

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Threading.Tasks;

namespace Example
{
    internal class Example
    {
        private static void Main()
        {
            Execute().Wait();
        }

        static async Task Execute()
        {
            var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("example@example.com", "Example User");
            var subject = "Sending with Twilio SendGrid is Fun";
            var to = new EmailAddress("example@example.com", "Example User");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = "<strong>and easy to do <a href='https://twilio.com'>anywhere</a>, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }
    }
}
```

Could you please provide a bit more of your source code so that I may attempt to reproduce? Thank you!

With best regards,

Elmer

**Comment by atmeginnis** [comment]
This was resolved.  It was actually a YAHOO issue.  My url did not have HTTP or HTTPS so it caused some email clients to void the anchor tag.
Thanks,
ANDY
    On Thursday, March 5, 2020, 11:36:02 AM PST, Elmer Thomas <notifications@github.com> wrote:  
 
 
Hello @atmeginnis,

I am unable to reproduce this issue with the following code:
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Threading.Tasks;

namespace Example
{
    internal class Example
    {
        private static void Main()
        {
            Execute().Wait();
        }

        static async Task Execute()
        {
            var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("example@example.com", "Example User");
            var subject = "Sending with Twilio SendGrid is Fun";
            var to = new EmailAddress("example@example.com", "Example User");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = "<strong>and easy to do <a href='https://twilio.com'>anywhere</a>, even with C#</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }
    }
}
Could you please provide a bit more of your source code so that I may attempt to reproduce? Thank you!

With best regards,

Elmer
