### ISSUE TITLE
Locked out of my account due to IP address whitelisting

### ISSUE THREAD

**Issue by ScottB3** [sendgrid/sendgrid-csharp#978]
I can not log into my account. I signed up for a free account and logged in from my computer at work and then at home I went to log in to upgrade and purchase a plan.
I didn't know about white listing IPs and IP management. 

I am completely locked out and can't log in from work or at home. Can you please help me to get back into my account so I can upgrade and start to
use the service? 

The support ticket gave me a code and said that you could call my phone number in my account and I could give you the code. Can we please do this and call me or email me
or something?

I didn't know how the process works initially.

Thank you,

C. Scott Blevins

**Comment by childish-sambino** [comment]
I'm don't know of any codes that support would give that can be helped by the community. Best to follow up with support to resolve this.

**Comment by thinkingserious** [comment]
Hello @ScottB3,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by ScottB3** [comment]
I don't get this. You need to go to support.sendgrid.com to file a support ticket and the website also needs you to log in. I am locked out and can't log in... I went to the support page for being locked out and I got a code it said they could call the phone in my account and give them the code to let me back in and to just let them know if that is what I want to do so I replied yes but haven't heard from anyone and it has been a couple of days... a good way to turn off a new customer who wants to pay money but can't!

**Comment by childish-sambino** [comment]
Can you use this link? https://support.sendgrid.com/hc/en-us/requests/new#ipam-lockout
