### ISSUE TITLE
Send Email Fails With Empty List of BCCs

### ISSUE THREAD

**Issue by indy-singh** [sendgrid/sendgrid-csharp#980]
#### Issue Summary

Just ran into this issue and lost half a day to figure out what was going on.

Basically when calling SendGridMessage.AddBccs with an empty list the request fails to send.

I believe this is the line of code in question:-

https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/SendGridMessage.cs#L457

#### Steps to Reproduce
```csharp
public class Program
{
	private const string NO_REPLY_ADDRESS = "NO_REPLY_ADDRESS";
	private const string RECIPIENT_ADDRESS = "RECIPIENT_ADDRESS";
	private const string API_KEY = "API_KEY";

	public static void Main(string[] args)
	{
		var client = new SendGridClient(API_KEY);

		var responseThatSucceeds = client.SendEmailAsync(CreateMessage()).Result;
		Console.WriteLine(responseThatSucceeds.StatusCode);

		var responseThatFails = client.SendEmailAsync(CreateMessageWithEmptyBlindCarbonCopies()).Result;
		Console.WriteLine(responseThatFails.StatusCode);
	}

	public static SendGridMessage CreateMessage()
	{
		var from = new EmailAddress(NO_REPLY_ADDRESS, NO_REPLY_ADDRESS);
		var to = new EmailAddress(RECIPIENT_ADDRESS);
		return MailHelper.CreateSingleEmail(from, to, "This is the subject", "", "This is the body");
	}

	public static SendGridMessage CreateMessageWithEmptyBlindCarbonCopies()
	{
		var sendGridMailMessage = CreateMessage();
		sendGridMailMessage.AddBccs(new List<EmailAddress>());
		return sendGridMailMessage;
	}
}
```

#### Technical details:

* sendgrid-csharp Version: `<package id="SendGrid" version="9.12.7" targetFramework="net472" />`
* Platform .NET Framework
* .NET Version: 4.7.2

I would expect the second send to work regards. Feels like the API should be easy to use.

Happy to send in a quick PR to fix it if that is welcome.

Cheers,
Indy

**Comment by childish-sambino** [comment]
A PR works for me.
