### ISSUE TITLE
How to get the unique reply content from replied mail ?

### ISSUE THREAD

**Issue by VQuery** [sendgrid/sendgrid-csharp#982]
#### Issue Summary

We have to get the exact replied mail content alone from mail reply. We are using inbound parse for getting mails from customer and redirect to our api and deserized all the values like , html , from , to, cc , etc.. and creating tickets.

Example:

I want to get the 'Please view this image' content alone from reply mail.

![image](https://user-images.githubusercontent.com/23099088/75741839-d06ff400-5d31-11ea-8887-1ada1b91b37f.png)

#### Technical details:

* sendgrid inbound parse
* Platform (ASP.NET Core Web API)
* .NET Core : 3.1

**Comment by childish-sambino** [comment]
Best I can tell, there's no perfect way as it depends on the email app and if the sender modified the original message. Here's a post about some ways to do this: https://stackoverflow.com/questions/278788/parse-email-content-from-quoted-reply

**Comment by VQuery** [comment]
Thanks @childish-sambino  , We are going to implement the regex collection for all the email app. We hope it will work !!!
