### ISSUE TITLE
Migration guide for those using sections/substitutions

### ISSUE THREAD

**Issue by aaronhudon** [sendgrid/sendgrid-csharp#986]
#### Issue Summary

Ok, so I have been warned that "sections" and "substitutions" are being deprecated from the API. I am having a heck of a time understanding the migration path. 

I am currently using the "legacy templates", and gather that they need to be migrated to "dynamic templates".

My C# code is replacing tokens in the transactional template by using:

SendGridMessage.AddSubstitution(...)
SendGridMessage.AddSection(...)

What is the proper migration path?  The two above mentioned APIs are still showing in the C# library as available (not deprecated)

**Comment by thinkingserious** [comment]
Hello @aaronhudon,

If you are migrating to transactional templates (they used to be called dynamic templates), then [this documentation](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional-templates) should help. Please take a look and let me know if you need any further assistance. Thanks!

With best regards,

Elmer
