### ISSUE TITLE
Azure Function creates CORS error

### ISSUE THREAD

**Issue by champcbg** [sendgrid/sendgrid-csharp#987]
#### Issue Summary

I am sending emails from an **azure function** and i am getting a CORS error.  This is code that is running in the azure function.

 ```
var client = new SendGridClient(Options.SGOptions.ApiKey);          

            var from = new EmailAddress(fromEmail, fromName);
            var to =  new EmailAddress(toEmail, toName);
            var msg = MailHelper.CreateSingleTemplateEmail(from, to, templateId, templateData);

            // Disable click tracking.
            // See https://sendgrid.com/docs/User_Guide/Settings/tracking.html
            msg.SetClickTracking(true, true);
            msg.SetOpenTracking(true);
            msg.CustomArgs=new Dictionary<string,string>();
            msg.CustomArgs.Add("SendRequestId", sendRequestId);          

            var response = await client.SendEmailAsync(msg);
```

and this is the response i get back from **var response = await client.SendEmailAsync(msg);**

`{"StatusCode":400,"Body":{"Headers":[{"Key":"Content-Type","Value":["application/json"]},{"Key":"Content-Length","Value":["136"]}]},"Headers":[{"Key":"Server","Value":["nginx"]},{"Key":"Date","Value":["Wed, 25 Mar 2020 23:21:15 GMT"]},{"Key":"Connection","Value":["keep-alive"]},{"Key":"Access-Control-Allow-Origin","Value":["https://sendgrid.api-docs.io"]},{"Key":"Access-Control-Allow-Methods","Value":["POST"]},{"Key":"Access-Control-Allow-Headers","Value":["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"]},{"Key":"Access-Control-Max-Age","Value":["600"]},{"Key":"X-No-CORS-Reason","Value":["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}]}`

I have tried a full access API key and also a api key that only allowed sending emails.  With both i got the same error.

#### Steps to Reproduce

1. Build the send grid client
2. Call the SendEmailAsync
3. Get Error

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: 9.13.1
* ASP.NET Core
* .NETCore Version: 3.1

**Comment by thinkingserious** [comment]
Hello @champcbg,

First, could you please try using `msg.AddCustomArg("SendRequestId", sendRequestId);`?

For helping troubleshoot further, could you please post your [request body](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#viewing-the-request-body)? 

With best regards,

Elmer

**Comment by champcbg** [comment]
> First, could you please try using msg.AddCustomArg("SendRequestId", sendRequestId);?

That produced the same result
`
{"StatusCode":400,"Body":{"Headers":[{"Key":"Content-Type","Value":["application/json"]},{"Key":"Content-Length","Value":["136"]}]},"Headers":[{"Key":"Server","Value":["nginx"]},{"Key":"Date","Value":["Fri, 27 Mar 2020 23:55:13 GMT"]},{"Key":"Connection","Value":["keep-alive"]},{"Key":"Access-Control-Allow-Origin","Value":["https://sendgrid.api-docs.io"]},{"Key":"Access-Control-Allow-Methods","Value":["POST"]},{"Key":"Access-Control-Allow-Headers","Value":["Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"]},{"Key":"Access-Control-Max-Age","Value":["600"]},{"Key":"X-No-CORS-Reason","Value":["https://sendgrid.com/docs/Classroom/Basics/API/cors.html"]}]}`

Here is the serialize `msg` object

```
{
    "from": {
        "name": "Greatness Team",
        "email": "admin@sstg.com"
    },
    "subject": null,
    "personalizations": [{
        "to": [{
            "name": "Test User 17",
            "email": "testuser17@test.com"
        }],
        "cc": null,
        "bcc": null,
        "subject": null,
        "headers": null,
        "substitutions": null,
        "custom_args": {
            "SendRequestId": "dab1b1bb-4590-4940-fd8e-08d7d22fa0a2"
        },
        "send_at": null,
        "dynamic_template_data": "{\"dynamic_template_data\": {\"username\": \"Test user 17\",\"confirmationCode\": \"5 4 3 2 1\"}}"
    }],
    "content": null,
    "attachments": null,
    "template_id": "d-767aa004ed164204a26f4692c10d211f",
    "headers": null,
    "sections": null,
    "categories": null,
    "custom_args": null,
    "send_at": null,
    "asm": null,
    "batch_id": null,
    "ip_pool_name": null,
    "mail_settings": null,
    "tracking_settings": {
        "click_tracking": {
            "enable": true,
            "enable_text": true
        },
        "open_tracking": {
            "enable": true,
            "substitution_tag": null
        },
        "subscription_tracking": null,
        "ganalytics": null
    },
    "reply_to": null
}
```

**Comment by champcbg** [comment]
I figured out the problem was in my `to` body
```

"to": [{
            "name": "Test User 17",
            "email": "testuser17@test.com"
        }],
```

my test email address was causing the failure.
