### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by JayaMadgul** [sendgrid/sendgrid-csharp#992]
Hi,
Iam unable to send emails using SendGrid WebAPI after creating new Account and verified Domain under Godaddy Provider.I aready raised Support Ticket on this issue 

![image](https://user-images.githubusercontent.com/63776467/79733929-80fe7b00-8313-11ea-8cb9-7b3461a380f1.png)

kindly look at the screen shots for Account details, Domain & Web API and please help me to proceed sending mails with this account and verified domain

![image](https://user-images.githubusercontent.com/63776467/79733546-edc54580-8312-11ea-8892-3a1d98e706f3.png)
 
![image](https://user-images.githubusercontent.com/63776467/79733619-09305080-8313-11ea-80cd-1ed7270f9306.png)

![image](https://user-images.githubusercontent.com/63776467/79829290-456dba80-83c0-11ea-8730-5c0e95aece38.png)

Thanks & Regards 
Jaya 
jaya1.ziraff@gmail.com

**Comment by childish-sambino** [comment]
The body in the response should contain additional error messaging. Recommend inspecting it for a more detailed reason.
