### ISSUE TITLE
Status Forbidden When Sending Email from Sendgrid

### ISSUE THREAD

**Issue by sami-lab** [sendgrid/sendgrid-csharp#994]
### Issue Summary
i am using asp.net core 2.2 to send email but every time i send email status is Forbidden. I put a Bearer in front of Api Key(Bearer SG) then status change to unauthorized.Below is my code

### Code Snippet
```csharp
# `  public class EmailSender : IEmailSender
    {
        public EmailAuthOptions Options { get; set; }
        public IConfiguration Configuration { get; }
        public EmailSender(IOptions<EmailAuthOptions> optionsAccessor,IConfiguration configuration)
        {
            Options = optionsAccessor.Value;
            Configuration = configuration;
        }
        public Task SendEmailAsync(string email, string subject, string message)
        {
            return Execute(Options.SendGridKey, subject, message, email);
        }

        public async Task Execute(string apiKey, string subject, string message, string email)
        {
                    
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress(Configuration["Email"], Configuration["Name"]);
            var to = new EmailAddress(email);
            
            var plainTextContent = message;
            var htmlContent =message;
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            try
            {
                var response= await client.SendEmailAsync(msg);            
            }
            catch
            {

            }          
        }
    }`
```

### Exception/Log
```
#

  | StatusCode | Forbidden | System.Net.HttpStatusCode


```

### Technical details:
* sendgrid-csharp version: 9.13.2
* csharp version: Asp.net core 2.2

**Comment by Cadulox** [comment]
I'm having the same problem. I'm using ASP.NET Core 3.1 and SendGrid 9.14.1.

My code:
`public async Task SendEmailAsync(string email, string subject, string message)
        {
            var apiKey = _config["SendGridKey"];
            var client = new SendGridClient(apiKey);

            var msg = new SendGridMessage()
            {
                From = new EmailAddress(_config["Email"], _config["SendGridUser"]),
                Subject = subject,
                PlainTextContent = message,
                HtmlContent = message
            };
            msg.AddTo(new EmailAddress(email));

            var response = await client.SendEmailAsync(msg).ConfigureAwait(false);
        }`

**Comment by childish-sambino** [comment]
Recommend catching the exception and logging the response body to get additional details about why it's forbidden.

**Comment by sami-lab** [comment]
> Recommend catching the exception and logging the response body to get additional details about why it's forbidden.
Actually there is no exception but email is not sent at client email(Status Forbidden). If you want any other info please let me know

![image](https://user-images.githubusercontent.com/56019715/80841524-0984f180-8c19-11ea-801c-04e16c7476f6.png)

**Comment by sami-lab** [comment]
The Issue is resolved. i did not verify single sender. Thanks to StackOverflow. Very disappointing that such information is not mentioned as part of their integration process -.

**Comment by sami-lab** [comment]
> I'm having the same problem. I'm using ASP.NET Core 3.1 and SendGrid 9.14.1.
> 
> My code:
> 
> # ` public async Task SendEmailAsync(string email, string subject, string message)
> ```
>     {
>         var apiKey = _config["SendGridKey"];
>         var client = new SendGridClient(apiKey);
> 
>         var msg = new SendGridMessage()
>         {
>             From = new EmailAddress(_config["Email"], _config["SendGridUser"]),
>             Subject = subject,
>             PlainTextContent = message,
>             HtmlContent = message
>         };
>         msg.AddTo(new EmailAddress(email));
> 
>         var response = await client.SendEmailAsync(msg).ConfigureAwait(false);
>     }`
> ```

Hello dear if your issue is still not resolve check this,
https://stackoverflow.com/questions/61139752/status-forbidden-when-sending-email-with-sendgrid/61272487#61272487
