### ISSUE TITLE
No error details when "Bad Request" returned

### ISSUE THREAD

**Issue by vincerogers** [sendgrid/sendgrid-csharp#995]
### Issue Summary
For one specific email address on a template email via MailHelper.CreateSingleTemplateEmail, I am getting a "Bad Request"status code back. I attempt to troubleshoot by following posted instructions to inspect the response body, but I see no additional details. This only happens with one specific email address. The same template email request works fine for other email addresses.

Here is the response body returned in full:
```
{
    "statusCode": 400,
    "body": {
        "headers": [
            {
                "key": "Content-Type",
                "value": [
                    "application/json"
                ]
            },
            {
                "key": "Content-Length",
                "value": [
                    "351"
                ]
            }
        ]
    },
    "headers": [
        {
            "key": "Server",
            "value": [
                "nginx"
            ]
        },
        {
            "key": "Date",
            "value": [
                "Wed, 15 Apr 2020 02:11:17 GMT"
            ]
        },
        {
            "key": "Connection",
            "value": [
                "keep-alive"
            ]
        },
        {
            "key": "Access-Control-Allow-Origin",
            "value": [
                "https://sendgrid.api-docs.io"
            ]
        },
        {
            "key": "Access-Control-Allow-Methods",
            "value": [
                "POST"
            ]
        },
        {
            "key": "Access-Control-Allow-Headers",
            "value": [
                "Authorization, Content-Type, On-behalf-of, x-sg-elas-acl"
            ]
        },
        {
            "key": "Access-Control-Max-Age",
            "value": [
                "600"
            ]
        },
        {
            "key": "X-No-CORS-Reason",
            "value": [
                "https://sendgrid.com/docs/Classroom/Basics/API/cors.html"
            ]
        }
    ]
}
```

### Steps to Reproduce
1. Send a single template email using CreateSingleTemplateEmail
### Code Snippet
```csharp

var msg = MailHelper.CreateSingleTemplateEmail(fromAddress, toAddress, templateId, templateData);
AddBccs(ref msg, bccTo);
return await Send(msg);
```

### Technical details:
* sendgrid-csharp version: 9.14.0
* csharp version: Core 3.1

**Comment by eshanholtz** [comment]
Hi @vincerogers,

Are you having issues with the email as the sender or receiver? If it's the sender, has the sender and/or the domain been [verified](https://sendgrid.com/docs/ui/sending-email/sender-verification/)?

**Comment by vincerogers** [comment]
Hi @eshanholtz , issue is on send. The domain has not been verified, so I can give that a try. Should I still be seeing some sort of error message regardless though?

**Comment by vincerogers** [comment]
@eshanholtz , I did verify the domain and got same results.

**Comment by eshanholtz** [comment]
Can you please [print the request body](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#viewing-the-request-body) and post it here?

**Comment by vincerogers** [comment]
I blanked out some of the template data with empty strings, hopefully nothing that would effect the outcome. I can message you the unedited version separately if helpful. Also as a heads up, SendGrid technical support is looking as well, in case you wanted to hold off. They had originally directed me here and closed my ticket, but then reopened it.

```
{
  "from": {
    "name": "Aprann",
    "email": "noreply@aprann.org"
  },
  "personalizations": [
    {
      "to": [
        {
          "email": "vince.j.rogers@gmail.com"
        }
      ],
      "dynamic_template_data": {
        "emailBody": "This is a test email, and this is the dynamic body portion of the template",
        "partnerReplyEmail": "",
        "partnerName": "",
        "partnerUrl": "",
        "partnerWebsite": "",
        "invoice": {
          "lines": [
            "line 1",
            "line 2"
          ]
        },
        "firstName": "Vince",
        "amount": "100.00",
        "date": "2020-05-05T13:36:54.8248065-06:00",
        "partnerLogoUrl": ""
      }
    }
  ],
  "template_id": "d-834713fe353243d5b969262c2697f678"
}
```

**Comment by eshanholtz** [comment]
I'm a bit confused by the code snippet you included in the original post. I see you use the mail helper to construct the message, and it looks like that's working successfully. You then have the line:
```csharp
AddBccs(ref msg, bccTo);
```
Referencing [an example of constructing an email using the helper library](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#kitchen-sink---an-example-with-all-settings-used), that line should be:
```csharp
// If bccTo is a single email
msg.AddBcc(bccTo);

// If bccTo is a list of emails
msg.AddBccs(bccTo);
```
Then, in your last line you have:
```csharp
return await Send(msg);
```

Referencing [documentation on using the mail helper to send transactional email](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#with-mail-helper-class), you should be using:
```csharp
var response = await client.SendEmailAsync(msg);

**Comment by vincerogers** [comment]
There are some helper methods along the way. The send lastly goes through:

```	
private async Task<Response> Send(SendGridMessage msg)
{
	return await _emailClient.SendEmailAsync(msg);
}
```

Keep in mind that the emails are working fine for all but one destination address. The root of my issue is that there is no additional error info in the failed response for me to troubleshoot off of for the one that is failing.

**Comment by eshanholtz** [comment]
Oh, it's a destination address it's failing on? I thought in an earlier comment you said it was the sender. Are you seeing any indication of this email in your recent [email activity](https://app.sendgrid.com/email_activity)? Does including the line `Console.WriteLine(response.Body.ReadAsStringAsync().Result);` when getting the response possibly print additional information?

**Comment by vincerogers** [comment]
Hi @eshanholtz , I feel silly now. I didn't properly follow the instructions for pulling the error result message. 

response.Body.ReadAsStringAsync().Result

Gives the following:

  | Name | Value | Type
-- | -- | -- | --
  | x | "{\"errors\":[{\"message\":\"Each email address in the personalization block should be unique between to, cc, and bcc. We found the first duplicate instance of [...] in the personalizations.0.bcc field.\",\"field\":\"personalizations.0\",\"help\":\"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.recipient-errors\"}]}" | string

Sorry for wasting your time!
