### ISSUE TITLE
SendGrid Marketing Api service v3/marketing/campaigns

### ISSUE THREAD

**Issue by rduman** [sendgrid/sendgrid-csharp#999]
I sent an email using SendGrid new marketing api service. [SendGrid](https://sendgrid.com/docs/for-developers/sending-email/single-sends-2020-update/
)
 I use https://api.sendgrid.com/v3/marketing/campaigns

```
var request = new RestRequest(Method.POST);
request.AddHeader("authorization", "Bearer ************************");
var requestJson = JsonConvert.SerializeObject(sendingMarketingEmail);
request.AddParameter("undefined", requestJson, ParameterType.RequestBody);
IRestResponse _response = _client.Execute(request);


{
    "name": "TEST__EMAIL",
    "send_at": "2020-05-13T15:47:36.2656452+01:00",
    "filter": {
        "list_ids": [
            "**********************"
        ],
        "send_to_all": false
    },
    "email_config": {
        "subject": "TEST_EMAIL",
        "html_content": null,
        "plain_content": "TEST_EMAIL PLAIN Content"
    }
}
```
### Response
```
{
    "categories": null,
    "created_at": "2020-05-13T14:30:17Z",
    "custom_unsubscribe_url": "",
    "filter": {
        "list_ids": [
            "**********************"
        ],
        "segment_ids": [],
        "send_to_all": false
    },
    "id": "****************",
    "name": "TEST__EMAIL",
    "send_at": "2020-05-13T15:31:22.2986812+01:00",
    "sender_id": null,
    "status": "draft",
    "suppression_group_id": null,
    "template_id": "",
    "updated_at": "2020-05-13T14:30:17Z",
    "ab_test": null
}
```

It created email. But, I couldn't get any email from sendGrid. I check sendgrid dashboard. There is nothing to see. Does any body solve this problem?

### Technical details:
* sendgrid-csharp version: v3
* csharp version: .Net Core 2.2

**Comment by thinkingserious** [comment]
Hello @rduman,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
